### ISSUE TITLE
Show graphics API in Perfomance Metrics tab in IGS

### ISSUE THREAD

**Issue by Azodan** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#894] opened 2024-12-17 08:57 UTC
### Application [Required]

Intel Graphics Software

### Processor / Processor Number [Required]

AMD Ryzen 7 5800X3D

### Graphic Card [Required]

Intel Arc

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build [Required]

Windows 11 24H2

### Describe the feature [Required]

It would be neat if the graphics API was showed in the Metrics tab.

![image](https://github.com/user-attachments/assets/2791362b-041f-4704-ad3e-66c969311be6)

**Comment by EstebanIntel** [comment] 2024-12-19 00:35
@Azodan Thanks for taking the time to provide feedback. :) I went ahead and filed a request with these details for the team to review and will be internally tracking this. I'm closing this one out with my comment since this is not a bug, but a feature request.

**Closed by EstebanIntel** 2024-12-19 00:35 UTC
Labels: Type: Feature Request
