### ISSUE TITLE
Black screen issue when using "Disable full screen optimization" and "Full screen"

### ISSUE THREAD

**Issue by kyh96403** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#107] opened 2021-12-22 01:43 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Most Game

### Game Platform [Required]

- [X] Steam
- [X] Origin
- [X] Microsoft Store
- [X] GOG Galaxy
- [X] Ubisoft Connect
- [X] Battle.net
- [X] Epic Games
- [X] Bethesda.net
- [X] Rockstar Games Launcher
- [X] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

1160G7/1165G7/1195G7

### GPU Driver Version [Required]

- [X] 30.0.101.1191 (*latest*)
- [X] 30.0.101.1121
- [X] 30.0.101.1069
- [X] 30.0.100.9955
- [X] 30.0.100.9894
- [X] 30.0.100.9864
- [X] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [X] DirectX11
- [X] DirectX10
- [X] DirectX9

### Windows Build Number [Required]

- [X] Windows 11
- [X] Windows 10 21H2 (*November 2021 Update*)
- [X] Windows 10 21H1 (*May 2021 Update*)
- [X] Windows 10 20H2 (*October 2020 Update*)
- [X] Windows 10 20H1 (*May 2020 Update*)
- [X] Windows 10 19H2 (*November 2019 Update*)
- [X] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

None.

### Description and steps to reproduce [Required]

When I change the resolution in the game, the screen goes blank and the screen becomes black, using "Disable fullscreen optimization"..
That problem is represent "OneGX Pro, OneXPlayer, GPD Win3..."

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1280x720, 1280x800

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

That problem occur only using "Disable fullscreen optimization" and fullscreen mode.
See below for "Disable fullscreen optimization" options.
https://www.minitool.com/images/uploads/news/2020/04/disable-fullscreen-optimizations/disable-fullscreen-optimizations-2.png

### Device / Platform name

OneGX Pro, OneXPlayer, GPD Win3

### Crash dumps [Required]

None.

**Comment by IGCIT** [comment] 2021-12-22 10:01
can you please provide more information?
https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/How-to-generate-Intel-System-Support-Utility-report

also specify which games, or at least some of them, that are having this issue.

thanks

**Comment by estebanr863** [comment] 2021-12-22 19:34
Hi @kyh96403,

Can you please explain why you need to disable the fullscreen optimization?

**Comment by Saracchini** [comment] 2021-12-22 19:42
Certain games show very blurry images in fullscreen in Portrait displays in Landscape mode (i.e. GPD Win3, OneXPlayer). The only way to play the game in full screen without blur is either disabling full-screen optmizations or running then in Windowed Borderless mode. Unfortunately for some games this means much lower performance. 

Some of games that this issue occur (severe visual glitches or black screen when using fullscreen exclusive with optimization disabled) :
- Megaman X Legacy Colection 1 and 2
- RUINER
- MechWarrior 5
- Star Wars: The Fallen Order
- Need for Speed Heat (occasionaly)

**Comment by estebanr863** [comment] 2021-12-22 19:42
Hi @kyh96403,

When changing resolutions, does the screen becomes black and stays that way or does the image comes back after a few seconds?

**Comment by Saracchini** [comment] 2021-12-22 19:50
Hi @estebanr863 , I'm not @kyh96403, would be useful to him provide his list of affected games too.
In my case, those games I mentioned allow setting screen to full screen in game (sometimes without any detrimental effects), however when settings are saved, and the game is re-opened, the screen will be totally black, and stays like that. You can alt+tab without issues , and if the game supports,  alt+enter to a windowed mode makes the image re-appear.

**Comment by kyh96403** [comment] 2021-12-27 00:18
@IGCIT 
Tekken 7, Borderland 1/2/3, BioShock 1/2/INF, Dead Space 1/2/3...
Infact all D3D9 or D3D11 game has this problem..
But vulkan game don't have problem.

@estebanr863 
In my case...
Cannot back screen...
So I need sleep mode or hibernation for restore screen.
But some game has no solution, so that is needed manual edit config file for borderless.

**Comment by estebanr863** [comment] 2022-03-09 18:45
Hi @kyh96403 @Saracchini and @IGCIT 

We were able to reproduce this issue and it has now been escalated to our driver development team. I just want to set the right expectation with you, as with the current workload, it may take from 3 to 6 months for a possible fix to be integrated into a release driver.

**Comment by estebanr863** [comment] 2022-05-10 20:10
@kyh96403 & @Saracchini,

A possible fix for this issue has been included in the [latest driver version](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html) 30.0.101.1960. Can you please perform a [clean install](https://www.intel.com/content/www/us/en/support/articles/000057389/graphics.html) of this driver version and test it?

**Comment by Saracchini** [comment] 2022-05-10 21:45
I'll be re-installing Megaman Collection and check if the issue is still there.

**Comment by Saracchini** [comment] 2022-05-10 22:49
I tested Megaman X Collection 1, and it does indeed start with FullScreen and disabled full-screen optimisations without issues !

**Comment by estebanr863** [comment] 2022-05-11 17:17
Thanks for testing @Saracchini. We will keep working on this issue.

**Comment by Saracchini** [comment] 2022-05-11 18:02
Well, I can confirm that I don't have anymore black screen issues when starting NFS Heat, Megaman X Collection 1 and 2.
I'm reinstalling RUINER and will confirm shortly.

**Comment by Saracchini** [comment] 2022-05-11 18:43
Just tested RUINER. 
It does start without a black screen in exclusive fullscreen and disabled optimisations. Regarding this issue, I don't see it anymore in the games  I mentioned. 

The screen starts very distorted, and that is a common issue with UE engine games in these rotated portrait display devices.
Usually this is fixed by entering in game settings and selecting the screen resolution again, or simplify choosing Borderless FullScreen. 
That is a separated problem, and I'm not sure if it's the engine or driver's fault.

**Comment by estebanr863** [comment] 2022-05-11 22:58
Thanks for testing @Saracchini! Since the issues is resolved, can this be closed?

**Comment by Saracchini** [comment] 2022-05-12 07:22
It's not me who opened the issue, neither I have all the games  @kyh96403 mentioned. It's solved on all the games I mentioned, so I believe that would be the case.

**Comment by IGCIT** [comment] 2022-05-12 07:34
@kyh96403 can you please test with latest driver 1960?

**Comment by kyh96403** [comment] 2022-05-16 11:02
@IGCIT 
I test it..
That is fixed...
Very thanks^^

**Closed** 2022-05-16 12:58 UTC
Labels: Info: Needs Replication, Type: Graphical Glitches
