### ISSUE TITLE
ARC A770 VRAM speeds run at 2000mhz instead of 2100mhz

### ISSUE THREAD

**Issue by bizude** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#160] opened 2022-10-23 15:36 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

All applications

### Processor / Processor Number [Required]

i9-13900K

### Graphic Card [Required]

Intel ARC A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.3491 (*latest*)
- [ ] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1 (*October 2021 Update*)
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

[intel-ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/9846917/intel-ssu.txt)

### Description and steps to reproduce [Required]

Myself and multiple other users on the _Intel Insiders_ Discord server have noticed that our ARC GPUs are running at 2000mhz VRAM, when ARC A770 was advertised to run at 2100mhz. 

### Crash dumps [Required]

Not Applicable, this is not a instability/crash report. 

### Application / Windows logs

![image](https://user-images.githubusercontent.com/81831122/197401364-da777703-3906-4c15-8e5e-1023747a4ce6.png)

**Comment by IbiPa** [comment] 2022-10-23 16:54
Also affected by it, i think the intended memory clock should in fact be 2187Mhz btw, i think 2100mhz should only make it the 17Gbps, when in fact it the LE cards should have 17.5Gbps.

**Comment by JamesCJ60** [comment] 2022-10-23 19:08
I'm also affected by this issue on my A770 LE:
![image](https://user-images.githubusercontent.com/20888782/197410926-5c62acad-8696-4921-8fec-56deab475373.png)

**Comment by ghostmotley** [comment] 2022-10-23 21:47
Same issue with me, Arc A770 16GB LE, GPU-Z, HWInfo64 and Arc Control are all reporting 2000MHz G6 speed (16Gbps) effective
![image](https://user-images.githubusercontent.com/116523810/197419781-df182463-e55e-4d74-be98-28c05e2384d0.png)

**Comment by Powermann293** [comment] 2022-10-24 09:11
I have the same issue. No matter if I was idling on my desktop or doing some absurdly heavy raytracing benchmark, the built in Arc Overlay would always stay at a flat 2000 Mhz.

**Comment by AssassinWarlord** [comment] 2022-10-24 10:50
With my A770 LE - at First start after driver installed - all clocks are fine:
![Screenshot 2022-10-18 152001](https://user-images.githubusercontent.com/17943122/197509653-06ce3390-e1f9-4994-8850-d19edb19d60b.png)

after reboot - only 2000Mhz memory clock :(
![A770 Maximale PCIe Energiespareinstelung - 38W Gesammtverbrauch](https://user-images.githubusercontent.com/17943122/197509764-1cb9f458-8e82-416c-91d1-f01457030ad8.jpg)

**Comment by Loeschzwerg3DC** [comment] 2022-10-24 14:51
I'm having the same problem.

![A770_drv3490_Mem-Clock](https://user-images.githubusercontent.com/116576813/197556252-e5fd88ff-2949-4ced-ba15-57b97af05b02.jpg)

**Comment by dmdelacy** [comment] 2022-10-24 15:50
does it pass with 3490 or 3435?

**Comment by BigNish7** [comment] 2022-10-25 01:34
Affects me as well. Device ID 56a0. Device Revision 08. V-BIOS 20.1053.3. ARC Control 1.0.4765.0. Driver 31.0.101.3490. Windows OS Version 22621.675 (11Pro 22H2).

![image](https://user-images.githubusercontent.com/116610885/197660712-ffbe2c73-8108-4e38-ad1c-62b2295d2c00.png)

**Comment by strangecargo** [comment] 2022-10-25 01:35
> With my A770 LE - at First start after driver installed - all clocks are fine: ![Screenshot 2022-10-18 152001](https://user-images.githubusercontent.com/17943122/197509653-06ce3390-e1f9-4994-8850-d19edb19d60b.png)
> 
> after reboot - only 2000Mhz memory clock :( ![A770 Maximale PCIe Energiespareinstelung - 38W Gesammtverbrauch](https://user-images.githubusercontent.com/17943122/197509764-1cb9f458-8e82-416c-91d1-f01457030ad8.jpg)

This is exactly what I experienced as well. I happened to see my "VRAM Effective Frequency" listed in Arc Control Center as 17.5GTs after it was first installed, but after subsequent reboots, it now shows 16GTs.

**Comment by IntelSupport-Rozilah** [comment] 2022-10-25 04:24
Hi All,
Thanks for contacting us, we will start to verify the issue as soon as possible and please be patient while we try to figure out this issue for you all. Stay tuned!

**Comment by AntVNS** [comment] 2022-10-26 09:54
Hi all, i have the same issue. 
When you look at the GPUZ screenshot of Techpowerup Arc review where is display the right memory clock. We can see they used Intel Arc: 101.3433 Press Driver in the review.
I tried to install this official old driver version gfx_win_101.3430 for the A770 but the install give me this error
Same situation with all the old version of the arc driver.

![Intelarcdrivers](https://user-images.githubusercontent.com/95941187/197995280-bc1aa803-0ffe-44d9-8667-f2b0fe5206a7.png)

I only be able to install the lastest drivers gfx_win_101.3490 or the beta version .3491
Why intel let us download the old driver but we can't install it?

**Comment by IGCIT** [comment] 2022-10-26 10:14
hi @AntVNS 

the official driver 101.3430 (and lower) is not compatible with A770

supported GPUs in driver **3430** and lower
![2022-10-26-121102_226x55_scrot](https://user-images.githubusercontent.com/76787191/197999963-f61ba034-c742-40b1-8e1a-d2aef1767e8e.png)

supported GPUs in driver **3490** and above
![2022-10-26-121011_219x69_scrot](https://user-images.githubusercontent.com/76787191/198000045-828f2430-6417-48f9-a029-0884b4d26d98.png)

the deskopt variant (A770) has been added in driver 3490, that is why you get that error.

**Comment by AntVNS** [comment] 2022-10-26 11:32
> hi @AntVNS
> 
> the official driver [101.3430](tel:101.3430) (and lower) is not compatible with A770
> 
> supported GPUs in driver **3430** and lower ![2022-10-26-121102_226x55_scrot](https://user-images.githubusercontent.com/76787191/197999963-f61ba034-c742-40b1-8e1a-d2aef1767e8e.png)
> 
> supported GPUs in driver **3490** and above ![2022-10-26-121011_219x69_scrot](https://user-images.githubusercontent.com/76787191/198000045-828f2430-6417-48f9-a029-0884b4d26d98.png)
> 
> the deskopt variant (A770) has been added in driver 3490, that is why you get that error.

Hi, thanks for your precision ;)

**Comment by BigNish7** [comment] 2022-10-26 12:11
Hi @AntVNS - that was an interesting pick-up re the GPUZ screenshot in the TechPowerUp review. I went back to look at the article/screenshot and actually found they also included a screenshot of Arc Control immediately below the GPUZ image and I could just make out the VRAM Clock Tile indicating 2000MHz and the VRAM Effective Frequency Tile is showing 16.00 GTs  - (refer attached image - image property of TechPowerUp). Below the Arc Control image is a table showing max overclock values they archived and it lists both the A770 and A750 memory clocks at 2,000MHz. Curious.  

![image](https://user-images.githubusercontent.com/116610885/198019648-8abcd606-68e6-495d-b034-395a9a0fd985.png)

**Comment by AntVNS** [comment] 2022-10-26 16:50
I see, The gpuz with press driver show the intel advertise speed for the 16gb A770. But Arc control show de 2000mhz memory. 
It's can be a software bug or same bios as the 8gb version. Wait and see Intel investigation and solution

**Comment by BigNish7** [comment] 2022-10-27 03:24
Just to add another piece to the puzzle - not that it's really needed - but I looked at Kit Guru's review of the A770 LE 16GB. They have a screenshot of Arc Control in their section on Overclocking (section 33) which shows the VRAM Clock Tile indicating 2186MHz and the VRAM Effective Frequency Tile indicating 17.50 GTs - (refer attached image - image property of Kit Guru). They used the press issued driver version 101.3433 in their review.

![image](https://user-images.githubusercontent.com/116610885/198182859-9b5bc22a-91a2-4e71-bfda-9df0e8fbe10f.png)

**Comment by EstebanIntel** [comment] 2022-10-27 23:46
Hi all,

A fix for this issue is included with our latest driver version [31.0.101.3793](https://www.intel.com/content/www/us/en/download/729157/751349/intel-arc-graphics-windows-dch-driver-beta.html). Please update your driver to this version and test it!

**Comment by BigNish7** [comment] 2022-10-28 06:15
Looks like updating to 31.0.101.3793 fixed the VRAM speed for me! Will check playing games etc. Thank you Intel. 

I'm not certain if there is a preferred way to update to a Beta driver? I just downloaded the .exe and installed over the top of the .3940 driver. Perhaps the preferred option is to remove the old driver via Uninstall Programs in Control Panel? I am assuming the driver update in Arc Control will only look for WHQL drivers?

 
![image](https://user-images.githubusercontent.com/116610885/198516358-148fa3a6-9ace-4406-834e-e63ba387f855.png)

**Comment by AntVNS** [comment] 2022-10-28 07:05
HI EstebanIntel, thank for the fix with this beta driver, work for me too. 

![ArcA770fix](https://user-images.githubusercontent.com/95941187/198524669-0379e1fd-3050-4ff2-af3e-ec2f86daac60.gif)

**Comment by IGCIT** [comment] 2022-10-28 09:01
@BigNish7 installing on top is fine, if you want to perform a clean install of the driver, the installer offers an option for that

![Screenshot 2022-10-28 105725](https://user-images.githubusercontent.com/76787191/198548387-33bf87f3-4a60-4d22-bd06-a3372f69552e.jpg)
![Screenshot 2022-10-28 105741](https://user-images.githubusercontent.com/76787191/198548426-6c29b8b7-049c-4c50-8930-efe0124df3d5.jpg)

**Comment by IGCIT** [comment] 2022-10-28 20:15
closing since this is confirmed fixed on [31.0.101.3793](https://www.intel.com/content/www/us/en/download/729157/751349/intel-arc-graphics-windows-dch-driver-beta.html)

if the problem persists for some of you, feel free to reply here and it will be reopened
thanks

**Closed by IGCIT** 2022-10-28 20:15 UTC
Labels: Info: Needs Replication, Type: Support
