### ISSUE TITLE
Star Wars: The Old Republic Texture Tearing

### ISSUE THREAD

**Issue by victorpravdin** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#296] opened 2023-04-27 13:04 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Star Wars: The Old Republic

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [X] EA app
- [X] Other (please specify)

### Other game platform

It's an EA game but it uses its own launcher

### Processor / Processor Number [Required]

Intel i5-11600K

### Graphic Card [Required]

Intel Arc A770

### GPU Driver Version [Required]

- [ ] 31.0.101.4335
- [X] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [X] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11343681/igcit_ssu.txt)

### Description and steps to reproduce [Required]

If you set the graphics settings to Ultra by choosing the "Ultra" quality preset the texture tearing appears. It happens to all textures in the world, the easiest way to see it is on the character selection screen:
![234651452-f93860c3-e042-4951-8885-f0d00f95770d](https://user-images.githubusercontent.com/104219572/234868984-294357f1-8f48-4dcb-afc2-6dfc5fbb04b6.png)
Changing the "Texture anisotropy" in the graphics settings to Off removes the tearing.
Downgrading the driver to the version 4255 solves the issue of texture tearing so it's probably a regression. That version, however, has another [issue ](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/229) that is fixed in 4314 

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![image](https://user-images.githubusercontent.com/104219572/234869471-1d6b8281-53fd-44d6-a93b-07875b9f513a.png)

**Comment by Arturo-Intel** [comment] 2023-04-27 23:48
Hello @victorpravdin

Thank you for your findings!
We will replicate this in our lab, we will keep you posted!

-- r2

**Comment by Karen-Intel** [comment] 2023-05-05 20:45
Hey @victorpravdin is it Star Wars Knights of the Old Republic or Star Wars Knights of the Old Republic II: Sith Lords?

Ty

Karen

**Comment by Karen-Intel** [comment] 2023-05-05 21:40
@victorpravdin Gotcha. Ty for the clarification. Will get back soon

Karen

**Comment by Karen-Intel** [comment] 2023-05-08 23:00
Hey @victorpravdin just a quick update

I was able to reproduce the texture tearing with my 13900K system + ARC 770 + GFX v.4314
I am already reporting this behavior internally so please do not close this post in case I have updates
Just remember that fixes take ~3 to 6 months to be released :)

Thank you so much for your help! Talk to you soon

Karen

**Comment by Karen-Intel** [comment] 2023-05-16 18:55
@victorpravdin question, I saw there was a recent update in the game.
Can you check if the issue is still visible on your end?
Thanks a lot

Karen

**Comment by Karen-Intel** [comment] 2023-05-17 16:11
Hey @victorpravdin great news!

I did some tests with the driver [v.4369](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html) (released today) and the texture tearing is not visible anymore. I am adding some [evidence ](https://www.youtube.com/watch?v=LiNk-gvsufY)for v/4369 + v.4355 so you can see there is a visible difference.

Please give it a go! We also have a [new DDU ](https://www.guru3d.com/files-details/display-driver-uninstaller-download.html)version which we recommend to use for the upgrade

Hope to hear from you soon!

Karen

**Closed as completed** 2023-05-17 21:19 UTC
Labels: Bug Type: Graphical Corruption
