### ISSUE TITLE
Minecraft Java Lighting Issues, Freezing, and Performance.

### ISSUE THREAD

**Issue by EliezYT** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#368] opened 2023-06-28 07:42 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Minecraft Java Lighting Issues, Freezing, and Performance on intel Arc.

### Processor / Processor Number [Required]

Intel Xeon W-2145

### Graphic Card [Required]

Intel Arc A770 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [X] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

![2023-06-28_00 39 22](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/110901380/a7e4b894-e55b-4926-a38b-ce30a861db38)

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/110901380/4f493e8a-c2b2-430f-b8e5-29eacb2e364d

### Description and steps to reproduce [Required]

I can't seem to replicate it but when I open up the world sometimes it freezes minecraft and runs very slowly.

When you go to see the shadows and lighting in the game in caves on the stone and other blocks it's not how it's supposed to be it's doing it in big strips of shadows it doesn't effect lighter areas but in the caves it's pretty noticable. 

The fps constantly is very low and unstable at very reasonable settings which makes it hard to play competitive on Minecraft.

### Device / Platform

Windows 11 22H2 Desktop

### Crash dumps [Required, if applicable]

N/A

### Application / Windows logs

N/A

**Comment by Arturo-Intel** [comment] 2023-06-28 14:08
Hi @EliezYT!
Did you start seeing this behavior when you change to the latest driver?
And also, can you confirm if you use DDU to install the driver
Are you using the latest version of Minecraft Java?

I will start replicating this in the lab
-- r2

**Comment by EliezYT** [comment] 2023-06-28 17:13
> Hi @EliezYT! Did you start seeing this behavior when you change to the latest driver? And also, can you confirm if you use DDU to install the driver Are you using the latest version of Minecraft Java?
> 
> I will start replicating this in the lab -- r2

I have seen this behavior ever since I got my gpu I used the last release beta drivers the same issue happened.

I didn't use DDU to install the driver instead I updated within the intel arc driver software.

Yes this is the latest version of Minecraft Java 1.20.1.

Thanks for the communication I appreciate it!

**Comment by Arturo-Intel** [comment] 2023-06-28 17:15
Thanks for info, 
Can you try to use DDU and reinstall the latest driver?

--r2

**Comment by EliezYT** [comment] 2023-06-28 18:06
> Thanks for info, Can you try to use DDU and reinstall the latest driver?
> 
> --r2

I used a DDU to completely wipe my system of anything from my old AMD gpu and my new intel Arc drivers I even updated to the newest version of Windows 11 22H2 and the problem still remains.

The same weird shadows and the on and off freezing on loading up a world for the first minute still remains along with the very unstable fps.

Honestly I love the intel arc and what it does it has been a great card to me but this issue is pretty big.

But I'm sure you guys can find a fix for this thanks for the communication!

**Comment by Arturo-Intel** [comment] 2023-06-28 18:18
@EliezYT I understand your frustration, favorite game and is not looking good. 
I am asking if you use DDU so we can have a base to start debugging, it is part of our process :p

Do you any mods installed? and if you do, can you share the list? 

I will come back with news later, please lets keep this thread open until we have a fix

--r2

**Comment by EliezYT** [comment] 2023-06-28 18:29
> @EliezYT I understand your frustration, favorite game and is not looking good. I am asking if you use DDU so we can have a base to start debugging, it is part of our process :p
> 
> Do you any mods installed? and if you do, can you share the list?
> 
> I will come back with news later, please lets keep this thread open until we have a fix
> 
> --r2

I usually use Optifine only for better performance that's where I noticed the issue then I tried vanilla Minecraft with no Optifine and it was still there it's one of my favorite games I've been playing since my childhood and even older versions have their issues on it's own like other threads have stated.

I heard around 3 years ago intel dropped a update for their integrated graphics that made OpenGL games like Minecraft more buggy and unstable I hope there is a fix because many people within the intel Arc community play this game and have been facing simular issues.

**Comment by EliezYT** [comment] 2023-06-29 06:45
> > I heard around 3 years ago intel dropped a update for their integrated graphics that made OpenGL games like Minecraft more buggy and unstable I hope there is a fix because many people within the intel Arc community play this game and have been facing simular issues.
> 
> The full random color on the whole screen if you grab any item? (#230) This is already being worked right now, and it is a big issue specially because it affects ARC too and also bc a big chunk of the community is affected by this,
> 
> I will continue replicating this, and if I need more info, i will back to you
> 
> Thank you for sharing this issue and your patience --r2

Yes it was the full random color when you grab any item and I appreciate the communication this makes me happy I chose Intel Arc.

**Comment by EliezYT** [comment] 2023-07-05 19:33
> > I heard around 3 years ago intel dropped a update for their integrated graphics that made OpenGL games like Minecraft more buggy and unstable I hope there is a fix because many people within the intel Arc community play this game and have been facing simular issues.
> 
> The full random color on the whole screen if you grab any item? (#230) This is already being worked right now, and it is a big issue specially because it affects ARC too and also bc a big chunk of the community is affected by this,
> 
> I will continue replicating this, and if I need more info, i will back to you
> 
> Thank you for sharing this issue and your patience --r2

How is this issue going? Have you replicated it? Thanks for the communication!

**Comment by Arturo-Intel** [comment] 2023-07-10 17:51
Hi @EliezYT 
About the random freeze: I am still unable to reproduce this behavior, If you have more info about it that could help to replicate it, please share

FPS drop: I was able to run the game around 120FPS:
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/eb96d26f-e050-4b02-bdbe-55474edcb5bf)
There was at the beginning some bellow 90fps probably due the map loading. Can you share me your FPS numbers to compare?

Regarding the shadows corruption, do you have a img where the corruption is not shown? Also this behavior happens 100% of the time?

--r2

**Comment by EliezYT** [comment] 2023-07-13 07:21
> Hi @EliezYT About the random freeze: I am still unable to reproduce this behavior, If you have more info about it that could help to replicate it, please share
> 
> FPS drop: I was able to run the game around 120FPS: ![image](https://user-images.githubusercontent.com/92489452/252426974-eb96d26f-e050-4b02-bdbe-55474edcb5bf.png) There was at the beginning some bellow 90fps probably due the map loading. Can you share me your FPS numbers to compare?
> 
> Regarding the shadows corruption, do you have a img where the corruption is not shown? Also this behavior happens 100% of the time?
> 
> --r2

The corruption is not shown in brighter areas but places like the caves where it's dark it shows. In the video when I go closer to the surface it doesn't show. It happens every time I get into a dark area 100% of the time.

My gpu is maxing out as shown in the footage giving me around 20-70fps with very modest settings as shown in the video.

I found rings around the sky? They are green, orange, and purple? I have no idea why they are there I made sure to check older versions of the game it shows there as well. They are shown in the video and image in the sky.

With the random freeze at the beginning it happens 10% of the time I can't seem to capture it on video for some reason but it makes the game take 30 seconds to load up the world while I'm standing in the world. My gpu also is maxing out while loading the world during the freeze I have no idea why the gpu is maxing out so much during gameplay it's barely doing anything.




![2023-07-13_00 15 07](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/110901380/f4610a1b-9c1d-4023-96c7-187fbf8acd29)


https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/110901380/d68737e5-5048-404a-9dbb-4f9559c44450

**Comment by EliezYT** [comment] 2023-07-14 07:20
> Ok... so far this are the issues you reported
> 
> 1. shadows corruptions - I need from you a screenshot/video where the shadows are looking OK vs with the corruption.
> 2. FPS drops - I saw on the last video the FPS drops when you were looking to the mountain. also the artifact was there too. Can you share me the seed used to crate that instance?
> 3. "rings"/artifacts in the sky - Please share me the seed used to create this instance.
> 4. 10% of a freeze at loading the map - This is going to be a little difficult for me to reproduce. I will keep pushing on this.
> 
> Normally we will have one case for each of the issues above, but right now, lets focus on getting all the data so I can reproduce it at the lab.
> 
> Also, can you share how you set all the text info on screen? --r2

1. The Shadow Corruptions only appear in dark areas like caves. As you can see in the daylight it doesn't happen neither does it happen in the night time but in the caves where it's darker it shows.

![2023-07-14_00 09 39](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/110901380/235b10d9-c50d-482b-af69-43e0c5c0ca14)
![2023-07-14_00 10 28](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/110901380/16a86d63-9b75-4d47-91a4-5fe1fe5d11cf)
![2023-07-14_00 12 12](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/110901380/bfeb9d04-542d-43b1-aecb-762001ff1296)
![2023-07-14_00 12 25](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/110901380/5293cef6-07a0-4a90-9d5b-28cb0f5061ba)

In the cave where I placed the torch it no longer shows because of the higher level of light.

![2023-07-14_00 15 11](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/110901380/604bfd84-53b3-423e-8f83-8e25436e8fcf)

I dug a hole down and covered it up showing no light in this picture and it makes blocks look very odd.

![2023-07-14_00 07 55](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/110901380/fc2bce68-929c-4367-be1c-33b1b10c3972)

2. In this picture it shows the seed and to get all the info on the screen press F3 on the keyboard. The seed however doesn't really matter because this can be replicated in any world and in pretty much any version of the game.

3. The freezing in the game usually appears when loading up a world either for the first time or loading it up again it doesn't happen often so it's hard to replicate but it does happen.

4. The issue that wasn't mentioned is how the gpu keeps maxing out while playing no matter what world or version this happens.

Thanks for the communication!

**Comment by Arturo-Intel** [comment] 2023-07-19 17:28
> Can confirm for iris xe too

What of the 4 things we are dealing here?

**Comment by Arturo-Intel** [comment] 2023-07-19 19:21
@EliezYT Did you try 101.4575?
I was unable to reproduce the shadow corruption in this version. 
Also the 100% of GPU usage is being fixed
https://youtu.be/g1VGJMfsyHE

I am still working on the freeze reproduction. 

keep you posted.

--r2

**Comment by EliezYT** [comment] 2023-07-19 19:55
> @EliezYT Did you try 101.4575? I was unable to reproduce the shadow corruption in this version. Also the 100% of GPU usage is being fixed https://youtu.be/g1VGJMfsyHE
> 
> I am still working on the freeze reproduction.
> 
> keep you posted.
> 
> --r2
![2023-07-19_12 47 03](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/110901380/b3c2eb5d-beab-4afe-91cb-09d49e87540c)

Odd I can still reproduce it in caves? It's more noticeable the lower the brightness is as shown in this screenshot.

![2023-07-19_12 49 22](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/110901380/9e45729a-7a0b-4dbe-948b-fa94fd5a5add)
 

I have tried 101.4575 it's helped for some things with my system not really Minecraft though it is great that the 100% gpu usage is being fixed that means we can hopefully have a higher render distance than normal.'

The main issue that I'm facing still is the studder during the gameplay hopefully that can get fixed with the gpu usage going down but we will have to see.

**Comment by EliezYT** [comment] 2023-07-19 20:26
> @EliezYT Did you try 101.4575? I was unable to reproduce the shadow corruption in this version. Also the 100% of GPU usage is being fixed https://youtu.be/g1VGJMfsyHE
> 
> I am still working on the freeze reproduction.
> 
> keep you posted.
> 
> --r2

It's odd I can't update to the new drivers as far as I can see I'm still using the old beta driver version of 101.4575 not the brand new non beta version I used a ddu to completely wipe the driver from my system and yet it still says the driver was released on 7/11/2023.

I can't test if any of the issue are fixed because of this any suggestions?

**Comment by Arturo-Intel** [comment] 2023-07-19 22:11
What I do when I am not sure if the driver is not installed correctly, using DDU in safe mode, I install a old driver then again DDU in safe mode reinstall the newer one

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/5d1d9618-0402-47b8-8e4e-ef7a3aefb092)

It is from that date.

--r2

**Comment by EliezYT** [comment] 2023-07-20 04:19
> 

Alright I got it all sorted out and it still happens.

![2023-07-19_12 47 03](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/110901380/0c4f8eb7-9796-4b0b-b3e3-7cb20d14a2b3)
![2023-07-19_12 49 22](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/110901380/112156da-5fc5-4489-b19a-31fe2987a7ae)

You can really see it at lower brightness also the gpu is still maxing out but hopefully if fixed it can help some of the performance issues.

Minecraft Java still however needs to be optimized the whole opengl platform needs improvements on arc as a whole for office tasks, Minecraft, and emulators.

Thanks for the communication I don't want to get rid of my arc gpu because there is a lot of potential in this series for a amd gpu that has vastly improved opengl performance over intel arc I'm excited thanks for the help!

**Comment by Danjhop4** [comment] 2023-07-27 17:00
the lag and juttering as it lags out

**Comment by Danjhop4** [comment] 2023-07-27 17:01
@Arturo-Intel  the lag seems to be forcing gc

**Comment by EliezYT** [comment] 2023-08-01 09:01
I tried out Minecraft on Driver 31.0.101.4577 and the same issues persists. 

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/110901380/b4835ab4-833e-413d-9961-2dd2ff85928c

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/110901380/578dda86-f909-4f7f-9ae5-5dbd02f0b1e9

I also finally caught the Random Freeze I have had on video and as you can see I get very low fps when entering a world sometimes and can't even move a whole lot or at all due to the fps being 0fps-4fps. Upon further testing I concluded that this happens a lot when exiting and reopening the game on the task bar.

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/110901380/843e3e8c-b3ff-4bf6-aed5-413032140e1a

The shadows are still messed up.

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/110901380/2799d3ee-bb28-40cc-bf01-f1fbf88fe2dd

The rings across the sky is still there as well.

**Comment by Danjhop4** [comment] 2023-08-01 16:17
can’t update without windows update don’t have the perms to clean install drivers

**Comment by EliezYT** [comment] 2023-08-02 04:21
> can’t update without windows update don’t have the perms to clean install drivers

odd try to contact support or open a issue here on github about it.

**Comment by Danjhop4** [comment] 2023-08-05 09:48
@EliezYT i did they closed the issue since I could not update

**Comment by EliezYT** [comment] 2023-08-06 21:16
> @EliezYT i did they closed the issue since I could not update

That sucks.

**Comment by EliezYT** [comment] 2023-08-19 08:10
@Arturo-Intel I have updated to the newest driver and the issue still persists are there any developments on this? The poor OpenGL performance in both Minecraft and emulating old games is affecting lots of people right now.

**Comment by Karen-Intel** [comment] 2023-10-17 18:32
Hey @EliezYT we are unable to reproduce in newer systems using ARC A770, which prevents us from creating an internal report about the behavior you're experiencing. Additional to this, your [CPU does not meet the minimal requirements](https://www.intel.com/content/www/us/en/support/articles/000091128/graphics.html) leading to a configuration we cannot support in this forum. We'll proceed to close this issue until you are able to test with a supported configuration and you're welcome to reopen this thread.

@IGCIT can you help us close? Xeon CPU is not supported in a config with A770 and we are unable to support. Thanks

Karen

**Closed** 2023-10-17 19:44 UTC
Labels: Info: Needs Replication, Type: Bad Performance, Type: Graphical Glitches
