### ISSUE TITLE
Pirate101 - Crash to desktop when teleporting from skyways when using Arc GPUs

### ISSUE THREAD

**Issue by candersogithub** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#756] opened 2024-04-03 00:00 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Pirate101

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [X] Other (please specify)

### Other game platform

KingsIsle Entertainment

### Processor / Processor Number [Required]

i7-10710U

### Graphic Card [Required]

Intel Arc 750

### GPU Driver Version [Required]

31.0.101.5333

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [X] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14844395/igcit_ssu.txt)

### Description and steps to reproduce [Required]

When I refer to "zoning" or "teleporting", these are actions that lead to the game loading a new area. Moving from one area to another.

Issue is seen when:

- Zoning from one skyway to another
- Zoning from a skyway to an island in the same skyway
- Teleporting (either back to Skull Island, or back to where you marked your X)

There is nothing particular that you need to do cause this to happen, other than using an Intel Arc GPU. You just need to have access to enough of the game to be able to teleport or zone into different areas. It does seem to happen more frequently for me when in MooShu skyways, or when teleporting back to Skull Island. It does not happen every time. It happens ~10% of the time.

If I switch back to onboard Intel graphics or to my 1650 Super, the issue never happens.

Also, I realize I have a unique setup, using a 10th gen NUC with an eGPU with an Intel a750, but I have spoken to others that play the game and have Arc GPUs in a more standard system and they have the same problem.

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

3440x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/87734277/a1009de3-5ae8-4313-81bc-4b69d75d0dfa)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/87734277/160f8351-d15a-4cc7-a938-162c322c052a)

### Device / Platform name

NUCi710FNH

### Crash dumps [Required, if applicable]

[Pirate_r750351.Pirate_1_160.162058-0330.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14844783/Pirate_r750351.Pirate_1_160.162058-0330.zip)

**Comment by candersogithub** [comment] 2024-04-03 18:48
Please let me know if you need any more info or clarification. I know it is an obscure game, but it is one of the few games that I can play with my wife and kids, and we all have fun with it...except when dad's game crashes and they all have to wait for me :)

**Comment by Vivek-Intel** [comment] 2024-04-05 07:59
@candersogithub thanks for reporting the issue. Can you try updating the driver to latest one [101.5382](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)

**Comment by candersogithub** [comment] 2024-04-06 01:15
I upgraded to that version 2 days ago. I will let you know if it happens again.

**Comment by Vivek-Intel** [comment] 2024-04-11 05:58
@candersogithub if issue is not happening anymore, can we close this thread and you can reopen it.

**Comment by candersogithub** [comment] 2024-04-11 19:13
I haven't had much time to test this much with the new drivers, but I have played a little bit and have not had it crash since this posting. It's odd because the issue has been there since the launch of the a750, and I update drivers pretty much every month. I am ok with reopening this thread if it occurs again.

I am curious to know what was included in the last driver update that may have resolved the issue. Any insight there?

**Comment by candersogithub** [comment] 2024-04-12 04:34
Ok, the game crashed again on my tonight. It seems like there is much higher likelihood of crashing when you are navigating in the MooShu skyways. It didn't trigger the game to create a crash dump, it just crashed straight to desktop. Here is the regular game log that was updated just as it rashed.
[Captains - Copy.log](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14953987/Captains.-.Copy.log)

**Comment by Vivek-Intel** [comment] 2024-05-21 02:31
Hi @candersogithub we were unable to reproduce this issue with latest drivers. can you check and tell us exactly where do you see the issue consistently. You have mentioned that issue is inconsistent so would appreciate if you can point us exactly where the chances of occurring the issue are maximum.

**Comment by candersogithub** [comment] 2024-05-21 04:11
The issue is most frequent when you are in your boat in these skyways (Subata, Hamamitsu and Khotan Skyways) and either zoning into a neighboring skyway or teleporting out of those skyways (like back to Skull Island or back to where you marked your X). I have not encountered the issue since my last posting, but I have not been playing the game as much and definitely not in the 3 mentioned skyways.

I would be curious to know if you could reproduce the issue with an older driver, just to make sure your system is capable of reproducing the issue at all.

**Comment by vgs1993** [comment] 2024-06-04 12:26
@candersogithub we have tried couple of systems to check this issue but we could not reproduce the issue consistently. In fact we reproduce the issue only once on older driver but after that we did not see any crash on old or latest driver at all.

It is not possible for us to debug the issue without reproducing it in our lab more consistently. Please keep upgrading to latest driver and know that we will give few more trial to reproduce it before we close this issue as inconsistent game behavior.

**Comment by Vivek-Intel** [comment] 2024-06-04 12:56
@candersogithub we have tried couple of systems to check this issue but we could not reproduce the issue consistently. In fact we reproduce the issue only once on older driver but after that we did not see any crash on old or latest driver at all.

It is not possible debug the issue without reproducing it in our lab more consistently. Please keep upgrading to latest driver and know that we will give few more trial to reproduce it before we close this issue as inconsistent game behavior

**Comment by candersogithub** [comment] 2024-06-04 18:39
OK, well that is good news to hear it is more stable on newer drivers. I have not been able to play the game much recently anyway, so it is not something I have actively been checking on. Thanks for your support.

**Comment by Vivek-Intel** [comment] 2024-06-13 03:08
Hi @candersogithub, we need to close this issue as of now because it seems like inconsistent game behavior and very low repro rate. We will re-look into this issue if it is reproducible consistently across all systems.

@IGCIT please help close this thread as of now.

**Closed** 2024-06-13 07:58 UTC
Labels: Info: Needs Replication, Type: Application Crash
