### ISSUE TITLE
Sons of the Forest 1.0 Visual glitches into hard crash with latest drivers (.5330)

### ISSUE THREAD

**Issue by rpknotts3** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#719] opened 2024-02-24 22:39 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Sons of The Forest

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5 5600x

### Graphic Card [Required]

Arc A750

### GPU Driver Version [Required]

31.0.101.5330

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssulog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14394618/ssulog.txt)

### Description and steps to reproduce [Required]

Game runs fine for a few minutes, but then these artifacts/glitches appear, GPU usage hits 100%, and my game hard crashes.
Happens regardless of the games graphical settings or if FSR is on. I tried turning them down to ultra low, but it happened regardless.
I've tried with both DXVK 2.3 and just straight DX11, happens with both.

Videos and images:
https://www.youtube.com/watch?v=n_yLFbdacU8
https://www.youtube.com/watch?v=1CvO371uia0

![SonsOfTheForest_tRxVTKG6C5](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/129074709/f3785471-97e7-43ba-9808-bd96e04873cd)
![SonsOfTheForest_CfigYfAiC8](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/129074709/37d89b4e-1eb7-41d7-8780-1aebcfbe31f2)

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Happens on all settings.

**Comment by Karen-Intel** [comment] 2024-02-26 22:04
Hello again @rpknotts3 could you please share your save game?

I need it to add it to my internal report. Ty

Karen

**Comment by rpknotts3** [comment] 2024-02-26 22:33
Here's the most recent save that the issue has happened on, @Karen-Intel 
[2026220925.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14412034/2026220925.zip)

**Comment by Karen-Intel** [comment] 2024-02-28 19:24
Ty @rpknotts3 :) I will create an internal report for this issue and share the number here

**Comment by Karen-Intel** [comment] 2024-03-07 19:41
@rpknotts3 this issue is hiding from us preeetty hard xD
We've tried to reproduce it to no avail. We will continue debugging it and get back to you.
We'd appreciate your patience as it might take a little bit more time.
The initial report number is: 6147932

Karen

**Comment by rpknotts3** [comment] 2024-03-09 23:22
@Karen-Intel The artifacts/crashes usually would happen around the helicopter crash site (specifically this one in the woods, not on the beach or the mountain.)  
![crashsite](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/129074709/93b46130-0f7a-418a-9766-e183ca28b5f5)
The issue happened quite frequently in a multiplayer game with 4 people total (I was not host), but also happened once or twice in the solo world which save I sent.
The only real steps to reproduce were to spawn in, and just walk around for a moment until the visual issues and the crash. 

I will note, there was a hotfix to the game released about a week ago, and the patch note says
"Fixed a visual issue that would cause screen artifacts near the landed helicopter."
 So the issue might have been fixed on Endnight's side.
 However, that it says "landed" and not "crashed" makes me think it's referring to the ending of the game, rather than the spawn point.

I'll update to .5333, and retest in both solo and multiplayer.
Thanks for the work ya'll are doing on this.

**Comment by rpknotts3** [comment] 2024-03-10 02:12
Having updated to the latest driver (.5333) and tested in both solo (with a brand new save on the current patch) and multiplayer, I had the exact same issue at the forest crash site.

[Solo crash](https://www.youtube.com/watch?v=1zApGXBVn6g)
[Multiplayer crashes](https://www.youtube.com/watch?v=pK4HD-wKyfU)

**Comment by Pashamolochko** [comment] 2024-03-11 21:34
I have the same problem with the new driver, and the frequency of crashes is unpredictable, but the probability that it will fail is greater when you play in multiplayer, and there is also a very noticeable problem when many textures of stones or tents drop significantly FPS, while the load on the GPU rises, and at the same time falls Video card consumption from average 160W to 100W

**Comment by rpknotts3** [comment] 2024-03-12 14:43
> I have the same problem with the new driver, and the frequency of crashes is unpredictable, but the probability that it will fail is greater when you play in multiplayer, and there is also a very noticeable problem when many textures of stones or tents drop significantly FPS, while the load on the GPU rises, and at the same time falls Video card consumption from average 160W to 100W

Yeah, the performance of the game is generally unpredictable on ARC, with just overall weirdness depending on where you are on the map. Friends with Nvdia and AMD don't seem to have many problems in this vein. That said, I can play with weirdness, I can't play with crashes.

**Comment by Pashamolochko** [comment] 2024-03-21 11:46
in Driver 31.0.101.5379, the problem with the stones was solved on my system

**Comment by rmorera-intel** [comment] 2024-11-07 23:11
Hi everyone please re-test with our latest [driver 32.0.101.6130](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) since it introduces several fixes and improvements for DirectX 11 API.

**Comment by rmorera-intel** [comment] 2024-11-11 14:31
I'll temporarily close this one but if the issue persists please let us know.

**Closed by rmorera-intel** 2024-11-11 14:31 UTC
Labels: Info: Needs Replication, Type: Application Crash
