### ISSUE TITLE
Lots of power headroom in Cyberpunk 2077

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#382] opened 2023-07-05 19:10 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Cyberpunk 2077

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [X] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 05.07.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11961058/Intel.SSU.05.07.2023.txt)

### Description and steps to reproduce [Required]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44057002/1c91f59d-46cd-4c58-8aa5-dd3dc4652fd2)
Look at the screenshot: The GPU reports being at 99% load, draws 170 watts, but the power limit is set to 228W. It means that the card is drawing around a quarter less than it could, potentially meaning that **the performance is one quarter less than what it could be**.
I noticed that the further up XeSS's quality is, the more the card draws (W/O: 210W; Ultra quality: 195W; Quality: 187W; Equilibrated: 183W; Performance: 173W). Then, could this mean that the further XeSS's upscaling is, the more unused headroom there is?
I am absolutely sure this is not some kind of CPU bottleneck, because I have a 13600K, which is overkill for CP77; Task Manager **and** Riva Tuner Statistics Server report the GPU as being at ~100% while the CPU is at ~45%; Setting the crowd density to a lower setting does not change anything
Edit: Cyberpunk is the only game to do this to this extent, and the issue is caused by XeSS, so it's why I thought this would be more of Intel's fault rather than CD Projekt Red's, deeply sorry if I am wrong and it's actually CDPR's fault

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Already stated them

### Device / Platform name

ASUS Prime Z790 WiFi D4

**Comment by Karen-Intel** [comment] 2023-07-05 22:40
Hello again @TheWonderfulTartiflette :)

Let me check what's going on and if I can repro I will get back here

Stay tuned!

K

**Comment by TheWonderfulTartiflette** [comment] 2023-07-06 22:26
Hello, I didn't use CapFrameX, so sorry I don't understand what you want from it. Could you tell me what to screenshot?
No problem, here it is : https://1drv.ms/u/s!AmnzYyniwxuygaMCo0Kvv7d70t4-UA?e=epHLS8 (In the chronological order, in the video I used : Performance -> No XeSS -> Ultra Quality -> Quality -> Balanced -> Performance

**Comment by Karen-Intel** [comment] 2023-07-06 22:30
@TheWonderfulTartiflette ty

What is the tool you're using to monitor the wattage consumption then? 

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/91162218/edfc662d-c069-4217-bb1c-88beda5484bb)

I'm using CapframeX on my end but can't seem to get info in watts

Thanks

K

**Comment by TheWonderfulTartiflette** [comment] 2023-07-06 22:37
Ah sorry, I'm using MSI Afterburner, this is the software I always use for it. But HWiNFO reports the exact same power consumption.
Maybe I found the setting to get the info on power draw on CapFrameX, "GPU TDP(W)" seems to be it, and it reports as well the same power consumption

**Comment by Karen-Intel** [comment] 2023-07-06 22:41
@TheWonderfulTartiflette gotcha. Will get back to test, thank you

Karen

**Comment by TheWonderfulTartiflette** [comment] 2023-07-07 16:09
> @TheWonderfulTartiflette gotcha. Will get back to test, thank you
> 
> Karen

Thanks. I don't know if this can be due to the same issue as Cyberpunk, but in "The Long Drive", there is this same issue, but way worse. At ~100%, the card draws only 130W when it's power limit is at 228W, making the game run at 30FPS even though the settings aren't that high, and it's a very graphically simple game

**Comment by TheWonderfulTartiflette** [comment] 2023-08-12 20:26
Hellom qre there qny updqtes on thisM

**Comment by Ilya-intel** [comment] 2023-08-25 10:08
@TheWonderfulTartiflette 
Just tried Cyberpunk 2077 with 4644 driver and power draw seems stable around 220W. Could you test it with latest gfx driver again?
![Cyberpunk+4644-2](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/143084944/5405b545-1c30-4dbe-b6fd-66575a8a0612)

**Comment by TheWonderfulTartiflette** [comment] 2023-08-25 10:53
@Ilya-intel No, still the same behavior. What are the settings you have used? For my part, I was using everything set to max (Psycho, and with Psycho Ray Tracing but no Path Tracing) with XeSS Perf
Btw, I have mentioned in my post that without XeSS I'm getting around 210W of power draw, but the headroom appears especially when XeSS is enabled. The further I go to the performance setting with XeSS, the less it draws

**Comment by Ilya-intel** [comment] 2023-08-25 11:04
@TheWonderfulTartiflette 
Hmm, I've just tested XeSS On/Off and RT on/off, it always gives me around 220W.
What Arc FW version do you have currently? It can be checked in Arc Control (see below).
![ArcCFW](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/143084944/86e06c5d-24c5-4257-b575-84e97a767436)

**Comment by TheWonderfulTartiflette** [comment] 2023-08-25 11:05
@Ilya-intel Same as you : 
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44057002/29468685-d7b9-4c6f-886c-4f71d1df9542)

**Comment by Ilya-intel** [comment] 2023-08-25 11:48
@TheWonderfulTartiflette 
I see in SSU that you're using BIOS ver. 0810, there is newer version available on the Asus site
https://www.asus.com/us/motherboards-components/motherboards/prime/prime-z790-p-wifi-d4/helpdesk_bios/?model2Name=PRIME-Z790-P-WIFI-D4
Worth trying if the issue is related to power delivery.
BTW, which PSU are you using?

**Comment by TheWonderfulTartiflette** [comment] 2023-08-25 12:21
@Ilya-intel Just updated it to 0810, nothing changed. I'm using a ThermalTake Smart BM2 650W, should be plentiful for my PC

**Comment by Ilya-intel** [comment] 2023-08-25 12:55
@TheWonderfulTartiflette 
Let's move on. Have you tried disabling Vsync and any FPS limiters?

**Comment by TheWonderfulTartiflette** [comment] 2023-08-25 12:56
@Ilya-intel Indeed, I never use them

**Comment by Ilya-intel** [comment] 2023-08-25 13:10
@TheWonderfulTartiflette 
Do you see the same values when use Arc Control's Overlay (Alt+O)?

**Comment by TheWonderfulTartiflette** [comment] 2023-08-25 13:13
@Ilya-intel Yep, even with the new PresentMon

**Comment by Ilya-intel** [comment] 2023-08-26 14:58
@TheWonderfulTartiflette 
I've ordered Z790 board from ASUS to test it's power behavior. 
Should arrive next week, stay tuned.

**Comment by TheWonderfulTartiflette** [comment] 2023-08-26 15:09
> @TheWonderfulTartiflette 
> I've ordered Z790 board from ASUS to test it's power behavior. 
> Should arrive next week, stay tuned.

Thanks a ton

**Comment by Ilya-intel** [comment] 2023-08-31 11:00
@TheWonderfulTartiflette 
I managed to replicate the issue with the new board, what's interesting is that now old board also showing this behavior :)
BTW, RTX Card + DLSS also acting the same.
I'm currently checking what can we do in this case, and let you know (it can take some time).

**Comment by TheWonderfulTartiflette** [comment] 2023-08-31 12:23
Thanks a ton

**Comment by Ilya-intel** [comment] 2023-09-04 12:17
@TheWonderfulTartiflette 

I've got something for you.
The Arc GPU (and any GPU for that matter) will consume as much power as it requires to complete the current task (up to PowerLimit 1). And XeSS works by rendering frames in a lower resolution and then upscaling them. And, the lower the XeSS setting, the lower the original renderer frame. For example, if the user set their resolution to 1080p, the GPU will actually render the frame at these resolutions:


XeSS Setting | Original Frame Resolution for 1080p output | Original Frame Resolution for 1440p output | Original Frame Resolution for 2160p output
| --- | --- | --- | --- |
Performance | 960x540 | 1280x720 | 1920x1080
Balanced | 1120x630 | 1493x840 | 2240x1260
Quality | 1280x720 | 1706x960 | 2560x1440

So, when setting the resolution to 1080p + XeSS Performance, the GPU has to:
•	Render a 960x540 frame
•	Upscale it to 1440p

And when setting the resolution to 1080p + XeSS Balanced, the GPU has to:
•	Render a 1120x630 frame
•	Upscale it to 1440p

The second requires a little more work, since the rendered frame is of a higher resolution. So, the GPU needs to work a little harder and consume more power. 

Now, maybe the game is not that graphically demanding, and the GPU can do both without hitting the PowerLimit 1; so, you can actually see the difference in power consumption from one XeSS setting to another. So, you can then try increasing the output resolution or the graphics settings to push the GPU further. In that case, the GPU will be power throttled, consuming full power regardless of the XeSS setting.

I hope this helped. If not, please let me know.

**Comment by TheWonderfulTartiflette** [comment] 2023-09-04 19:31
I do understand that the GPU has to do more work to produce a frame of XeSS
balanced than XeSS performance, but what triggers me is that in both cases,
the GPU reports being at 100% utilization, so it should draw as much power
on both cases, no?

**Comment by Ilya-intel** [comment] 2023-09-05 07:09
@TheWonderfulTartiflette 
GPU could be busy by different tasks that requires different amounts of power, for example here we see 2 major tasks: rendering and upscaling, rendering consumes more power than upscaling and when GPU have to render bigger frame - it will consume more power, than for smaller frame, but in both cases utilization will be around 100% since there is also upscaling that happening in the same time.

**Comment by TheWonderfulTartiflette** [comment] 2023-09-05 07:52
So this means there's no issue?

**Comment by Ilya-intel** [comment] 2023-09-05 07:54
@TheWonderfulTartiflette 
Yep,
I've got confirmation that it's normal and expected.

**Comment by TheWonderfulTartiflette** [comment] 2023-09-05 07:55
Thanks, sorry for the inconvenience then

**Closed** 2023-09-05 07:56 UTC
Labels: Info: Replicated, Type: Bad Performance
