### ISSUE TITLE
Baldur's Gate 3 artifacts when enabling Blur (Vulkan)

### ISSUE THREAD

**Issue by RhanCandia** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#452] opened 2023-08-24 08:03 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Basldur's Gate 3

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [X] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

R5 5600

### Graphic Card [Required]

Arc A750

### GPU Driver Version [Required]

- [X] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12426975/igcit_ssu.txt)

### Description and steps to reproduce [Required]

1. Run game in Vulkan.
2. Go to Options and enable blur (Circular / Quarter Denoise)
3. Talk to any NPC and notice the artifact somewhere in the screen like so (see small artifact at the top, it stays there no matter what the scene is):
4. Optional: Enable Bloom and see it glow and make it even more distracting.
5. Optional 2: Enable FSR1.0 at any quality and you'll see a lot of flickering on character edges.

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/7951366/4e2ef3db-41dd-42a3-a1ae-f86994cc40ff)

And also, would it be possible for you to check with Larian and implement XeSS? FSR2.2 is coming next month. No word about XeSS. Intel, you are missing out. This game has become huge and XeSS not being here is a missed oportunity.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

1440p

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Only setting that matters:
Blur: Circular / Quarter or Quarter Denoise

**Comment by BiZkViT96** [comment] 2023-08-24 11:10
Judging by the type and the color of artifact is it because of PresentMon? Or bug is still there even without PresentMon?

**Comment by RhanCandia** [comment] 2023-08-24 13:45
> Judging by the type and the color of artifact is it because of PresentMon? Or bug is still there even without PresentMon?

The artifact has been there since Baldur's Gate 3 launched and I've only installed PresentMon today.

**Comment by Arturo-Intel** [comment] 2023-08-24 17:15
@RhanCandia hmm I can see it too, It only happens when the blur option is activated, right?
Will communicate this to our devs team.

--r2

**Comment by RhanCandia** [comment] 2023-08-24 17:50
> @RhanCandia hmm I can see it too, It only happens when the blur option is activated, right? Will communicate this to our devs team.
> 
> --r2

Thanks for acknowledging.

Yes, only when blur is enabled. Another bug is when blur is enabled, and you also enable FSR1.0, you get blocky flickering dark/shadow artifacts around your characters when in conversations.

Another issue is when on Vulkan mode, if you open your inventory or in party tab mode, you will see that the shadows casted on the characters are blocky and glitchy.

These issues don't happen in DX11 mode by the way. But performance is significantly lower when in DX11. So I always prefer Vulkan mode which offers 30 to 40% more frames but with some graphical issues.

**Comment by RhanCandia** [comment] 2023-08-26 04:25
Issue still persist in the latest 4669 driver and with BG3's latest patch (Patch 1).

**Comment by rmorera-intel** [comment] 2024-01-18 17:59
@RhanCandia can you please verify if the issue is still visible on our latest driver [31.0.101.5085/31.0.101.5122 (WHQL Certified)](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) ?

**Comment by rmorera-intel** [comment] 2024-01-23 20:05
Hi again @RhanCandia , I re-tested the game with the aforementioned driver and could not see the issue, hence I am closing this bug report now.

**Closed by rmorera-intel** 2024-01-23 20:05 UTC
Labels: Info: Replicated, Type: Graphical Glitches
