### ISSUE TITLE
Vulkan vkCreateDevice fails with ERROR_INITIALIZATION_FAILED

### ISSUE THREAD

**Issue by Neo-Zhixing** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#299] opened 2023-04-29 22:15 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Quake II RTX; All Vulkan games with VK_KHR_acceleration_structure enabled

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i9 10850k

### Graphic Card [Required]

Intel Arc A770 (16G)

### GPU Driver Version [Required]

- [X] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[aaa.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11360160/aaa.txt)

### Description and steps to reproduce [Required]

With VkAccelerationStructureKHR extension enabled, vkCreateDevice fails with return value ERROR_INITIALIZATION_FAILED.

![image](https://user-images.githubusercontent.com/8980455/235326298-e7fd734d-3629-44e8-8fd7-733d00a0ef4c.png)

Steps to reproduce:
1. Clone this repository: https://github.com/EmbarkStudios/kajiya , or download Quake II RTX on Steam, or any other repository that uses Vulkan Ray Tracing
2. On startup, Vulkan device creation fails with VK_ERROR_INITIALIZATION_FAILED
3. If you remove VK_KHR_acceleration_structure from the list of enabled device extensions, device creation succeed.

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

N/A

### Crash dumps [Required, if applicable]

Validation layer output:
terminator_CreateDevice: Failed in ICD C:\\Windows\\System32\\DriverStore\\FileRepository\\iigd_dch_d.inf_amd64_be925909b882ee5b\\.\\igvk64.dll vkCreateDevice call
vkCreateDevice:  Failed to create device chain.

**Comment by Arturo-Intel** [comment] 2023-05-05 21:15
Hi @Neo-Zhixing !
I try to use the kajiya repo but i found an compilation error that is already reported in their github site, so I went and use Quake II rtx instead. 

If I run the game with the defaults I can play the demo with out any error, so I assume VkAccelerationStructureKHR extension is not enabled or is not used.

I went to the video options and under ray tracing API there are 2 options with "KHR":
![image](https://user-images.githubusercontent.com/92489452/236569321-28b6faf9-51df-4fe5-b0d4-ecc81f521aac.png)
![image](https://user-images.githubusercontent.com/92489452/236569336-499d8134-b167-43a1-9606-b70d35450390.png)

I can play normally with both options
maybe I am missing something

Can you share your game configuration?
--r2

**Comment by Neo-Zhixing** [comment] 2023-05-11 20:23
@Arturo-Intel It seems that this was caused by a conflict between the Intel driver and the AMD driver. Uninstalling the AMD Driver made it work for me.

I used to have an AMD 6600XT GPU and when I replaced it with the Intel Arc A770, the AMD driver wasn't uninstalled.

It's not clear which driver caused the problem exactly. It would be great if can help reproducing this problem. Just install both GPUs at the same time and see if that causes any problems. I will also report this problem to AMD as well.

Thank you for your time helping with this!

**Comment by Arturo-Intel** [comment] 2023-05-11 21:36
oh ok, so there was 2 drivers installed (Intels and AMDs) now It makes sense that's why we recommend to use DDU to do a cleanup before installing a new driver/GPU. 

BTW that option was the one to enable the VkAccelerationStructureKHR structure?

I am glad you found the root cause.

**Comment by Neo-Zhixing** [comment] 2023-05-13 11:06
Technically both would be using VkAccelerationStructureKHR . In my case Quake RTX just crashes on start saying "Failed to create a Vulkan Device".

I would not say that "having two drivers installed" is the root cause tho. One (esp graphics programmers) might want to install both GPUs on the same system for easy testing. The AMD integrated graphics on the Ryzen 7xxx series might also conflict with Intel although I wasn't able to test it out.

Afaik Intel Arc and NVIDIA cards coexists on the same system without issues.

Let's keep this issue open in case other people run into this problem in the future.

**Comment by Arturo-Intel** [comment] 2023-05-15 17:03
I will create an article to share this to the community, also I need to confirm if having both drivers (AMD + Intel) should behave like this. 
> _I would not say that "having two drivers installed" is the root cause tho._
We can change this to drivers conflict, how about that?

 > _One (esp graphics programmers) might want to install both GPUs on the same system for easy testing._
Normally you want to tests your apps/games in a normal environment (only one driver installed) because is what your customer mostly will have.

**Comment by Arturo-Intel** [comment] 2023-06-01 15:28
@Neo-Zhixing if the issue is not present we can close this issue, we will document this in our knowledge database.

**Comment by Neo-Zhixing** [comment] 2023-06-07 00:29
Thanks. I will close this for now.

**Closed** 2023-06-07 00:29 UTC
Labels: Info: Needs Replication, Type: Application Crash
