### ISSUE TITLE
OpenMW not working well

### ISSUE THREAD

**Issue by Dredd893** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#760] opened 2024-04-09 09:50 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

OpenMW (https://github.com/OpenMW/openmw/releases)

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [X] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Amd Ryzen 7800x3d

### Graphic Card [Required]

Intel Arc 770

### GPU Driver Version [Required]

31.0.101.5382

### Rendering API [Required]

- [ ] Vulkan
- [X] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

Later

### Description and steps to reproduce [Required]

Just try to play the game. It has really low fps, I guess it's due to OPENGL.

Note: same issues appear if you use an Intel CPU (I tried).

By the way, the current workaround seems to be to use this one: https://www.reddit.com/r/OpenMW/comments/187q239/better_performance_on_intel_arc_windows/

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920*1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

All to maximum, apart from distance

### Crash dumps [Required, if applicable]

None

**Comment by Folstar** [comment] 2024-04-09 17:05
I had a similar experience with OpenMW on an Arc750. Performance was single-digit FPS until using the linked workaround, and then it was well above 100 FPS in most game areas.

**Comment by Nikaim** [comment] 2024-04-11 21:32
Use [mesa-dist-win](https://github.com/pal1000/mesa-dist-win). Get [mesa3d-24.0.5-release-msvc.7z](https://github.com/pal1000/mesa-dist-win/releases/download/24.0.5/mesa3d-24.0.5-release-msvc.7z) and put all files from x64 to OpenMW folder.

> I had a similar experience with OpenMW on an Arc750. Performance was single-digit FPS until using the linked workaround, and then it was well above 100 FPS in most game areas.
Use [mesa-dist-win](https://github.com/pal1000/mesa-dist-win). Get [mesa3d-24.0.5-release-msvc.7z](https://github.com/pal1000/mesa-dist-win/releases/download/24.0.5/mesa3d-24.0.5-release-msvc.7z) and put all files from x64 to OpenMW folder.

**Comment by DealsBeam** [comment] 2024-04-13 12:52
Also, you can try to use DXVK https://github.com/doitsujin/dxvk

**Comment by Nikaim** [comment] 2024-04-14 20:08
> Also, you can try to use DXVK https://github.com/doitsujin/dxvk

DXVK translate only DirectX render to Vulcan. OpenMW used OGL.

**Comment by zlice** [comment] 2024-04-15 12:53
there are some opengl regressions in kotor in [mesa 24](https://gitlab.freedesktop.org/mesa/mesa/-/issues/10863)

may be related. not sure if anyone tried old drivers to compare

**Comment by 4evrplan** [comment] 2024-06-14 18:47
I'm seeing the exact same performance issue with OpenMW using an Arc a750 (CPU is an i3-10100, 16 Gb of RAM [2x8 dual channel at 3200 MHz]). Using the mesa workaround helps immensely, but I believe it could be better with improved driver support for OpenGL and this would improve many other games as well.

**Comment by Dredd893** [comment] 2024-06-14 21:03
I was thinking today about this issue. I think that maybe the drivers will never support opengl and Intel is too focused on other stuff (and rightly so). Maybe when Battlemage will be out, we will have some sort of new.

**Comment by 4evrplan** [comment] 2024-06-14 21:29
I've said pretty much the same thing on Reddit, that Intel doesn't care about OpenGL, but another user asked me to add my voice here. I'm the guy that made the Reddit post you linked to, BTW.

**Comment by mujeeb-intel** [comment] 2024-08-02 23:06
Hey @Dredd893 Can you please provide me step-by-step instructions on how to download this application and how to replicate the issue? I want to try on the latest driver update. I remember something similar being fixed recently.

**Comment by mujeeb-intel** [comment] 2024-08-05 18:55
Hi @Dredd893 could you please let me know the steps for the above mentioned question?

**Comment by 4evrplan** [comment] 2024-08-05 19:50
> Hi @Dredd893 could you please let me know the steps for the above mentioned question?

@mujeeb-intel, I know you were asking Dredd, but I believe I can provide what you need. First, you'll need to install a copy of The Elder Scrolls III: Morrowind. Both Good Old Games and Steam usually have a good price on it. It looks like Dredd and I are both using the GOG version. Then, you'll need to download OpenMW from the OpenMW website and install it. When you run the launcher the first time, it will ask you where your copy of Morrowind is installed. They have much more complete instructions here: `https://openmw.readthedocs.io/en/latest/manuals/installation/index.html`.

**Comment by mujeeb-intel** [comment] 2024-08-05 20:29
Awesome! Thanks alot @4evrplan This will get me started, ill message you here if I have any questions.

Thanks, again!

**Comment by 4evrplan** [comment] 2024-08-05 20:41
@mujeeb-intel, I do have the latest driver installed, but I'm afraid it'll be awhile before I'm able to test my setup again and answer that question. It might not be today. If you don't already figure it out first, I'll try it out and get back to you when I can. Thank you for your patience.

**Comment by mujeeb-intel** [comment] 2024-08-05 20:46
Not a problem at all. Ill try to get the testing going with this.  @4evrplan  Thanks.

**Comment by Dredd893** [comment] 2024-08-06 16:27
> Hey @Dredd893 Can you please provide me step-by-step instructions on how to download this application and how to replicate the issue? I want to try on the latest driver update. I remember something similar being fixed recently.

Sorry Mujeeb, githhub didn't notify me. I read the mail only today.

**Comment by mujeeb-intel** [comment] 2024-08-07 21:48
No Worries @Dredd893 

@4evrplan so I went ahead and got it working. I gotta admit that first time installing was a headache running the mwopen. Steam forum came to the rescue thankfully.

But I went ahead and ran the game on the latest graphics driver, did not counter any stuttering. All the time it was either 75fps or 120+fps. Running at the highest settings. Felt pretty smooth to me.

 Do you see the same?

**Comment by mujeeb-intel** [comment] 2024-08-08 01:08
No worries. 

@Dredd893 you want to give it a shot? Looks like it's pretty smooth on my system.

**Comment by mujeeb-intel** [comment] 2024-08-12 16:38
I'll go ahead and close this ticket. If you think or see any issues, you can always refer back to this.

Thank you.

**Closed by mujeeb-intel** 2024-08-12 16:38 UTC
Labels: Info: Needs Replication, Type: Bad Performance
