### ISSUE TITLE
DX12 issues with Witcher 3

### ISSUE THREAD

**Issue by debjit-das** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#611] opened 2023-11-24 16:15 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Witcher 3 Wild hunt

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5 11400f

### Graphic Card [Required]

Intel Arc A750 LE

### GPU Driver Version [Required]

31.0.101.4972

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[W3Dx12Issue.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13460858/W3Dx12Issue.txt)

### Description and steps to reproduce [Required]

Terrain glitches in and around doorways/entrances and roads while using DX12. 

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

High Settings, No RT

**Comment by debjit-das** [comment] 2023-11-24 16:17
![screenshot_83124](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/33541606/188cc716-9187-4900-8758-0352b0f6d801)

**Comment by Arturo-Intel** [comment] 2023-11-29 18:22
@debjit-das can you share me a save file where the behavior is?

**Comment by Arturo-Intel** [comment] 2023-12-26 14:56
@debjit-das Can you help me with the save file where you see this behavior?

**Comment by Arturo-Intel** [comment] 2024-01-12 16:56
@debjit-das If you still seeing this behavior in the future, please open a new case.
Could not reproduce,
Closing this case.

**Closed by Arturo-Intel** 2024-01-12 16:56 UTC
Labels: Info: Needs Replication, Type: Graphical Glitches
