### ISSUE TITLE
Sound delay at the beginning off audio play back via Display Port

### ISSUE THREAD

**Issue by MarkD1212** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#458] opened 2023-08-27 09:03 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

MarkD1212

### Processor / Processor Number [Required]

12th Gen Intel(R) Core(TM) i7-12700K

### Graphic Card [Required]

Intel(R) UHD Graphics 770

### GPU Driver Version [Required]

- [X] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Other Windows build number

22621.2215

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12447623/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Display port on Dell S3221QS (I have updated to Dells latest firmware) which has built in speakers. 200-300 ms sound delay HDMI has no sound delay issue for me. This issue has been around a long time. Please refer to the following:

https://community.intel.com/t5/Intel-ARC-Graphics/The-card-has-delay-when-outputting-the-beginning-of-an-audio/m-p/1517935/emcs_t/S2h8ZW1haWx8dG9waWNfc3Vic2NyaXB0aW9ufExMUldDUlBKQ0ZJN0YwfDE1MTc5MzV8U1VCU0NSSVBUSU9OU3xoSw#M7227

https://www.reddit.com/r/IntelArc/comments/14g8cvy/if_you_want_to_report_bugs_to_intel_arc_engineers/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=2&utm_content=1

### Device / Platform

Asus z-690-A Windows 11 Pro Version 22621.2215

**Comment by TheWonderfulTartiflette** [comment] 2023-08-27 09:51
I confirm that I have been experiencing the same issue. It feels like the audio chip on the GPU shuts down when no audio has been played for a while, but takes some time to boot up

**Comment by MarkD1212** [comment] 2023-09-04 06:53
I have just updated to driver  31.0.101.4672, the sound issue appears to be resolved. I will confirm over the next week - thanks Mark

**Comment by TheWonderfulTartiflette** [comment] 2023-09-04 15:22
@MarkD1212 doesn't seems resolved for me, still the same issue (for me)

**Comment by TheWonderfulTartiflette** [comment] 2023-09-14 16:40
Any update on this? This is really annoying, and has been with me since I own my card

**Comment by MarkD1212** [comment] 2023-09-14 17:01
I have updated the driver to 4672 and sound delay issue resolved. I have loaded the new driver 4824 and all is OK as well. Could I suggest a fresh install, or a clean driver update?

**Comment by MarkD1212** [comment] 2023-09-26 09:11
I have done a clean install of Windows 11 with latest driver 4826. Sound is now in sync, but a very minor delay in starting occasionally on DisplayPort, Asus Z-690-A.

**Comment by TheWonderfulTartiflette** [comment] 2023-10-28 12:15
@MarkD1212 look at this : #566

**Comment by MarkD1212** [comment] 2023-10-29 02:40
Thanks for the update TheWonderfulTartifette - now it a Windows problem? Really.

> @MarkD1212 look at this : #566

**Comment by TheWonderfulTartiflette** [comment] 2023-10-29 07:57
Seems like yeah, I trust Intel employees here way more than on the Community Forums

**Comment by freak2fast4u** [comment] 2023-10-30 13:05
OP is on UHD 770 (Alder Lake iGPU), not Arc A770 :-)

Also using a DP connection, on Windows 10, Smplayer, foobar2000 or even youtube in firefox all work fine, meaning audio resumes as soon as I unpause any audio app after a few minutes. So it could totally be a Windows 11-specific problem. I'll be more vigilant about it in the following weeks in case I missed something, but I haven't witnessed this so far on my end. 

The only vaguely related thing I can remember was using VLC, on Windows 10, and the resume delay for the audio stream was < 1 sec (video resumed immediately), so it could be a completely different problem specific to VLC. I was also explicitely trying to reproduce this specific issue, so I probably wouldn't have noticed it if I wasn't looking for it. 

On an unrelated note, my Samsung TV exhibits the exact same problem you're describing with it's native youtube app (video resumes immediately, and audio resumes 5 seconds later, but is properly synced nonetheless) and it drives me insane, so if I had encountered it on my PC with Arc A770 I definitely would have noticed ;-)

**Comment by Gabriela-Intel** [comment] 2024-01-29 23:04
Hey everyone. This was supposed to be resolved with 23H2 (SV3) but there's still some reports of the issue occurring. Some folks in validation were also able to observe the issue after updating the OS. I've reopened the original bug for the team to investigate.

**Comment by Gabriela-Intel** [comment] 2024-07-31 21:09
Hi again folks. I'm going to ask that you all please report this to Microsoft. As previously mentioned, we've reported this but have not had any traction on it so we are forced to close the issue. Apologies in advance for this taking so much time for it to end up not being resolved.

**Closed by Gabriela-Intel** 2024-07-31 21:09 UTC
Labels: Info: Needs Replication, Type: Support
