### ISSUE TITLE
minecraft rtx performance issues and crashes

### ISSUE THREAD

**Issue by joelschwartz** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#193] opened 2022-12-14 18:37 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

minecraft bedrock windows 10 edition preview build

### Game Platform [Required]

- [ ] Steam
- [X] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

10700k

### Graphic Card [Required]

intel arc A770 16 gigabyte

### GPU Driver Version [Required]

- [ ] 31.0.101.3959 (*latest*)
- [ ] 31.0.101.3802
- [X] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H1
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Windows 10 21H1
- [ ] Other (Please specify)

### Intel System Support Utility report

none

### Description and steps to reproduce [Required]

The problems are that when you load the minecraft preview build and install the rtx worlds from the marketplace they can rarely load and will either crash or the screen will stay black screen. When I installed custom rtx packs the same thing would happen when I applied them to my personal worlds it could only load one in every 15 times. I do have a 3070 ti and it can crash on that gpu but it doesn't crash the same number of times compared to the intel arc gpu's. Even when the worlds load the performance was around 35-40 fps at 1080p with TAAU up scaling since it can't run at native resolution. 

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![Minecraft Preview 11_3_2022 12_40_51 PM](https://user-images.githubusercontent.com/22087235/207678075-ba9692b0-55ed-45a9-a91b-c0e653bc4759.png)
![Minecraft Preview 11_3_2022 12_46_32 PM](https://user-images.githubusercontent.com/22087235/207678181-7c3f78ba-710b-46e0-92ec-89e37653ba65.png)
![minecraft](https://user-images.githubusercontent.com/22087235/207678583-09a13e9b-7079-41ab-888c-e19595eadaba.jpg)

### Device / Platform name

windows 10

### Crash dumps [Required, if applicable]

none

**Comment by IGCIT** [comment] 2022-12-14 19:50
Hi, thank you for feedback, this is a duplicate of #190 and a fix will be released on a future driver update :)

see here for more details: https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/190#issuecomment-1346116221

if you want to add more info or findings about this issue, please do so in #190 

thank you

**Closed by IGCIT** 2022-12-14 19:50 UTC
Labels: Info: Needs Replication
