### ISSUE TITLE
ELEX 2 massive graphical issues

### ISSUE THREAD

**Issue by TimoMueller** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#115] opened 2022-03-02 16:01 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

ELEX 2

### Game Platform [Required]

- [X] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz

### GPU Driver Version [Required]
- [X] 31.0.101.4255
- [X] 31.0.101.4148 Beta
- [X] 31.0.101.4146
- [...]
- [X] 31.0.101.4090 Beta
- [X] 31.0.101.4034
- [X] 31.0.101.4032
- [X] 31.0.101.3975 Beta
- [X] 31.0.101.3959
- [...]
- [X] 31.0.101.3222
- [X] 30.0.101.1631
- [X] 30.0.101.1404
- [X] 30.0.101.1340
- [ ] 30.0.101.1191
- [ ] 30.0.101.1121
- [ ] 30.0.101.1069
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

will be provided later

### Description and steps to reproduce [Required]

Just start the game and you'll see the issue.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

1280x720

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Indifferent for this issue.
![20220302163313_1](https://user-images.githubusercontent.com/1918290/156399075-32d57c8a-16aa-4942-8518-663cc17ab16d.jpg)
![20220302163319_1](https://user-images.githubusercontent.com/1918290/156399078-eb104cf4-5e34-4845-8c24-7066bc2b7658.jpg)
![20220302163343_1](https://user-images.githubusercontent.com/1918290/156399081-e4d601c5-c7d7-4453-bece-72a85adc8784.jpg)
![20220302163409_1](https://user-images.githubusercontent.com/1918290/156399082-9724e8fa-9a9e-483b-b562-8c44be176010.jpg)
![20220302163442_1](https://user-images.githubusercontent.com/1918290/156399084-63517dbc-711d-49b8-8675-514dc4c13fe3.jpg)
![20220302163300_1](https://user-images.githubusercontent.com/1918290/156399089-7625dac4-bd2e-4a8c-81f8-825f4810cd3b.jpg)

### Device / Platform name

GPD Win 3

### Crash dumps [Required]

will be provided later

**Comment by TimoMueller** [comment] 2022-03-06 12:03
There is an interesting comment in #114 .
It seems that an older 27.* driver works with ELEX 2.

**Comment by nielo360** [comment] 2022-03-06 15:53
Its some sort of regression in vulkan that is causing this glitch/bug in ELEX 2 & Rage 2 that isnt in the present  27.20.100.8729 for the 1195g7 cpu.

**Comment by Risingdawn1** [comment] 2022-03-10 00:03
The black edge artifacting issue was still present in 27.20.100.8729, only the newer lighting issue was absent with older drivers. 

The black artifacting issue has been present on all Intel drivers, even for uhd chipsets going back to Elex 1 launch.

**Comment by TimoMueller** [comment] 2022-03-24 19:10
Issue is still present on *.1404 and *.1631

**Comment by estebanr863** [comment] 2022-04-26 22:16
Hi @TimoMueller 

This issue was already reported internally, and we are working on it. However, I do want to set the correct expectation that a possible fix may take from 3 to 6 month to be integrated into a public release driver.

**Comment by TimoMueller** [comment] 2022-08-04 00:16
Issue is still presen on *.3222. The DirectX 12 beta version crashes during startup.

**Comment by TimoMueller** [comment] 2022-12-24 06:06
Issue still present on *.3959 and *.3975 Beta.

**Comment by TimoMueller** [comment] 2022-12-30 14:47
31.0.101.4032 fixed one part of these issues that affected ELEX and ELEX 2.
Other graphical issues still present on DX11 version.

DX12 won't start on any driver version.

**Comment by TimoMueller** [comment] 2023-01-27 17:18
31.0.101.4090 didn't fix any of the remaining issues.

**Comment by TimoMueller** [comment] 2023-03-01 09:53
31.0.101.4146 didn't fix any of the remaining issues.

**Comment by Arturo-Intel** [comment] 2023-03-03 16:37
Hi @TimoMueller 

Did you run a [DDU](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html) clean install before installing any new driver?

4146 has been reported to fix a good amount of corruptions...

-r2

**Comment by TimoMueller** [comment] 2023-03-23 09:04
Tried DDU and still the same issues. Tried *.4148 Beta and there's no difference.

**Comment by TimoMueller** [comment] 2023-03-24 22:09
31.0.101.4255 didn‘t fix this issue.

**Comment by EstebanIntel** [comment] 2023-04-12 18:03
Hi @TimoMueller, unfortunately, due to the development team limited resources and needing to work on other higher priority game issues, this issue won't be fixed.

**Closed** 2023-08-31 17:38 UTC
Labels: Info: Replicated, Type: Graphical Glitches, Info: Won't fix
