### ISSUE TITLE
DXGI_ERROR_DEVICE_RESET when playing NFS Unbound

### ISSUE THREAD

**Issue by weebawop** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#640] opened 2023-12-14 15:13 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Need For Speed Unbound

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [X] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5-12500h

### Graphic Card [Required]

A370M

### GPU Driver Version [Required]

31.0.101.5074

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13674969/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Random crashes occur when playing (mostly online, doing linkups), the way they happen is the same but I get different errors on occasion, "getdeviceremovedreason" is the most common.

![Screenshot 2023-12-13 005955](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46519780/22bb1097-a3fb-4598-bc11-7c76fd3a7066)

<img width="408" alt="Screenshot 2023-12-12 181307" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46519780/04596edf-eb2e-4ec1-ba64-fc050f701e31">

Often this crash affects other programs, like sometimes discord will freeze/crash, or webview2 will crash etc. I always ensure I have plenty of free RAM before I open the game, not sure what the cause of the issue is

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1920x1200

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![Need for Speed™ Unbound 14_12_2023 18_17_10](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46519780/6f0d03cc-18f0-481a-9e2c-de8f14a970b3)
![Need for Speed™ Unbound 14_12_2023 18_17_18](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46519780/8120ad65-efb5-430f-98f2-50b5bacaebc9)
![Need for Speed™ Unbound 14_12_2023 18_17_23](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46519780/61b85542-9ee5-4a8f-bb60-4d7670f81b54)
![Need for Speed™ Unbound 14_12_2023 18_17_26](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46519780/860537a7-0ebe-47a7-8d85-2989720f2841)

### Crash dumps [Required, if applicable]

this is the dump generated by the game

[CrashDump_2023.12.14_17.54.06.059.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13674936/CrashDump_2023.12.14_17.54.06.059.zip)

**Comment by Ilya-intel** [comment] 2023-12-20 10:40
Hey @weebawop ,
I've played Unbound for several hours on a similar laptop and haven't faced such issues.
Could you try to use DDU to uninstall the current graphics driver and try a [newer](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) driver (5081) instead?

**Comment by weebawop** [comment] 2023-12-25 18:41
hello @Ilya-intel , I DDU and updated to the latest driver and the crashes feel even more frequent, I've had 3 today alone, the game will just freeze and then crash with no error or popup, the one that happened a few minutes ago happened when I was in a linkup

**Comment by weebawop** [comment] 2023-12-25 18:44
<img width="478" alt="image" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46519780/fcdb1249-8558-4f75-adae-76bf6f924300">

I also would like to note that the performance monitoring in arc control has been missing a few options in the latest drivers, mainly GPU VRAM usage, when I revert to the 4578 driver for example, all the monitoring options work again

**Comment by weebawop** [comment] 2023-12-25 19:46
<img width="343" alt="Screenshot 2023-12-25 222320" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46519780/0a4a26b6-292f-4989-a85f-b33a72661ffb">

just happened, this time it was after i'd just completed the final race in an online playlist, this happens often, after the final race the game crashes

**Comment by Ilya-intel** [comment] 2023-12-27 15:25
@weebawop 
Hmm, strange, just tested a few online races with another Laptop with Arc and still no issues.
Have you checked temperatures for overheating during game play?

**Comment by Ilya-intel** [comment] 2023-12-27 15:50
@weebawop 
BTW, do you have page file allocated automatically, or set up manually?
<img width="281" alt="image" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/143084944/31d58f04-0044-4d12-8be5-3035a4c76d76">

**Comment by weebawop** [comment] 2023-12-30 10:00
@Ilya-intel how do i tell if it's overheating? I play with my laptop on a cooling pad, and I monitor CPU temps they hover around the mid 70s, peaking at 80 sometimes. as for the pagefile it's set manually to 17.4 GB

**Comment by Ilya-intel** [comment] 2023-12-30 11:08
@weebawop 
80 is usually ok for laptop, even if GPU and CPU have common cooling pipes.
Could you try to set the page file to Automatic, then restart the laptop and try to play again?

**Comment by weebawop** [comment] 2024-01-16 14:22
hello @Ilya-intel , so setting the page file to automatic seemed to fix the issue for a few weeks, but now i'm experiencing another issue that has come out of nowhere, any time i crash into like a cop, the game will freeze and then crash, it's been happening the last 2 or 3 days consistently, especially in linkups. I don't know whether it's to do with the effects or what, I haven't changed graphics settings

this is a screenshot i grabbed after the freeze occurred
![Need for Speed™ Unbound 15_01_2024 17_58_00](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46519780/b79879e1-cf30-463e-919e-0373faaf5341)

**Comment by Ilya-intel** [comment] 2024-01-19 09:58
Hi @weebawop ,
There was a message for me here, but I couldn't see it.
Have you tried the page file adjusting?

**Comment by weebawop** [comment] 2024-01-19 12:53
hello @Ilya-intel , yes I had sent a message about a different crash I was having but I figured out the issue. Changing the page file setting to auto seems to have fixed the DXGI error thank you very much. Though I had another problem which is that the game's performance will drop off after a while playing online, instead of getting FPS in the 40s, it will drop to the low/mid 30s and sometimes the 20s. When this happens the GPU usage will also increase, from around 90% up to 97 98%, I've seen people say this happens due to a VRAM leak issue, are you able to investigate?

**Comment by Ilya-intel** [comment] 2024-01-26 09:44
@weebawop 
We've tested Unbound and it seems to work OK.
<img width="710" alt="NFS unbound test" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/143084944/619e4cad-f563-4f39-8e18-53d50340ec9c">

So, I'd advise checking the power settings of the laptop.

**Comment by Ilya-intel** [comment] 2024-02-12 09:11
Hey @weebawop ,
Any luck with Unbound?

**Comment by freak2fast4u** [comment] 2024-02-20 20:18
FWIW, I've just started playing NFS Unbound, and 1 hour into the game, it just silently terminated, no popups or anything. I'm using the 5330 drivers btw, with an A770. 

I should mention I have explicitely DISABLED the pagefile, because 32GB of RAM should be enough to hold Windows 10, the game, and a few services, no problem, so I will try with paging set to auto as suggested, however if there is a memleak, this will only delay the inevitable. Btw, @weebawop has stated that enabling paging in auto mode prevents a crash but slows the game to a crawl, which is still a hint to a possible memory leak. 

Here are both crash dumps (for the same crash, two .dmp files were produced) : 
[CrashDumps_nfs_unbound_freak2fast4u.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14350653/CrashDumps_nfs_unbound_freak2fast4u.zip)

Event viewer shows a virtual memory exhaustion multiple times, with NFS eating 16GB of RAM (well below the 32GB I have) : 
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3486369/82997867-29ff-4209-a042-2307bf7b22a1)

I will be running NFS Unbound again with some monitoring tools to see if I can spot a curve going to infinity and beyond ;)

NB : I'm using high settings, with XeSS enabled in Quality mode.

**Comment by freak2fast4u** [comment] 2024-02-20 21:39
VMMap gives me this timeline for the NeedForSpeedUnbound.exe process : 
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3486369/a2e4b5bc-7084-49b0-9f3d-2905fe88d90d)

Am I reading this wrong or is this a blatant memleak ? 

Here's the corresponding .mmp file : [NeedForSpeedUnbound_vmmap.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14351400/NeedForSpeedUnbound_vmmap.zip)

**Comment by freak2fast4u** [comment] 2024-02-21 20:13
With paging set to auto, I got to play a little less than 2 hours, with the same crash at the end : 

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3486369/dfe87ef2-b0b3-4fc3-b8ad-67c0258dafa7)

And a vmem exhaustion reported in event viewer (id 2004, source Resource-Exhaustion-Detector) : 
[event_vmem_exhausted_pagefile_is_auto_evtx.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14364528/event_vmem_exhausted_pagefile_is_auto_evtx.zip)

**Comment by Ilya-intel** [comment] 2024-02-23 09:55
@freak2fast4u 
Welp, I've spent 2 hours in the game (online and solo) and no crashes, hangs, memory leaks....
Thanks for sharing logs, I'll try to figure out the root cause.

**Comment by Ilya-intel** [comment] 2024-04-04 09:03
@freak2fast4u @weebawop 
Could you try the latest 5382 driver?
I still cannot replicate this issue.

**Comment by freak2fast4u** [comment] 2024-04-04 23:22
@Ilya-intel : Just spent the evening playing, no mem/vmem leaks, no crashes, no visual glitches.
Something new though ... my usb keyboard was laggy, sometimes wouldn't register key presses, and sometimes would repeat them like 10 times until it stopped (even though I didn't press the key 10 times). Not sure if it's an issue with some game update or how the driver interacts with the system yet, though I haven't rebooted my system in a few days. Will give it another shot tomorrow. Will also double check Process Lasso isn't acting up (my system generally works better with it than without, but you never now ...). 
Catch you later :)

**Comment by freak2fast4u** [comment] 2024-04-09 13:47
Alright, new test today, the first few minutes are sluggish, then the performance stabilizes. I'm not sure why, I don't remember having this problem when I first tried the game a few months back, I'll look into it further.

**Comment by freak2fast4u** [comment] 2024-04-21 15:58
A few days later, and even on latest 5444 beta, everything's working fine, no problems here. 
Something was definitely solved since this issue cas created. 

@weebawop : how about you ?

**Comment by Ilya-intel** [comment] 2024-05-02 09:33
@freak2fast4u Thanks for confirming!

@IGCIT I guess we can close this one.

**Closed** 2024-05-02 11:20 UTC
Labels: Info: Needs Replication, Type: Application Crash
