### ISSUE TITLE
Performance issues with House Flipper 2 

### ISSUE THREAD

**Issue by GottaSlay** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#670] opened 2024-01-12 17:47 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

House Flipper 2

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 7 5800X3D

### Graphic Card [Required]

Acer Intel Arc A770 Predator BiFrost OC

### GPU Driver Version [Required]

31.0.101.5085

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13922451/igcit_ssu.txt)

### Description and steps to reproduce [Required]

https://www.youtube.com/watch?v=r8NYlYqvvCI A video of me showcasing the performance of the game with both Very Low and Ultra Quality graphics presets. The game runs at a low fps regardless of the graphics settings.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

3440x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/43540181/846635d1-2be6-4d2a-a092-7172dd2ef2d2)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/43540181/11ad0097-a565-4990-a761-c1d3250b78b9)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/43540181/241c519f-ad41-4ea9-98ee-5da6bcfaf6c0)

**Comment by GottaSlay** [comment] 2024-01-19 00:46
I've just tested the game with DXVK and the framerate nearly doubles.

**Comment by Ilya-intel** [comment] 2024-01-24 13:03
@GottaSlay 
I also see performance issues with HF2.
There is intensive work on perf improvements for DX11 titles happening now.
I'll let you know when the fix will be published.

**Comment by GottaSlay** [comment] 2024-10-22 16:49
Hey, I no longer have the card installed in my system so unfortunately I cannot test. Hopefully someone else can report :)

**Comment by Ilya-intel** [comment] 2024-10-29 09:26
I'll be closing this thread since the issue is gone now.

**Closed by Ilya-intel** 2024-10-29 09:26 UTC
Labels: Info: Needs Replication, Type: Bad Performance

**Comment by GottaSlay** [comment] 2024-11-10 20:33
Just came to let u guys know that the game does know run significantly better! As well as some other DX11 titles.
