### ISSUE TITLE
MechWarrior 5 : Blank screen in game with DX12 mode

### ISSUE THREAD

**Issue by Saracchini** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#74] opened 2021-08-11 18:26 UTC
#### Checklist [README]

- [x] Device is not undervolted nor overclocked.
- [x] Device is using the [latest drivers](https://downloadcenter.intel.com/download/30381/Graphiques-Intel-Pilotes-DCH-Windows-10).
- [x] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Required]

---
#### Game Platform [Required]
- [x] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Other

---
#### Processor / Processor Number [Required]

Intel i7 1165g
---
#### GPU Driver Version [Required]
- [x] 30.0.100.9805 (*latest*)
- [x] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

---
#### Rendering API [Required]
- [ ] Vulkan
- [ ] OpenGL
- [x] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

---
#### Windows Build Number [Required]
- [ ] Windows 11 (*Insider Preview*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [x] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (*Please specify your build number*)

---
#### Description and steps to reproduce [Required]

In launch options, add "-dx12"

1.  Start Game and choose Single-Player mode
2.  Choose Instant Action
3. Select a map
4. Start the game
5 . Screen is totally blank or heavily tinted

---
#### Device / Platform [Optional][Recommended]

GPD WIn3 i7 1165g. Stock TDP (25-28W)

---
#### Game Settings [Optional][Recommended]

---
#### Save game (*if possible, could help solve the issue faster*) [Optional]

---
#### Windows mini dump (*small memory dump*) (*if available*) [Optional][Recommended]

---
#### Game custom logs (*if available*) [Optional][Recommended]

![Capture2](https://user-images.githubusercontent.com/18572281/129083104-7bdfa166-c62b-493f-b38e-ca3c45e2101b.PNG)

**Comment by RSaracchini** [comment] 2021-08-12 08:16
I found more details about the issue.
The Heavy tinting/Blank screen issue happens in maps with atmospheric effects (fog, snow, etc). If clear weather is selected, gameplay is smooth (better performance than using DirectX11) and no issues happen.

**Comment by RSaracchini** [comment] 2021-08-13 08:22
Another update: If one switches graphic options in-game (for instance Special effects), the blank screen issue disappears until someone starts a new map.

**Comment by RSaracchini** [comment] 2021-08-14 10:02
Testing configs shows that issue does not happen if one sets Graphics Effects to High or Ultra. With certain atmospheric effects the screen is totally opaque with Low and Medium Graphics Effects.

**Comment by Saracchini** [comment] 2021-08-22 15:20
Cannot reproduce the issue in Beta 9862. Even with Low Graphic Effects I cannot see the heavy tint, Opaque glitch screen. I'll keep testing but issue **seems** fixed.

**Comment by Saracchini** [comment] 2021-08-24 14:43
After a more throughful test, I found out some biomes do show issues yet depending on the Graphics Effects option:
 - Volcanic biome (hellstorm weather). Graphics Effects: Low
 - Forest Autumn (deluge weather). Graphics Effects: Medium
 
 There's a heavy screen tinting or some visual artifacts. Usually it is easily solvable by going into the graphics options and switching between Low/Medium. issues happen more often with Low effects. 
![mech5_autumbiome2_deluge](https://user-images.githubusercontent.com/18572281/130637700-1c89d651-4361-445e-a414-f48115460cc7.png)
![mech5_volcanicniome_hellstorm](https://user-images.githubusercontent.com/18572281/130637714-64bc75d5-c289-44e8-a396-1a44d812e109.png)
![mech5_volcanicniome_hellstorm2](https://user-images.githubusercontent.com/18572281/130637720-c6f14f2b-f718-4e1e-a716-c73871bf5c5b.png)

**Comment by Saracchini** [comment] 2021-09-11 10:24
Issue persists with 9864 but in a less often. Sometimes the game show up correct graphics, sometimes it shows totally random artifacts. Effect can be reproduced by changing Graphics Effects quality. This issue seems quite common with latest DirectX12 Unreal Engine games.

**Comment by Saracchini** [comment] 2021-11-11 17:46
Graphic Issues persist with latest 1069 driver.

**Comment by Saracchini** [comment] 2021-11-17 17:08
Graphic Issues persists with latest 1121 driver.

**Comment by estebanr863** [comment] 2021-11-23 22:28
Hi @Saracchini, can you please help us perform a quick test and press _Alt-Enter_ when you get the issue to go back to the desktop, and then press those same keys again to return to the game?

**Comment by Saracchini** [comment] 2021-11-24 09:47
Certainly.
I did the test and when switching between screen modes with ALT+ENTER, the issue is gone, and returns when returning to fullscreen bordererless. Curiously, If you  switch from a good state in fullscreen borderless, the windowed one will be bugged instead, and return to a good state when you switch back.

I also have a seed for a map that the issue happens very consistently: MDMxNjY5ODQwMTY5NDcxMDQw

![mech5-scene](https://user-images.githubusercontent.com/18572281/143214400-f0f8d2b6-98ac-49e5-a382-f94d45b84e1f.jpg)

On a side note: I tested with The Ascent and the same behavior occurs. I'll be reporting it in that issue too.

**Comment by estebanr863** [comment] 2021-12-06 20:42
Hi @Saracchini, we have confirmed that the root cause of this issue is the same as the one on #78. The fix is in development, so I'll let you know when it is included in a driver release

**Comment by Saracchini** [comment] 2022-02-08 15:19
Issue persists in 1340 driver.

**Comment by estebanr863** [comment] 2022-07-28 22:29
Hi @Saracchini,

A possible fix for this issue has been included in the[ latest driver](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html) version 30.0.101.3222. Can you please test it and let us know?

**Comment by Saracchini** [comment] 2022-07-29 13:18
Issue was not solved in 3222. The behaviour, If anything, it got worse, as I can see the visual glitches in the mission setup screen, which never happened before. In certain cases, staying long on this screen causes also a TDR.
The in-mission glitches also happen as in previous drivers.

**Comment by Saracchini** [comment] 2022-10-27 15:20
Tested with 3790, clean install.
Issue persists. I do not managed to get a TDR on the mission setup screen, which was intermittent in 3729 to the point of being unplayable in DX12.

**Comment by Saracchini** [comment] 2023-03-01 12:48
Issue still persists on 31.0.101.4146.

**Comment by EstebanIntel** [comment] 2023-03-07 23:13
Hi @Saracchini, unfortunately, due to the development team limited resources and needing to work on other higher priority game issues, this issue won't be fixed.

**Closed** 2023-08-31 17:43 UTC
Labels: Info: Replicated, Type: Graphical Glitches, Info: Won't fix
