### ISSUE TITLE
Spotify with hardware acceleration on exhibits graphical glitching when GPU is under heavy VRAM load

### ISSUE THREAD

**Issue by willamettefour** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#206] opened 2022-12-27 04:20 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Spotify

### Processor / Processor Number [Required]

i5-12490F

### Graphic Card [Required]

ASRock Arc A770

### GPU Driver Version [Required]

- [X] 31.0.101.3975 (*latest*)
- [X] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Windows 10 21H1
- [ ] Other (Please specify)

### Intel System Support Utility report

[intel_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10304540/intel_ssu.txt)

### Description and steps to reproduce [Required]

1. Place GPU under a significant memory load (>6GB of usage seems to reliably cause the issue on my 8GB card)
2. Open Spotify after minimizing

Side note: OCCT with hardware acceleration also exhibits the same issue. Other programs with hardware acceleration like Discord don't.
![Spotify_3gOCx4Fs0u](https://user-images.githubusercontent.com/94886283/209577781-b73435b4-36b0-48d6-b39b-844aa703e7ab.png)

**Comment by IntelSupport-Arun** [comment] 2022-12-27 08:54
Hi @willamettefour ,
Thank you for reaching out to our support.
Could you try To tune the Intel® Arc™ performance parameters on Arc Control and see any improvement by following the below steps:

1. Click the Performance tab on Arc Control
2. Click the Configure button
3. Move the corresponding slider to tune the parameter you want. You can tune multiple parameters.
4. The available parameters are:

GPU Performance Boost: Adjusts voltage and frequency characteristics to improve performance while staying within the same power limits. This feature may cause system instability.
GPU Voltage Offset: Allow for manual control of voltage by applying a positive offset in millivolts.
GPU Power Limit: Set a limit for maximum power consumed by the GPU
GPU Temperature Limit: Set a maximum temperature limit that the GPU should not exceed

5. Toggle the Apply setting on system boot switch to allow Arc Control to apply the new configured values every time your system boots.

Please give a try and let me know your observations.

**Comment by willamettefour** [comment] 2022-12-27 18:37
Upping the voltage didn't fix it (i tested by increasing it in 10mV steps and rebooting after each change). Also, I don't know if this is expected behavior, but the clock speed rose steadily as voltage increased despite GPU Performance Boost remaining at 0.
![10mV](https://user-images.githubusercontent.com/94886283/209708492-7b6a0340-1eef-402f-b7c8-38dfe505fb1b.png)
![30mV](https://user-images.githubusercontent.com/94886283/209708500-eb5a9654-0ae3-44b2-91be-c4cc670cc17f.png)
![50mV](https://user-images.githubusercontent.com/94886283/209708474-b4621cff-a6a4-491f-a042-5d3698309fd5.png)
![70mV](https://user-images.githubusercontent.com/94886283/209708473-90feae6c-f601-4728-a524-05ced55c38b7.png)

**Comment by IntelSupport-Arun** [comment] 2022-12-28 10:51
Hi @willamettefour ,
Thank you for the try and update.
I have the following questions to you for further investigation:
1. May I know what are the applications you are running along with Spotify? Please specify if any
2. Are you forcing the GPU load? I would like to know the exact steps to reproduce the issue.
3. Please set the power plan to "High Performance" and see if the issue is happening or not

**Comment by willamettefour** [comment] 2022-12-28 17:57
1. No other programs need to be running in the foreground in order to cause the issue. I've attached a list of all the running processes before applying the VRAM load
2. I have been using OCCT to force a load on the VRAM in order to replicate the issue. Setting the Memory slider under Test -> VRAM to 80% seems to reliably cause Spotify to start glitching out. The duration of the test doesn't seem to matter. I originally experienced the issue while running DaVinci Resolve, which used ~7GB of VRAM
3. The High Performance power plan does not fix the issue
[Running-Process-List.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10315632/Running-Process-List.txt)

**Comment by IntelSupport-Arun** [comment] 2022-12-30 09:09
Hi @willamettefour ,

Thank you for the update and details.
, There is a new ARC driver [31.0.101.4032](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html?) has been released but we recommend you to do a fresh installation of OS & [Clean installation for graphics driver](https://www.intel.com/content/www/us/en/support/articles/000057389/graphics.html) this time .
Also, please uninstall the Spotify app and re-install it. 
Please give it a try with the latest driver and update the result.

**Comment by willamettefour** [comment] 2022-12-30 21:44
A clean install of Windows 11 22H2 (22621.382) and driver 4032 did not fix it

**Comment by IntelSupport-Arun** [comment] 2023-01-04 08:08
Hi @willamettefour ,

Thank you for the update from your side.
I have verified the issue on our side and able to reproduce the issue with the latest graphics driver [31.0.101.4032](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html?).
We will be working on a fix and will share you once it's fixed. I want to give you a heads-up that the fix may take 3 to 6 months to be included. Please stay tuned.

**Comment by Arturo-Intel** [comment] 2023-04-25 17:37
hello @willamettefour,

Can you try with the latest stable driver?  [4255](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html) 

I was unable to reproduce this behavior

--r2

**Comment by willamettefour** [comment] 2023-04-25 22:31
I haven't tested with the latest stable drivers yet, but it appears that the issue is no longer present in beta driver 4311

**Comment by Arturo-Intel** [comment] 2023-04-25 22:36
Glad to read that! @willamettefour!

@IGCIT can we close this case?

**Closed** 2023-04-26 04:49 UTC
Labels: Info: Needs Replication, Type: Graphical Glitches
