### ISSUE TITLE
Far Cry 6 Crash within 10-20 seconds, major graphical glitches 

### ISSUE THREAD

**Issue by Combine1196** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#86] opened 2021-10-08 03:32 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Far Cry 6

### Game Platform [Required]

- [ ] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [X] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Other (please specify)

### Processor / Processor Number [Required]

1165i7

### GPU Driver Version [Required]

- [X] 30.0.100.9894 (*latest*)
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 (*Insider Preview*)
- [X] Windows 10 21H2 (*Insider Preview*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Description and steps to reproduce [Required]

Game has extreme major graphics rending issues. Unable to see anything and crashes within a few seconds and has low frame rate.

### Device / Platform

GPD Win 3 1165i7

### Game Settings

Lowest settings 
.80 resolution scale

**Comment by estebanr863** [comment] 2021-12-31 16:25
Hi @Combine1196, can you please provide captures of the corruption you are seeing?

**Comment by Combine1196** [comment] 2021-12-31 20:04
Sent from Yahoo Mail on Android 
 
  On Fri, Dec 31, 2021 at 11:25, ***@***.***> wrote:   


Hi @Combine1196, can you please provide captures of the corruption you are seeing?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by estebanr863** [comment] 2022-03-09 20:13
Hi @Combine1196,

Regarding the crashing issue, a posible fix for this has been included in the [latest drivers](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html).

On the graphical gliches issue, we were able to reproduce this issue and found that its root cause to be on the game side. We have already escalated this issue to the game developer, but now is up to them to fix the issue.

**Comment by estebanr863** [comment] 2022-04-05 16:09
Hi @Combine1196, can you please update to the [latest drivers](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html) AND update your game to the latest version, and test if the issue is still present?

**Comment by estebanr863** [comment] 2022-04-12 22:25
Hi @mva94, @IGCIT and @Valkirie,

We are not ssen this issue on the latest drivers and @Combine1196 is not responding. Can this be closed?

**Closed** 2022-04-13 07:34 UTC
Labels: Info: Needs Replication, Type: Application Crash
