### ISSUE TITLE
Age of Empires IV problem with shadow circles

### ISSUE THREAD

**Issue by Pawels1992** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#182] opened 2022-11-11 19:39 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Age of Empires IV

### Game Platform [Required]

- [ ] Steam
- [ ] Origin
- [X] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 9 3900

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [ ] 31.0.101.3793 (*latest*)
- [ ] 31.0.101.3491
- [X] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1 (*October 2021 Update*)
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

[skan.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/9992865/skan.txt)

### Description and steps to reproduce [Required]

<img width="918" alt="Zrzut ekranu_20221111_202032" src="https://user-images.githubusercontent.com/118018071/201416572-964bcdaf-cb66-49cc-9a78-0ba491f4dd34.png">

When Resolution Scaling is set to 100% there are problem with shadow circles. The same problem is with stable driver .3490 and with new one .3793. Circles disappear only at 30% resolution scale. 

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

3840x2160

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

All setting set to Ultra/High

**Comment by IntelSupport-Arun** [comment] 2022-11-16 14:06
Hi @Pawels1992 ,
We are looking into this issue and will update you soon.

**Comment by IntelSupport-Rozilah** [comment] 2022-11-18 03:27
hi @Pawels1992,
There is new beta release, could you try it [31.0.101.3802](https://www.intel.com/content/www/us/en/download/729157/intel-arc-graphics-windows-dch-driver-beta.html), let me know your finding.

**Comment by Pawels1992** [comment] 2022-11-19 12:30
Hi! Unfortunately, it didn't solve the problem. Circular shadows disappear when changing the resolution scale or setting the image quality to low (picture 1). 
<img width="765" alt="Zrzut ekranu_20221119_130532" src="https://user-images.githubusercontent.com/118018071/202850882-91d41deb-6278-4c66-988a-e26771ab0519.png">
<img width="768" alt="Zrzut ekranu_20221119_132255" src="https://user-images.githubusercontent.com/118018071/202850885-7e915fcf-ec42-4cfc-9fe0-38c0eab4714d.png">

**Comment by IntelSupport-Arun** [comment] 2022-11-23 05:55
Hi @Pawels1992 , You mean the issue is fixed only by changing the resolution scale or setting the image quality to low? 
What about the other Game graphic quality High and Medium, are you observing the issue? please confirm

**Comment by IntelSupport-Rozilah** [comment] 2022-11-30 06:36
hi @Pawels1992,
The case has been verified on our side and we are able to reproduce it with our configurations as below:
Processor: AMD Ryzen 7 5800K 8-core
Graphic Driver version: 31.0.101.3802
We will be working on a fix. I want to give you a heads-up that the fix may take 3 to 6 months to be included.

**Comment by Pawels1992** [comment] 2023-01-04 13:36
Hi! New driver .4032 fixed this problem!

**Closed** 2023-01-04 19:54 UTC
Labels: Info: Needs Replication, Type: Graphical Glitches
