### ISSUE TITLE
Arc Control won't remember its settings between reboots

### ISSUE THREAD

**Issue by yetdragon** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#336] opened 2023-06-05 09:11 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel Arc Control

### Processor / Processor Number [Required]

13th Gen Intel(R) Core(TM) i5-13500

### Graphic Card [Required]

Arc A770 LE

### GPU Driver Version [Required]

- [ ] 31.0.101.4382
- [X] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Other Windows build number

22621.1778

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11650673/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Intel Arc Control does not remember its settings between reboots in most cases (I wrote "in most cases" because it sometimes remember settings for no reason). In other words, when I reboot my computer or close and restart Arc Control, some of the settings are reset to default. The applicable settings are as follows (Names may not be correct since I'm not using English UI).

- Auto update settings in Driver
- App location
- Enable data collection
- Per-game settings
- All of the studio settings
- Overclock and fan control settings

Some of the settings are remembered including Global Game Settings and Display Settings.

**Comment by Karen-Intel** [comment] 2023-06-05 22:22
Hey @yetdragon thank you for your report

Hmm, I will do some more testing on this as I have been modifying a few things for a couple games and I still see them saved (I have rebooted my PC probably 4-7 times in the last days) but I will pay attention to those options you enlisted

Will be back soon

Karen

**Comment by Karen-Intel** [comment] 2023-06-08 23:18
Hey @yetdragon just a small update

I've not been able to reproduce this issue yet :(
Question, have you tried DDU to upgrade your driver? It does help when we start seeing issues with ARC Control

Please let me know, thanks

Karen

**Comment by yetdragon** [comment] 2023-06-08 23:27
Yes, I reinstalled the latest driver using DDU.

I found a few people experiencing what seems like a similar issue as mine on Intel community, so I think this issue is not something only I have.

- <https://community.intel.com/t5/Graphics/Arc-Control-keeps-going-back-to-default-settings-after/td-p/1440438>
- <https://community.intel.com/t5/Intel-ARC-Graphics/Intel-Arc-Control-notifications-settings-are-reset-when-the-app/td-p/1490720>

**Comment by Karen-Intel** [comment] 2023-06-08 23:30
Hey @yetdragon thank you

The fix is still in progress but let's keep this post open when it has been released. I will let you know in this thread 

Thank you for the insights, talk to you soon

Karen

**Comment by yetdragon** [comment] 2023-06-17 02:58
Sorry for late reply, it seems GitHub does not notify edits.

I tried 4382 (using DDU) but all settings are reset once I reboot or close and reopen the Arc Control just like 4369.

**Comment by yetdragon** [comment] 2023-06-17 03:02
I found something.

If you launch Arc Control by start menu shortcut, it will remember its settings. However, if you use Alt + I to launch it, it will reset all of the settings and even if you launch it through shortcut after, it remains reset.

**Comment by TheWonderfulTartiflette** [comment] 2023-06-17 19:43
Having this issue as well, even with 4499

**Comment by WouterNed** [comment] 2023-08-16 15:31
I have this issue too, on the previous version and on the current 1.71.5235.2 version. This is what I found:
Essentially all my settings are set to default when switching between the overlay version and the windowed version of the control center not through the GUI switch button, but through the closure of the center and the opening through the hotkey or the system tray.
So: Open windowed through system tray, switch to overlay through GUI, close overlay through GUI or clicking elsewhere, opening overlay with Alt+I, switching to windowed through GUI, closing windowed through GUI, opening windowed through system tray. This will all preserve the settings.
Opening windowed through system tray, closing through GUI, opening overlay through Alt+I will reset the settings. Same for closing overlay, and then opening windowed through system tray.

Solution for me is to disable overlay in the settings. That way this cannot happen again. Strangely enough I expect this setting to cause the hotkey Alt+I to launch the control center in windowed mode. But instead the hotkey is dead and does nothing. This is contrary to the tooltip which states that "Control center will always launch in windowed mode".  Do I have to make a new bugreport for this?

**Comment by Joseph-Intel** [comment] 2023-09-22 18:43
Hi @yetdragon I was able to do some testing on our latest driver and arc control version. Driver V.4826 arc control V.1.73.5335.2 our Arc control developers are aware of it not keeping games when manually added and are working on a fix. For capture, broadcast settings i noticed that it was keeping the settings. for the fan settings, it was NOT keeping the settings. Does this seem accurate to what you're seeing? Would you be able to test out this version and let me know your findings?

**Comment by yetdragon** [comment] 2023-09-27 18:27
Hey @Joseph-Intel, I tested the latest driver and Arc Control, and it was the same as before. It resets every setting if I launch it with Alt + I after reboot (given that Arc Control is registered as a startup program, using the start menu does not reset settings). One thing that changed is that if I launch it through the start menu AND press Alt + I, it does not reset its settings. This is my last reply.

> If you launch Arc Control by the start menu shortcut, it will remember its settings. However, if you use Alt + I to launch it again, it will reset all of the settings and even if you launch it through a shortcut after, it remains reset.
>
> It looks like Alt + I launches another Arc Control rather than opening the already launched one.

**Comment by Joseph-Intel** [comment] 2023-09-29 16:39
Hi @yetdragon I found that our Arc control devs have seen this issue previously and are working on a fix. I will be able to provide updates and let you know when a fix should be out.

**Comment by Joseph-Intel** [comment] 2023-12-15 17:34
Hi @yetdragon This should be fixed in our latest driver V1015081. Please retest and let us know your results! Thanks

**Comment by yetdragon** [comment] 2023-12-15 22:40
Hi, @Joseph-Intel. All settings seems to be working except the **Performance Tuning** ones. They were reset to default after a reboot.

**Comment by freak2fast4u** [comment] 2023-12-15 23:23
Same testimonial here. I've been running on a clean install of the latest beta drivers, and for some unknown reason the performance tuning ones went back to factory settings. It was somewhere between wednesday and friday this week. Hmm ... maybe a windows update ? The only change on my system was this windows patch installed on thursday : https://support.microsoft.com/en-us/topic/december-12-2023-kb5033372-os-builds-19044-3803-and-19045-3803-9cea61c6-072b-41f1-8cf2-7c7bfdd12d5c

**Comment by Joseph-Intel** [comment] 2023-12-18 20:55
@yetdragon This seems to be more of an intermittent issue now. After further testing, it did end up resetting back to default. I noticed it saved it more often (After full shutdown and turning back on) specifically when the GPU temp limit was adjusted to ~85C. Is this similar to what you're seeing?

**Comment by Susie1818** [comment] 2024-01-06 10:49
@Joseph-Intel @Karen-Intel 

I have kind of replicated the bug. Driver version 5081. I have two user accounts on a Windows 11 system. One is an administrator account and the other is a standard user account. The standard user account has no access to quite a few performance tuning options as I received a notication message from Arc Control saying that those functions are not available without admin privilege. The problem is: if I reboot or shut down the PC when using the standard user account, the performance tuning parameters won't be saved and then the next time when the PC boots up, when I login as the admin, I will see performance tuning parameters (Performance Boost, Voltage Offset, Power Limit, Temperature Limit, and Fan Control) are reset to default values. On the contrary, if I reboot or shut down the PC when using the administrator account, those configurations will be saved and restored the next time I login.

Key point: if you want to reboot or shut down the system, you must be using the administrator account.

I guess this is a policy-related issue. I do hope the standard user account be unable to adjust the GPU settings as it is designed right now, but at the same time I don't want my Arc Control tuning settings to be forsaken if the PC is shut down or rebooted by the standard user account. As far as I am concerned, the standard user account is actually my mom, and we share the same comupter in the living room. It's not possible to ask my mom not to shut down the PC.

**Comment by Gabriela-Intel** [comment] 2024-01-26 22:49
Sorry for the delayed response everyone! I'm taking this one over from Joseph.
	
@Susie1818 I read through your response and can confirm that this is policy related and expected behavior due to the required usage of an admin account.

Other than that the general  issue with Arc Control resetting between reboots should have been resolved as of Arc Control version 1.74.x. So those of you who haven't updated yet please give it a shot using the latest drivers and let me know if this is still a problem.

Thanks!

**Comment by Gabriela-Intel** [comment] 2024-02-06 17:30
I haven't seen other reports of this issue so let's continue with closing @IGCIT

**Closed** 2024-02-06 18:06 UTC
Labels: Info: Needs Replication, Type: Arc Control
