### ISSUE TITLE
[MSI Afterburn / Intel Arc Control] Wrong Sensor Data for Multi GPUs 

### ISSUE THREAD

**Issue by vitduck** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#669] opened 2024-01-11 13:20 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

MSI Afterburner / RTSS / Arc Control Center 

### Processor / Processor Number [Required]

13900KS

### Graphic Card [Required]

Arc A770

### GPU Driver Version [Required]

Other (Please specify)

### Other GPU Driver version

101.5081

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13903434/ssu.txt)

### Description and steps to reproduce [Required]

In system with multiple Intel GPUs, for instance, integrated graphics and Arc graphics, spurious sensor data was obtained. 
This long standing bug [IGCL/#44](https://github.com/intel/drivers.gpu.control-library/issues/44) affects applications that relying on  IGCL backend to display sensor data in the overlay. 

- MSI Afterburner / RTSS 
- Intel Arc Control

1. [MSI Afterburner / RTSS]: UHD770 + A770 
![RTSS](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/575950/397ee465-d8d8-42b4-9a0d-8765b8209a71)
The above figure is obtained via RTSS's internal HAL. 
When GT is disabled, all sensors are correctly populated.  
In contrast, either the sensors cannot be initialized or spurious data appears, such as `GPU2 memory usage`
Here, `GPU2` is a ghost GPU due to a MSI Afterburner's bug that have been recently fixed. 

2. [Intel Arc Control]: A750 + A380 
![Arc Control](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/575950/bb688a5e-42dc-4125-bec9-dbb4e5748754)
The above figure is a courtesy from the author of MSI Afterburner-Unwinder at [Guru3d](https://forums.guru3d.com/threads/intel-a770-no-sensor-information-with-enabled-integrated-graphics.450773/#post-6198090)
The ghost `GPU2` has now been fixed with the latest build of Afterburner. 
Yet, due to both A750 and A380 shares the same sensors, spurious data shows up in both RTSS and Intel Arc Control. 

UHD770 is crucial for taking advantage of Intel's Deep Link technology. 
So disabling the GT is not a viable solution those who have full Intel system. 

Regards.

**Comment by EstebanIntel** [comment] 2024-01-11 19:57
Hi @vitduck,

Since the issue is already reported and tracked on https://github.com/intel/drivers.gpu.control-library/issues/44, is there any reason to also open it here?

**Comment by vitduck** [comment] 2024-01-12 00:27
Hi @EstebanIntel 

This is an somewhat obscured bug in IGCL that has been stalled for almost a year. 

Since it is not mentioned in `Known Issues` section of driver release notes, I open it here so users who own both Intel CPU and GPU are aware that it will break their RTSS overlays in games. 

AFAIK, there are two solutions: 
- Disable iGPU and loose performance in Handbrake and Davinci Resolve  
- Import the sensor data from HWiNFO, which will require purchasing a license 
Unfortunately, both of them are far from desirable. 

If you feel that this is an unnecessary burden of the record, please feel free this ticket. 
Thanks.

**Comment by vitduck** [comment] 2024-01-16 05:17
For those who relying on RTSS for their gaming overlay, it is recommended to use the the most recent 7.3.5 RC. 
The enumeration issue has been partially addressed, and now RTSS can display correct telemetry in the overlay with iGPU. 

https://forums.guru3d.com/threads/msi-ab-rtss-development-news-thread.412822/page-217#post-6198767

![RTSS_RC](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/575950/a2a44ade-fcad-485b-88fb-8a6b41ef2608)

However, if you have two dGPUs in your system, the telemetry is still subjected to aforementioned bug.

**Comment by EstebanIntel** [comment] 2024-01-17 20:34
Hi @vitduck,

Thanks for the update. I have reached out internally to the people involved in the original issue https://github.com/intel/drivers.gpu.control-library/issues/44. We will be investigating further. And once we come to a conclusion, I'll update this thread.

**Comment by vitduck** [comment] 2024-01-18 00:43
@EstebanIntel 

Thanks very much for your help.

**Comment by Customayzer** [comment] 2024-01-28 20:20
There is no way to overclock two arc a770 in arc control. Windows sees two video cards perfectly and they work well, but only one can be adjusted/overclocked. It's been a year since they can't fix it. And this correction will bring buyers, believe me.

**Comment by EstebanIntel** [comment] 2024-07-10 17:05
Hi @vitduck,

The [latest driver version](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) 32.0.101.5762 has a fix for this issue. Can you test this fix?

**Comment by vitduck** [comment] 2024-07-12 04:17
Hi @EstebanIntel  

Thanks for reaching out regarding the latest update. 
And I much appreciate Intel's continuous effort to improve the driver. 

Unfortunately, due to a long standing issue on fan control with the Acer Bifrost A770, I have sold my card. 
It is just a matter of perspective. 
For Intel, certain issue such as fan control is dismissible, but for users who interact daily with the card, it is a nuisance. 

I think that @Customayzer can test this new driver at let you know. 

If there is no further activity within next week, please close the issue at your convenience. 
Thanks.

**Closed** 2024-07-15 20:45 UTC
Labels: Info: Needs Replication, Type: Support
