### ISSUE TITLE
Ramping fans

### ISSUE THREAD

**Issue by papatango45** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#467] opened 2023-09-03 11:49 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows 11 desktop

### Processor / Processor Number [Required]

i5 13600k

### Graphic Card [Required]

Acer Preditor bifrost Arc A770 oc

### GPU Driver Version [Required]

- [X] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssulog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12505948/ssulog.txt)

### Description and steps to reproduce [Required]

Gpu fans are constantly ramping up and down, even when I alter it manually in the Arc App. Never did until about 3 driver updates ago.

### Device / Platform

Asus Prime Z790-P wifi D4

**Comment by IGCIT** [comment] 2023-09-03 11:55
duplicate of #430 

this is a known issue that is being worked on, please see #430 for updates

thanks

**Closed by IGCIT** 2023-09-03 11:55 UTC
Labels: Info: Needs Replication
