### ISSUE TITLE
Counter Strike: Global Offensive (CSGO) Crashes on Startup (Crash to Desktop)

### ISSUE THREAD

**Issue by DoragonHunter** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#295] opened 2023-04-27 13:03 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Counter Strike: Global Offensive (CSGO)

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 7 5800X3D (8-Core / 16-Threads)

### Graphic Card [Required]

Intel Arc A770 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [X] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11343711/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Counter Strike: Global Offensive (CSGO) crashes on startup and to the desktop without any error messages with the latest drivers. Attached is the dump of the crash. 

Steps to reproduce: 

1. Start game from steam
2. Screen will go blank and crashes to desktop

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

3440x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

None. Game crashes to desktop.

### Crash dumps [Required, if applicable]

https://drive.google.com/file/d/19BL7Y_5mo8lQoggV2eCrmj4RoLkqcrU6/view?usp=sharing

**Comment by Karen-Intel** [comment] 2023-04-27 23:40
Hey @DoragonHunter thank you for your post!

We're performing some testing with the new driver and will get back to you once we are done!

Karen

**Comment by Karen-Intel** [comment] 2023-04-28 16:34
Hey @DoragonHunter a few questions
1. Can you share the password of the .7z file you attached?
2. How many times did you have to replay the game for the crash to reproduce?

I downloaded the game, loaded fine, just wandered around after joining a party and I could not see the crash at any point. Was pointing the camera randomly just to see if that triggered the crash. I also did other tests expectating and no crashes at all
[Here's how it looks for me.](https://www.youtube.com/watch?v=Ik3kf2cEG9Q)

We also have a new [DDU version ](https://www.wagnardsoft.com/forums/viewtopic.php?t=4491) we recommend you to use it as, as you have seen in the video, we could not reproduce this strange behavior.

Please let us know

Karen

**Comment by DoragonHunter** [comment] 2023-04-28 16:59
> Hey @DoragonHunter a few questions
> 
> 1. Can you share the password of the .7z file you attached?
> 2. How many times did you have to replay the game for the crash to reproduce?
> 
> I downloaded the game, loaded fine, just wandered around after joining a party and I could not see the crash at any point. Was pointing the camera randomly just to see if that triggered the crash. I also did other tests expectating and no crashes at all [Here's how it looks for me.](https://www.youtube.com/watch?v=Ik3kf2cEG9Q)
> 
> We also have a new [DDU version ](https://www.wagnardsoft.com/forums/viewtopic.php?t=4491) we recommend you to use it as, as you have seen in the video, we could not reproduce this strange behavior.
> 
> Please let us know
> 
> Karen

Password is 4846ec8e3c8ae465f260c4d9115bd38a

The crash only seems to happen if the driver isn't DDUed. The game will crash if the Intel driver has been upgraded/updated even with the clean install checked. I tested with the latest DDU version and the game now starts up.

**Comment by Karen-Intel** [comment] 2023-04-28 17:05
@DoragonHunter that is wonderful news! 

As for DDU usage, we recommend it specially when Beta drivers are used or start seeing this kind of issues. I'm glad it helped you! Also, this DDU version comes with great improvements so it was really worth a try
I'm sure this thread will help other users in case they start seeing similar behavior in other systems.

Would you agree to close this post? You can close it or I can request the admin to do it

Thank you for your help!

Karen

**Comment by DoragonHunter** [comment] 2023-04-29 00:23
Sure, you can close this post for now.

**Comment by Karen-Intel** [comment] 2023-04-29 00:27
@IGCIT please help us close this post. Issue was fixed with latest DDU V18.0.6.3 and GFX Driver v4314

Ty

Karen

**Closed** 2023-04-29 07:15 UTC
Labels: Info: Needs Replication, Type: Application Crash
