### ISSUE TITLE
Need For Speed Heat performance drop/stuttering with driver 9684/9805/9862

### ISSUE THREAD

**Issue by Saracchini** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#73] opened 2021-08-11 09:32 UTC
#### Checklist [README]

- [x] Device is not undervolted nor overclocked.
- [x] Device is using the [latest drivers](https://downloadcenter.intel.com/download/30381/Graphiques-Intel-Pilotes-DCH-Windows-10).
- [x] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Required]

---
#### Game Platform [Required]
- [ ] Steam
- [x] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Other

---
#### Processor / Processor Number [Required]

Intel i7 1165g
---
#### GPU Driver Version [Required]
- [x] 30.0.100.9805 (*latest*)
- [x] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

---
#### Rendering API [Required]
- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [x] DirectX11
- [ ] DirectX10
- [ ] DirectX9

---
#### Windows Build Number [Required]
- [ ] Windows 11 (*Insider Preview*)
- [x] Windows 10 21H1 (*May 2021 Update*)
- [x] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (*Please specify your build number*)

---
#### Description and steps to reproduce [Required]

1.  Start game in off-line /single-player mode
2.  Select free-roaming (daylight)
3.  Drive

The game suffered a significant performance drop with driver 9684. Game was running at 30-50 fps very smoothly with 9466 driver. After update the game stutters significantly to the point to be unplayable. Verified if issue is due drivers by reverting to 9466 version and issues disappear.  

Game was running with Origin overlay. Disabling has no difference in results. 

---
#### Device / Platform [Optional][Recommended]

GPD Win 3 1165g, default TDP (25-28W)

---
#### Game Settings [Optional][Recommended]

All settings in Medium. TAA enabled. 

---
#### Save game (*if possible, could help solve the issue faster*) [Optional]

---
#### Windows mini dump (*small memory dump*) (*if available*) [Optional][Recommended]

---

**Comment by RSaracchini** [comment] 2021-08-11 18:23
Tested with newest 9805. Issue persists.

**Comment by Saracchini** [comment] 2021-08-22 15:21
Low performance issue persists for Beta 9862.

**Comment by Risingdawn1** [comment] 2021-10-05 10:24
Could you test the following fix, as this seemed to improve performance for me on an 1165 and would help to isolate the issue:

"You can limit your CPU processor count by creating a user.cfg file in the game’s main folder and using these commands. The config below is for quad-cores with Hyper Threading (4 cores, 8 threads). You can change these values to your liking:"

Thread.ProcessorCount 4
Thread.MaxProcessorCount 4
Thread.MinFreeProcessorCount 0
Thread.JobThreadPriority 0
GstRender.Thread.MaxProcessorCount 8

**Comment by Saracchini** [comment] 2021-10-05 10:47
> Could you test the following fix, as this seemed to improve performance for me on an 1165 and would help to isolate the issue:
> 
> "You can limit your CPU processor count by creating a user.cfg file in the game’s main folder and using these commands. The config below is for quad-cores with Hyper Threading (4 cores, 8 threads). You can change these values to your liking:"
> 
> Thread.ProcessorCount 4 Thread.MaxProcessorCount 4 Thread.MinFreeProcessorCount 0 Thread.JobThreadPriority 0 GstRender.Thread.MaxProcessorCount 8

Tried the settings above. It does lower CPU usage but do not solve the stuttering, and using the exact same settings gives superior performance with 9466 drivers (43-45 fps) vs the latest beta 9894 (29-30 fps) in the same scene. 
That is clearly a driver problem.

**Comment by evang-x** [comment] 2021-10-29 22:12
Hello, I haven't been able to reproduce the performance issues/stuttering with driver 30.0.100.9684.

-Launched Game
-Selected Play Solo Mode
-Drove around and observed steady [40FPS].

**Game Settings**
Screen Resolution: 1280x720
Vertical Sync: Off
HDR Mode: Auto
Resolution Scale: 100.0%
Graphics Quality: Medium
TAA Enabled 

Can you tell me if this is the correct settings? Thank you.

**Comment by Saracchini** [comment] 2021-10-30 07:51
@evang-x 
I'm currently running it at 720p with Low Quality Preset, with 80% resolution scale and High quality textures.
Actually changing the preset show no much change except by a fixed drop value in frame rate.
Running the game for a while shows that for a certain amount of time CPU usage us very high, which seems to be the reason of the stuttering. After approximately 2-3 minutes, CPU usage drops down and frame rate shoots to 50-60.

I do observe better performance with 9466. Notably: 
 - When in the garage, on first boot. Press C/Button Y to view the car. In 9466 transition is somehow smooth and frame rate is near 43. In 9955, there's a sudden frame drop, which stabilizes, and frame rate is near 30-35. 
 - On offline mode. In the starting point, driving to the closest race track (within the stadium behind).  9466 shows better performance with frame rate oscillating between 30-45. 9955 shows a slightly frame rate with higher variation, with frames often around 29-30 in the same scene.
 - Note that after the CPU usage suddenly drops , performance is on par with 9466 (aforementioned track fraamerate goes up to 50).

**Comment by Saracchini** [comment] 2021-11-17 17:08
Graphic Issues persists with latest 1121 driver.

**Comment by estebanr863** [comment] 2022-04-27 15:43
Hi @Saracchini 

The latest beta driver version [30.0.101.1934](https://www.intel.com/content/www/us/en/download/19387/intel-graphics-beta-windows-dch-drivers.html) includes a possible fix for this issue. Can you please install this driver and test it?

**Comment by Saracchini** [comment] 2022-04-28 14:16
Tested, and issue persists with 1934 (Now I'm in Windows 11). If anything, it takes more time to CPU usage go down.

**Comment by estebanr863** [comment] 2022-05-10 20:13
Hi @Saracchini,

A possible fix for this issue has been included in the [latest driver version](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html) 30.0.101.1960. Can you please perform a [clean install](https://www.intel.com/content/www/us/en/support/articles/000057389/graphics.html) of this driver version and test it?

**Comment by Saracchini** [comment] 2022-05-10 21:15
Tested. Behaviour is similar to 1934. The performance is MUCH worse than in 9466 driver.

**Comment by estebanr863** [comment] 2022-05-11 17:18
Thanks for testing @Saracchini. We will keep working on this issue.

**Comment by estebanr863** [comment] 2022-05-24 16:55
Hi @Saracchini 

We have continued to test this issue in our lab and after trying on multiple systems, we don’t see the issue on driver 30.0.101.1960. At this point, it seems that the issue may be caused by your specific device, maybe some thermal restrictions due to the small form factor. Our advice is for you to contact your device manufacturer for support, because as mentioned, other systems with the same CPU don’t show this issue.

**Comment by pacoa-kdbg** [comment] 2022-05-25 05:50
Hi @estebanr863 
I  repliciated the performance issue.


Seems something related to CPU, 

when I run this game on an i7 1195G7, even at lowe framerates I get a CPU usage of ~75% at CPU speeds of 3-3.6GHz.

You can take a look to it on this video ( please take a look to the temps too, they never go over 90C, always around 80c)
https://www.youtube.com/watch?v=VcLiwch-LhI




Just for reference, this is exactly the same game running on Vega 8  APU.

You can see how CPU clock speeds never go over 2.4 GHz and  getting better framerates  
https://www.youtube.com/watch?v=_6b95u7pOBI

**Comment by estebanr863** [comment] 2022-05-27 23:12
Hi @pacoa-kdbg,

Thanks for your testing. However, from your video I don't see any stuttering or lag that make the game not playable (as reported by @Saracchini).

I do see your framerate drop below 30 fps sometime, but that is expected, since the Iris Xe integrated GPU in the i7-1195G7 doesn’t comply with the [game’s minimum requirements](https://www.ea.com/games/need-for-speed/need-for-speed-heat/about/pc-system-requirements)([1370 3DMark score](https://benchmarks.ul.com/hardware/gpu/Intel+Iris+Xe+Graphics+G7+96EU+review) for IrisXe vs [1673 3DMark score](https://benchmarks.ul.com/hardware/gpu/NVIDIA+GeForce+GTX+760+review) for Nvidia GTX 760).

**Comment by Saracchini** [comment] 2022-05-27 23:25
As mentioned. One should wait for quite long when using newer drivers. After this wait, CPU usage drops quickly and the game frame rate goes up quite fast. There are no thermal issues as CPU temperature on my device does not go above 75C.
That issue is not observed in the 9466 driver, as the CPU usage goes down fairly quickly after starting free-roaming.
On top of that this is not observed as well if someone use [DXVK](https://github.com/Sporif/dxvk-async) to force rendering using Vulkan instead DX11.

**Comment by Saracchini** [comment] 2022-06-07 17:53
It is the inverse problem. The game starts slow and with very high CPU usage, and after 2-3 minutes later the CPU usage drops down (from 100% to  40-60% usage), and frame rate goes up (in the racetrack behind the starting point, from 23-30 to 43-50).

**Comment by estebanr863** [comment] 2022-06-24 16:21
Hi @Saracchini,

We were able to replicate this issue and we are currently trying to identify the driver code change that may have introduced it.

**Comment by EstebanIntel** [comment] 2023-03-07 23:14
Hi @Saracchini, unfortunately, due to the development team limited resources and needing to work on other higher priority game issues, this issue won't be fixed.

**Closed** 2023-08-31 17:44 UTC
Labels: Info: Replicated, Type: Bad Performance, Info: Won't fix
