### ISSUE TITLE
ManiaPlanet - freezing after few seconds with 4502 drivers

### ISSUE THREAD

**Issue by stalker-svk** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#363] opened 2023-06-26 13:38 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

ManiaPlanet

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5-13500

### Graphic Card [Required]

Arc A770 LE 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[SSU.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11869448/SSU.txt)

### Description and steps to reproduce [Required]

game menu works fine, after loading a track the game freezes after few seconds and needs to be force closed via task manager, with previous beta driver 4499 it worked fine

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![Capture](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/137794439/20d586dd-6ce0-4a3e-91b4-8192b323f4b7)

**Comment by stalker-svk** [comment] 2023-06-26 13:39
I forgot to mention that the game needs DXVK to run on Arc GPU, I'm using latest DXVK 2.2

**Comment by Arturo-Intel** [comment] 2023-06-26 16:45
@stalker-svk 
Thank you for sharing this, I will replicate this on the lab.
I will come back to you if I have some questions regarding this issue
--r2

**Comment by stalker-svk** [comment] 2023-06-26 22:06
Here I include crashdump from that game
[LogCrash_000000014069F1C2.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11875042/LogCrash_000000014069F1C2.txt)

**Comment by Karen-Intel** [comment] 2023-06-30 18:52
Hey @stalker-svk I was able to repro a similar behavior, the game would not launch for me at all so I will test the regression and get back in case we need more info.

TY

Karen

**Comment by stalker-svk** [comment] 2023-07-01 09:57
@Karen-Intel you need to use DXVK 64bit (d3d11.dll and dxgi.dll)to launch the game

**Comment by Joseph-Intel** [comment] 2023-08-30 19:13
Hey @stalker-svk. I was able to recently test out our new driver V.4669 and I was not able to reproduce the issue. [https://youtu.be/-NyovmNKr50](url). Would you be able to test this on your end and let us know your results?

Thanks!

**Comment by stalker-svk** [comment] 2023-08-31 19:22
> Hey @stalker-svk. I was able to recently test out our new driver V.4669 and I was not able to reproduce the issue. [https://youtu.be/-NyovmNKr50](url). Would you be able to test this on your end and let us know your results?
> 
> Thanks!

hi, the game you tested is the new Trackmania but my bug report is about ManiaPlanet which is older version of trackmania https://www.maniaplanet.com so you tested different game

**Comment by Joseph-Intel** [comment] 2023-08-31 21:37
Gotcha, apologize for the confusion. I will be able to test this out and let you know my results

**Comment by freak2fast4u** [comment] 2023-08-31 21:38
@stalker-svk : could you clarify which trackmania game you are playing ? ManiaPlanet isn't a game, it's a platform, a launcher of sorts, for many trackmania games.

There was an old free to play variant called : TrackMania Nations Forever, which I can't remember if it used ManiaPlanet or not (I think so).
Then there was at least Trackmania² Stadium and Trackmania² Canyon, that are integrated to ManiaPlanet (I own those, so I know for sure).
And there's the latest Trackmania which is launched via Ubisoft Connect, which I also own, and has no integration with ManiaPlanet that I can see.

**Comment by stalker-svk** [comment] 2023-09-01 09:03
> @stalker-svk : could you clarify which trackmania game you are playing ? ManiaPlanet isn't a game, it's a platform, a launcher of sorts, for many trackmania games.
> 
> There was an old free to play variant called : TrackMania Nations Forever, which I can't remember if it used ManiaPlanet or not (I think so). Then there was at least Trackmania² Stadium and Trackmania² Canyon, that are integrated to ManiaPlanet (I own those, so I know for sure). And there's the latest Trackmania which is launched via Ubisoft Connect, which I also own, and has no integration with ManiaPlanet that I can see (at least in the UI).

it happened in all maniaplanet games (trackmania 2 canyon, stadium, lagoon nd valley) but with the new driver it seems fixed

**Comment by Joseph-Intel** [comment] 2023-09-06 15:28
Hi @stalker-svk After testing again with the correct game on my end I was unable to reproduce the issue. Would you be okay with closing this thread and if the issue comes up again reopening?

Thanks

**Closed** 2023-09-06 16:51 UTC
Labels: Info: Needs Replication, Type: Application Crash, Type: Regression
