### ISSUE TITLE
Fallout New Vegas Crashing

### ISSUE THREAD

**Issue by Code-Vlue** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#518] opened 2023-09-17 16:11 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Fallout New Vegas

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5 3600

### Graphic Card [Required]

Arc A750

### GPU Driver Version [Required]

- [X] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [X] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssulog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12643217/ssulog.txt)

### Description and steps to reproduce [Required]

Game crashes when entering a building sometimes, also crashes sometimes when getting into dialog with a character.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

All settings max at 1080P.

**Comment by Ilya-intel** [comment] 2023-09-26 08:44
@Code-Vlue 
This issue is currently being checked by our developers. I'll update you in this thread on any related news.

**Comment by Ilya-intel** [comment] 2023-11-27 11:43
Hey @Code-Vlue ,
Seems like the issue is fixed with latest gfx driver. I've played a bit and it seems stable for me.
Could you also try it?

**Comment by Code-Vlue** [comment] 2023-12-06 15:00
> @Code-Vlue 
> 
> Have you managed to check the game with the latest driver?

I apologize I actually don't have an Arc GPU to test on anymore.

**Comment by IGCIT** [comment] 2023-12-06 15:10
closing, if someone else come in with the same issue, we will reopen

**Closed by IGCIT** 2023-12-06 15:10 UTC
Labels: Info: Needs Replication, Type: Application Crash
