### ISSUE TITLE
Arc Control and Intel DSA says that I am up-to-date with drivers, when I'm not

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#459] opened 2023-08-27 13:18 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel Arc Control / Intel DSA

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [ ] 31.0.101.4669
- [X] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 27.08.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12448051/Intel.SSU.27.08.2023.txt)

### Description and steps to reproduce [Required]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44057002/6e6b8c88-f627-4c34-b610-1687411f6211)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44057002/e9b03359-683b-49bb-b8ee-4074db1dace5)
I am currently on 4644. 4669 is out now since 4 days, but DSA and Arc Control still tell me that I am up-to-date, even when I refresh their scans
(The DSA screenshot has been translated with Chrome's Google Translate)

### Device / Platform

ASUS Prime Z790-P WiFi D4

**Comment by Azonnali** [comment] 2023-08-28 20:52
Also happens to me.

**Comment by TheWonderfulTartiflette** [comment] 2023-08-29 14:45
It's the first time that happened to me btw, and even 3 days after, it still tells me I'm up to date

**Comment by Code-Vlue** [comment] 2023-09-09 02:47
This happened to me as well and only happened when I updated through DSA, it said that it would "Replace custom OEM drivers" and now always says I'm up to date.

**Comment by TheWonderfulTartiflette** [comment] 2023-09-14 16:48
I'm not sure, but I noticed that, at least once, when DSA checks automatically if I'm up to date, it'll say that I am, but when I do it manually, it'll suggest me the new drivers. But I can confirm that the "Installing this Intel graphics driver will remove customizations made by your computer manufacturer (OEM)." message is a bit annoying, especially given that I've made my PC by myself, and my Arc is a Limited Edition, so no OEM whatsoever

**Comment by Karen-Intel** [comment] 2023-09-19 18:24
Hi guys! This issue has been reported already and it is still a WIP on our end. We're adding your feedback on the Internal report, leaving internal tracking number here FYI: 14018835564

Karen

**Comment by Code-Vlue** [comment] 2023-09-19 18:29
@Karen-Intel Thanks for letting us know.

**Comment by rmorera-intel** [comment] 2024-10-30 22:29
Hi everyone, it has been ages since our latest update here.
Just wanted to double-check: according to our records this issue should not occur since driver 31.0.101.5074 and Arc Control build 74.3

By now our latest driver is 32.0.101.6130 with Arc Control build 80.5 with IDSA so could you please check and confirm?

**Comment by Azonnali** [comment] 2024-10-31 11:06
Hi there, on my end, the issue is resolved. However i mostly updated outside of Arc Control. 
Since i dont have the .6130 driver installed I`ll give it a go later today and will give an update here.

**Comment by rmorera-intel** [comment] 2024-11-08 22:45
I'll go ahead and close this report, if somehow the issue persists feel free to re-open it or submit a new one.

**Closed by rmorera-intel** 2024-11-08 22:45 UTC
Labels: Info: Needs Replication, Type: Support
