### ISSUE TITLE
Assassin's Creed: Origins and Assassin's Creed: Odyssey

### ISSUE THREAD

**Issue by Susie1818** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#588] opened 2023-11-08 12:05 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

AC: Origins and AC: Odyssey

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [X] Ubisoft Connect
- [ ] Battle.net
- [X] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

intel Core i5-13500

### Graphic Card [Required]

intel Arc A770

### GPU Driver Version [Required]

31.0.101.4952

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[SSU_20231105.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13296372/SSU_20231105.txt)

### Description and steps to reproduce [Required]

Bad performance with current DX11 driver.

Using DXVK Async makes the performance almost doubled.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Using in-game "High", "Very High", "Ultra" graphics settings presets

**Comment by IGCIT** [comment] 2023-11-08 12:51
hi,

duplicate of #289

as mentioned in there, the usage of dxvk is the accepted solution for these games while more driver improvements are being developed

**Closed by IGCIT** 2023-11-08 12:51 UTC
Labels: Info: Needs Replication
