### ISSUE TITLE
Mass Effect Legendary Edition - Frametime issues

### ISSUE THREAD

**Issue by bizude** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#162] opened 2022-10-25 02:46 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Mass Effect Legendary Edition

### Game Platform [Required]

- [ ] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [X] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i9-13900K

### Graphic Card [Required]

Intel ARC A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.3491 (*latest*)
- [ ] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1 (*October 2021 Update*)
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

[intel-ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/9856691/intel-ssu.txt)

### Description and steps to reproduce [Required]

Start gameplay
Running highest settings

Framerate in general is very good in this game, but it has frequent dips which make it feel stuttery. Imposing a framerate limiter to 120fps (or lower) will mitigate this issue somewhat, but it is still perceptible at 120hz. 

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![image](https://user-images.githubusercontent.com/81831122/197670125-14d4d269-44fd-4cf5-a24d-582cde67c5cc.png)

### Crash dumps [Required]

N/A - There is no crash occuring. 

### Game custom logs

This is an example of turning around in a hallway 

![image](https://user-images.githubusercontent.com/81831122/197669924-5cec8596-dd62-476a-8f70-4bffd8839b7d.png)

**Comment by IntelSupport-Rozilah** [comment] 2022-10-25 04:29
hi @bizude , 
thanks for contacting us, we will start to validate the issue and will update you soon. Stay tuned!

**Comment by IntelSupport-Rozilah** [comment] 2022-10-28 07:19
hi @bizude,
I have a few questions here to verify the issue, did the issue happens in the below situations?:
1. internal Intel gfx or another brand of external gfx card?
2. other than fullscreen display mode?
3. VSync: on?

**Comment by bizude** [comment] 2022-10-30 04:12
1. This is using ARC A770 LE
2. Fullscreen mode is enabled
3. V-Sync is disabled

**Comment by IntelSupport-Rozilah** [comment] 2022-11-03 03:07
hi @bizude,
is issue reproduce in [31.0.101.3793](https://www.intel.com/content/www/us/en/download/729157/intel-arc-graphics-windows-dch-driver-beta.html) as well?

**Comment by IntelSupport-Rozilah** [comment] 2022-11-04 05:06
hi @bizude,
Just to inform you that this issue has already been reported internally and we are
working on it. I want to give you a heads-up that the fix may take 3 to 6 months to be included.

**Comment by bizude** [comment] 2022-11-05 16:01
> hi @bizude, is issue reproduce in [31.0.101.3793](https://www.intel.com/content/www/us/en/download/729157/intel-arc-graphics-windows-dch-driver-beta.html) as well?

It seems to be reduced in the newest beta driver.

**Comment by EstebanIntel** [comment] 2023-03-07 23:05
Hi @bizude, unfortunately, due to the development team limited resources and needing to work on other higher priority game issues, this issue won't be fixed.

**Closed** 2023-08-31 17:35 UTC
Labels: Info: Replicated, Type: Bad Performance, Info: Won't fix
