### ISSUE TITLE
Can't launch Rocket League and Apex Legends at all

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#347] opened 2023-06-19 09:09 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Apex Legends, Rocket League

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4499
- [X] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 19.06.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11786354/Intel.SSU.19.06.2023.txt)

### Description and steps to reproduce [Required]

Try to launch Apex and Rocket League on 4499
I almost sure that this is caused by the GPU because I reversed drivers to 4382 (without rebooting btw), and the issue was gone, I was able to launch Apex and RL. Idk if it's a driver regression though, because going again to 4499 (still without rebooting) didn't make the issue appear again
It's not the first time I have issues with both games, they'll refuse to launch very, very often (For Apex, the Easy AntiCheat window will appear, load, and nothing happens; For RL, a blank window will appear for 5 seconds, and close)
I know I post a lot of issues on this GitHub repo, I just report every issue related to my Arc I can

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

19020x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

None

### Device / Platform name

ASUS Prime Z790 WiFi D4

**Comment by Karen-Intel** [comment] 2023-06-19 15:46
Hey @TheWonderfulTartiflette thank you for reporting this
I will check on my end if it is a regression and get back to you :)

Karen

**Comment by Karen-Intel** [comment] 2023-06-20 00:10
Hey @TheWonderfulTartiflette quick update

Both Apex Legends on Steam and Rocket League in Epic Games Launcher work fine for me (My system is a 13900k + A750 8GB + Gfx v.4499) [Here's the evidence](https://www.youtube.com/watch?v=W_HDddjlH_U) and I haven't received reports from other users about a similar issue.

Something we spotted before was that a basic system review can help a lot when facing SW problems ( I had a user that had a loose power cable to his GPU and that was causing a lot of issues) so, you can give it a try.

Also, make sure your iGPU driver is updated to the latest (I'm not seeing info in your SSU regarding your UHD 770, maybe its not enabled?), if it is enabled, sometimes windows forces the default driver so would be worth to check that too.

Hope to hear from you soon

Karen

**Comment by TheWonderfulTartiflette** [comment] 2023-06-20 10:51
> Hey @TheWonderfulTartiflette quick update
> 
> Both Apex Legends on Steam and Rocket League in Epic Games Launcher work fine for me (My system is a 13900k + A750 8GB + Gfx v.4499) [Here's the evidence](https://www.youtube.com/watch?v=W_HDddjlH_U) and I haven't received reports from other users about a similar issue.
> 
> Something we spotted before was that a basic system review can help a lot when facing SW problems ( I had a user that had a loose power cable to his GPU and that was causing a lot of issues) so, you can give it a try.
> 
> Also, make sure your iGPU driver is updated to the latest (I'm not seeing info in your SSU regarding your UHD 770, maybe its not enabled?), if it is enabled, sometimes windows forces the default driver so would be worth to check that too.
> 
> Hope to hear from you soon
> 
> Karen

Idk what I did prior, but yesterday evening (Paris timezone) I could launch the games, but not anymore now. So I tried to reseat cables, checking visually the PC, but nothing more changes. Could there be a way to get the logs of when the games won't launch to figure what's the issue maybe?

**Comment by Karen-Intel** [comment] 2023-06-20 14:49
Hey @TheWonderfulTartiflette 

1. If you can get the logs we can analyze if there is any GPU related info.
2.  Some games have hybrid config. I had a user that reported that a game would not launch if the iGPU was enabled. The problem was that the outdated driver was having a conflict with the ARC one and it just wouldn't launch. [This user fixed it](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/331) by updating the iGPU driver after we shown in a vid the version we had in our iGPU.

Karen

**Comment by TheWonderfulTartiflette** [comment] 2023-06-21 20:09
> Hey @TheWonderfulTartiflette
> 
> 1. If you can get the logs we can analyze if there is any GPU related info. Most games create a dump file in the folders where user info is stored, you can look there if there's a dump that was created
> 2. Some games have hybrid config. I had a user that reported that a game would not launch if the iGPU was enabled. The problem was that the outdated driver was having a conflict with the ARC one and it just wouldn't launch. [This user fixed it](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/331) by updating the iGPU driver after we shown in a vid the version we had in our iGPU.
> 
> Karen

Normally, Apex Legends creates a crashdump in the Documents folder, but I couldn't find any. For Rocket League, I couldn't find anything on the internet about crashdumps actually
So yeah I tried with enabling the UHD770 of my 13600K, worked for some time (like when not enabling it could work for some time as well) and now still won't launch, so no new improvement

**Comment by Karen-Intel** [comment] 2023-06-21 22:10
Hey @TheWonderfulTartiflette 
I'm sorry to hear that, however we're running out of options as we cannot repro the bug you're seeing on our end :(

I think the best would be to try with a brand new OS profile (you can create a new user) and see if it runs there.
If not, would be good to check in EA and Steam forums in case anyone has run into similar behaviors.

Let us know if there's anything else we can do to help

Karen

**Comment by Karen-Intel** [comment] 2023-09-19 20:23
@IGCIT can you help us close this one? We're unable to repro and user has not reported the same issue again. We can reopen if needed. TY

Karen

**Closed** 2023-09-19 21:47 UTC
Labels: Info: Needs Replication, Type: Application Crash
