### ISSUE TITLE
Can't see underwater on skyrim

### ISSUE THREAD

**Issue by silverax** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#618] opened 2023-12-02 02:20 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

The elder scroll V: Skyrim + dawnguard 

### Processor / Processor Number [Required]

Ryzen 5 5600G

### Graphic Card [Required]

Sparkle Intel Arc A750 ORC OC Edition,

### GPU Driver Version [Required]

31.0.101.4972

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [X] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13533136/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Load a saved game, move underwater

**Comment by Squall-Leonhart** [comment] 2023-12-02 05:40
This has forever been a game bug caused by a shader that applies blur exponentially, mods have been available to fix it since hte early days of Oldrim

https://www.nexusmods.com/skyrimspecialedition/mods/24079

**Comment by IGCIT** [comment] 2023-12-02 19:54
hi @silverax, can you attach a screenshot?
unless it is different from how the game should look, this will be closed since this is how the game behaves

**Comment by silverax** [comment] 2023-12-04 20:31
This is diferent, like full black
https://steamcommunity.com/sharedfiles/filedetails/?id=3105392187

**Comment by Squall-Leonhart** [comment] 2023-12-05 07:09
Green actually, its the same bug unforunately.

https://www.nexusmods.com/skyrim/mods/14007

**Comment by silverax** [comment] 2023-12-05 21:40
Seems that the mod is not compatible with dawnguard :( thanx anyway for the time

**Comment by Felipe-Intel** [comment] 2023-12-06 14:37
Thanks for the information @silverax. We'll proceed to close this thread.

**Closed by Felipe-Intel** 2023-12-06 14:37 UTC
Labels: Info: Needs Replication, Type: Graphical Glitches
