### ISSUE TITLE
WHERE BIOS VERSION 1064 FOR GIGABYTE CARDS???

### ISSUE THREAD

**Issue by Noobachyo** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#542] opened 2023-09-28 16:30 UTC
### Application [Required]

bios version

### Processor / Processor Number [Required]

i3-10105f

### Graphic Card [Required]

Intel Arc A380

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

Why is there still no version 1064, even though more than a month has passed? I was told that the new version should come out a couple of weeks after it is released on other video cards, but this never happens. I emphasize once again that this version almost completely solves the problem with image dimming in the game "Warface", which I have been playing for almost a year. Why should I suffer like this? I don't understand. I'm tired

**Comment by IGCIT** [comment] 2023-09-29 06:55
duplicate of #457 

i understand your frustation, please, use the already open issues instead of opening duplicates

thanks

**Closed by IGCIT** 2023-09-29 06:55 UTC
Labels: Type: Feature Request
