### ISSUE TITLE
Please remove Dotnet 7.0 dependence from Arc drvier installer on Windows.

### ISSUE THREAD

**Issue by UnderCooled** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#691] opened 2024-01-29 09:32 UTC
### Application [Required]

Arc Driver Installer

### Processor / Processor Number [Required]

i7-12700H

### Graphic Card [Required]

Arc A770M

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

I've written about this in the support forum, I don't get the reason why Arc Driver installer needs Dotnet 7.0 dependence, which is only being used by the installer.exe after the main setup extracted and showed the splash screen.

After the splash screen of main setup, user's computer will quietly install Dotnet 7.0.7, and this is not even the lastest version, and the ASP.net add-on for no reason.

If I extract the main setup with 7-zip, I can install driver through Device Manager without any "Dotnet 7.0" involved, I can also install Arc Control with the EXE in extras folder, it's a WiX tool packaged installer right? I use DDU to clean up my old GPU driver, and install the drivers with Device Manager, and the Arc Control installer, the UWP graphic control panel get auto installed without any problem, look no Dotnet 7.0 involved.

I believe Intel makes lots of driver installers, why on earth, arc driver installer needs the "Windows Desktop Runtime"? It's an old one, the 7.0, in maintenance mode...

If your driver continues to install old dotnet runtimes on users' computer, without even tells them to remove them after your bump like from dotnet 6.0 to 7.0, it's a waste of space on an SSD system partition.

If I can install the driver and extra apps without any magic tricks, I believe you smart engineers can make this installer using NSIS/InnoSetup/WiX Tools.

PS: I make this issue because I was using your driver installer (gfx_win_101.5186_101.5234.exe), to update my driver without a success, as I said, main setup quietly installed Dotnet 7.0.7, while I've installed the latest 7.0.15, the installer.exe in the temp popup the error I don't have the right dotnet runtime, and lead me to download "Windows Desktop Runtime 7.0.15" which I've installed, please just stop this madness, you can even write a powershell script with digital signature to install driver and apps...

**Comment by UnderCooled** [comment] 2024-01-29 13:22
I checked the installer.exe in ILSpy, it uses WPF on .Net, if the installer is only being use on Windows, why not target .Net Framework 4.8, it's preinstalled on Win10/11, so that you don't need to aim a moving target of dotnet release cycle.

**Comment by bandit8623** [comment] 2024-01-30 02:00
thank you for this!  arc control ba ck by manual forces of nature :)

**Comment by rmorera-intel** [comment] 2024-01-30 22:22
Hi @UnderCooled I checked with the driver installer team and DotNet 7.0's primary role is only to kickstart the gfx installer. I'm sending your feedback to the driver installer team to see this changed in the future, however I can't promise any particular outcome.
 
As for issues #682 and #688 we are currently investigating the root cause and will be updating each post soon.

Thank you for your feedback on removing the DotNet 7.0 dependency. If there is no other comment or question I'll close this one.

**Closed** 2024-01-31 21:20 UTC
Labels: Type: Feature Request

**Comment by UnderCooled** [comment] 2024-03-11 02:46
@feamsr00 When I **"manually"** updated to v31.0.101.5333, noticed there's a note on the release page:

> Notes
> 
> Self-installing format (.exe) is the easiest installation method and our recommendation.

I've tried to execute the installer in Windows sandbox, it still needs dotnet 7, the manual way of installing drivers and arc control may skip the HDMI firmware updates, but I'm using DisplayPort anyway.

I've skipped install arc control this time, tested a few games, the performance seems fine, less background processes is better :-)
