### ISSUE TITLE
God of war texture issues and game hangs, kratos cannot move anymore

### ISSUE THREAD

**Issue by mva94** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#110] opened 2022-01-14 22:19 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

God of war 

### Game Platform [Required]

- [X] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

I7 1195g7

### GPU Driver Version [Required]

- [X] 30.0.101.1191 (*latest*)
- [ ] 30.0.101.1121
- [ ] 30.0.101.1069
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

Will do

### Description and steps to reproduce [Required]

Start game 
Walk around and notice the textures not being displayed correctly 
Check out this video for more information https://youtu.be/ou4_j-TJMjk

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1280×800

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![20220114_231751](https://user-images.githubusercontent.com/78859716/149592524-0729dae4-6d6c-40b6-a0ed-1f6c964afe9d.jpg)
![20220114_231758](https://user-images.githubusercontent.com/78859716/149592539-8ae3d2aa-b8cf-4938-9f78-ccc18ff573c1.jpg)

### Device / Platform name

Oxp mini

### Crash dumps [Required]

No crash

**Comment by IGCIT** [comment] 2022-02-01 14:37
closing this as:

- texture issue is a game bug and a fix is in development (not a driver bug)
- hangs and crashes are caused by memory leaks (and affects all vendors) and/or game bugs

i had hangs too because the game fulled my 16gb of ram (gpd win 3)

if/when the game will be in a good shape we can see if drivers issues are present

**Closed by IGCIT** 2022-02-01 14:37 UTC
Labels: Info: Needs Replication, Type: Graphical Glitches, Top 5
