### ISSUE TITLE
Final Fantasy VII Remake Intergrade

### ISSUE THREAD

**Issue by Risingdawn1** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#106] opened 2021-12-17 19:33 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Final Fantasy VII Remake Intergrade

### Game Platform [Required]

- [ ] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [X] Epic Games
- [ ] Bethesda.net
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

1165g7

### GPU Driver Version [Required]

- [X] 30.0.101.1191 (*latest*)
- [ ] 30.0.101.1121
- [ ] 30.0.101.1069
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11
- [X] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

Can't generate

### Description and steps to reproduce [Required]

Game crashes with: Video Driver Crash, within 10-15 minutes of playtime during opening Mako Reactor section, regardless of settings

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

1280x720, 1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

All settings result in crash.

### Device / Platform name

Onexplayer

### Crash dumps [Required]

Can't find dump

**Comment by estebanr863** [comment] 2022-03-09 20:14
Hi @Risingdawn1 

We were able to reproduce this issue and it has now been escalated to our driver development team. I just want to set the right expectation with you, as with the current workload, it may take from 3 to 6 months for a possible fix to be integrated into a release driver.

**Comment by estebanr863** [comment] 2022-07-22 16:00
Hi @Risingdawn1,

Our driver development team is experiencing a high volume of requests for fixes on game issues. And since we have limited resources, this means that fixes for issues on games outside of our top games list (we maintain an internal list of top games, considering the most played, recently released, etc.) will need to be put on hold. The fix for this issue falls into this category, so we currently cannot commit to target date for this fix to be released. I’ll update you once the development of a fix for this issue is resumed.

**Comment by EstebanIntel** [comment] 2022-10-27 00:26
Hi @Risingdawn1,

A possible fix for this issue is included with our latest driver version [31.0.101.3790](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html). Can you please install this version and test it?

**Comment by EstebanIntel** [comment] 2022-11-04 22:56
Hi @Risingdawn1,

Where you able to test the fix?

**Comment by EstebanIntel** [comment] 2022-11-22 15:04
Hi @IGCIT,

This game is no longer crashing on the latest driver in our Lab and @Risingdawn1 is not responding. Can this be closed?

**Closed** 2022-11-22 15:06 UTC
Labels: Info: Needs Replication, Type: Application Crash
