### ISSUE TITLE
Intel Arc Control intermittently fails to open, and once failed, can no longer open even after rebooting.

### ISSUE THREAD

**Issue by SapphireDrew** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#868] opened 2024-11-18 02:22 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel Arc Control

### Processor / Processor Number [Required]

Intel Core i7 9700K @ 3.6 GHz

### Graphic Card [Required]

ASRock Challenger OC Edition Intel Arc A580

### GPU Driver Version [Required]

32.0.101.6297

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build [Required]

Windows 10 22H2

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/user-attachments/files/17793593/igcit_ssu.txt)

### Description and steps to reproduce [Required]

I experienced the problem outlined here: https://www.intel.com/content/www/us/en/support/articles/000091851/graphics.html twice already.

Seems like this is a known issue that either hasn't been completely resolved or is a regression. When the problem occurs, it become also impossible to open Windows Task Manager, preventing me from killing and restarting Intel Arc Control, even after rebooting. Either way, it's annoying I have to reinstall and reboot yet again...

### Device / Platform

PC - Windows 10

### Application / Windows logs

[arcc_2024_11_16___11_59_56.log](https://github.com/user-attachments/files/17793623/arcc_2024_11_16___11_59_56.log)
[arcc_2024_11_16___11_59_57.log](https://github.com/user-attachments/files/17793624/arcc_2024_11_16___11_59_57.log)

[arcc_2024_11_17___21_1_29.log](https://github.com/user-attachments/files/17793596/arcc_2024_11_17___21_1_29.log)
[arcc_2024_11_17___21_4_39.log](https://github.com/user-attachments/files/17793597/arcc_2024_11_17___21_4_39.log)
[arcc_2024_11_17___21_10_26.log](https://github.com/user-attachments/files/17793598/arcc_2024_11_17___21_10_26.log)
[arcc_2024_11_17___21_11_42.log](https://github.com/user-attachments/files/17793600/arcc_2024_11_17___21_11_42.log)
[arcc_2024_11_17___21_16_10.log](https://github.com/user-attachments/files/17793601/arcc_2024_11_17___21_16_10.log)

**Comment by Gabriela-Intel** [comment] 2024-12-04 22:45
We haven't seen this reported in some time. I tried to replicate, but I'm not seeing any issues with it failing to open. What exactly are you doing prior to launching Arc Control? Some replication steps may help us try to see the issue.

**Comment by Gabriela-Intel** [comment] 2024-12-10 16:35
Since you are building a new system and will be retesting the issues you filed, let's close this for now. If the issue is seen again with the new build, then please reopen the issue.

**Closed by Gabriela-Intel** 2024-12-10 16:35 UTC
Labels: Info: Needs Replication, Type: Arc Control
