### ISSUE TITLE
Risen 2 flickering vegetation

### ISSUE THREAD

**Issue by TimoMueller** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#116] opened 2022-03-06 15:04 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Risen 2

### Game Platform [Required]

- [X] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz

### GPU Driver Version [Required]

- [X] 31.0.101.3975 Beta
- [X] 31.0.101.3959
- [...]
- [X] 31.0.101.3222
- [X] 30.0.101.1631
- [X] 30.0.101.1404
- [X] 30.0.101.1340
- [ ] 30.0.101.1191
- [ ] 30.0.101.1121
- [ ] 30.0.101.1069
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [X] DirectX9

### Windows Build Number [Required]

- [X] Windows 11
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

will be provided later

### Description and steps to reproduce [Required]

Start the game and travel to the first island with jungle vegetation.
Trees and bushes are constantly flickering
![20220306155500_1](https://user-images.githubusercontent.com/1918290/156928919-31f86bf0-1dda-408b-bbfc-9eb2dcf098ea.jpg)
![20220306155504_1](https://user-images.githubusercontent.com/1918290/156928920-81897710-2b02-48db-b903-286292cfde78.jpg)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1280x720

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

everything set to maximum quality.

### Device / Platform name

GPD Win 3

### Crash dumps [Required]

will be provided later

**Comment by TimoMueller** [comment] 2022-03-24 19:12
Issue is still present on *.1404 and *.1631

**Comment by estebanr863** [comment] 2022-04-26 22:16
Hi @TimoMueller 

This issue was already reported internally, and we are working on it. However, I do want to set the correct expectation that a possible fix may take from 3 to 6 month to be integrated into a public release driver.

**Comment by estebanr863** [comment] 2022-05-10 20:13
Hi @TimoMueller,

A possible fix for this issue has been included in the [latest driver version](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html) 30.0.101.1960. Can you please perform a [clean install](https://www.intel.com/content/www/us/en/support/articles/000057389/graphics.html) of this driver version and test it?

**Comment by estebanr863** [comment] 2022-05-17 17:49
Hi @TimoMueller,

Were you able to test this?

**Comment by estebanr863** [comment] 2022-05-23 22:59
Hi @IGCIT,

The fix for this issue was tested in our lab and we are not able to see it anymore. Since @TimoMueller is not responding, can this be closed?

**Comment by TimoMueller** [comment] 2022-08-03 23:59
This issue can be reopened. Vegetation is still flickering like crazy on *.3222.
Seems like an issue with alpha textures.

**Comment by IntelSupport-Rozilah** [comment] 2022-08-11 03:48
hi @TimoMueller,

We started working on this issue, in meantime can you attach SSU report as our reference?

**Comment by IntelSupport-Rozilah** [comment] 2022-08-16 04:29
hi @TimoMueller,

we still working on this issue, it will be good if you attach a video recording of the issue to narrow down the finding and as our reference as well.

**Comment by IntelSupport-Rozilah** [comment] 2022-08-19 05:45
hi @TimoMueller,
I replicated the issue on our end, it is reproducible on the latest driver: 30.0.101.3222 as below:
![image](https://user-images.githubusercontent.com/44628772/185550734-84cce7b2-5646-4f15-9c7f-765cbd681eed.png).
We will be working on a fix. I want to give you a heads up that the fix may take 3 to 6 months to be included.

**Comment by TimoMueller** [comment] 2022-12-24 06:07
Issue still present on *.3959 and *.3975 Beta.

**Comment by EstebanIntel** [comment] 2023-05-22 17:01
Hi @IGCIT, this issue is fixed for us in out lab test and @TimoMueller is not responding. Can this issue be closed?

**Closed** 2023-05-22 18:34 UTC
Labels: Info: Needs Replication, Type: Graphical Glitches
