### ISSUE TITLE
16X MSAA in Dirt Rally 2.0 drops performance much more than expected

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#667] opened 2024-01-10 18:36 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Dirt Rally 2.0

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

31.0.101.5084

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 10.01.2024.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13891599/Intel.SSU.10.01.2024.txt)

### Description and steps to reproduce [Required]

Without MSAA, Max settings, in the American map, I'm getting 120FPS, and with 16X MSAA, I'm getting 55FPS. Sure, MSAA has a cost, and 16X even more, but this shouldn't drop performance this much. This goes along to what I noticed about Arc struggling with MSAA in basically every game, leading sometimes to crashes, and sometimes to very low performance.
I couldn't find online a 16X vs. no MSAA for other GPUs on Dirt Rally 2.0, but on most games, there's at most a 10% difference. Here, it's more than 50%

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Max

**Comment by BelleNottelling** [comment] 2024-01-19 12:06
Do you potentially mean 16x anisotropic filtering and not 16X MSAA?

Anisotropic filtering improves the quality of textures when viewed at an angle and does typically have a negligible performance hit.

MSAA on the other hand is like a selective super-sampling to render specific elements of a game a higher resolution to reduce aliasing and while it isn't as demanding as just selecting a higher resolution, it does have a noteworthy FPS impact.

For example, on my 6950 XT with GTA V going from MSAA off to 8x MSAA takes me down from ~150 FPS to ~80 FPS. If you're actually talking about MSAA here, then the FPS drop you are seeing is 100% to be expected

**Comment by jpovixwm** [comment] 2024-01-22 18:24
MSAA indeed seems unusually slow on Intel GPUs. Take a look at https://bugs.chromium.org/p/chromium/issues/detail?id=1145793 and https://bugs.chromium.org/p/chromium/issues/detail?id=527565

**Comment by Felipe-Intel** [comment] 2024-01-22 22:53
Hello @TheWonderfulTartiflette I made the following tests to the game swapping GPUs and results were very similar between cards

	                                                AVG FPS		
Settings	                Intel A770	Intel A750	RTX 4060
All off Ultra Low	100%	        100%	        100%
All off Ultra	        54.80%	        56%  	        53%
Ultra + x16 MSAA	31.70%	        32.80%	        not available
Ultra + x8 MSAA	not tested	41.20%     	41.60%

as noted by @BelleNottelling, MSAA will have a performance impact, more so when used at the highest possible.

We will proceed to close this ticket since this is expected behavior.

**Closed by Felipe-Intel** 2024-01-22 22:53 UTC
Labels: Info: Needs Replication, Type: Bad Performance

**Comment by TheWonderfulTartiflette** [comment] 2024-01-23 08:57
@Felipe-Intel my bad, I didn't remember that MSAA was this resource intensive, sorry for the useless ticket
