### ISSUE TITLE
Unhiding Text Content aka IT Content setting for USB-C and DisplayPort to HDMI adapters

### ISSUE THREAD

**Issue by pq15239** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#880] opened 2024-12-12 12:00 UTC
### Application [Required]

Intel Graphics Command Center

### Processor / Processor Number [Required]

7th to latest Gen

### Graphic Card [Required]

7th to latest Gen

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build [Required]

Windows 11 24H2

### Describe the feature [Required]

Many computers (especially laptops and tablets) nowadays only have USB-C and/or DisplayPort outputs.

The Intel Graphics Command Center has a setting called **Text Content** (previously called **IT Content**) for HDMI outputs, which can adjust the HDMI Content Type bit to automatically switch a TV into PC mode for example:

- https://community.intel.com/t5/Graphics/Detailed-explanation-of-quot-IT-Content-quot-option-in-Control/m-p/425262/highlight/true#M36561
- https://www.hdmi.org/spec/hdmi1_4b

But [similar to the Quantization Range and Color Depth and Color Format settings](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/878), the **Text Content** (aka **IT Content**) setting is hidden from the Intel Graphics Command Center when using USB-C/DisplayPort to HDMI adapters.

Can this be fixed so that this setting is also available for USB-C/DisplayPort to HDMI adapters?

Otherwise it's not possible to adjust the HDMI Content Type bit to automatically switch a TV into PC mode for example, when using Intel graphics.

There should be no reason for hiding that setting for USB-C/DisplayPort to HDMI adapters.

And this issue should not be closed until there is a driver update to unhide (i.e. make available) the **Text Content** (aka **IT Content**) setting for USB-C/DisplayPort to HDMI adapters on all Intel processors with 7th to latest Gen graphics.

Can a driver update be released for all Intel processors with 7th to latest Gen graphics which unhides (i.e. makes available) that setting for USB-C/DisplayPort to HDMI adapters?

**Comment by Gabriela-Intel** [comment] 2024-12-16 21:08
Hey there @pq15239! Thanks for taking the time to provide feedback. :) I went ahead and filed a request with these details for the team to review. I'm closing this one out with my comment since this is not a bug, but a feature request.

**Closed by Gabriela-Intel** 2024-12-16 21:08 UTC
Labels: Type: Feature Request

**Comment by Gabriela-Intel** [comment] 2025-02-03 23:41
Hey @pq15239. Thanks for reaching out again. At this time, I'm sorry to say that we can't accommodate this since IGCC is currently in maintenance mode. The primary focus during this period is to ensure the stability, security, and performance of the existing app.

Apologies for the disappointing news :/ That being said we do appreciate your understanding and continued support.
