### ISSUE TITLE
A770LE Fans Max Speed Locking to 1200RPM +- 50RPM

### ISSUE THREAD

**Issue by XBravRevolutionz** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#278] opened 2023-03-29 21:15 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Heaven Benchmark 4.0 (Any Games generating a load)

### Game Platform [Required]

- [X] Steam
- [X] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [X] Other (please specify)

### Other game platform

Benchmark Tool - Direct Download

### Processor / Processor Number [Required]

Ryzen 9 3900X

### Graphic Card [Required]

Intel ARC A770 LE

### GPU Driver Version [Required]

- [ ] 31.0.101.4257
- [X] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[sys_info.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11105485/sys_info.txt)

### Description and steps to reproduce [Required]

Any tweaks to the performance settings in ARC Control Center seem to potentially set the fan states to govern to a maximum of 1200RPM (with some spikes to 1250RPM). This persists across driver updates and when restoring the defaults in ARC Control Center including a reboot.

Steps to Reproduce:
1) Modify settings under Performance Tuning (e.g., limit GPU temp to 80°C from the default 90°C, increase GPU power limit)
2) Run a constant load on the GPU (e.g., Heaven Benchmark, observed > 90% Render Activity)
3) Using Performance Telemetry overlay, observe the GPU Temperature and VRAM Temperatures rise to limits defined in ARC Control Center with the Fan Speed Locking at 1200RPM.
4) Stop load on GPU and observe the card cool down by means of GPU clock rate reduction, but fans still locked at 1200RPM.
5) Reboot system.
6) With configuration loaded at boot, run load again. Observe the same as noted in 3 and 4.

As this card does not have any fan curve settings exposed, it is impossible to see the governing values and thresholds in ARC Control Center.

Through other tests, the fans can achieve 2700RPM if governed differently. A locked in speed of 44% of maximum speed results in completely inadequate cooling, and the speeds will constantly be throttled by the GPU Temperature as the fans cannot keep up.

Currently using driver 4255, however, this has occurred and been present since at least 4091 on both beta and stable drivers.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Heaven Benchmark 4.0:

Preset: Custom
API: DirectX 11
Quality: Ultra
Tessellation: Extreme
Stereo 3D: Disabled
Multi-Monitor: Disabled
Anti-aliasing: x8
Resolution: 1920x1080

### Device / Platform name

MSI X470 Gaming Pro Max

**Comment by Karen-Intel** [comment] 2023-03-30 00:38
Hi @XBravRevolutionz  thank you for posting your findings!

We'll check if this same behavior is spotted in our end and get back to you in case we have questions

Stay tuned!

Karen

**Comment by Karen-Intel** [comment] 2023-03-30 15:50
Hey @XBravRevolutionz 

Help needed. For debug purposes, can you share the info of your card under this section?

![image](https://user-images.githubusercontent.com/91162218/228892913-47d94ca1-7dd0-4cd7-899f-8f1d0ba8d1ac.png)

Thanks, keep me posted :)

Karen

**Comment by XBravRevolutionz** [comment] 2023-03-30 16:34
Hey @Karen-Intel 

Here you go! 

![image](https://user-images.githubusercontent.com/102002385/228904010-669eace9-36e7-49d0-a500-600a17f73f1c.png)

Please note that although Resizable Bar is showing as Not Supported, it is indeed active according to all other utilities. It doesn't show as "Enabled" unless I've disabled SVM in my BIOS.

**Comment by XBravRevolutionz** [comment] 2023-04-10 17:52
Hey @Karen-Intel,

When backdoor modifying ACC to expose fan curves, I've witnessed the curves defaulting to a max level of ~40%, which would correspond to a rough speed of 1200RPM. I'll see if I can get a screenshot later, but even resetting the settings to defaults does not correct this. If you manually modify the fan curves, the fans will respond instantly and will persist at the modified rates across reboots.

Is there a particular reason why the fan curve options are hidden for these GPUs? I've encountered significant performance boosts and stability by increasing the default trends to have the fans at 100% (~2800RPM) by the time the temps exceed 75°C. At these speeds, the card never throttles on temperature.

I appreciate any feedback you can bring to us. Thanks!

**Comment by Karen-Intel** [comment] 2023-04-10 22:18
Hi @XBravRevolutionz thank you! Please share the SS if you can, the issue is still under investigation.

Karen

**Comment by Karen-Intel** [comment] 2023-04-11 21:28
Hey @XBravRevolutionz apologies on the delay. Here are my findings on this issue

I've tried to reproduce it using the Unigine Benchmark 4 on a system with AMD Ryzen 5 + A770 LE + driver v.4255 + Win10 res 1920 x 1080.

After doing the modifications you mention in the steps to reproduce in the Performance Tuning within ARC Control and running the benchmark, I could not reproduce the Fan Speed Locking at 1200RPM and the temperature remained between 70 °C - 75 °C at all times, I could not observe that it raised over the 80°C
[This is a video I took while running the benchmark](https://youtu.be/5NILFprbCeA). I ran it around 3 times and the RPM has been fluctuating as expected in every run.

![ARC Control - Benchmark](https://user-images.githubusercontent.com/91162218/231291675-ab79d022-dd19-41b8-8009-8b471f23c0d8.png)

Something we have observed that helps in similar cases with ARC Control Telemetry (showing weird data) is performing a clean driver install with [DDU.](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html) 
Can you please let me know if you've tried this already? 

And about the fan curve options, I can submit it as a feature request so the team in charge is aware of it. 
Can you share the details on how you got to make the modifications?

Thanks, hope to hear from you soon

Karen

**Comment by XBravRevolutionz** [comment] 2023-04-12 16:55
Hey @Karen-Intel,

DDU or a fresh install of the drivers does usually correct this issue, but that is due to the configuration files being purged during a reinstall. I believe the holding "overclocking" settings may get into an undesirable state, and these values remain unchanged even when resetting the settings in the app as they're not normally accessible by the user.

This leads into the fan control modification in ACC. The "fan_mode" settings are not revealed in ACC as the visibility criteria is not met. By changing the performance_tuning.js value on (Currently) Line 111 to set visible to "true" instead of evaluating whether the feature is supported, the fan control options in ACC are exposed including curve editing.

![image](https://user-images.githubusercontent.com/102002385/231527848-ad7253b4-861f-47b9-a5d7-2848a57909fb.png)

![image](https://user-images.githubusercontent.com/102002385/231528027-296ba9dd-5304-4462-9c87-7068a10066c4.png)

The changed settings persist across reboots without issue.

Although the workaround is to basically state "all cards have fan control", it would be nice if the actual device profile settings within ACC list the A770LE and other cards as properly having fan control options.

I will work to recreate the 1200RPM scenario above and will create a detailed sequence as soon as I can. Thanks!

**Comment by Karen-Intel** [comment] 2023-04-28 17:49
Hey @XBravRevolutionz any update about recreating the 12000 RPM scenario? Just checking on pending items

Thank you

Karen

**Comment by Nidzhun** [comment] 2023-05-11 14:35
Have same issue with fans - 1200 rpm max after changing settings in performance menu - with Arc a750 and latest 4335 driver.

**Comment by Karen-Intel** [comment] 2023-05-11 14:43
Hey @Nidzhun thank you for your report. 
Can you share the exact steps to reproduce? I was waiting for feedback from the post submitter but no answer, we need more data to follow this up
Thanks a lot

Karen

**Comment by Nidzhun** [comment] 2023-05-11 15:28
Steps for reproduce this issue same that other already share. I change in Arc control for example power limit to 180 and run Superposition 4k opt benchmark and fan rpms start rising to 1200rpms+- and don't exceed this value, temperature rise to 90+ degrees. This can be fix only after restoring default values and rebooting system. What i additinally can say about it, if i change power limit with ArcTools app - it is not official tool for Arc graphic cards that allow same tweaking that Arc Control provide - fans works properly.

**Comment by Karen-Intel** [comment] 2023-05-11 15:43
@Nidzhun Okido, I'll get on the lab and provide an update soon, stay tuned

Karen

**Comment by Nidzhun** [comment] 2023-05-14 11:48
> Karen

I try to install other versions of Arc Control software and find out that version 1.53.4776 from 3491 driver don't have this issue - i can change all options in performance menu without fans rpms been locked to 1200.

**Comment by Karen-Intel** [comment] 2023-06-07 19:39
Hi all just FYI here's the article about [this issue](https://www.intel.com/content/www/us/en/support/articles/000094286/graphics.html)
We're going to keep this post open until the new firmware has been released.

Thanks

Karen

**Comment by Nidzhun** [comment] 2023-07-24 18:04
Hello again! It seems that with latest driver and arc control software i can't reproduse issue anymore, all working fine.

**Comment by Karen-Intel** [comment] 2023-07-24 21:17
@Nidzhun Yeeei I'm glad it is working for you now :) ARC Control has a new version with a few improvements

@IGCIT can you help us close this one? Not observed anymore w/ARC Control v.17

Karen

**Closed** 2023-07-25 08:18 UTC
Labels: Info: Needs Replication, Type: Arc Control
