### ISSUE TITLE
Fifa 22 stalls at pre-match drills with option to continue to match never appearing

### ISSUE THREAD

**Issue by diesel-dogg** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#151] opened 2022-06-24 15:58 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Fifa 22

### Game Platform [Required]

- [ ] Steam
- [X] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

1165g7

### GPU Driver Version [Required]

- [ ] 30.0.101.3109 (*latest*)
- [X] 30.0.101.1994
- [ ] 30.0.101.1960
- [ ] 30.0.101.1934
- [ ] 30.0.101.1660
- [ ] 30.0.101.1631
- [ ] 30.0.101.1404
- [ ] 30.0.101.1340
- [ ] 30.0.101.1191
- [ ] 30.0.101.1121
- [ ] 30.0.101.1069
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11
- [X] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [X] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssuOutput.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/8977454/ssuOutput.txt)

### Description and steps to reproduce [Required]

- Problem appears to be with certain textures associated with players/kits in the game. When these are selected, the game will freeze on the kit selection menu (directx11) or will proceed to the pre-game drills screen but not beyond that (directx12)

- This doesn't always happen but is easier to reproduce if a new driver version is installed and the shader cache is not yet fully compiled by the game for the driver. 

- A situation where I can consistently reproduce it is- select Champions League 2-legged semi-final from kick-off-> select Arsenal as away team and Liverpool as home-> the first match should go through fine-> when the option is presented to play the return leg, select that option-> kit selection screen is presented for the return leg of the tie-> proceed to match with default kits-> pre-match drill appears but option to go into the match never shows up.

Of course, there are other team/kit combinations that cause this too and it's a problem intel have acknowledged in the past

- This was a problem that was earlier reported to have been fixed by intel in a driver update and it did seem to have been fixed for a while but from version 1994 onwards, it is again present. 

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

1280*720

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

MSAA off and other settings to High in the companion settings app. Framerate capped to 60 in the companion settings app

### Crash dumps [Required]

no crash logs

**Comment by IntelSupport-Rozilah** [comment] 2022-06-27 03:49
hi @diesel-dogg,

I will start verifying the case as soon as possible once our setup is ready and will get back to you, so stay tuned!

**Comment by diesel-dogg** [comment] 2022-06-27 11:08
Posting a couple of videos to showcase the problem. In both, I complete the first match, go to the option of playing the return leg and proceed to select the "Play Match" option. 

In the DX12 version, you can see that I am taken to the pre-match drills and I am also able to run the drills but the option to start the actual match never appears on screen. For DX11, I have replicated the exact situation but I am able to proceed to the match. While the game always stalls at this point when using DX12, in DX11, it's hit or miss-- on some occasions, it just freezes and I have to reboot the system while other times (as shown in the video), it proceeds as expected. 

Please note that the game only supports DX12 officially and I have to modify a config file to manually force DX11. Performance is generally quite poor running this game with DX11. 

[DX12 gameplay](https://drive.google.com/file/d/1jsy8qYbC5ax8SaxYr8e-73fz8hTOC-7Y/view?usp=sharing)
[DX11 gameplay](https://drive.google.com/file/d/1g3f4jvA5wd_amJsMeGcgJrC3XfR3X-PL/view?usp=sharing)

**Comment by IntelSupport-Rozilah** [comment] 2022-06-29 02:26
hi @diesel-dogg,
The case is reproducible on our side. However, this doesn't seem to be a driver issue, as the game is not crashing
and a button seems to be not loading correctly, so the player cannot go in advance.
We found this reported to the origin communities multiple times for this case and the resolution provided worked as well from our end.
Could you please try and revert back to use if it's working as below link:
1. https://answers.ea.com/t5/Bug-Reports/FIFA-22-Stuck-on-Pre-Match-Game-with-no-Option-to-Skip/td-p/10873954
    - refer to this Youtube video solution: https://youtu.be/7UCBUkKsroU
2. https://answers.ea.com/t5/FIFA-20/quot-press-start-or-esc-to-play-the-match-quot-doesn-t-appear/td-p/8848761/page/2
   - refer to #17 
3. https://answers.ea.com/t5/Other-FIFA-Games/quot-PRESS-START-OR-ESC-TO-PLAY-quot-missing-after-playing-pre/td-p/6740786

**Comment by diesel-dogg** [comment] 2022-06-29 08:49
Thanks for looking at this. As I had shown in the videos I posted previously, the problem is circumvented by forcing directx11 but the performance is significantly poor compared to dx12 and there are occasional TDRs still with dx11. 

Currently, I am relying on DXVK to force the game to use vulkan and while that fixes the problem, I get a very prominent blue tint over all objects that should otherwise be white in the game. 

With regards your past Fifa 22 fixes-- I do acknowledge that this exact issue was never previously claimed to be fixed but I do remember that this had stopped happening and the game used to work fine after one of your TDR fixes for Fifa21/22. Unfortunately, I do not remember the exact driver version at this time. Of course, it is also possible that EA updated the game which again reintroduced the problem.

**Comment by IntelSupport-Rozilah** [comment] 2022-06-30 06:51
It is good if you remember which driver version is working well for next level study.
did you try link 1 and link 2 methods for on your end, may be the issue is fix  with good performance and without blue tint on objects?.

**Comment by diesel-dogg** [comment] 2022-07-02 10:55
The only consistent way I am able to get the game to work is by using vulkan. On the 1994 driver, the blue tint problem on Vulkan (via DXVK) is not present so I am using that for the time being. I'll open a ticket with EA and see if they can fix this for intel GPUs as they did fix it for more nvidia cards from what I know

**Comment by IntelSupport-Rozilah** [comment] 2022-07-05 07:59
@diesel-dogg, thanks for the reply and keep updated here if EA fix for Intel GPU as well.
@IGCIT , seems the case is not an Intel driver bug and the user has agreed to go to EA support, please proceed to close this case.

**Closed** 2022-07-05 10:58 UTC
Labels: Info: Needs Replication, Type: Regression, Type: Graphical Glitches
