### ISSUE TITLE
Stuttering in Ghostrunner

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#534] opened 2023-09-23 11:46 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Ghostrunner

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4826
- [ ] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 23.09.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12706336/Intel.SSU.23.09.2023.txt)

### Description and steps to reproduce [Required]

Stutter in Ghostrunner, with spikes up to 87ms when the game runs on average at 9ms (120FPS), everything set to max, ray tracing, 100% render scale.
In this recording, CapFrameX even says that 2% of the frames are stutter
CapFrameX recording : https://drive.google.com/file/d/1N6h4mCNNMT2Kp6fXhbR1CM_rQO0Gpjt7/view?usp=sharing

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920×1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Max, 1080p

### Device / Platform name

ASUS PRIME Z790-P WiFi D4

**Comment by Ilya-intel** [comment] 2023-10-04 11:28
@TheWonderfulTartiflette 
Tested same setting as you have and couldn't confirm stuttering. I also tested RTX 3060 with same settings and it shows a little bit of stuttering (see below). 
Your issue might be caused by RAM or CPU configuration.

Arc A770:
![ScreenshotA770](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/143084944/8cfff320-5176-4322-b288-a6d8a7b720b2)

RTX 3060
![ScreenshotNV3060](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/143084944/2223b33d-e00a-46ac-932e-050fe0439c4b)

**Comment by TheWonderfulTartiflette** [comment] 2023-10-04 11:30
Ram or CPU? Well I have 32gb of 3600MT/s RAM and a 13600K, so these should be plenty enough, no?

**Comment by Ilya-intel** [comment] 2023-10-04 11:45
@TheWonderfulTartiflette 
Either CPU or RAM or both. 
I've tested on 12600K and 16Gb DDR5 6000MT/s.
So, it might be related to memory config; probably tuning its' timings and/or frequency will affect stability, but this is a topic of discussion on game forum.

**Comment by Ilya-intel** [comment] 2023-10-05 09:21
@TheWonderfulTartiflette 
FYI just tested the game on a weaker PC with DDR4 3200MT/s and A750 with the same maximal graphics settings and still don't see that much of a stuttering.
![Screenshot 2023-10-05 110853](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/143084944/327af79f-b56b-43f7-9efe-80d7781765c2)

**Comment by Ilya-intel** [comment] 2023-10-12 08:53
@IGCIT 
Please close this case.

**Closed** 2023-10-12 16:03 UTC
Labels: Info: Needs Replication, Type: Bad Performance
