### ISSUE TITLE
Counter Strike Global Offensive will not fullscreen itself again after alt-tabbing out

### ISSUE THREAD

**Issue by AverageGithubBugReporter** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#224] opened 2023-01-18 23:05 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Counter Strike Global Offensive

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5-12400F

### Graphic Card [Required]

Arc A770 Special Edition

### GPU Driver Version [Required]

- [X] 31.0.101.4034 (*latest*)
- [X] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [X] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10451838/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Start up Counter Strike and keep alt tabbing out of the game when it's in fullscreen mode (not borderless windowed) and eventually the game will refuse to fullscreen itself again

Happened twice alone last night while I was playing, the first time the game closed itself while I was clicking on it trying to get it to reopen, second time I alt-tabbed out and it simply refused to open again, forcing me to close the game manually

Running the game in borderless windowed seems to circumvent this

Happens on both driver 4032 and 4034

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2560x1440p

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

<img width="1280" alt="Screenshot 2023-01-18 180301" src="https://user-images.githubusercontent.com/123030628/213314388-559dc9f2-ef94-4e54-95fa-054e2464bdd3.png">
<img width="1280" alt="Screenshot 2023-01-18 180338" src="https://user-images.githubusercontent.com/123030628/213314395-b8ca40fa-bdd5-43fd-b93a-71d81ab86f36.png">

### Crash dumps [Required, if applicable]

[(failed)csgo_20230117_225733_2_x00EF40A0.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10451860/failed.csgo_20230117_225733_2_x00EF40A0.zip)

**Comment by IntelSupport-Arun** [comment] 2023-01-19 12:55
Hi @AverageGithubBugReporter ,

Thank you for reaching out to us.

This is a known issue in the steam community and can see the below recommendation. Give it a try if you haven't tried it yet:

1. Go to ‘focus assist‘, and Turn off the  ‘When I’m playing a game.  After this Try to launch the game and verify the issue.

2. Go to **C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive** , then right click the **csgo.exe** (the one with the shortcut icon) and select properties and check the box disable "fullscreen optimizations" under the compatibility tab. After this Try to launch the game and verify the issue.

**Comment by AverageGithubBugReporter** [comment] 2023-01-19 16:31
> Hi @AverageGithubBugReporter ,
> 
> Thank you for reaching out to us.
> 
> This is a known issue in the steam community and can see the below recommendation. Give it a try if you haven't tried it yet:
> 
>     1. Go to ‘focus assist‘, and Turn off the  ‘When I’m playing a game.  After this Try to launch the game and verify the issue.
> 
>     2. Go to **C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive** , then right click the **csgo.exe** (the one with the shortcut icon) and select properties and check the box disable "fullscreen optimizations" under the compatibility tab. After this Try to launch the game and verify the issue.

Hello, I have done as requested here, I did the following:

Open CSGO>change display output to fullscreen only>close game>disabled fullscreen optimizations>reopened the game

The game does not launch at all with that option enabled, the game launches and the screen goes black for a second, then the game closes itself

Unchecking "disable fullscreen optimizations" allows the game to launch normally again

**Comment by IntelSupport-Arun** [comment] 2023-01-20 10:52
Hi @AverageGithubBugReporter ,
 Is the issue still observed even after  "disabling fullscreen optimizations"? Could you confirm?

**Comment by AverageGithubBugReporter** [comment] 2023-01-20 17:37
> Hi @AverageGithubBugReporter , Is the issue still observed even after "disabling fullscreen optimizations"? Could you confirm?

Hello, the game does not open at all with "disable fullscreen optimizations" enabled in the properties of the CSGO.exe

A black screen comes up for a second, then the desktop shows up again and nothing happens

**Comment by IntelSupport-Arun** [comment] 2023-01-24 17:58
Hi @AverageGithubBugReporter ,
Thank you for the confirmation.  We will verify from our side and let you know the update soon.

**Comment by IntelSupport-Arun** [comment] 2023-01-25 11:20
Hi @AverageGithubBugReporter ,

I have verified the issue on our side and cannot reproduce the issue. Im able to ALT+TAB while playing the game.
Please see the below video for your reference. 
https://youtu.be/TMJIXtz6sSE

**Comment by AverageGithubBugReporter** [comment] 2023-01-26 01:21
Hello @IntelSupport-Arun thanks for your reply

I will attempt to get a video of this occurring sometime this week so you can see what I'm talking about

I have since switched back to an NVIDIA system and repeatedly alt-tabbed out of the game and this has not occurred yet so I very much suspect it is Arc related.

Thanks for your time

**Comment by IntelSupport-Arun** [comment] 2023-01-26 09:49
Hi @AverageGithubBugReporter ,

Can you try disabling the steam overlay under the general setting in steam?

**Comment by IntelSupport-Arun** [comment] 2023-01-30 03:04
Hi @AverageGithubBugReporter ,

Any latest news for us? Did you try disable the steam overall setting?

**Comment by AverageGithubBugReporter** [comment] 2023-01-30 04:59
Hello, sorry I haven't had time as of late

I'll check this tomorrow and report back

**Comment by Vipitis** [comment] 2023-02-03 01:34
I have experienced a similar issue. As I am running dual displays and playing the game at a not native resolution. What has worked for me is to first go to desktop on the main screen (where I play the game) and then don't ATL+tab back in, but instead click on the desktop once and then wait a second, click on the game in the taskbar and it opens correctly on the main screen. 

There have been several issues where the game opens on the wrong screen, or applications running on the 2nd screen end up on the main screen as well as the game crashing and the main screen non stuck to it's non native resolution. 
I can post a full report and steps to reproduce it if that helps

**Comment by IntelSupport-Arun** [comment] 2023-02-07 06:07
Hi @AverageGithubBugReporter ,

Do you have any updates for us?

Hi @Vipitis,
Thank you for the input. For your issues, we recommend you to raise a new ticket with the full reports so that other customers can benefit from your ticket. Also we are recommending here to verify the issue with the latest Arc Graphics driver [31.0.101.4091](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html?) before.

**Comment by IntelSupport-Arun** [comment] 2023-02-08 07:57
Hi @AverageGithubBugReporter , Since we are not getting any reply from your side and we cannot reproduce the issue on our side  we proceed to close this case.
Also, there is a new version of the graphics driver [31.0.101.4091](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html?) you may please verify it.
For any new issue, you may please raise a new thread and we will continue our support.

**Comment by IntelSupport-Arun** [comment] 2023-02-08 07:59
Hi @IGCIT , We are not getting any response from the customer side and we are unable to reproduce the issue on our end, so please proceed to close this case.

**Closed** 2023-02-08 08:32 UTC
Labels: Info: Needs Replication, Type: Graphical Glitches
