### ISSUE TITLE
Call of Duty Vangaurd. Fps drops in menu and when taking damage.

### ISSUE THREAD

**Issue by mongoose999** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#113] opened 2022-02-26 23:59 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Call of Duty Vangaurd

### Game Platform [Required]

- [ ] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [X] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

1165g7 

### GPU Driver Version [Required]

- [X] 30.0.101.1340 (*latest*)
- [ ] 30.0.101.1191
- [ ] 30.0.101.1121
- [ ] 30.0.101.1069
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

1

### Description and steps to reproduce [Required]

Just run the game immediately the menu will run extremely slow and around 15fps. 
During gameplay anytime you are shot or take any damage the frame rate dips to 5fps until the damage overlay dissapears. 

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1280x720 or any resolution

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Any setting. Same results 

### Device / Platform name

Onexplayer 

### Crash dumps [Required]

Game doesn't crash

**Comment by estebanr863** [comment] 2022-05-23 22:55
Hi @mongoose999,

Please note that the Core i7-1165G7 is well below the game’s minimum requirements. The [game requirements](https://support.activision.com/vanguard/articles/minimum-recommended-system-requirements-vanguard) ask for at least an Nvidia 960, which has a [3DMark score of 2293](https://benchmarks.ul.com/hardware/gpu/NVIDIA+GeForce+GTX+960+review). While the Intel Xe GPU [3DMark score is 1370](https://benchmarks.ul.com/hardware/gpu/Intel+Iris+Xe+Graphics+G7+96EU+review). Been this the case, we cannot ensure that the game will run as the developer intended, as the game requires more performance than this Intel integrated GPU can deliver.

That been said, a similar issue to what you described was reported internally, but on Intel Arc GPUs. This may have a similar root cause to your issue, and if it is found that a fix can be developed on our side, it may also help you. We are working on trying to replicate this Arc issue. So, I will monitor this other issue and let you know the outcome.

**Comment by EstebanIntel** [comment] 2022-10-27 00:26
Hi @mongoose999,

A possible fix for this issue is included with our latest driver version [31.0.101.3790](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html). Can you please install this version and test it?

**Comment by EstebanIntel** [comment] 2022-11-04 22:55
Hi @mongoose999,

Where you able to test the fix?

**Comment by mongoose999** [comment] 2022-11-04 23:59
Yes I have tested it today. It seems to be working now. Thank you. I would
say the game is playable now roughly 30fps

**Closed** 2022-11-05 08:38 UTC
Labels: Info: Needs Replication, Type: Bad Performance
