### ISSUE TITLE
"Retro Scaling Type" feature not working correctly

### ISSUE THREAD

**Issue by Susie1818** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#665] opened 2024-01-06 14:53 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows 11 desktop

### Processor / Processor Number [Required]

intel Core i5-13500

### Graphic Card [Required]

intel Arc A750 LE

### GPU Driver Version [Required]

31.0.101.5081

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[SSU_20240106.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13850068/SSU_20240106.txt)

### Description and steps to reproduce [Required]

Global Game Settings ➜ Post-Processing ➜ Retro Scaling Type ➜ Fixed Width

When trying to draw a 1920x1080 desktop on a 2560x1440 monitor, the mouse pointer still uses the mapped location on the 2560x1440 area, resulting in user being unable to click on the right place.

[Demonstration here](https://youtu.be/WImlYKosRsU).

**Comment by Susie1818** [comment] 2024-01-12 03:47
@Ilya-intel 

The video you shared didn't even shrink to pixel-to-pixel 1080p physically. I don't know what you were doing.

**Comment by Ilya-intel** [comment] 2024-01-12 09:01
@Susie1818 
Do you have a video recording of the issue?

**Comment by Susie1818** [comment] 2024-01-12 09:17
@Ilya-intel 

> Do you have a video recording of the issue?

Please see the original post. I've included a video already.

**Comment by Ilya-intel** [comment] 2024-01-12 09:52
@Susie1818 
My bad, now I see.
I'll collect more logs and information and pass it to devs.
Thanks for reporting.

**Comment by Ilya-intel** [comment] 2024-03-07 10:14
Hi @Susie1818 ,
I got some information from devs.
So currently we're working on the updated version of Arc Control which will include a lot of fixes for known issues and this one was also taken into consideration.
However, this issue will be here for some time until the fixed version goes live.

**Comment by Susie1818** [comment] 2024-03-07 11:04
Hi @Ilya-intel 

Thank you for keeping me posted.

**Comment by Ilya-intel** [comment] 2024-03-18 10:48
Hey @Susie1818 ,
We'll proceed to closure of this thread since the issue is reported and there is nothing else we can do here.
This [article](https://www.intel.com/content/www/us/en/support/articles/000097910.html) will be updated once the scaling will be fixed.

**Comment by Ilya-intel** [comment] 2024-03-19 09:44
@IGCIT 
Please close this thread.

**Closed** 2024-03-19 10:51 UTC
Labels: Info: Replicated, Type: Graphical Glitches
