### ISSUE TITLE
[Critical] Windows cannot boot after 4952 installation

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#574] opened 2023-11-02 11:14 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Widower

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

31.0.101.4900

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

Can't

### Description and steps to reproduce [Required]

I have tried to install 4952. When the installation finished, I was not able to click with my mouse, even though I could move it and I tried to replug it. So I rebooted my PC, and I'm constantly getting "PAGE_FAULT_IN_NON_PAGED_AREA" BSOD just after the BIOS screen. Windows is now telling me that it cannot boot by itself, and tells me that I should repair it. I'm currently trying to repair it
It's not a support ticket, but more like a critical issue report

### Device / Platform

ASUS Prime Z790-P WiFi D4

### Crash dumps [Required, if applicable]

Can't 

### Application / Windows logs

Can't

**Comment by freak2fast4u** [comment] 2023-11-02 16:37
I can't help but notice the VBIOS version has been updated to 1068 : 
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3486369/9204c167-c9be-48e7-bae8-7283989fed8f)

Which version of the drivers shipped this ? I don't see it mentionned in the release notes.

**Comment by freak2fast4u** [comment] 2023-11-02 16:50
My recent chain of driver installs went as follows, and this upgrade went fine for me : 
- DDU + install 4887 WHQL (to remove 4900 which brought some perf regressions in 3dmark benchmarks)
- Install 4900 on top after a manual download from intel.com, and checking the "clean install" checkbox during install
- Install 4952 using DSA, and not checking the "clean install" checkbox (which all things considered would be the typical thing to do right ? I wanted to keep my settings, and messing around with DDU shouldn't be necessary after all ...).

So far so good.

A few ideas here : 
- OP's mobo or mobo drivers are broken, though since he's using DSA, dare I guess this shouldn't happen :)
- windows 11 install is broken in some way, maybe after a recent update
- the vbios update went wrong for an unknown reason
- something else altogether

Let's see who else is affected ...

**Comment by TheWonderfulTartiflette** [comment] 2023-11-02 18:35
Well actually I really need help, because even DDUing in safe mode and restoring the system does not help

**Comment by Karen-Intel** [comment] 2023-11-06 15:35
@TheWonderfulTartiflette @freak2fast4u thank you for posting your findings. We are looking for info regarding this new FW update. In the meantime, I have been able to upgrade without any issue in my system. Uninstalling DDU in safe mode would be enough for the system to boot. Like freakfast4u said, let's see who else has been impacted

Karen

**Comment by TheWonderfulTartiflette** [comment] 2023-11-06 15:46
@Karen-Intel well actually no, DDUing did not even do anything, even though it has been done successfully.
Same for booting in safe mode. I could only boot in safe mode with support for network (even though I did not actually have access to the internet)

I sent my PC to a local PC repair store, and they told me that they tried a ton of things, and nothing worked. They also told me that the driver update "broke core Windows components". 
If it's really needed, maybe I could send the phone number of the PC repair store, do that you guys can get info from them for some sort of clues about what happened?

**Comment by Arturo-Intel** [comment] 2023-11-06 15:56
@TheWonderfulTartiflette Hmm "broke core windows components", Ok, lets wait for more reports.
We can't reproduce this behavior on our end, 
It could be something isolated on your side.

At the end, the repair store guys reinstalled windows on your PC?
Or what did they do to fix it?

--r2

**Comment by freak2fast4u** [comment] 2023-11-06 15:56
@TheWonderfulTartiflette now you mention it, I ended up in a similar situation when reenabling the Ryzen IGFX and installing adrenalin drivers at some point. I ended up running some powershell scripts to repair the driver store and I found myself lucky that it worked. I don't have access to my browsing history right now, but I'll search into it as soon as I come home later this evening. I'm not sure how the procedure might differ from windows 10 to 11 though, but it could be worth a shot. I'll catch you later.

**Comment by TheWonderfulTartiflette** [comment] 2023-11-06 16:16
@Arturo-Intel nope, because my bad I resent  them the PC because they told me that had to check a couple more things before being sure that the only fix is reinstalling all of Windows

**Comment by TheWonderfulTartiflette** [comment] 2023-11-06 16:17
@freak2fast4u faudra qu'on refasse un cs un jour :)

**Comment by TheWonderfulTartiflette** [comment] 2023-12-05 09:21
So in the end, they said that the update basically broke the BIOS. They flashed it, and it worked

**Comment by Karen-Intel** [comment] 2023-12-07 19:18
Yeei we're glad your system is working!

@IGCIT can we close this one? Seemed to be related to a BIOS issue :)

Karen

**Closed** 2023-12-07 19:21 UTC
Labels: Info: Needs Replication, Type: Support
