### ISSUE TITLE
When you reboot the system, the GPU no longer sends a video signal to the screen

### ISSUE THREAD

**Issue by M4th12** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#277] opened 2023-03-28 20:38 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows

### Processor / Processor Number [Required]

AMD Ryzen 1700X

### Graphic Card [Required]

Intel Arc A750

### GPU Driver Version [Required]

- [X] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssllog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11093938/ssllog.txt)

### Description and steps to reproduce [Required]

Start the system, go to windows and restart, HDMI output was used, i not have a DP port, ReBar was enable

[ssllog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11093946/ssllog.txt)

### Device / Platform

AMD platform B450

**Comment by Karen-Intel** [comment] 2023-03-30 02:20
Hi @M4th12 

Thank you for posting your findings. We'll check issue repro on our end and get back to you if we have questions, talk to you soon

Karen

**Comment by Karen-Intel** [comment] 2023-03-30 15:49
Hi @M4th12 

Help needed. For debug purposes,, can you share the info of your card under this section? 

![image](https://user-images.githubusercontent.com/91162218/228892525-701af17d-cbd7-44dd-a4ad-ca1ecfc91f07.png)

It will help me a lot, thanks!

Karen

**Comment by M4th12** [comment] 2023-03-30 17:04
Hi, the version that I have is 20.1053.0
![Arc Panel](https://user-images.githubusercontent.com/89078127/228911582-c5034479-fc4e-464c-be21-d01f0747a2c4.PNG)

**Comment by Karen-Intel** [comment] 2023-03-30 17:27
Hi @M4th12 thank you. I just confirmed you have the right version :)

However, due to the symptom, I should continue my debug. I will get back soon with my findings

Thanks! 

Karen

**Comment by Karen-Intel** [comment] 2023-03-30 19:53
Hi @M4th12 

Just FYI, I was able to reproduce the same behavior using the HDMI port only. 
After a few consequent restarts I could determine a 50% of failure rate in a system very similar to yours.
However, I have found that our development team is already aware of this issue and it might take from 3 to 6 months to have a fix released. We recommend to keep your drivers up to date and not to close this post, as in due course we will come back and update.

Thank you so much for your help debugging this issue along with us! Have a great day :)

Karen

**Comment by M4th12** [comment] 2023-03-31 08:34
> I have a very similar issue, I can only get the signal back by unplugging and plugging back in the HDMI cable after a restart. Latest drivers 4255, windows 11 22H2.

Mine even if I unplug and replug don't send a signal, I need to force a shutdown

**Comment by M4th12** [comment] 2023-04-08 09:56
Hi @Karen-Intel, I did some more tests, I tried with a DP cable and now the computer every time I restart it gets signal back but I also tried reconnecting HDMI and now it works, I also tried on another monitor but so far it seems to work. I don't know what the DP cable did but now they both work

**Comment by ghyatzo** [comment] 2023-04-08 11:40
I found the same thing. After switching to DP everything works now.

**Comment by Karen-Intel** [comment] 2023-04-10 15:46
Thank you both @M4th12 and @ghyatzo I'm very glad to see you're getting signal from the GPU after a reboot. 
Now if the issue is not present anymore, would you mind helping me closing this case?
Thanks a lot for you help. If you see the issue again we can always open a new one

Karen

**Comment by Arturo-Intel** [comment] 2023-05-12 03:57
@IGCIT I think we can close this case now :)

**Closed** 2023-05-12 06:29 UTC
Labels: Info: Needs Replication, Type: Support
