### ISSUE TITLE
Constant audio stuttering, and audio timing issues, in nearly every game I play. everything else works flawlessly.

### ISSUE THREAD

**Issue by bleujei** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#737] opened 2024-03-13 18:27 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Control, God of War (2018), Remnant 2, Remnant: From the Ashes, Uncharted Collection, Final Fantasy 7 Remake/Intermission

### Game Platform [Required]

- [X] Steam
- [X] Microsoft Store
- [X] GOG Galaxy
- [X] Ubisoft Connect
- [X] Battle.net
- [X] Epic Games
- [X] Rockstar Games Launcher
- [X] EA app
- [X] Amazon Games app
- [X] Other (please specify)

### Other game platform

PC gamepass

### Processor / Processor Number [Required]

ryzen 7600x

### Graphic Card [Required]

Intel Arc a750 8gb founders

### GPU Driver Version [Required]

31.0.101.5333

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [X] DirectX11
- [X] DirectX10
- [X] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

This doesn't support the file type? are you kidding me?

### Description and steps to reproduce [Required]

It happens just as you're playing, it's like the audio either goes too fast or too slow, some sound effects happen before specific voice lines that are supposed to go first, characters voices don't match their mouth's movement, first time I noticed it really bad, was playing God of War 2018, 1440p, mid settings, in the first fight against baldur, kratos would be doing a spartan rage scream and he's not in spartan rage yet. it's weird and off putting. I've ignored it for a while, because the majority of my issues disappear on a monthly basis, so I assumed someone would report it, and get to it, but that hasn't happened yet. 

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1280x720, 1920x1080, 2560x1440

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Yea I'm not sending pictures of an audio issue, that makes no sense

**Comment by Arturo-Intel** [comment] 2024-03-13 20:22
@bleujei would be awesome if you can share a video of this behavior

**Comment by Felipe-Intel** [comment] 2024-03-18 20:53
hello @bleujei 
Any luck recording the video? Please capture this with an external device like a mobile phone so the recording doesn't use system resources. Also, if among the titles you mentioned is one where this issue can be consistently reproduced (always the same scene or location in the game) and that doesn't take to long to get there, please share the details. If you have a saved game file in such place, that would be helpful too.

**Comment by bleujei** [comment] 2024-03-18 20:57
I think I can do that, because unless it's stopped happening since my first
playthrough, god of war definitely did it worst, but I am also a full time
college student, and I really don't have very much free time, between,
school, work, and being a single parent. I will try to fit an hour into my
schedule to do that.

**Comment by Felipe-Intel** [comment] 2024-03-25 19:03
Hi @bleujei following up with this. Just wanted to tell you to try with our latest driver available, 101.5379 as of today, 3/25. You can find it [here](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)

**Comment by freak2fast4u** [comment] 2024-04-01 16:44
FWIW, the only game I have in common with OP's list is FF7R, and it's smooth as butter with freesync enabled in my case on 5379 drivers (7800X3D, A770 16GB). No audio issues over here in any other of my games. 
There's a few frame pacing issues with the 60fps frame limiter in-game, though I can't conclude it's a driver issue at all, it could be a game issue for all I know. 
I didn't test other recent drivers with this game, since I played it last over 6 months ago. 
I just used this issue as an excuse to play through FF7R/Intermission and it went fine :)

@bleujei : 
- is game mode enabled in windows ? (it should be enabled imho)
- did you make sure to disable windows game dvr ? At least if you're not using it ...
- What's your motherboard model ? 
- Have you installed the latest chipset and audio drivers and bios ? 
- Have you tried disabling the iGPU ? I needed to do this for some games that switch to AMD graphics even if it's an iGPU. You wouldn't necessarily notice since Windows will silently pass the graphics through the PCI-E bus to where your display is connected (on your Intel Arc card). 
- Are you using the motherboard jack audio output, or the HDMI/DisplayPort audio out via your display ? 
- If you're using HDMI or DP out, which one is it and what's your screen model ? 
- Please try posting the ssu report again, it's a simple text file. If it doesn't work, zipping the file will do the trick. There's some useful info in there for the Intel engineers.

**Comment by bleujei** [comment] 2024-04-01 16:56
Latest drivers installed on everything, I'm running the Msi b650m-a pro
wifi motherboard. My audio issues stopped in FF7R after I forced windows to
stop using my 7600x as the video driver, not sure why it defaulted to that,
but that's the only one I managed to fix like that. I also experience this
issue the most, when using HDMI, my audio stutters when using Bluetooth
headphones, but I've deduced that's likely windows screwing with the
bluetooth drivers, after disabling and re-enabling them, my bluetooth audio
works fine, still have issues with HDMI, can't speak on Display port, don't
have a set up that allows for it yet. Sorry if I'm not being mpre helpful
or clear about things, haven't built a pc since amd was running vega still,
and I get lost in my work easily.

**Comment by Felipe-Intel** [comment] 2024-04-03 18:37
Hi @bleujei I played God of War (13400+A750, 16GB RAM, Win10, driver 5382) and I haven't experienced stuttering or audio timing issues. This was a freshly installed win10 22h2 with no updates, needed for other test. Then I proceeded to install all the updates Windows recommended until the OS was up-to-date, tested the game again and had no issues either. 
Aside from disabling the AMD iGPU (are you doing it in the BIOS?), have you tried (or could you try) with another cable and/or monitor? I'm assuming you are seeing this issue with a straight connection between your Arc card and your monitor. If this is not the case, please share the exact details of your setup. On the other hand, if you find the problem is with your monitor, please share the make and model and in the meantime I'd recommend to contact its manufacturer customer support to report this issue. 

Finally, you can try [verifying your Windows system files](https://support.microsoft.com/en-gb/topic/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system-files-79aa86cb-ca52-166a-92a3-966e85d4094e) since you are seeing the problem with multiple games. BTW, are you seeing this issue with a media player, streaming service via app (twitch, discord) or in the browser (youtube, disney+, etc)??

**Comment by bleujei** [comment] 2024-04-03 18:46
I only experience this with games, not videos, shows, movies or music, all
of that works flawlessly. I don't have another monitor that I can test this
with, all I got is hdmi. I have the a750 connected directly to a 60hz 4k
HDR Phillips TV through HDMI, not positive on the exact model, I'll double
check. Windows is completely up to date. Also forgot to mention I am
running 32gbs of 6000mhz ddr5 ram with the previously mentioned specs. The
IGPU is disabled from the Bios. Rebar is on, from the bios. It's exhausting
how much I've checked things lmao. I'm gonna keep trying to figure it out
though. I'm rooting for Intel in this GPU race.

**Comment by Felipe-Intel** [comment] 2024-04-04 03:45
A few more suggestions: 
Try different HDMI cable(s). Not all cables are created equal. 
Test with VSync ON an OFF. 
If this doesn't work, I will need your help with some data and logs.

**Comment by Felipe-Intel** [comment] 2024-04-16 21:36
Hi @bleujei Were you able to try the above recommendations? Unfortunately we don't have a similar panel and as mentioned before, I didn't experience any problem with the equipment I have available.

**Comment by Felipe-Intel** [comment] 2024-04-23 16:01
Since we have not heard any feedback regarding our previous post, we will close this thread now. If you need further assistance, please create a new thread and refer to this one.

**Closed by Felipe-Intel** 2024-04-23 16:01 UTC
Labels: Info: Needs Replication, Type: Support
