### ISSUE TITLE
Whole display occasionally flickers black playing video in Firefox

### ISSUE THREAD

**Issue by stefan2225** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#357] opened 2023-06-23 17:43 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Mozilla Firefox

### Processor / Processor Number [Required]

Intel i9-12900K

### Graphic Card [Required]

Intel Arc A770 Limited Edition

### GPU Driver Version [Required]

- [X] 31.0.101.4502
- [X] 31.0.101.4499
- [X] 31.0.101.4382
- [X] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [X] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11850844/igcit_ssu.txt)

### Description and steps to reproduce [Required]

When playing back video in Firefox I occassionally have my screen flicker black for a moment as if it turned off for a moment. Sometimes it happens rarely while other times it happens 3-5 times in a row (please see attached video). Shortly before it happening a white line may appear at the upper part of my screen.
I have not tested all sites but I first noticed this watching YT Shorts and normal Youtube. I have tried many different driver releases, reinstalling each multiple times with DDU. I can't reproduce this in either Microsoft Edge or Google Chrome.

However when I disable Adaptive Sync on my monitor's OSD this seems to almost completely stop it from happening (disabling it inside Windows' settings and Arc Control doesn't make it stop).
All in all I think this is a very weird issue and don't know how to proceed. I tried another OS (Linux, opensuse tumbleweed to be specific) and the issue does not appear there. The iGPU on the very same drivers doesn't show this problem. Only changes I have done in the firmware since installing this card are enabling ASPM native control and setting every pcie link to L1.

Some more information about my system:
CPU: Intel i9-12900K
Motherboard: MSI Pro Z690-A WIFI (ddr5 version)
PSU: be quiet! Straight Power 11 Modular 80+ Platinum 650 watts
Monitor: LG Electronics 27GN800-B (there is a 2022 and a 2023 version, not sure of any differences but I bought mine in 2022)

I opened a ticket on Intel's support page on the 8th of this june but it seems to be going nowhere, not sure if I haven't been clear enough but they are trying to schedule a remote session with me right now. I have tried recording this with Arc Control but it does not show up in video.

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/33325954/2c50f466-1e5a-473b-85f1-7cd8c2a99569

**Comment by Karen-Intel** [comment] 2023-06-23 18:48
Hey @stefan2225 thank you for your report!

We have seen similar behavior when launching Spotify web in Firefox in an ASUS 32" monitor. 
Can you try if it does the same for you? > Monitor going black for a sec and then waking back up.
Just thinking it might be related and looking for other ways to repro.

If you can also share the refresh rate of your monitor or the details on ADVANCED to see if it has SDR or VRR that would be great :)

Apologies on the delay on Intel Support, workload is heavy but now that you have got to us we will be reporting it ASAP.
 
Now, for updates and fixes once the root cause has been found, we will post here when the fix is target to get in a public release (which might take from 3 up to 6 months, sometimes takes less than that) so let's keep this post open in the meantime and we will get back here as soon we get news or if we need anything else.

Have a great weekend

Karen

**Comment by stefan2225** [comment] 2023-06-23 19:12
Hello,

Thanks for responding.
I'm using the monitor in SDR mode, I think I could enable HDR but this monitor has no certification (it says this in advanced display settings)
Monitor supports 144hz but I am running it at 120hz (see attached image, unfortunately my windows language isn't english)

I'm trying to reproduce it in Spotify right now but no results yet, nothing happening when opening it or playing a song - I'll get back to you once I manage to reproduce it

![grafik](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/33325954/a7e7d32d-228e-4b28-8e8b-c36c2589ecc7)

**Comment by stefan2225** [comment] 2023-06-23 20:14
Forgot to mention, yes the monitor supports VRR, that's what I meant before by Adaptive-sync.

**Comment by Karen-Intel** [comment] 2023-06-26 18:24
@stefan2225 Thank you for the details

I am already submitting this issue with the details you shared. Like I mentioned, the fix may take a while to be out but we will update here in case we get any news sooner.

Have a great week!

Karen

**Comment by stefan2225** [comment] 2023-08-19 13:29
@Karen-Intel any update on this?

completely disabling Pcie ASPM support in BIOS seems to fix this, I would assume it's a issue with the GPU quickly entering some sort of idle state and then immediately returning from it causing the screen flicker.

**Comment by Karen-Intel** [comment] 2023-08-23 15:54
Hey @stefan2225 yeah we have not been able to consistently reproduce anymore :(
I remember you mentioned it was related to Adaptive Sync, which is what we thought was causing it. We're currently testing with AORUS systems with BIOS updated to the latest and cannot be able to repro.
I can see there's [a new BIOS version for your system](https://www.msi.com/Motherboard/PRO-Z690-A-WIFI/support), can you update your machine and let us know if you see any change? 

TY

Karen

**Comment by stefan2225** [comment] 2023-08-26 14:12
@Karen-Intel I am on the latest available BIOS version (7D25vAD) for my system and using driver v.4644. No change in behavior. Maybe specific to my motherboard vendor?

**Comment by Karen-Intel** [comment] 2023-10-17 16:35
Hey @stefan2225 we've got several improvements in these type of issues. Could you let me know if you're still facing it w/driver v.4887? TY in advance

Karen

**Comment by Karen-Intel** [comment] 2023-10-24 17:46
@IGCIT could you help close this one please? Customer can reopen if issue persists with driver v.4900

Karen

**Closed** 2023-10-24 18:08 UTC
Labels: Info: Needs Replication, Type: Graphical Glitches
