### ISSUE TITLE
Trackmania needs dxvk to be opened

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#340] opened 2023-06-12 15:31 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Trackmania 2020

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 12.06.2023 (4382).txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11725217/Intel.SSU.12.06.2023.4382.txt)

### Description and steps to reproduce [Required]

Try to launch Trackmania, nothing else. It will tell you that the game files are corrupted or something, but this gets fixed when using dxvk (even though that brings some issues)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

Any

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Not applicable

**Comment by TheWonderfulTartiflette** [comment] 2023-06-12 16:29
> @TheWonderfulTartiflette Are you seeing this issue in the free version of the game? https://store.steampowered.com/app/2225070/Trackmania/
> 
> --r2

This is the one I've been talking about, so yes I do

**Comment by Arturo-Intel** [comment] 2023-06-12 16:37
@TheWonderfulTartiflette ok thanks, just to confirm is this the error message you are seeing when trying to play the game?
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/e7803cda-9f78-43e3-baa8-ff820760c29a)

--r2

**Comment by Arturo-Intel** [comment] 2023-06-12 16:40
OK, Let me get in touch with our devs here and open an internal case to track this one. 

Thank you for reporting this,
-- r2

**Comment by TheWonderfulTartiflette** [comment] 2023-06-16 22:10
> OK, Let me get in touch with our devs here and open an internal case to track this one.
> 
> Thank you for reporting this, -- r2

Thanks. Quick question: If I report something in IGCIT, a bug is confirmed, and after like a month, the bug is then fixed, will you notify me on the original GitHub issue that the bug has been fixed, or like the Intel Arc community forums, you'll close the thread and never notify the user who reported the issue about the bug status?

**Comment by Arturo-Intel** [comment] 2023-06-16 22:48
We will close this case when you confirm the issue is fixed in XXXX driver version :)
So no worries, you will get notified in this thread when we have a fix

**Comment by TheWonderfulTartiflette** [comment] 2023-06-17 19:45
Thanks a lot, I hope that'll be fixed soon!

**Comment by IGCIT** [comment] 2023-06-17 19:47
please keep this open until a fixe has landed, you will be pinged to confirm it has been fixed when a driver with a possible fix is released

thanks

**Comment by TealDolphin** [comment] 2023-06-21 07:00
I have the exact same issue with the free version of trackmania. I am on windows 10 build 19045.3086 I get the same pop-up when I try to open it on my arc card but it launches to the menu just fine when I force windows to launch from integrated graphics. I am on the beta driver 31.0.101.4499, would you prefer a new ticket opened to give you more information or is letting you know here good enough?

**Comment by Arturo-Intel** [comment] 2023-06-21 14:31
@TealDolphin No need for a new thread. This case is still Work in progress. When we have news about this I will share it through this thread.

--r2

**Comment by Vipitis** [comment] 2023-06-25 00:01
This has been a known issue since November (if not October). The devs (Nadeo/Ubisoft) have noted that it is investigated in their forum back in October 2022 [since been closed?](https://discussions.ubisoft.com/topic/174735/trackmania-not-starting-with-intel-arc-gpu/6?lang=en-US) - here seems to be an [archived mirror](https://devtrackers.gg/trackmania/p/0e12a611-trackmania-not-starting-with-intel-arc-gpu)

How ever, their "official" stance from the Steam Discussion has been the following:
> You're using a Intel GPU, those are not supported by the game and you need to get another graphics card

[source](https://steamcommunity.com/app/2225070/discussions/1/3762229949247721580/#:~:text=handful%20of%20factors%3A-,%2D,-You%27re%20using%20a) and they tell you to use DXVK instead further down. But told me it's being looked at back in [February](https://steamcommunity.com/app/2225070/discussions/1/3762229949254388791/#c3762229949255026315). This isn't exclusive to the steam release of the game. It did exactly the same earlier in Ubisoft Connect. 

This issue might simply be related to the game checking if your graphics vendor is "intel" and then throwing this error to avoid players with iGPU playing the game and therefore shouldn't be too difficult to address. Intel has marketed some game releases with Ubisoft like Settlers.

**Comment by TealDolphin** [comment] 2023-06-25 02:34
Thanks for all the information. That's a strange position from Nadeo in my opinion given that it works flawlessly with dxvk and works great, although low resolution, on my amd igpu.

I launch it from Epic Games through Ubisoft Connect so the issues seem inherent to Trackmania and not specific to how it is launched.

**Comment by lel-amri** [comment] 2023-09-06 09:33
Hello there, thanks for working on this. I'm surprise the issue comes from Intel and not the game itself. Could you, if possible, share the technical explanation of why the game didn't work with Intel GPUs before the eventual fix ?

**Comment by TealDolphin** [comment] 2023-09-06 17:22
The weird part is that the game plays fine on an igpu.

It is stated by the developers of the game that this is a known issue and
that they don't plan on doing anything about it at this time.

**Comment by Vipitis** [comment] 2023-09-19 00:39
as of driver 4826 (today) the game launches without dxvk and works as expected. 

took 11 months but it's finally addressed. I would love to know if this really was as simple as adding the game to the internal whitelist...

**Comment by IGCIT** [comment] 2023-09-19 08:26
closing as fixed in driver 4826

**Closed by IGCIT** 2023-09-19 08:26 UTC
Labels: Info: Replicated, Type: Application Crash
