### ISSUE TITLE
Resident evil 8

### ISSUE THREAD

**Issue by mva94** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#50] opened 2021-05-02 11:30 UTC
#### Checklist [README]

- [x] Device is not undervolted nor overclocked.
- [x]  Device is using the [latest drivers](https://downloadcenter.intel.com/download/30381/Graphiques-Intel-Pilotes-DCH-Windows-10).
- [x] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Required]
Resident evil 8

---
#### Processor / Processor Number [Required]
I7 1165g7

---
#### GPU Driver Version [Required]
- [x] 27.20.100.9466 (*latest*)
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

---
#### Rendering API [Required]
- [ ] Vulkan
- [ ] OpenGL
- [x] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

---
#### Windows Build Number [Required]
- [x] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)

---
#### Description and steps to reproduce [Required]

1. Start the game 
2. Crash after a minute or so 
3. 

---
#### Device / Platform [Optional][Recommended]
ONE XPLAYER (prototype)

---
#### Game Settings [Optional][Recommended]

---
#### Save game (*if possible, could help solve the issue faster*) [Optional]

---

**Comment by Valkirie** [comment] 2021-05-02 11:56
Please share all game settings so that we can circle which option is causing the crash. Wasn't able to reproduce on 1035G7 with game settings set to Performance, fullscreen.

**Comment by bcysewsk** [comment] 2021-05-12 08:58
We see issue in first minutes of gameplay in random places. It's infact an OS issue and we're working over WA on our side. May it be the same what you're observing? Does crash happening always in the same place or in random moments? Do you see that after starting gameplay or either in game menu?
We would be fully sure that it's the same issue if you would be able to collect memory dump for us. Here's how to do that:
https://www.windows10forums.com/articles/how-to-enable-minidump-logs-in-windows-10.50/
We would require full dump not a small dump as it's presented. *.dmp file should show after game crash in C:\Windows\Minidump or C:\Windows\LiveKernelReports
If you would have problems with that it's fine we will be working to fully enable game

**Comment by mva94** [comment] 2021-05-12 09:02
It is never in game menu always in game .
Happens randomly after after few minutes,  sometimes 20 minutes. 
The only thing affecting this is the vram usage,  if I put all the settings to their lowest values it takes longer to crash,  as soon as you increase say a bit the textures it crashes. 
I am going to try that out today for you 
Nice to see you here!

**Comment by mva94** [comment] 2021-10-18 17:53
@bcysewsk steam version

**Comment by estebanr863** [comment] 2021-10-20 17:36
Hi all,

Just wanted to let you know that a possible fix for this issue was included in the latest driver version 30.0.100.9955 (https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html). I would appreciate if any of you guys can help us test this out. If you do, please do a clean install of the driver (https://www.intel.com/content/www/us/en/support/articles/000057389/graphics.html). This is just me been super cautious, since I have had some issues in the past when upgrading to a new driver without doing a clean install.

**Comment by PacoAvelar** [comment] 2021-10-21 21:10
I tested the demo on steam using latest 30.0.100.9955

**Comment by estebanr863** [comment] 2021-11-02 21:23
Hey @mva94, any updates?

**Comment by mva94** [comment] 2021-11-03 00:16
@estebanr863 I indeed didn't see a crash after gaming for 30 minutes , cannot talk for the Microsoft version but steam version is now fixed .

Thanks for your great work!

**Closed** 2021-11-03 00:16 UTC
Labels: Info: Needs Replication, Type: Application Crash
