### ISSUE TITLE
World of Warcraft: The War Within Visual bug

### ISSUE THREAD

**Issue by imitheo99** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#839] opened 2024-08-29 17:15 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

World of Warcraft

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [X] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i7-8700k

### Graphic Card [Required]

Arc A770

### GPU Driver Version [Required]

32.0.101.5972

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build [Required]

Windows 11 23H2

### Intel System Support Utility report

![WoWScrnShot_082924_180107](https://github.com/user-attachments/assets/a14baf57-824b-4f40-a222-113414eadecf)

### Description and steps to reproduce [Required]

Visual artifacts in the War Within underground areas when you look up

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2560x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![WoWScrnShot_082924_181245](https://github.com/user-attachments/assets/a51007c5-89a4-4efb-b57f-b096a46cd175)
![WoWScrnShot_082924_181254](https://github.com/user-attachments/assets/7206ac24-616f-42da-b668-a5917788ac0d)
![WoWScrnShot_082924_181300](https://github.com/user-attachments/assets/d3c2bbf3-bfe1-456b-baee-0f3a7f450d82)
![WoWScrnShot_082924_181303](https://github.com/user-attachments/assets/2f9ff12b-ed21-448d-b453-e3d4e100429b)

**Comment by stalker-svk** [comment] 2024-09-02 19:48
I can confirm this fog bug, happens to me as well, A770 16GB and all settings maxed, it happens since War Within prepatch in all underground areas
![WoWScrnShot_090224_214740](https://github.com/user-attachments/assets/3853e84b-2112-4bde-bdb8-fadfe980a3f5)

**Comment by Zack-Intel** [comment] 2024-09-04 22:30
Hi @imitheo99 and @stalker-svk 

Thank you for bringing this to our attention. I will begin working on reproducing and keep you posted.

In the meantime, can you clarify a couple of questions for me so I can get a better idea of the issue:

1. Does this issue only happen underground? And does it get worse/change when there are more artifacts in the frame?
2. Does reducing the graphics settings change how the issue appears, if at all?
3. Do just the visuals get affected, or is there a drop in FPS/performance as well when reproducing the issue?

**Comment by stalker-svk** [comment] 2024-09-05 21:01
it goes away when I set "Compute effects" setting to Low which disables volumetric fog and it that bug does not affect FPS

**Comment by stalker-svk** [comment] 2024-09-06 12:41
![WoWScrnShot_090624_143748](https://github.com/user-attachments/assets/4ae44178-2cda-4462-9eda-e4ae45671565)
happens also outside, not only underground. it happens wherever is the fog,

**Comment by stalker-svk** [comment] 2024-09-16 20:16
it looks fixed in latest driver

**Comment by imitheo99** [comment] 2024-09-16 20:28
I checked, looks like it got fixed!

**Closed** 2024-09-16 21:57 UTC
Labels: Info: Needs Replication, Type: Graphical Glitches
