### ISSUE TITLE
In-Game Overlay not displaying in Borderlands 3 with Intel Arc Control version 1.57.4034.4 at 25x14 fullscreen on a native 4k panel

### ISSUE THREAD

**Issue by BigNish7** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#167] opened 2022-10-28 13:24 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Borderlands 3

### Game Platform [Required]

- [ ] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [X] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 9 5950X

### Graphic Card [Required]

Intel Arc A770

### GPU Driver Version [Required]

- [X] 31.0.101.3793 (*latest*)
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1 (*October 2021 Update*)
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

[System Support Log.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/9888575/System.Support.Log.txt)

### Description and steps to reproduce [Required]

Playing Borderlands 3 in 2560 x 1440 on a native 4k panel (Asus  VG28UQL1A via DisplayPort 1.4a). Game starts and runs perfectly. While still showing opening credits, the In-Game Overlay works. However it seems that when game transitions to 2560x1440 Fullscreen mode the In-Game Overlay no longer is displayed when using the ATL-O command. 

Arc Control appears with keyboard Alt-I command at all times. When in-game and Arc Control is open, can see In-Game Overlay toggle moving from OFF to ON (and back again when repeating ALT-O commands), but Overlay not displaying - refer attached last two images. 

When ALT-Tab out of game (game still running) to desktop, In-Game Overlay appears with ALT-O command. When Game icon is clicked on taskbar and game appears, In-Game Overlay disappears.  

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

2560 x 1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![image](https://user-images.githubusercontent.com/116610885/198597479-b5d9eacc-4113-4793-968f-c3b8a21490d5.png)
![image](https://user-images.githubusercontent.com/116610885/198597630-f1f2f786-ea43-40c6-8314-5dfb54ab962a.png)
![image](https://user-images.githubusercontent.com/116610885/198597742-a868faac-14e1-4c17-92f9-656bda19e172.png)

Arc Control with In-Game Overlay OFF
![image](https://user-images.githubusercontent.com/116610885/198598870-94629791-f410-4b3f-8f5a-10c60eec7fba.png)

Arc Control with In-Game Overlay ON - no Overlay appears
![image](https://user-images.githubusercontent.com/116610885/198599257-790147b9-7ef3-4a49-85a3-56694e87a47e.png)

### Device / Platform name

Home built PC.

### Crash dumps [Required, if applicable]

N/A.

### Save game

N/A

### Game custom logs

N/A

**Comment by BigNish7** [comment] 2022-10-29 00:36
The second in-game image I attached in my original post was incorrect. I accidently repeated the first image. I apologise for any confusion. I have attached two new images below which shows what I mean. I added the red boxes to highlight the issue. 

Arc Control with In-Game Overlay OFF:
![image](https://user-images.githubusercontent.com/116610885/198753500-572f4e3c-f05e-4855-8ff7-d625e16e776d.png)


Arc Control with In-Game Overlay ON - but In-Game overlay not being displayed:
![image](https://user-images.githubusercontent.com/116610885/198753585-3e299169-3f26-4993-b724-2a5bfe816ecc.png)

**Comment by Maniir** [comment] 2022-10-30 20:43
This was happening to me when I updated from 3490 to 3793, but after I DDU'd and fresh installed 3793, it started working again.

**Comment by BigNish7** [comment] 2022-10-31 01:40
Thanks for sharing your experience @Maniir. When I originally upgraded to 3793, I simply clicked on the 3793 .exe and installed it over the top of 3490 - this may have been the cause of my issue.. 

To experiment a little, I did the following:
1. Used DDU to uninstall 3793.
2. I did a fresh install of 3793, but this did not solve the issue for me. The In-Game Overlay in Borderlands 3 still did not appear as per my original Issue.
3. I used DDU again to uninstall 3793 and did a fresh install of 3490. I can confirm that the In-Game Overlay worked perfectly as expected with 3490 in Borderlands 3. Interestingly the reason I changed to 3793 was because I had the A770 VRAM speed issue. However on reinstalling 3490, my memory speed was back up to 2186MHz - even after several reboots. Strange!
4. I then upgraded from 3490 to 3793 the approach suggested to me in another post - that is when at the Install step clicking on the 'Customize' button and then checking the 'Execute a Clean Install' box. 
5. I can now confirm that the In-Game Overlay works as expected in Borderlands 3 with the 3793 driver. 

I don't know if my issue was based on my driver installation method or perhaps an unintended mismatch between Driver and Arc Control versions or if there was something else at play given the fresh install of 3793 resulted in the same issue for me but seemed to fix it for you. However, by using the suggested upgrade method from 3490 to 3793 seems to have solve the problem for me.

I appreciate it is early days and there is a lot of experimenting and changes going on, but it would be good if Intel at some point could adopt a formal and clear Diver and/or Arc Control upgrade protocol for users to follow. AMD was always rather flaky on upgrade methodology in my opinion.   

Thank you very much for sharing your experience as it certainly helped me try something new to solve my issue.

**Comment by IntelSupport-Rozilah** [comment] 2022-10-31 13:10
hi @BigNish7,
I understand that you face some difficulties to upgrade the driver version, [here](https://www.intel.com/content/www/us/en/support/articles/000089899/graphics/intel-arc-dedicated-graphics-family.html#:~:text=Steps%20to%20Install%201%20Check%20your%20system%20meets,system%20once%20the%20driver%20installation%20is%20complete.%20) is steps that will assist you after this to upgrade Intel Arc driver and as you can see the latest driver installer offers the option to perform a clean install. After enabling this option, the installer will first uninstall the current driver and then install the new driver.
![image](https://user-images.githubusercontent.com/44628772/199014327-54962aed-8279-4daa-99e7-61533ce3bbb7.png)
Hope I answered your question and if the issue is resolved on your side, please feel free to close this case.

**Comment by BigNish7** [comment] 2022-10-31 22:35
Thanks you for the guidance @IntelSupport-Rozilah. Happy to close the case.

**Comment by BigNish7** [comment] 2022-11-08 23:37
After upgrading to Intel Arc Control version 1.57.4034.4, I noticed that the Overlay was no-longer being displayed in Borderlands 3. 

The Overlay does display correctly with the Intel Arc Control version 1.0.4765.0 that comes with the 3490 driver. 

The reason I am reopening this issue is that I not noticed that I had the older Intel Arc Control version 1.0.4765.0 with the latest 3793 driver (refer image). 

![image](https://user-images.githubusercontent.com/116610885/200698117-d1c22e3f-43dd-45e7-b8ec-340097751233.png)

After using DDU and starting the driver installation from scratch, I was able to install both 3793 and Arc Control 1.57.4034.4. It was then that I noticed that the Overlay not longer worked in Borderlands 3. 

I therefore suspect it it an issue with Intel Arc Control and not the driver.

**Comment by IntelSupport-Rozilah** [comment] 2022-11-15 08:43
hi @BigNish7,
just to inform that we start to verify the issue, stay tuned!

**Comment by BigNish7** [comment] 2022-11-16 12:16
Hi @IntelSupport-Rozilah,

I tried your suggestions 1 and 3 but they did not resolve the issue. I will have access to a different monitor over the weekend. Note I only have the A770 connected. I noticed you are launching Borderlands 3 from Steam. I am using the EPIC Games launcher - could that be a potential source of the issue?

I tried to capture my issue using the Capture feature in Arc Control Studio, but received the following error: Could not start Capture. Device operation failure. Make sure you're not connected to a VPN. Error code -17 (refer image). Can you assist me with what I might be doing incorrectly as I would like to capture in .mp4 what is happening. 

Note the Overlay only disappears when the screen resolution changes from my desktop 4K to the game at 25x14 - just after Claptrap moves across the bottom of the screen from left to right. 

![image](https://user-images.githubusercontent.com/116610885/202176673-b7963e5f-c119-4aec-96cd-a80a46f409db.png)

**Comment by IntelSupport-Rozilah** [comment] 2022-11-17 05:07
hi @BigNish7,
1. I noticed you are launching Borderlands 3 from Steam. I am using the EPIC Games launcher - could that be a potential source of the issue?--> yes i launched from Steam because we have purchased the game before but we will start purchase from Epic Game as well to verify again the issue. Stay tuned!
2. Capture feature in Arc Control Studio issue --> i have no issue to capture the game video using Arc control, i tried with and without network connection working properly for both. Could you try without VPN or network connection?.
if still not working you can use Intel® Graphics Command Center from Microsoft store to capture game video as well.
4. Lets try again install 3793 from gfx_win_101.3793.exe and hit run and do Execute a clean installation mean while check the device manager for the update.

**Comment by BigNish7** [comment] 2022-11-17 13:24
Thanks for the tips to try. I reinstalled 3793 and Executed a clean install - I got the option to Repair. I checked Device Manager and have the correct driver installed (refer image below). Just be clear, I am playing Borderlands 3 with DX12.

![image](https://user-images.githubusercontent.com/116610885/202448660-a16ef352-9561-424f-bef5-4d61bd60a577.png)

Just to note I have a stand alone PC connected to the the internet so not sure why I am getting the message about being connected to a VPN? 

As suggested, I used the Intel Graphics Command Centre to capture the video as Borderlands 3 starts and shows the point at which the Overlay stops being displayed. Note the Overlay is being displayed as expected while the game starts. I open Open Arc Control and ALT-O a coupe of times. Just at the point the game transitions to 25x14 the Overlay disappears. Note that Claptrap always stutters just over halfway across the screen (the stuttering was also present with my 6900XT) and I always get that quick glimpse of my desktop as the game changes resolutions. You will see that Arc Control stays open, but the Overlay disappears. You will also see the Overlay slider going back and fourth as I hit ALT-O a couple of times. I then close Arc Control and Alt-Tab back to the desktop to stop the recording. Interestingly the Overlay is displaying in back in the desktop.  

I trust this helps show what I am finding. If you want me to do any more specific recording, just let me know.

https://user-images.githubusercontent.com/116610885/202456828-720db7d6-a15b-4251-b5ad-4288d181eb96.mp4

**Comment by IntelSupport-Rozilah** [comment] 2022-11-18 03:22
hi @BigNish7,
1. Thanks for the recording and it is clear enough to verify the issue.
2. Just to note I have a stand alone PC connected to the the internet so not sure why I am getting the message about being connected to a VPN? --> i suspect your network may be is not open network that causing this issue, did you try without a network connection to record via arc control?.
3. Note that Claptrap always stutters just over halfway across the screen (the stuttering was also present with my 6900XT) ---> it may be caused by game issue but i will confirm it with another brand of the graphic card here once purchasing the game is done.
4. There is new beta release, could you try it [31.0.101.3802](https://www.intel.com/content/www/us/en/download/729157/intel-arc-graphics-windows-dch-driver-beta.html), let me know your finding.

**Comment by BigNish7** [comment] 2022-11-18 05:54
Hi @IntelSupport-Rozilah. I am very happy to report the upgrade to 3802 and its newer version of Arc Control has fixed the issue with the Overlay in my Borderlands 3. Congratulations to the Intel Dev team! Please refer attached image. 

![image](https://user-images.githubusercontent.com/116610885/202629176-b404d148-e476-487f-9708-6ad84904cb2b.png)

I am also happy to confirm that Intel Arc Control now appears as a program in Add/Remove programs. I had noticed that earlier versions were not listed.
 
![image](https://user-images.githubusercontent.com/116610885/202629795-ba433de4-97f1-4ab0-8213-c00e926c1f87.png)

I know you must be getting lots and lots of requests now that the cards are out in the wild, but I wanted to take the time to thank you for working with me to address my specific issues. I really welcomed the chance to purchase an Intel discrete GPU and be part of the extended team working through the issues always with a positive mindset of incrementally improving an already solid product. 

I will keep playing with the Capture feature with your suggested approach. Given 3802 has fixed my issue, I am happy to close this issue.

**Comment by IntelSupport-Rozilah** [comment] 2022-11-18 06:16
hi @BigNish7, 
happy to hear that solved the issue and happy as well to work with you. You may submit a new GitHub case if you have new questions and we are happy to assist you. so as a conclusion the issue was fixed on 3802 version.
@IGCIT please close the case as the customer agreed to close the case.

**Closed** 2022-11-18 07:18 UTC
Labels: Info: Needs Replication, Type: Arc Control
