### ISSUE TITLE
Arc Control opens during a Remote Desktop session

### ISSUE THREAD

**Issue by Feri-6** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#718] opened 2024-02-23 00:06 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Windows 10 Remote Desktop

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [X] Other (please specify)

### Other game platform

Windows 10

### Processor / Processor Number [Required]

11th Gen Intel(R) Core(TM) i7-11370H

### Graphic Card [Required]

 Intel® Iris® Xe Graphics

### GPU Driver Version [Required]

31.0.101.5330

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

-

### Description and steps to reproduce [Required]

I use the built in Windows Remote desktop connection to log into a PC. Every time I log in or log out through RDC, Intel Arc Control opens.
Is there a way to prevent this?

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

-

### Device / Platform name

-

### Crash dumps [Required, if applicable]

-

### Save game

-

**Comment by IGCIT** [comment] 2024-02-23 08:53
hi @Feri-6,

at the moment this is intended behavior, a fix is planned tho, see #621

closing as duplicate of #621

**Closed by IGCIT** 2024-02-23 08:53 UTC
Labels: Info: Needs Replication, Type: Arc Control

**Comment by AndyPullis** [comment] 2024-02-28 14:29
I am also having this issue and its annoying. Please fix.
