### ISSUE TITLE
Chromium Application Hang on System resume

### ISSUE THREAD

**Issue by kphillisjr** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#310] opened 2023-05-11 20:36 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Chromium (Steam or Discord)

### Processor / Processor Number [Required]

AMD Ryzen 7 5700G with Radeon Graphics         

### Graphic Card [Required]

Acer PREDATOR BIFROST Intel® Arc™ A770 OC  APBF-IA770-16G-OC | DP.BKCWW.P02

### GPU Driver Version [Required]

- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [X] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Other Windows build number

22621 (22H2)

### Intel System Support Utility report

[Intel_System_Support_Utility.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11455966/Intel_System_Support_Utility.zip)

### Description and steps to reproduce [Required]

The basic steps are as follows...

1. Login to system
2. Start Firefox, Steam, and Discord.
3. open firefox window, and play a few videos.
4. pause a video on firefox.
5. browse the steam store. The videos should autoplay
6. go to steam library
7. play a few games (I forgot which one)
8. exit the games.
9. open discord
10. play an embedded youtube video in discord
11. pause embedded youtube video
12. change channels to another discord chat
13. let computer go to sleep
14. wake computer up about 45 minutes later
15. This may take a few tries. I tend to leave my pc on overnight, and it goes to sleep. I do know that i sometimes will have a video paused on firefox when the system goes into suspend mode.

### Device / Platform

Windows 11

### Crash dumps [Required, if applicable]

[minidump-050923-7640-01.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11456059/minidump-050923-7640-01.zip)
[minidump-051123-13687-01.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11456060/minidump-051123-13687-01.zip)

### Application / Windows logs

[Windows_SystemEvents.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11456094/Windows_SystemEvents.zip)

**Comment by Karen-Intel** [comment] 2023-05-11 21:54
Hey @kphillisjr thank you for sharing the very detailed repro steps. We will try with some of the games we have and get back to you in case we have questions

Talk to you soon

Karen

**Comment by Karen-Intel** [comment] 2023-05-17 15:46
Hey @kphillisjr I have some updates for you

We have a new driver release[ v.4639](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html).
I have done some tests (leaving my PC in idle for periods of 45 minutes > 1 hour and a half > 13 hours) and it has resumed from sleep without any issues, using this driver version. I have done pretty much the same you have, I was playing COD Black Ops Cold War on Steam + Twitch + Discord and it my system resumed without any issues.

Could you please give it a go?
We also recommend to use the latest [DDU](https://www.guru3d.com/files-details/display-driver-uninstaller-download.html) version for the upgrade

Keep me posted!

Karen

**Comment by Karen-Intel** [comment] 2023-08-03 17:25
Hi @kphillisjr could you please let me know if this behavior is still reproducible with driver v.4577?

TY

Karen

**Comment by kphillisjr** [comment] 2023-08-28 10:10
I have a few updates with the v4644 driver.

- The application hang on System resume has mostly stopped. I still occasionally get a system hang on resume, but the more annoying behavior is the full screen flicker.
- The primary monitor on the system will flicker if I forget that I am watching videos on Firefox and the system goes into suspend mode.
- My Monitor I am using that has repeated flickers is the Asus TUF Gaming VG289Q1A ( https://www.asus.com/displays-desktops/monitors/tuf-gaming/tuf-gaming-vg289q1a/ ) that is connected to the displayport on the Arc Video card. The flicker will end if I slow power cycle the monitor a few times. The issue does not happen when I reboot the system though.
- The most recent monitor flickering occurred with the following programs open:
  - Chromium (Steam) - on store main page.
  - Chromium (Epic Games Store) - On store main page.
  - Firefox (Playing a twitch video)
  - Intel Arc Control.
- The result of this Power resume is as follows...
  - System wide - After logging back in the system screen starts flickering until it settles in an off position. I can get video back by slow power cycling the monitor a few times or restarting the computer, but either way this is not expected behavior.
  - Intel Arc Control - This stopped working and I had to forcibly close the program and it's assistant software with the task manager.
  - Firefox - Resumed as intended, but not exactly usable since the screen is flickering.
  - Chromium (Steam) - Works without any issues I can detect.
  - Chromium (Epic Games Store) - NAlso works as intended.

**Comment by Karen-Intel** [comment] 2023-10-17 15:45
Hey @kphillisjr this issue has not been updated for a while and no constant reproduction on our end lately due to the sleeping states updates in our driver that were implemented a few versions back. 
Could you let us know if this behavior is still reproducible with driver v.4887?

TY

Karen

**Comment by Karen-Intel** [comment] 2023-10-24 17:19
Hey @IGCIT can you help us close this one? Last communication attempt was last week, no recent reply from customer. Thanks

Karen

**Closed** 2023-10-24 18:09 UTC
Labels: Info: Needs Replication, Type: Application Crash
