### ISSUE TITLE
Intel Arc GPU Driver Inoperative without Resizable BAR (RE-BAR) Support

### ISSUE THREAD

**Issue by AuracleTech** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#315] opened 2023-05-16 01:38 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [x] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows 10 / Windows 11

### Processor / Processor Number [Required]

AMD Ryzen 7 2700 Eight-Core Processor, 3200 Mhz, 8 Core(s), 16 Logical Processor(s)

### Graphic Card [Required]

Intel Arc A770 Limited Edition 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

Non accessible

### Description and steps to reproduce [Required]

The GPU driver is inoperative if the system does not support Resizable BAR.
This means that without RE-BAR support, the operating system is inoperative.
It is said that [RE-BAR is not required](https://www.intel.ca/content/www/ca/en/support/articles/000092416/graphics.html) which is why I bought the Arc A770, yet now I face multiple issues as I cannot update my drivers or my computer is unusable.
- Install latest drivers with PC that doesn't support RE-BAR.
- Reboot
- PC Freezes

### Device / Platform

Windows 10

### Crash dumps [Required, if applicable]

Non accessible

### Application / Windows logs

Non accessible

**Comment by Vipitis** [comment] 2023-05-16 01:45
Same experience with i5 6600K and A750 LE: both drivers 4311 and 4314 froze the OS after like 10 seconds. Mouse will still move and you can still click buttons and use shortcuts (Ctrl+alt+del) but image will only update after you unplug your monitor and plug it back in. 

Current solution: reboot into safemode DDU, install 4146 via the .zip (delete IDSA installer for good measure).

**Comment by DoragonHunter** [comment] 2023-05-16 02:50
Please ensure your system meets the MINIMUM SYSTEM REQUIREMENTS before even using Intel Arc. Many of you are using an unsupported CPU and Mobo/Platform configuration as stated on the box and Intel:

https://www.intel.com/content/www/us/en/support/articles/000091128/graphics.html

**Comment by AuracleTech** [comment] 2023-05-16 03:01
> Please ensure your system meets the MINIMUM SYSTEM REQUIREMENTS before even using Intel Arc. Many of you are using an unsupported CPU and Mobo/Platform configuration as stated on the box and Intel:

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/40531871/4dda8be5-f6db-4990-8892-4fa81c542e22)
https://www.intel.ca/content/www/ca/en/support/articles/000092416/graphics.html

Thank you

**Comment by Arturo-Intel** [comment] 2023-05-16 14:42
Hi @AuracleTech
did you use the [DDU ](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html) tool to do a clean up before installing the drivers? Also this issue happens on any drivers version? or only in the 4335?
Please share with me the discord group where this is being discussed

We have an AMD system in the lab, let me do some experiments disabling the reBar

--r2

**Comment by Arturo-Intel** [comment] 2023-05-16 14:44
@Vipitis Using the DDU + removing the IDSA helps you with the problem?
Do you see this issue in the 4335?

--r2

**Comment by Vipitis** [comment] 2023-05-16 15:22
@Arturo-Intel I got the newest version of DDU via the Intel support page link, removed my current drivers, then donwloaded the 4335 driver (only available via .exe) and installed that. I uncheck IDSA in the installer (and also arc control since you can't just install arc control), additionally I check "fresh installation". 

And during the final stages of the installer. The system suffer the symptoms. Mouse would still move, but nothing else would react. Unplugging the monitor and plugging it back in did show me an updated view. 

But I made a new discovery. I also have a 2nd screen plugged in via HDMI. so I unplug the 2nd screen and rebooted. With just a single screen connected (via Display Port). The issue didn't happen (at least in the minute or so I waited). But it did happen as soon as I plugged in that secondary monitor again (via HDMI). 

So I would like to offer this additional observation as a potential vector and will ask all other known cases if they use multiple screens. 


The discord where this is getting discussed on is the Intel insiders discord, which gets advertised on the Intel Arc website and within arc control. I can send you a list of 5 support threads of this exact issue. 

Will do some more testing with just a single monitor plugged in. Hope this helps. I never tried drivers 4255 or 4257.

**Comment by AuracleTech** [comment] 2023-05-16 17:13
> @Arturo-Intel For me I only simply installed the latest drivers without uninstalling as they are supposed to work side by side anyway from what people told me on intel community discord.

The installation got the screen entirely black so I waited 30 minutes to make sure it finished before restarted my PC, and from there as soon as the computer booted the screen was entirely frozen. I have like ~2 seconds working to type my password, after those ~2 seconds everything freezes and nothing respond (not even my cursor for me).

So I uninstalled the latest drivers using safe mode and then re-installed `31.0.101.4146` and now it's "working" but now I am facing lots of new issues due to the fact my drivers aren't updated.

I only tested the latest and `31.0.101.4146` but from what I heard the latest and second-latest are the ones causing issues.

**Comment by J0dla** [comment] 2023-05-17 16:59
@AuracleTech Hey, are you sure your system doesnt support rebar ?
AMD Smart Access Memory (ak. ReBar) was released for 400 chipsets like 3 years ago.
Example for gigabyte how to turn it on:
BIOS -> Advanced settings -> BIOS Tab -> CSM (disabled)
BIOS -> Advanced settings -> Peripherals Tab -> Above 4G Decoding (enable it) and Re-Size BAR support (auto)
If not there they could be in diffrent places it can vary from bios.
For example in ASUS you just click icon in main BIOS menu and switch from OFF->ON and thats it
Example how to check is it on:
Go to device manager -> graphics card -> resource tab -> look for "Large memory range" that means its on

**Comment by Vipitis** [comment] 2023-05-18 16:14
I DDU'd once more and tried the newly released 4369 WHQL driver. And got exactly the same experience as with all previous 43 week drivers. Meaning WHQL certification was granted for this twice now. 
Last time single monitor only let me kind use the OS (but it messed up as soon as I tried a game or similar). This time it was broken as ever with a single monitor connected.

Sadly the release notes for the drivers don't mention any kind of changes which could cause this - is there a better changelog to look at than the "highlights" linked on the download site?

**Comment by Vipitis** [comment] 2023-05-19 07:24
@feamsr00 
> As of now, I have only the "Microsoft Basic Display Adapter" until Intel figure's this out.
> 
> :(

You can install the 4146 driver which doesn't seem to have this issue and it's still working great. You will only be missing any improvements they made since. 

https://www.intel.com/content/www/us/en/download/726609/772016/intel-arc-iris-xe-graphics-whql-windows.html

**Comment by AuracleTech** [comment] 2023-05-20 18:53
https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/40531871/bb991c25-412f-470c-ac9f-f073c270f7f1

**Comment by Arturo-Intel** [comment] 2023-05-22 16:32
Thanks @AuracleTech for the vid, this will help us to push harder the bug to the corresponding team

**Comment by Arturo-Intel** [comment] 2023-05-23 15:51
Hi everyone,

Can you share me the OS version you are seeing the issue.
So far it looks only happens in win 10 right? (@AuracleTech)

Also, it looks none of you have an integrated GPU in your systems. Please confirm if this is correct :)

I will continue with my experiments.
So far I can not reproduce it in a win11 system with or without iGPU

--r2

**Comment by Vipitis** [comment] 2023-05-23 16:42
Hey, I am on Windows 10, 21H2 I believe (will correct if untrue). My CPU is a i5 6600K and it does have an iGPU. However it doesn't show up in my task manager as a GPU anymore (it used to a while ago). In my (MSI Z170I) bios, I have "initiate graphics adapter" set to PEG, both my monitors are connected to the A750. 
I haven't heard about anyone that has a rebar capable system, but experienced this when turning rebar off in bios, but also haven't heard about anyone testing it. 

I will test if my iGPU can still be addressed in windows or output a video signal (in bios, in safemode, with driver 4146, with driver 4369) in a day or two. And then update with my findings.

**Comment by Arturo-Intel** [comment] 2023-05-23 16:55
> ...both my monitors are connected to the A750.

I didnt tested with multimonitors, maybe that is the trigger

**Comment by AuracleTech** [comment] 2023-05-23 18:18
Here's my tested Windows versions :

- Windows 10 Home ( with previous nvidia drivers ) : **Inoperative**
- Windows 10 Pro ( clean install ) : **Inoperative**
- Windows 11 Pro ( clean install ) : **Inoperative**

**Comment by Arturo-Intel** [comment] 2023-05-23 18:38
Update:
Was able to reproduce this issue with Windows 10 Pro and 101.4369 using HDMI, single monitor, no ReBar, no iGPU

I also tried the same configuration as above but with Display Port; this time I could not reproduce the issue, 
can you guys try with a Display port in your end?

Meanwhile I will share this data to the driver's team.

Thank you for your patience
-- r2

**Comment by AuracleTech** [comment] 2023-05-23 19:00
I have 2 monitors
- Hdmi
- DisplayPort ( main )

I unplugged HDMI from GPU
Updated drivers
Computer froze as soon as drivers installed

![PXL_20230523_185026441~2](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/40531871/c63c8481-44e9-4bfd-acd6-0a561bf7a222)

same thing when reboot, frozen ( Discord didn't even had time to load )

![PXL_20230523_185321868~2](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/40531871/46f2f3e0-bf3a-43d1-a5d7-3e1f5c4bbfb6)

here we go again

**Comment by Arturo-Intel** [comment] 2023-05-23 19:35
>"... works as long as you do not open anything heavy"
Good tip, I was able to reproduce with Display port too, but only in Win10

@AuracleTech can you share me your [SSU log](https://www.intel.com/content/www/us/en/download/18377/intel-system-support-utility-for-windows.html)

**Comment by AuracleTech** [comment] 2023-05-23 19:42
Hopefully "perform a clean install" when you install arc drivers doesn't clean any important log
[ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11547852/ssu.txt)

**Comment by LadyMikea** [comment] 2023-05-23 20:57
Windows 10 Home, single HDMI, drivers 4314+. No rebar enabled, "freeze", rebar enabled but without "Above 4G Decoding" (bios lack this option), "freeze". Mouse cursor move freely and I can "unfreeze" a screen for a few seconds by turning on/off monitor. Just bizarre, all the 4314+ drivers are WHQL ones... 

 
![a](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/134446597/82207244-46d4-4053-91b7-e66077ba61fa)

**Comment by Vipitis** [comment] 2023-05-23 22:02
@LadyMikea if you can enable ReBAR in bios you should also have Above 4G decoding. It might be under a different name. Have you googled around or can share what board you have? On my board the option was called "crypto currency mode" for example.

**Comment by AuracleTech** [comment] 2023-05-26 14:26
From Intel
> Based on our research performed this issue that you are expecting is already under investigation under bug #18029726035

from researching I see this issue is mentioned [here](https://community.intel.com/t5/Intel-ARC-Graphics/Driver-31-0-101-4314/td-p/1483059)

**Comment by Arturo-Intel** [comment] 2023-06-01 13:35
@AuracleTech 
Can you please try with the [101.4382](https://www.intel.com/content/www/us/en/download/729157/intel-arc-iris-xe-graphics-beta-windows.html?) driver version?

From my end I cant reproduce the issue

--r2

**Comment by Arturo-Intel** [comment] 2023-06-01 15:03
@IGCIT can we close this issue

**Comment by Vipitis** [comment] 2023-06-01 22:07
Hey, I still have my A750 and installed this new driver. I also installed it directly on top. Without DDU first or checking the "fresh installation"  checkbox. 

It doesn't seem to freeze my monitor/OS anymore. So unless this happens in games, I assume it's actually closed.

**Comment by Arturo-Intel** [comment] 2023-06-01 22:13
@Vipitis Thank you for the confirmation, It would be very helpful if you run some games on it. I'm not sure if the performance will be good w/o the ResBar.
--r2

**Comment by Arturo-Intel** [comment] 2023-06-02 00:13
@feamsr00 Sounds fair, please use the latest beta driver and share what you found, Thank you for your time. 
@IGCIT can we open this case?

**Comment by Arturo-Intel** [comment] 2023-06-15 15:29
@aolszowka If I understand correctly in 101.4382 is no longer the issue right?

**Comment by aolszowka** [comment] 2023-06-15 15:34
@Arturo-Intel That is correct; the Beta Drivers (101.4382) do not appear to exhibit the same issues/problems that the "stable" driver does. I intend to get running on that driver in production sometime next week and I'll really be able to put it through its paces then.

**Comment by Vipitis** [comment] 2023-06-21 22:09
with .4502 there now is a WHQL release where this issue seems to be gone. (I did not try .4499)

**Comment by Karen-Intel** [comment] 2023-08-10 18:01
@IGCIT can you help us close this one? It has been fixed since v.4502 and no updates since. Thanks

Karen

**Closed** 2023-08-10 19:51 UTC
Labels: Info: Needs Replication, Type: Support
