### ISSUE TITLE
Grand Theft Auto V does not launch/crashes on launch via the RageMP 3rd party launcher

### ISSUE THREAD

**Issue by NoxNostraEst** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#156] opened 2022-09-06 09:01 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Grand Theft Auto V, ran via the RageMP Launcher

### Game Platform [Required]

- [X] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [X] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   

### GPU Driver Version [Required]

- [X] 31.0.101.3413 / 31.0.101.2111 (*latest*)
- [ ] 31.0.101.3222 / 31.0.101.2111
- [ ] 30.0.101.3113
- [ ] 30.0.101.3109
- [ ] 30.0.101.1994
- [X] 30.0.101.1960
- [ ] 30.0.101.1934
- [ ] 30.0.101.1660
- [ ] 30.0.101.1631
- [ ] 30.0.101.1404
- [ ] 30.0.101.1340
- [ ] 30.0.101.1191
- [ ] 30.0.101.1121
- [ ] 30.0.101.1069
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11
- [X] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

-

### Description and steps to reproduce [Required]

1. Download GTA V via Steam or Epic Games.
2. Download and install the RageMP third-party game launcher (https://rage.mp/)
3. Run the RageMP launcher via updater.exe
4. Join any server (it might take some time for everything to load - especially since the first time it has to download server-side GTA mods). Wait until EAC starts running. Eventually, EAC will show "Waiting for game" and everything will start to shut down one by one.

Note: The game launches normally once the Iris Xe drivers are disabled and the Microsoft basic display adapter is used. 

Video posted by another user: https://youtu.be/BJxTM4qkVmo

### Game graphic quality [Required]

- [ ] Low
- [X] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

In-game medium settings preset. 

Note: The base game launches normally, regardless of the settings. However, it does not launch via the launcher at all.

### Device / Platform name

-

### Crash dumps [Required]

Error when attempted to generate.

### Save game

N/A. Multiplayer only launcher. 

### Game custom logs

-

**Comment by IntelSupport-Arun** [comment] 2022-09-07 05:13
Hi  @NoxNostraEst ,
Thank you for contacting us. I have the following questions to you for further investigation:
1. Since the game normally launches by itself and the issue only occurs with the Rage MP, did you contact the RAGE Multiplayer's support/developer?

2.  I can see similar questions have been asked in the Rage MP discussion forums. I found a few solutions and do let me know if you already tried else please give a try and let me know the observation:
- [Solution1](https://forum.gta.world/en/topic/55554-fixguide-rage-mp-crashing-at-loading-server-resources/)
- [Solution 2](https://rage.mp/forums/topic/9428-how-to-solve-common-problems-using-ragemp-11/)
- [Solution 3](https://rage.mp/forums/topic/8352-rage-doesnt-launch-gta-5-after-chosing-server/)

**Comment by NoxNostraEst** [comment] 2022-09-07 09:37
Hello! 

1. The RageMP developers were indeed notified of this issue and as far as I have been told by other people with the same issue, they were clueless on why this is happening. A modder who is more experienced than me and develops an optimization for RageMP looked into the Iris Xe issue more in-depth and could not find a fix either [Old message screenshot](https://i.gyazo.com/1512b41001146bb5bddcd829b898b15e.png). More recently, when another guy asked about the Iris Xe issues on discord, he mentioned that RageMP "doesn't support Iris Xe drivers", but of course, there's no 100% confirmation on this fact. RageMP updates are pretty rare since it's merely the platform that supports the multitude of community-created servers and since they currently did not manage to fix it, you are our only hope.

2. I believe I have gone over the vast majority of possible fixes listed there, plus more from other sources, but to no avail. I have also installed the above-mentioned patch, which is completely optional but a life-saver performance-wise for a lot of people (non-Iris Xe users - the patch does not do anything for us), but it didn't help. I will still attempt to look over fixes and keep you up to date, however, I wish to mention that the game starts perfectly once the Iris Xe drivers are disabled. I know other Iris Xe users that attempted a plethora of methods to fix their game with no success. Some of them, including myself, got the game running after disabling the drivers and using the Microsoft basic display adapter. Of course, at that stage, the game is unplayable due to excessive lag. I have attempted to re-enable the driver once the game loaded in, but it would turn into a black screen.

As I have said, your help would be our only grain of hope at the moment since this launcher is basically also the platform for hundreds of populated servers that we cannot join in any other way. If need be, for contacting the devs, I believe their [Discord](https://discord.gg/tChBaeu) is the most efficient method. We would highly, HIGHLY, appreciate any small bit of help!! And thank you for your reply!

**Comment by IntelSupport-Arun** [comment] 2022-09-08 11:33
Hi @NoxNostraEst 
Thanks for the comments. 
Are you facing any issues while launching the game offline(With Intel Iris Graphics)? Please double confirm.
Meanwhile, I will verify the issue on our side and let you know the observations.

**Comment by asad-khak** [comment] 2022-09-13 14:33
@IntelSupport-Arun hello, i'm facing the exact same problem.  I also have intel xe.

**Comment by NoxNostraEst** [comment] 2022-09-15 19:05
@IntelSupport-Arun Small update from devs: they also suggested to contact you. (reference: https://rage.mp/forums/topic/11415-to-the-devs-rage-mp-not-working-with-intel-iris-gpu/?do=findComment&comment=37888)

**Comment by asad-khak** [comment] 2022-09-16 09:26
https://rage.mp/forums/topic/11415-to-the-devs-rage-mp-not-working-with-intel-iris-gpu/#comment-37888 
the developers said to contact you

**Comment by IntelSupport-Arun** [comment] 2022-09-20 06:23
HI @NoxNostraEst , Thank you for the updates.
The issue has been verified on our side, and we are able to reproduce it. We will be working on a fix. I want to give you a heads up that the fix may take 3 to 6 months to be included. Please stay tuned for our next update.

**Comment by IntelSupport-Arun** [comment] 2022-12-16 06:15
hI @NoxNostraEst , The latest graphics drivers [31.0.101.3959](https://www.intel.com/content/www/us/en/download/729157/761751/intel-arc-graphics-windows-dch-driver-beta.html) and [31.0.101.3975](https://www.intel.com/content/www/us/en/download/729157/761751/intel-arc-graphics-windows-dch-driver-beta.html) have the fix for this issue. Please try from your side and let me know the observations. If issue is fixed with the latest driver please close this case. Thank you.

**Comment by NoxNostraEst** [comment] 2022-12-16 20:15
Hello! I've tested 3959 and it works so I assume 3975 should also work!! I cannot express our gratitude on behalf of all the Iris Xe users! Thank you very much! This was a great interaction, so keep up the good work! Closed!

**Closed** 2022-12-16 20:17 UTC
Labels: Info: Replicated, Type: Application Crash
