### ISSUE TITLE
Provide rotation shortcut key support for IGS

### ISSUE THREAD

**Issue by plainround** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#882] opened 2024-12-14 06:48 UTC
### Application [Required]

Intel Graphics Software

### Processor / Processor Number [Required]

14600k

### Graphic Card [Required]

A750

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build [Required]

Windows 11 24H2

### Describe the feature [Required]

Provide rotation shortcut key support for IGS, so I no longer need to download IGCC Beta. For example: Ctrl + Alt + ←: Rotate the screen to the left (90 degrees).

**Comment by Gabriela-Intel** [comment] 2024-12-17 17:07
Hi @plainround  Thanks for taking the time to provide feedback. :) I went ahead and filed a request with these details for the team to review and will be internally tracking this. I'm closing this one out with my comment since this is not a bug, but a feature request.

**Closed by Gabriela-Intel** 2024-12-17 17:07 UTC
Labels: Type: Feature Request
