### ISSUE TITLE
Halo : Infinite flickering texture issues

### ISSUE THREAD

**Issue by mva94** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#99] opened 2021-11-17 09:17 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Halo infinite 

### Game Platform [Required]

- [ ] Steam
- [ ] Origin
- [X] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Other game platform

Game pass 

### Processor / Processor Number [Required]

I7 1195g7

### GPU Driver Version [Required]

- [ ] 30.0.101.1121 (*latest*)
- [X] 30.0.101.1069
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Description and steps to reproduce [Required]

Just start the game as the issue already happens in the menu 
Check out this video: https://youtu.be/qPwph5LQlV0

### Device / Platform

One x player

### Game Settings

- 800p dynamic resolution 
- low preset

**Comment by KaeAlSa** [comment] 2021-11-17 11:41
I have the same problem. Same device. But I've also tried on the 1121 beta driver and my game is from Steam.

**Comment by estebanr863** [comment] 2021-11-23 17:04
Hi @mva and @KaeAlSa, can you guys please run this app and attach the resulting file? https://www.intel.com/content/www/us/en/support/articles/000057926/network-and-io.html

**Comment by KaeAlSa** [comment] 2021-11-23 17:53
[Intel log.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/7590137/Intel.log.txt)

**Comment by EvilMath** [comment] 2021-12-13 21:08
[output.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/7706984/output.txt)

**Comment by estebanr863** [comment] 2022-03-09 20:17
@mva94, @KaeAlSa and @EvilMath 

We were able to reproduce this issue and found that its root cause to be on the game side. We have already escalated this issue to the game developer, but now is up to them to fix the issue.

**Comment by estebanr863** [comment] 2022-03-28 17:52
Hi @mva94, @KaeAlSa and @EvilMath

Can you update your graphics driver to the [latest version](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html) 30.0.101.1631 and test if the issue is still present?

**Comment by jfavelar** [comment] 2022-03-28 18:14
There are still some issues (this video says it is using march 23 driver -> 1631) 
I will test later this weekend to make sure it is accurate


https://www.youtube.com/watch?v=-FMO9-Lz2dU

**Comment by pacoa-kdbg** [comment] 2022-03-28 18:17
Looks like there are still some issues,

https://www.youtube.com/watch?v=-FMO9-Lz2dU

**Comment by estebanr863** [comment] 2022-03-28 19:25
Thanks for helping test it! We'll keep looking into the issue.

**Comment by IGCIT** [comment] 2022-05-04 12:17
reported to be fully working now, can you please confirm so we can close this?

**Comment by mva94** [comment] 2022-05-04 12:42
@IGCIT game isn't solved https://youtu.be/XuppKHUaBWw

**Comment by estebanr863** [comment] 2022-09-07 16:03
Hi all,

The latest version of driver ([31.0.101.3413](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html)) includes a fix for the flickering textures. Please give a try and let me know if it works for you.

**Comment by pacoa-kdbg** [comment] 2022-09-07 17:56
Hi all, 
I can confirm that latest driver solves this issue, can be closed now .

**Closed** 2022-09-07 18:28 UTC
Labels: Info: Needs Replication, Type: Bad Performance, Type: Graphical Glitches, Top 5
