### ISSUE TITLE
Dolby Atmos via HDMI passthrough stops working

### ISSUE THREAD

**Issue by ksof1** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#475] opened 2023-09-06 13:52 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Dolby Access

### Processor / Processor Number [Required]

Intel Core i9-12900K

### Graphic Card [Required]

Inter Arc A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[atmos.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12538029/atmos.txt)

### Description and steps to reproduce [Required]

My setup is as follows: LG C9 OLED connected to A770 via HDMI 2.1 Cable, LG C9 OLED connected to Dolby Atmos soundbar. TV supports Atmos and DTS lossless passthrough no problem.

Issue: when TV restarts/reengages display mode, sound output stops working regardless of whether Atmos output device was TV (directly) or the soundbar (earc passthrough). Windows shows that LG TV works as sound output device, the music and sounds appear to be playing but no actual output is happening. Restart fixes the issue. Sometimes turning off atmos in windows and turning it on again helps, but not 100% of the time. With HDR enabled (which uses different pipeline for Atmos) the situation is even worse and resurrecting the sound could take over several PC reboots, reengaging HDR and turning the TV on and off again. 

The situation is very annoying because of how slow my TV switches display modes. Say, starting a game automatically engages Low Latency mode which tv may take a few seconds to engage and during that time driver first thinks the TV was turned off, so it refreshes the windows screen output, then sees the TV is back on again and it refreshes the screens output again during which the sound just disappears. 

Aforementioned issue did never occur on Radeon RX 6800XT GPU, nor did it occur on Nvidia RTX 3070 Super Laptop, so its definitely up to INTEL HDMI drivers. Also, the TV was way quicker at switching to and out of ALLM/HDR mode on non-intel GPUs. 

### Device / Platform

Windows 11 22h2

**Comment by ksof1** [comment] 2023-09-08 07:53
Turn display off also triggers this issue. Just went out for 10 minutes after having a session playing with Atmos sound, it was working fine. The display turned off as per windows power saving functional, I came back, woke it up - no sound output. Needed to reboot the PC for it to come back.

**Comment by Gabriela-Intel** [comment] 2024-01-19 16:39
Hi @ksof1! I gave this a shot using a similar configuration (details below) but I wasn't able to see the issue using the steps provided above. Have you had the chance to test again to see if you're still seeing this issue reported back in September?

i5-12600K + A770
Samsung Q900C Soundbar connected via HDMI eARC (supports Dolby Atmos)
Samsung TU7000 (with HDMI ARC)
Driver 101.5085
Confirmed Dolby Atmos is enabled in-game using Windows Settings & Dolby Access (also confirmed using soundbar remote)

Let me know, thanks!

**Comment by ksof1** [comment] 2024-01-25 10:44
> Hi @ksof1! I gave this a shot using a similar configuration (details below) but I wasn't able to see the issue using the steps provided above. Have you had the chance to test again to see if you're still seeing this issue reported back in September?
> 
> i5-12600K + A770 Samsung Q900C Soundbar connected via HDMI eARC (supports Dolby Atmos) Samsung TU7000 (with HDMI ARC) Driver 101.5085 Confirmed Dolby Atmos is enabled in-game using Windows Settings & Dolby Access (also confirmed using soundbar remote)
> 
> Let me know, thanks!

Issue still present. Turning the TV off, then on again, sound stops passing through and despite windows showing the sound device working correctly, on actual sound is being output. As before, reboot fixes it. 

Arc Driver 5084, fresh Windows 23h2 install

To replicate the issue I:
I turned the TV on
Enabled HDR on the TV display via windows
Switched default sound output to LG TV 
(TV's sound settings is set to "Passthrough via eARC")
Enabled Atmos in a drop down menu in Windows (Atmos only works when Atmos device is set as default output) 
Sound works as intended
Turned the TV off
Turned the TV on
No sound coming out
Reboot fixes the issue

**Comment by Gabriela-Intel** [comment] 2024-01-31 17:48
@ksof1 I tried to replicate the issue again using the new set of steps provided but I couldn't observe any type of audio loss/drops using the same config I mentioned before. By chance do you have another display supporting HDMI ARC that you could test this out on?

**Comment by ksof1** [comment] 2024-02-01 11:30
No, but there are people with similar issue as me.

https://community.intel.com/t5/Graphics/Intel-A770-16GB-audio-issue-when-Dolby-Atmos-via-Dolby-Access/td-p/1444463

https://community.intel.com/t5/Graphics/Arc-A770-16GB-Dolby-Atmos-issues/td-p/1529022

**Comment by Gabriela-Intel** [comment] 2024-03-15 20:42
Hey again @ksof1. I've tried replicating the issue on and off for the past couple of weeks with no success. Did you already try using another HDMI cable? Also we have new graphics drivers available in the [Download Center](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html?) since you last commented. Have you tried updating to the latest?

**Comment by Gabriela-Intel** [comment] 2024-03-22 21:56
Unfortunately I'm going to close this since I haven't been able reproduce over the past couple of months and I don't see any updates on this issue

@IGCIT

**Comment by Gabriela-Intel** [comment] 2024-03-22 21:58
By the way, it may be worth reporting this directly to Dolby so they can escalate directly to Intel if they can confirm it's an issue with Arc.

**Closed** 2024-03-23 08:31 UTC
Labels: Info: Needs Replication, Type: Support
