### ISSUE TITLE
Rage 2 Red flashing screen broken in drivers .1190 and .1340

### ISSUE THREAD

**Issue by nielo360** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#114] opened 2022-02-28 09:21 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

RAGE 2

### Game Platform [Required]

- [ ] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [X] Epic Games
- [ ] Bethesda.net
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

intel i7 1195g7

### GPU Driver Version [Required]

- [X] 30.0.101.1340 (*latest*)
- [X] 30.0.101.1191
- [ ] 30.0.101.1121
- [ ] 30.0.101.1069
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/8152034/ssu.txt)

### Description and steps to reproduce [Required]

RAGE 2 is broken with red screen flashing everywhere on both latest and previous drivers, The only drivers that work fine are from 2020  starting with 27.

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1280x800

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Its tried on all preset settings,

### Device / Platform name

Onexplayer mini 

### Crash dumps [Required]

There is no crash.

**Comment by Saracchini** [comment] 2022-02-28 10:11
Running Steam version at 1121 with game default settings, and in this driver version the game does seems to run without visual glitches or performance issues. Seems to be a regression issue.

**Comment by nielo360** [comment] 2022-02-28 11:56
I tried several drivers from the 37.  series none worked all showed red screen glicthes on rage 2 only the 27. series of drivers worked perfectly.

**Comment by nielo360** [comment] 2022-02-28 23:43
The only driver that works is 27.20.100.8729  this driver is not available on intels download page its NUC driver that comes from windows update all others fail. This the driver that windows 11 keeps auto downgrading to despite updating drivers. Please look into this issue and resolve.

**Comment by nielo360** [comment] 2022-03-04 06:40
Is there anyone looking into this issue?

**Comment by nielo360** [comment] 2022-03-06 04:04
27.20.100.8729 this is also the only driver that runs ELEX 2 . same bug as RAGE 2 is fixed with this old driver please look at this thread

**Comment by nielo360** [comment] 2022-03-19 15:54
any progress

**Comment by nielo360** [comment] 2022-03-31 16:34
Bump for any update since even new drivers do nothing

**Comment by nielo360** [comment] 2022-04-06 15:48
still broken with latest driver no fix

**Comment by nielo360** [comment] 2022-04-18 04:00
Still nothing. No fix

**Comment by estebanr863** [comment] 2022-04-21 01:52
Hi @nielo360,

Does the issue you are seen matchs this one?

https://user-images.githubusercontent.com/87549650/164355749-f773f2ef-cb47-4420-8df8-c39c58f92440.mp4

**Comment by estebanr863** [comment] 2022-05-16 20:48
@nielo360 thanks for confirming that. This issue was already reported internally, and we are working on it. I do want to set the right expectation with you that it might take from 3 to 6 months for a fix to be merged into our public release drivers.

**Comment by estebanr863** [comment] 2022-05-27 22:53
Hi @nielo360,

We aren’t seen the issue on the latest driver 30.0.101.1994. Can you please install this driver version and test it?

**Comment by nielo360** [comment] 2022-05-30 12:24
Same issue with 30.101.1994 I just tested it in the outdoors it goes flashing red again, indoors its normal. Please check again

**Comment by nielo360** [comment] 2022-06-06 06:39
> Hi @nielo360,
> 
> We tested again and we are not seeing any corruption on driver 30.0.101.1994. I’m attaching a video of my latest test, where no flashing red light can be seen with this driver version. If you continue to have the issue on your device, it may be caused by some customization added by your device manufacturer, so my advice is to contact this manufacturer for support.
> 
>  Rage.2.no.issue.on.30.0.101.1994.mp4

You are the wrong chipset, I have this chipset it works fine this is an issue with the new chipset 1195G7, please check on that. the thread is for that specific chipset.

**Comment by nielo360** [comment] 2022-06-07 03:51
> Hi @nielo360,
> 
> Both the i7-1165G7 and the i9-1195G7 use the exacte same GPU, the 96 EU Iris Xe. The only diference between these two SKUs is CPU performance, but their integrated GPUs are identical.

This is not the case as this issue happened to several people. I own a 1165g7 the drivers were never an issue with rage 2, you can test it urself and see it.  This issue is exclusively happening on 1195g7, while i dont know the reason, both 1195g7 devices I tried it on had this issue.  On my gpd win 1165 and win max 1165 no problem at all even with old drivers.

**Comment by IGCIT** [comment] 2022-06-07 08:24
hi @nielo360, can you please try to do a clean install of latest driver 1994 and test again in your 95g7 device?
and if possible upload a video and/or your save in the spot you see the glitch.
thanks

@estebanr863
is the one in your video the Epic Games version?
this reminds me the #51 issue, where the MS store version is still affected even if you fixed the drivers.

if nielo uploads his save, it should be possible to confirm if the issue is still happening in that specific spot

**Comment by nielo360** [comment] 2022-06-07 09:03
I did do a clean install before, and redownloaded the epic version. There is no need for save game it happened right when you go into the games first area as the video shows. I also tried the game pass version which had the same issue.  If I revert to the old intel nuc driver both work fine.

**Comment by estebanr863** [comment] 2022-06-12 00:25
Hi @nielo360,

Can you please provide the [SSU](https://www.intel.com/content/www/us/en/support/articles/000057926/memory-and-storage.html)  of your system with a i7-1165G7 that does not reproduce the issue?

**Comment by nielo360** [comment] 2022-06-12 00:59
its provided

**Comment by IGCIT** [comment] 2022-06-12 08:01
@nielo360  the one in the issue is 11**95**g7, he is asking for one of 11**65**g7 from your devices without the issue

**Comment by estebanr863** [comment] 2022-06-24 16:19
Hi @nielo360,

As I mentioned before, the iGPUs in the 1165G7 and the 1195G7 are exactly the same. You can verify that on ark.intel.com, where the Device ID for both iGPUs is identical.

![image](https://user-images.githubusercontent.com/87549650/175576340-271be38e-07eb-4fec-858a-eaab67927553.png)

However, not all CPUs/iGPUs are created equally, even for the same SKU. Similar to other electronics, Intel CPUs/iGPUs have revisions, where some changes may be introduced from one revision to the next. Although these changes are intended to fix issues, sometimes they introduce other issues inadvertently.

Checking the revision of your 1195G7 from the initial SSU you attached, I see it’s a REV_03. While the 1165G7 I’m using for testing is a REV_01. So, my current hypothesis is that some change introduced in REV_02 or REV03 may be causing the issue for you but not showing up for me. This is why I requested the SSU for you 1165G7 system, so I can check the revision and try to isolate where the issue was introduced.

**Comment by estebanr863** [comment] 2022-07-22 15:59
Hi @nielo360,

Our driver development team is experiencing a high volume of requests for fixes on game issues. And since we have limited resources, this means that fixes for issues on games outside of our top games list (we maintain an internal list of top games, considering the most played, recently released, etc.) will need to be put on hold. The fix for this issue falls into this category, so we currently cannot commit to target date for this fix to be released. I’ll update you once the development of a fix for this issue is resumed.

**Comment by estebanr863** [comment] 2022-09-20 19:41
Hi @nielo360,

The [latest driver](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html) 31.0.101.3413 include a change that might possibly help fix this issue. Can you please test this?

**Comment by pacoa-kdbg** [comment] 2022-09-21 23:05
Hi @estebanr863 
I just tested it on 31.0.101.3413 using an i701195G7 and I can confirm the issue is no longer present .
This issue can be closed .

**Closed** 2022-09-27 07:11 UTC
Labels: Info: Needs Replication, Type: Regression, Type: Graphical Glitches
