### ISSUE TITLE
My 1440p monitor can only output at 1080p resolution now

### ISSUE THREAD

**Issue by jim-jay** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#433] opened 2023-08-16 13:54 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

windows11

### Processor / Processor Number [Required]

i5-13400

### Graphic Card [Required]

Arc A770

### GPU Driver Version [Required]

- [X] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12360161/ssu.txt)

### Description and steps to reproduce [Required]

I use ddu to uninstall driver 4577,
then a fresh install for 4644.
Now I can only select 1920 x 1080(recommand) for my display

**Comment by jim-jay** [comment] 2023-08-16 14:06
I replaced the dp line with an HDMI line and the problem was solved，this problem only occurs when using the DP line

**Comment by Arturo-Intel** [comment] 2023-08-16 15:32
Hi @jim-jay 
Did you try with another DP cable? just to be sure the cable is not the culprit

--r2

**Comment by Arturo-Intel** [comment] 2023-08-16 16:05
Can you use [DDU ](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html) in safe mode when installing 4644?

Why I am asking this? I am using the same resolution (1440p) on my side and I am using 4644 and DP without any problem.
The only difference is the monitor model itself.

With DDU we can have a clean installation and start moving from there.

-- r2

**Comment by jim-jay** [comment] 2023-08-16 16:34
I always use DDU in safe mode following the article you noticed.
And I tried a clean install again, no difference.

**Comment by Rotluchs** [comment] 2023-08-18 22:04
exactly which Arc A770 Model / Brand or Manufacturor btw?

there is an unusual amount of error reports right now regarding products from Asrock and especially Acer with  newest driver 4644 directly from intel's DL HP and the firmware/bios update it installs ...

most error reports regarding 4644 right now - no matter what the symptom/issue is - are connected to cards from Asrock or Acers Predator (which seems to have the most problems with this 'default' driver / fw bios, since acers card seems to be the most modified Arc card of all right now (regarding software, and maybe also regarding custom OC / power / fan curves )

**Comment by Arturo-Intel** [comment] 2023-08-23 16:13
@jim-jay can you run a dxdiag and share the results?

**Comment by jim-jay** [comment] 2023-08-27 16:07
I have upgraded the driver to 4669, but the problem has not been solved. Here is the result of dxdiag.
[DxDiag.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12448365/DxDiag.txt)

And my monitor is **Philips BDM3270QP**

**Comment by Bill177** [comment] 2023-08-29 21:19
Hi
I have the same issue with newer Drivers 4644 & 4669.

My monitor : BenQ BL2420PT 2K

**Comment by jim-jay** [comment] 2023-09-04 12:17
Hi, @Arturo-Intel 
I have installed the driver 4672 and this issue is still not fixed.

**Comment by fancycookin** [comment] 2023-09-06 21:24
Hi @Arturo-Intel 

Same issue as OP. haven't been able to run my monitor at its native resolution after driver update.

Here's my [DxDiag.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12542645/DxDiag.txt)

Monitor: LG 34UM95
Native Resolution: 3440x1440
Connection: DisplayPort 1.2
GPU: BiFrost Arc A770 OC Graphic Card
Last Working Driver Version: 31.0.101.4577

Thank you @jim-jay for starting the thread. 👍

**Comment by pcslide** [comment] 2023-09-07 02:27
@fancycookin I think so as well.  FYI, the DisplayPort on my card is complete dead now.  I am not sure if  it was the new firmware caused the breakdown of the hardware.  I had sent the card back to reseller for further inspection.

**Comment by fancycookin** [comment] 2023-09-14 23:21
Issue still presists with latest WHQL driver: 31.0.101.4824 (WHQL Certified)

The driver update is replacing my monitor's .inf file, and now is capped at 1080p instead of running at 3440x1440. 

Attaching before and after screenshots of my LG monitor from device manager.
![before](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/10814926/89bea7e4-7de1-407d-a9dd-c298ff7b24de)
![after](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/10814926/7152b7e6-5e80-4913-b8fc-3930a7bedc1d)

**Comment by Arturo-Intel** [comment] 2023-09-15 00:21
@fancycookin thats a good piece of info. Ty!
I'm curious, Can you rollback the driver for your monitor after the installation of the latest driver?

We are root causing this issue with the dev team.  Thank you for your patience 

-- r2

**Comment by fancycookin** [comment] 2023-09-15 18:04
> Hi all,
> 
> Issue still persist on my side with 4824.
> 
> I'm adding reports and screenshots.
> 
> [4824 Capture](https://user-images.githubusercontent.com/143556168/268223225-e3ceb42d-86e1-46c0-8b84-169630876ffe.png) [4824 report.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12617325/4824.report.txt)

@Arturo-Intel  not sure how helpful this is but I noticed that if I try to do a **Update Driver** on **Generic Monitor** through Device Manager, then windows will think the best driver for it is this **Digital Flat Panel (640x480 60Hz)** device that @Bill177 seems to also be getting post driver update on his system.

**Comment by Tek-mate** [comment] 2023-09-18 21:25
I'm experiencing this issue after driver 4577 - issue remains on all drivers through to 4824.
Intel Arc Control - No monitor ID's displayed.
HDMI works and rolling back to 4577 allows full resolution.

Intel Arc A770 8MB (ASROCK) with 2x LG Ultrawide Montors connected via DP.

It would seem to me that the card is not correctly identifying the monitor via DP and falling back to a safe resolution.  
As I can roll back to 4577 and have full resolution, I would put this squarely in a regression in the Driver.  

I cannot see if Intel are aware of it as its not listed in the release notes as a known issue.

**Comment by Tek-mate** [comment] 2023-09-18 21:26
I'm experiencing this issue after driver 4577 - issue remains on all drivers through to 4824.
Intel Arc Control - No monitor ID's displayed.
HDMI works and rolling back to 4577 allows full resolution.

Intel Arc A770 8MB (ASROCK) with 2x LG Ultrawide Montors connected via DP.

It would seem to me that the card is not correctly identifying the monitor via DP and falling back to a safe resolution.  
As I can roll back to 4577 and have full resolution I would put this squarely in a regression in the Driver.

**Comment by fancycookin** [comment] 2023-09-19 01:46
> I cannot see if Intel are aware of it as its not listed in the release notes as a known issue.


I do agree that this should be included in known issues of all the drivers after 4577

**Comment by fancycookin** [comment] 2023-09-19 19:34
Any luck with 31.0.101.4826 anyone?

**Comment by Tek-mate** [comment] 2023-09-19 22:02
👎No luck here - still poor resolution on 4826.
It's hard to tell if its on Intel's agenda - or how widespread the issue is.

From my experiance HDMI is ok, potentially ok if on the mainboard headeres (video signal redirected through mainboard).   
I cannot see what was changed in the driver to regress such a low level function !.

**Comment by Arturo-Intel** [comment] 2023-09-19 22:09
It is in our agenda, we are working with our drivers team to root cause this issue.
I will post any news rearding this case on this thread.

Once again, thank you for your patience
-- r2

**Comment by Tek-mate** [comment] 2023-09-19 22:40
Thanks Arturo - that feedback goes a long way.   
Let us know if we can be of assistance with testing.

**Comment by fancycookin** [comment] 2023-09-25 21:36
I went out and bought a new DisplayPort 2.0 cable and tried that, issue still persists.

**Comment by Tek-mate** [comment] 2023-09-25 22:45
I've tried some cables too - no help.   HDMI works for me, but I only have 1 port.
Still not on the release notes and I believe they no longer offer the older driver for download which worked.

Its been 3-4 driver releases with the issue.  
Trying to wait patiently.  ;-)

**Comment by Rotluchs** [comment] 2023-09-25 23:56
..if you need older driver versions that you no longer have stored locally on your PC,
you can find them for re-download on https://www.techpowerup.com/download/intel-graphics-drivers/# 
I do not know why intel themselves are no longer either hosting or linking them, they will only show last two (1 whql other is beta)

PS: you should uninstall any gpu software & drivers via DDU in save mode as admin first, before re-installing / downgrading drivers.
note that this procedure will not automatically downgrade your gpu bios.
if the error is bios related, a simple driver downgrade wont help.

in that case, you will have to flash old bios manually. you can find a guide & most if not all bios files also on techpowerup, plus a gui flash tool that's based on  or built around intel's own github stuff afaik.

if your error should be PCON fw related, then there is no fix because there is no way to manually flash or downgrade that part of the GPU FW/BIOS yet. driver installer seems to use a different routine for that one as it is reported,

so you will have for an official intel fix, or any info from intel how to obtain & force pcon fw file downgrade.

**Comment by Tek-mate** [comment] 2023-09-26 14:44
Thanks Rotluchs I luckily had the older driver saved, but that will be useful to others as the 101.4577 version is the one without the display resolution issue.

Reading through the threads of what I think are the same issues, it looks like different brands of Intel arc and different manufacturers of the monitors are suffering.   

**From what I can see though (from the reports and logs), is it only related to UltraWide monitors connected via DP.   
Does anyone have a non ultra-wide monitor with the same problem ?**  

Otherwise I think it would be more wide spread a problem ?

**Comment by Tek-mate** [comment] 2023-10-03 14:07
@Arturo-Intel 
Just tagging you in as I found a common connection with the resolution issues suffered after the 4577 driver release.

It appears that all users having the issues are on **Ultrawide format monitors**.
It appears that UHD 620 users are affected on laptop external displays.

Intel Arc users only appear to have the problem via DisplayPort connections
Intel UHD 620 users have the issue on external HDMI port.

All users can rollback the driver to achieve the correct native resolution - indicating driver issue.

The issue is quite wide spread but differing descriptions of the issue (and some issues caused by poor cabling) are masking the issue.

For me it seems that the monitor is purely not detected correctly and therefore offers a safe fall back resolution.   Mine and others have no monitor name in the intel app / windows system panel.

I'm loosing a significant amount of screen real estate and the regression has been around for 8 weeks - is there any feedback from the engineers on this issue ?

**Comment by Tek-mate** [comment] 2023-10-03 14:16
Also (to prove the Ultrawide aspect ratio is the issue) I've plugged a -
Dell Monitor P2416D a none ultrawide display, and can get a resolution of 2560x1440 on the same cable and port perfectly (Which is more pixels to push).  
My LG ultrawide monitor should run at 2560x1080 but fails.

My guess is someone hasn't taken in to account the less common ratios in the drivers, and would wager that the same code issue is in the UHD igpu's as well.  
Can you please pass this information on to the engineers ?

- Paul

**Comment by Bill177** [comment] 2023-10-03 14:31
> It appears that all users having the issues are on **Ultrawide format monitors**

**Comment by Tek-mate** [comment] 2023-10-03 15:03
@Bill177  - Thats with your BenQ BL2420PT 2K, monitor right - I must have looked that up wrong as I read it as a Ultrawide (its not I've double checked) and is similar to my Dell which is displaying the correct resolution.   

Just to confirm you were on display port ? (Its shows as display port in your screenshots but I remember reading a known bug is that it doesn't display the right port on some releases ).  

Paul

**Comment by Bill177** [comment] 2023-10-03 15:37
> Just to confirm you were on display port ? (Its shows as display port in your screenshots but I remember reading a known bug is that it doesn't display the right port on some releases )

@Tek-mate Yes was using Displayport and HDMI was perfectly fine. The bug where it doesn't display the right port only effected Intel Arc Control.

And yes I believe it's effecting monitors from several brands with all kind of different aspect ratio's example here :
https://community.intel.com/t5/Graphics/Arc-750-1920x1200-Missing-In-Both-4644-amp-4669/m-p/1518844#M121721

I've returned my card so I can't do anymore testing.

**Comment by fancycookin** [comment] 2023-10-03 15:57
> I'm loosing a significant amount of screen real estate and the regression has been around for 8 weeks - is there any feedback from the engineers on this issue ?

Agreed, at least acknowledge it in the known issues in the changelog of new drivers. It's also extremely discouraging that the support threads that were opened up on Discord related to this issue are getting closed down due to inactivity as well.

**Comment by Arturo-Intel** [comment] 2023-10-04 17:22
Hello everyone!

Rest asure our dev team is working to get the root cause of this issue as we speak.
I will post any news on this matter, ty for your patience

Thanks @Tek-mate for the sumary you provide, it really helps!.
-- r2

**Comment by Tek-mate** [comment] 2023-10-05 17:03
@Arturo-Intel 

Really appreciate the effort and thank you.   

Not sure if its helpful but these are a list forum posts that I think are all related to this issue. 


[My 1440p monitor can only output at 1080p resolution now · Issue #433 · IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT (github.com)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/433)
https://community.intel.com/t5/Graphics/Arc-750-1920x1200-Missing-In-Both-4644-amp-4669/m-p/1518844#M121721
[Latest Intel Arc A770 driver update forcing 1440p monitors to run at 1080p - Intel Community](https://community.intel.com/t5/Intel-ARC-Graphics/Latest-Intel-Arc-A770-driver-update-forcing-1440p-monitors-to/td-p/1526628)
[Monitor saying out of signal - Intel Community](https://community.intel.com/t5/Graphics/Monitor-saying-out-of-signal/m-p/1527702#M122906)

[Second monitor has lower resolution after update - Intel Community](https://community.intel.com/t5/Graphics/Second-monitor-has-lower-resolution-after-update/m-p/1524928#M122525)

[Driver causing my Dual Monitor to stop working. - Intel Community](https://community.intel.com/t5/Graphics/Driver-causing-my-Dual-Monitor-to-stop-working/m-p/1524667#M122496)

[Re: Intel Arc A770 16G no native resolution on 2560x1080 Display with Driver newer 4578 - Intel Community](https://community.intel.com/t5/Graphics/Intel-Arc-A770-16G-no-native-resolution-on-2560x1080-Display/m-p/1529242#M123119)

[Can not set up 3 monitors with Intel HD Graphics 4000 - Intel Community](https://community.intel.com/t5/Graphics/Can-not-set-up-3-monitors-with-Intel-HD-Graphics-4000/m-p/365806#M25649)

[Re: DP Monitor not detected after driver update of A770 LE 16gb graphics card - Intel Community](https://community.intel.com/t5/Graphics/DP-Monitor-not-detected-after-driver-update-of-A770-LE-16gb/m-p/1529235#M123117)

[Arc 750 1920x1200 Missing In Both 4644 & 4669 - Intel Community](https://community.intel.com/t5/Graphics/Arc-750-1920x1200-Missing-In-Both-4644-amp-4669/m-p/1517972#M121594)

[31.0.101.4577 Driver update broke triple monitor 2560x1440 display. - Intel Community](https://community.intel.com/t5/Graphics/31-0-101-4577-Driver-update-broke-triple-monitor-2560x1440/m-p/1521480#M122028)

[Intel Iris Xe driver not supporting 4k monitor resolution - Intel Community](https://community.intel.com/t5/Graphics/Intel-Iris-Xe-driver-not-supporting-4k-monitor-resolution/m-p/1526763#M122779)

[v101.4644 breaks DP output · Issue #440 · IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT (github.com)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/440)

**Comment by Tek-mate** [comment] 2023-10-05 22:36
@Arturo-Intel 
Just tried the latest beta drivers .... 101.4885 - and holy smoke - back to the correct resolution on both monitors - correctly listed in device manager.
Can you let us know what the issue was ?

Huge thanks for the team, I can finally configure my powertoys fancy zones up now.   👍👍

(I did a straight install of the beta driver without clean install, or DDU)  available here.... https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html?

**Comment by Arturo-Intel** [comment] 2023-10-05 22:48
@Tek-mate 
I am glad it is fixed now, I am going to wait to see if anyone can help us to confirm the fix in their end. 
Will check the other links you share to double confirm the fix

>Can you let us know what the issue was ?

I am quite not sure to be honest, my guess is that someone of our devs root cause the issue and fixed asap, without any heads ups. It is a pleasant surprise tho.

--r2

**Comment by jim-jay** [comment] 2023-10-05 23:01
@Arturo-Intel 
I just installed the driver 4885(without DDU) and my problem has been solved perfectly.

**Comment by Arturo-Intel** [comment] 2023-10-05 23:10
@jim-jay 
Thanks for the confirmation!

**Comment by Arturo-Intel** [comment] 2023-10-10 17:38
@IGCIT Can we close this case please?

**Closed** 2023-10-10 19:34 UTC
Labels: Info: Needs Replication, Type: Support
