### ISSUE TITLE
edid override does not work when an edid has been generated instead of being embedded

### ISSUE THREAD

**Issue by ciphray** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#111] opened 2022-02-18 17:05 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows

### Processor / Processor Number [Required]

i7-1185G7

### GPU Driver Version [Required]

- [X] 30.0.101.1340 (*latest*)
- [ ] 30.0.101.1191
- [ ] 30.0.101.1121
- [ ] 30.0.101.1069
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11
- [X] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

[Win-max-2021.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/8098979/Win-max-2021.txt)

### Description and steps to reproduce [Required]

![edid-override1](https://user-images.githubusercontent.com/19839730/154727798-53e3c9fe-6947-497d-aa4f-91c991889182.png)
![edid-override2](https://user-images.githubusercontent.com/19839730/154727800-3847d137-3248-4a0f-9325-1689944ab99c.png)

I am using a GPD win max 2021, the panel itself functions properly with display frequencies down to 24hz and up to 60hz
I can make use of these in linux, however in windows applying an edid override does not show up in the list of selectable resolutions

intel graphics command center does show the additional frequencies under info, however it does not show under general
as pictured in the attachments

it has a mipi panel, and there is no edid embedded in the bios that i'm aware of, so the fakeedid that gets generated appears
to have priority over the windows edid override

would it be possible to correct this so that the edid override in windows is able to function as it should?

This is especially helpful when gaming on low power igpus, being able to sync to refresh rates under 60 allows power savings and smoother frametimes when unable to maintain 60fps

### Device / Platform

GPD WIN MAX 2021

### Crash dumps [Required]

no crashes happen as a result of this

**Comment by estebanr863** [comment] 2022-02-22 15:50
Hi @ciphray,

The Intel Graphics Driver is always expecting the EDID info from the panel. If on your device you suspect that the panel doesn't have an EDID programed, our advice is to contact the support team of your device's manufacturer so they can address this issue.

**Comment by ciphray** [comment] 2022-02-22 16:22
Windows does show an edid that matches out with the capabilities of the display in the registry

however the driver does not apply edid overrides when a mipi panel is in use, could this be fixed?

command center recognizes the edid information in the override in the information screen

but will not allow me to select the resolution it shows as being supported

**Comment by estebanr863** [comment] 2022-02-22 18:06
@ciphray the problem here is that there is no way we can ensure that the app you are using to override the EDID fully complies with the EDID standard. I understand that you are trying to find a workaround to the panel not having an embedded EDID. However, EDID override is not something we can support since the correct way to address this issue for the manufacturer of the panel to correctly add the EDID to the panel.

**Comment by ciphray** [comment] 2022-02-22 21:05
https://docs.microsoft.com/en-us/windows-hardware/drivers/display/overriding-monitor-edids

https://community.intel.com/t5/Graphics/Feature-Request-implement-EDID-override/m-p/253019

I'm not really looking for more than it to function with mipi panels with your driver as your driver does with edp, hdmi and other display types

as i mentioned in my original post i can use this same edid under linux so it functions with this panel on this device, but every mipi based device i have ignores edid overrides while using an intel igpu in windows

I've been able to use this exact panel with this same edid in another motherboard with an edp to mipi converter

![image](https://user-images.githubusercontent.com/19839730/155218419-99d0edd2-7b36-4b63-9d7f-4ad76058d6e6.png)

on intel, edid overrides are stated to work with internal panels, is excluding mipi panels from using edid overrides intentional?

**Comment by estebanr863** [comment] 2022-02-28 20:34
Hi @ciphray 

As I mentioned before, I understand that you are trying to find a workaround to your issue, but I must again recommend that you contact the support team of your device manufacturer, since only they can fix this issue permanently.

Now, regarding the workaround, I was able to override the EDID using this [app](https://www.monitortests.com/forum/Thread-Custom-Resolution-Utility-CRU) I found online on a i7-1165G7. So, as you mentioned, the drivers do support this feature. Being this the case, if the app you are using to override the EDID is not working as intended, I advise you to contact the developer of your app. Please do note that in my case, for the overridden EDID options to show up on Windows, **I had to disconnect and re-connect the video cable from the monitor after the override was applied**. If you intend to override the EDID for an internal display, you may not be able to comply with this spec, and thus this workaround may not be available to you.

**Comment by ciphray** [comment] 2022-02-28 20:50
I've tried CRU, i've in fact used it with this same panel in the past on a different motherboard and that works fine as it has an edp>mipi dsi converter, 

I've also tried the same edid extracted from this very device on a different bios version with an alternate refresh rate from
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Enum\DISPLAY\

Command center sees the frequency, but will not allow it to be selected

I have dell/lenovo tablets with direct mipi dsi panels and they exhibit the same behavior

if i intentionally use an invalid edid on hdmi or edp, those will show the resolution as selectable even if the device would give issues with it selected, but with a direct mipi dsi connection even with a valid edid for the panel, it's ignored

**Comment by ciphray** [comment] 2022-02-28 21:04
![Screenshot (21)](https://user-images.githubusercontent.com/19839730/156058285-92200ed4-d818-4974-81f7-3a9dd5fb6830.png)
![Screenshot (22)](https://user-images.githubusercontent.com/19839730/156058289-df00905c-1bb7-4672-8867-77ce0fcd40cc.png)
here it is with the original edid used as an override, the original bios had the display set to 61hz
attempting to use that edid displays it in the information screen, but the display is still set to 60hz

**Comment by estebanr863** [comment] 2022-02-28 23:20
@ciphray,

When you apply the EDID override, can you change the Refres Rate in the Windowds Advanced Display Setting? (even when not available in the Intel Graphics Command Center)
![image](https://user-images.githubusercontent.com/87549650/156075024-05350113-1049-4ec1-94c2-022c92f7646d.png)

**Comment by ciphray** [comment] 2022-02-28 23:28
No, it's not available there, the mode is reported as 60.000HZ only
and list all modes does not show it either
![listallmodes](https://user-images.githubusercontent.com/19839730/156076066-be7bd66d-d66b-4dfd-8371-8ad167c05caf.png)

**Comment by estebanr863** [comment] 2022-02-28 23:41
@ciphray,

Since EDID override works as intended on Intel manufactured devices (the ones I tested in our lab) but not on yours, indicates that only your device manufacturer can provide you a fix.

The fact even at the OS level the EDID override is not working, seems to indicate that some of the customizations the manufacturer of your device’s graphics may be blocking this feature.

**Comment by ciphray** [comment] 2022-02-28 23:54
@estebanr863 

Appreciate your time
If this can't be changed with an EDID override, is there any other means I might be able to add other display modes/alter the existing one?
Such as a DTD or VBT override?
I see the registry entries for DTD but they do nothing as far as I can tell
and in some of intel's documentation I see mentions of a VBT override but nothing further on the subject in public documents that I've seen
Under linux I am able to override the EDID, and VBT and add other display modes that function

**Comment by estebanr863** [comment] 2022-03-01 20:16
@ciphray

We do have an internal tool that can be used to override the VBT. However, this tool and its documentation are only available under NDA, since it is mostly intended for OEMs and embedded system designers.

**Comment by estebanr863** [comment] 2022-03-08 15:32
Hi @ciphray,

Can this issue be closed?

**Comment by estebanr863** [comment] 2022-03-09 20:43
Currently, the first priority is the EDID and then it is followed by the DTDs. We are aware that this is not standard, as per CTA-861, DTDs should take precedence (specifically when using the Video Format Preference Data Block or VFPDB). This is a known bug that may get fixed in future driver updates.

Regarding the specific registry key you pointed out, unfortunately I cannot confirm if is still used by the latest drivers.

**Closed** 2022-03-13 21:36 UTC
Labels: Info: Needs Replication
