### ISSUE TITLE
[Black screen | CTD ] Total War Rome 2

### ISSUE THREAD

**Issue by dsuded** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#359] opened 2023-06-23 21:01 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Total War Rome 2

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i9 10850K

### Graphic Card [Required]

Intel Arc A770 16 GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11852936/igcit_ssu.txt)

### Description and steps to reproduce [Required]

1) Change graphics settings to any except "Very High", for example set it to "Ultra"
2) Start Grand campaign as any faction

Game should crash or black screen with sound in the background.
Interestingly, if graphics settings is set to "Very High", grand campaign starts normally.
Also, benchmark option does not load (Graphics > Benchmark).

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![20230623224617_1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/20488959/facab7f4-2ec3-4357-8f76-1d829a282458)

**Comment by Arturo-Intel** [comment] 2023-06-26 16:37
Hi @dsuded, 

Will replicate this on the lab, will come back to you if I have some questions.
--r2

**Comment by Karen-Intel** [comment] 2023-06-30 20:59
Hey @dsuded quick update

There was a beta driver release with huge updates for games with DX11.
I have been able to run the benchmark successfully. Could you give it a go?

![TWR2](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/91162218/04684d4c-ef16-414c-b1c7-9cbb6a28e02e)

Please let me know

Karen

**Comment by dsuded** [comment] 2023-06-30 21:35
Hi @Karen-Intel! Are you using Arc A770? In the image i see UHD 770 GPU.

I have installed latest beta driver 4512 however results are still the same. I can get the Benchmark and Grand Campaign to consistently load only on Very High settings. I have played a bit more with the settings and found that Texture Quality is main culprit - **when set to any other setting beside Ultra the game will load as expected**. Out of curiosity I tried dxvk workaround and the Ultra settings work fine so it looks like DX11 should be looked at.
I will experiment a bit more and reply if I find out something else.

**Comment by Karen-Intel** [comment] 2023-06-30 21:51
> Hi @Karen-Intel! Are you using Arc A770? In the image i see UHD 770 GPU.
> 
> I have installed latest beta driver 4512 however results are still the same. I can get the Benchmark and Grand Campaign to consistently load only on Very High settings. I have played a bit more with the settings and found that Texture Quality is main culprit - **when set to any other setting beside Ultra the game will load as expected**. Out of curiosity I tried dxvk workaround and the Ultra settings work fine so it looks like DX11 should be looked at. I will experiment a bit more and reply if I find out something else.

Ah in CapframeX IDK why it always shows my UHD as main but I have my ARC mapped in the Graphics. If I disable my iGPU it will show my ARC as main, CapframeX issue.
I think I could repro the same issue with Extreme quality on Graphics settings, but I will keep on testing and provide an update next week.

Karen

**Comment by dsuded** [comment] 2023-08-25 21:06
Do you have some update on this, it's been a while.

**Comment by Karen-Intel** [comment] 2023-08-25 22:03
Hi! Just FYI most of the cases take ~ 3 to 6 months for a fix to be released (sometimes it takes longer than that)
Have you tested with our latest driver? v.4644 WHQL, please let us know :) Thanks

Karen

**Comment by segacorpceo** [comment] 2023-10-10 22:46
> Hi! Just FYI most of the cases take ~ 3 to 6 months for a fix to be released (sometimes it takes longer than that, sometimes doesn't) Have you tested with our latest driver? v.4644 WHQL, please let us know :) Thanks
> 
> Karen

Game still crashes while playing the campain after a couple turns same with Atilla Total War.

**Comment by segacorpceo** [comment] 2023-10-20 23:22
Here is my Rome 2 save file. 
[rome 2 save.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13059163/rome.2.save.zip)


> @segacorpceo can you please share your save game? TY
> 
> Karen

**Comment by Arturo-Intel** [comment] 2023-12-19 00:51
@dsuded I was able to start the campaign without any black screen or crash with 101.5081

Can you confirm this?

**Comment by dsuded** [comment] 2023-12-19 16:22
> @dsuded I was able to start the campaign without any black screen or crash with 101.5081
> 
> Can you confirm this?

I will try and report back.
BR

**Comment by segacorpceo** [comment] 2023-12-22 19:30
@Arturo-Intel 
The campaign loads on ultra now but when entering land battles in the campaign the game still blackscreens, also when setting graphics preset to extreme settings even the benchmark blackscreens.

**Comment by rmorera-intel** [comment] 2024-10-31 15:17
Hello everyone, I have good news: I was able to confirm the issue is not fixed with driver [32.0.101.6130 and newer](https://www.intel.com/content/www/us/en/download-center/home.html).
I know this took a considerable amount of time to get fixed so I thank you all for your patience.

I'll proceed to close this now.

**Closed by rmorera-intel** 2024-10-31 15:17 UTC
Labels: Info: Replicated, Type: Application Crash
