### ISSUE TITLE
Genshin Impact has blurry/unfocused textures given a certain distance compared to using other graphics cards

### ISSUE THREAD

**Issue by martin-ngyn** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#388] opened 2023-07-16 05:18 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Genshin Impact

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [X] Other (please specify)

### Other game platform

Direct installation

### Processor / Processor Number [Required]

Ryzen 5 3600

### Graphic Card [Required]

Intel Arc A750

### GPU Driver Version [Required]

- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [X] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[intel arc a750 ssu log.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12063324/intel.arc.a750.ssu.log.txt)

[gtx 1660ti ssu log.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12063322/gtx.1660ti.ssu.log.txt)

### Description and steps to reproduce [Required]

When playing Genshin Impact, objects rendered at a certain distance will always have blurry textures compared to other systems using different graphics cards.

For example, in this event for patch 3.8 called "Spinoblaster", Intel Arc A750 system has blurrier textures on the targets throughout. However, a system with GTX 1660 ti has focused textures.

**Intel Arc A750 system**
![spino blaster blurry](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/81234267/28861f6b-9e54-4232-88ba-727fe3d55ef1)

**Nvidia GTX 1660 ti system**
![non-blurry spinoblaster](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/81234267/2b5380e1-64f1-494d-a5bb-25ae3bae1bc1)

Another example that is more reproducable (once event ends, cannot replicate using example above).

When you teleport to Liyue, and you do not move, panning the camera to the chests to the left will have blurry textures on the Intel Arc A750 system compared to the GTX 1660 ti system.

**Teleport here and do not move your character**
![liyue teleporter](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/81234267/9a542f57-26e8-452e-bffd-606765229b0e)

**Intel Arc A750 system**
![blurry liyue](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/81234267/f41431d6-831a-4628-bb77-f545f47e45e1)

**Nvidia GTX 1660 ti system**
![non-blurry liyue](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/81234267/dceac7a3-dbf4-4f4e-bdef-cdc47788608b)

Both systems have the exact same graphics settings.

So in summary:

- Given a certain distance and having the same graphics settings across both
- Intel Arc A750 produces blurry textures compared to the Nvidia 1660 ti system

If you move closer to the object, it will focus, but the point is it's always going to give you unfocused textures more consistently on the Intel Arc A750, distracting your gameplay.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Both systems have the exact same graphics settings:
![graphics settings 1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/81234267/bd4f03c9-5460-4e29-a698-f445eb9d78de)

![graphics settings 2](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/81234267/22773de7-a693-4c6e-ad78-dd921f92fd4e)

### Device / Platform name

Desktop PC

**Comment by martin-ngyn** [comment] 2023-07-17 11:45
Here's a video showing how going further away from an object makes the textures blurry.

Look at the textures of the log.

https://youtu.be/ZBeke40lHIw

Other graphics cards wouldn't have this problem to this extent.

**Comment by J0dla** [comment] 2023-07-17 17:07
I was intriqued because i played it yesterday for 3hrs so i tried to replicate, used your settings on FHD run for a while did same test on beach. With ARC A380  on 4514 driver and couldnt find it:
https://youtu.be/aPq0DR0AsMM
Maybe newer driver will fix it for you :(

**Comment by martin-ngyn** [comment] 2023-07-18 11:36
Thanks for doing some tests.

I've upgraded to 31.0.101.4575 and I'm still having the same issues. I've also tried to test my graphics settings (turn something to low/off, and check for issue, then revert and test another setting) and it's still having issues.

**Comment by Arturo-Intel** [comment] 2023-08-08 21:23
Sorry for the late response, I am working my way to that particular point in the game to reproduce the blurry texture.
Will keep you posted

-- r2

**Comment by martin-ngyn** [comment] 2023-08-10 02:10
In theory this happens everywhere in the game, but if you want a nice early reproducable place to test this, try going to this teleporter in Springvale and once you teleport, do not move from your location.

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/81234267/d7ee8ec6-afa7-4869-8f3c-7f64149f1a52)

If you look at the rock, sign and haystacks, they will be blurrier.

![springvale blurry marked](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/81234267/be5f0a89-818a-4879-88e8-a4c9da4f3dd8)

![springvale clear](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/81234267/4a40b052-a508-45d0-90fe-ac6b5b5f25ea)

Another tip to save time is that you don't have to go through story to access most teleporters. You can just walk straight there and activate it.

**Comment by BiZkViT96** [comment] 2023-08-10 04:44
@martin-ngyn I noticed that too, does this happens for you on some domains entrances as well? Here is example with Hidden Palace of Lianshan Formula domain.
![GenshinImpact_2023_08_10_11_35_57_401](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/88586431/c90a9fe0-c25f-4987-8ff1-11f92fa3c5bc)
![GenshinImpact_2023_08_10_11_36_03_603](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/88586431/1b2ab0d7-b3c3-49d9-b14d-9be87bbd6909)
During opening animation for some reason texture goes to lower res mipmap.
![GenshinImpact_2023_08_10_11_36_14_236](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/88586431/31886381-8220-4fc6-ab75-68f23b5549f9)
![GenshinImpact_2023_08_10_11_36_20_607](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/88586431/e87769c9-11ec-4f53-808b-2eb604b96fc3)

I always thought that this just is how it works.

**Comment by martin-ngyn** [comment] 2023-08-10 08:07
@BiZkViT96 Yes this happens for me for that domain door too. 

Generally the issue is being far away (it's not even that far away), you get low res textures, then going closer and waiting a few seconds will give you higher res.

What's happening to this domain door as you open it is:

1. Open door
2. Camera pans out away from door, causing door textures to be low res
3. Camera animation zooms in to door, causing door textures back to normal

**Comment by martin-ngyn** [comment] 2023-08-26 08:25
After upgrading to 31.0.101.4644, things have vastly improved for textures. They seem to focus at better distances now.

Only anomaly I'm seeing is that all domain doors are blurry no matter how close you are.

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/81234267/0fbb3203-5251-430d-aca3-68836b508bae)

**Comment by BiZkViT96** [comment] 2023-08-26 11:48
@martin-ngyn I noticed it too, but I'm not sure if it's because of a new driver or a game update.

As I understand it, you have an Arc A750 and a GTX 1660 TI. Could you please upload output_log.txt from both systems?

You can find it here:
C:\Users\XXX\AppData\LocalLow\miHoYo\Genshin Impact\

Simply find place (domain door) in game where you can see the texture bug and close the game.

Keep in mind that the log file is overwritten when the game is restarted.

**Comment by martin-ngyn** [comment] 2023-08-27 04:28
@BiZkViT96 these are the output logs when looking at the same domain door from both systems.

[intel arc a750 ssu log.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12447257/intel.arc.a750.ssu.log.txt)

[gtx 1660ti output log.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12447256/gtx.1660ti.output.log.txt)

**Comment by BiZkViT96** [comment] 2023-08-27 04:59
@martin-ngyn A750 is SSU log and not a game log,

**Comment by martin-ngyn** [comment] 2023-08-27 07:57
@BiZkViT96 sorry here's the proper file. Also updated previosu comment to fix it.

[arc a750 output log.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12447488/arc.a750.output.log.txt)

**Comment by BiZkViT96** [comment] 2023-08-27 09:29
@martin-ngyn Judging by the logs, you were in front of the gate before you closed the game.

There is one interesting difference in the logs, and it is at the very end.

Look for "Genshin Loading Log: BaseLevel FinishLoadSceneAynsc AllEntityReady"

There are two of them, the first its when you launched the game and second where you are in front of the gate.

At the end of that batch Intel GPU prints "Invalid mesh load operation, not belonged to lod loader"

I believe this refers to a problem with textures.

All after that line is you quitting the game, like 

"MoleMole.GameManager:DestroyCurLevel()"
"[2023-08-27 12:26:04.859] Genshin Start Log: GameManager CreateNewGameWorld Home"
"[2023-08-27 12:26:08.327] Call QuitApplication"
etc.

I looked at my recent log after an hour and a half of playing and it also contains the line "Invalid mesh load operation, not belonged to lod loader"

I would advise you contacting HoYoverse support and refer to this issue. You can do it through the main menu. This is what I did, with my crashing driver problem.

In any case, it will be better than waiting for a response from Intel. If HoYoverse devs find a source of the problem in the driver, they will contact Intel and pressure them to fix it. Otherwise, you can wait for the fix up to 6 months.

**Comment by Arturo-Intel** [comment] 2023-09-22 22:58
@martin-ngyn Hi, did you try with the latest driver? (101.4826) 
I was checking in all the locations in this thread and I dont see the blurry/unfocused textures.

Can you confirm?

--r2

**Comment by martin-ngyn** [comment] 2023-09-23 06:13
@Arturo-Intel 

The majority of texture issues were fixed in recent firmware updates. The only minor issues I see left are domain doors (notice the triangle in the middle being blurry).

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/81234267/f5f632e2-a23f-4f59-b2d2-710eff591cef)

**Comment by martin-ngyn** [comment] 2023-12-18 06:24
@Arturo-Intel 

I'm on 31.0.101.5081.

The domain you've checked "Temple of the Falcon" looked okay. However, when I check "Hidden Palace of Lianshan Formula".

I'm not super bothered by these textures as most of the main game have proper textures now so I'm happy to close this issue if that helps.

![temple of the falcon](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/81234267/334b3321-1106-4cad-97f2-10002fe3dfa9)
![hidden palace of lianshan formula](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/81234267/82254590-5aaa-4448-b024-682e4e5e1ba9)

**Comment by Arturo-Intel** [comment] 2023-12-18 17:42
@martin-ngyn OK, seems to be related to the texture itself.

>I'm not super bothered by these textures as most of the main game have proper textures now so I'm happy to close this issue if that helps.

will close this issue then, thx for your help guys.

-- r2

**Closed by Arturo-Intel** 2023-12-18 17:42 UTC
Labels: Info: Needs Replication, Type: Graphical Glitches
