### ISSUE TITLE
Portal RTX fails to launch

### ISSUE THREAD

**Issue by BelleNottelling** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#333] opened 2023-06-02 03:29 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Portal with RTX

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i7 13700K

### Graphic Card [Required]

Arc A770 LE 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11631552/igcit_ssu.zip)

### Description and steps to reproduce [Required]

Portal with RTX fails to launch completely. It's always crashed for me, even with testing driver version `4255` which specifically mentioned fixing issues with the game:
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/17304943/2f34858b-d4e6-48e8-b432-47c4551a6d4c)

For me, the game just opens inside of Windows for a few seconds and then closes. No error messages, no loading screen, nothing.
This behavior has remained the same even after upgrading my PC and completely re-installing windows.
You can force the game to launch using `-vulkan` in the launch options, however this bypasses the RTX remix functionality and results in a completely broken game. Someone in this [reddit post](https://www.reddit.com/r/IntelArc/comments/105o5za/portal_rtx_now_launches_in_driver_4032/) apparently had it working previously and suggested using `-window` in the launch arguments, however for me the behavior of the game remained the same. I've attached the game's `hl2_d3d9.log` here, although as far as I can tell everything it logged is just verbose information with a few warnings.
 
[hl2_d3d9.log](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11631594/hl2_d3d9.log)

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

N/A

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

N/A. Can't even get to the settings

**Comment by Karen-Intel** [comment] 2023-06-02 20:59
Hey @BelleNottelling thank you for your report
Yeah it had been fixed before, let me confirm the regression and of course I will be reporting this internally

Please keep the post open, I will post any update as soon as I have it

Karen

**Comment by nixcamic** [comment] 2023-06-30 16:13
Would like to point out that Portal RTX Vulkan also has lots of graphics issues, any chance of getting the DX12 version to work?

**Comment by BelleNottelling** [comment] 2023-07-07 00:12
Hello, @Karen-Intel I was wondering you had any luck replicating this?

> Would like to point out that Portal RTX Vulkan also has lots of graphics issues, any chance of getting the DX12 version to work?

Portal RTX does not have a DX12 version and is Vulkan only (using NVIDIA's modified version of DXVK). I assume you are getting confused because the game can be launched with a `-vulkan` option which is graphically broken because it's no long using RTX Remix.

**Comment by Karen-Intel** [comment] 2023-07-07 14:49
@BelleNottelling yes I did, it has been reported and still under development.

I will ask for updates and get back here when I have news :)

K

**Comment by BelleNottelling** [comment] 2023-07-07 22:14
> @BelleNottelling yes I did, it has been reported and still under development.
> 
> I will ask for updates and get back here when I have news :)
> 
> K

Thanks!

**Comment by Karen-Intel** [comment] 2023-07-10 17:54
Hey @BelleNottelling update on this issue

After being analyzed for our development team, the fix must be implemented by the software vendor. 
The issue is related directly to the game being done for NV but there is no current compatibility for AMD and Intel, as the issue is present on both.

The best would be to submit the issue directly to NVIDIA Lightspeed studios and request for game compatibility for AMD and Intel's HW or add the clarification that the game should be ran only with NVIDIA GPUs. :(

Karen

**Comment by BelleNottelling** [comment] 2023-07-10 20:57
> AMD and Intel, as the issue is present on both.

Really? It at least previously used to work on both RDNA2 and RDNA3 GPUs:
https://www.youtube.com/watch?v=BrAnoDKTQAQ
https://youtu.be/CZ6YVyGUaHk?t=242

In the time since those videos were recorded, the game got one patch which bumped the version number from 1.05 to 1.06 and had exactly two changes listed, and none of the comments on this update say anything about it breaking compatibility with AMD  cards:
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/17304943/d7f8f525-1768-43f8-9fe6-1bbbf67306aa)

**Comment by Karen-Intel** [comment] 2023-07-10 21:15
@BelleNottelling yeah, I'm actually in process of getting a RDN card to verify the issue myself but that's the info we got straight from the dev team :(, in the meantime there's not much I can do, apologies in advance

Karen

**Comment by BelleNottelling** [comment] 2023-07-11 03:40
Thanks, @Karen-Intel 
I'll wait to see what you find

**Comment by Karen-Intel** [comment] 2023-07-12 16:39
Hey @BelleNottelling thank you for your patience

We could only get our hands on an AMD system with iGPU (We also have an ARC in that one, which is not even plugged and disabled in the OS) and the game crashes just the same. [Have a look
](https://www.youtube.com/watch?v=kSa_5l-FaXI). 

And as it used to work before, maybe something broke but we need Lightspeed studios to help us with this 
Would it be okay to close this thread now? Thank you :)

Karen

**Comment by BelleNottelling** [comment] 2023-07-12 23:25
> Would it be okay to close this thread now?

No, actually that would not be okay. I just had my friend test the game on his RX 6900 XT (RDNA2). He tested it with the latest game patch and the most up-to-date AMD drivers for his GPU ([23.7.1](https://www.amd.com/en/support/kb/release-notes/rn-rad-win-23-7-1)) and the game works. He can get in-game without it crashing. The performance isn't good, but that's to be expected because this game uses path-tracing.
Here's a picture he sent me of it working:
https://cdn.discordapp.com/attachments/1083825459466354700/1128826479178960946/IMG_4208.jpg

Furthermore, the iGPU crash that you got is *nothing* like the crash I am seeing on my A770. On the A770, the game opens to a blank window, goes unresponsive, and then crashes. It does not display the intro logos or make any attempt to load the main menu of the game. I suspect that the iGPU crashed because it is *significantly* below the minimum requirements for Portal RTX and the menu of the game actually does render the background using RT.

**Comment by Karen-Intel** [comment] 2023-07-13 00:02
Hey @BelleNottelling that is just fine. 
Help, could your friend send you a video of the game working?
I'm actually waiting for a RDN card to add it to my lab machine, which I might get this week or by the beginning of next week
I'm up to perform some regressions and provide evidence so the issue can be pursued, so anything you can get for me would be wonderful Looking forward to hear from you soon!

Karen

**Comment by BelleNottelling** [comment] 2023-07-13 03:23
Hi, @Karen-Intel 
After much thought, I've purchased an RX 6950 XT and I will be selling my A770 when that arrives.
Once I have the new card installed, I can give you the video evidence that Portal RTX does in fact work on RDNA2 and RDNA3 GPUs, but I will be unable to do testing for the A770.

Thank you

**Comment by nixcamic** [comment] 2023-07-13 03:28
I am willing to keep testing on my A750.

**Comment by Karen-Intel** [comment] 2023-07-13 16:01
@BelleNottelling understood. Thank you for the heads up, I'll appreciate if you can share your evidence and thank you for all the issues you have submitted. Your efforts helped us have a better product :)
@nixcamic I will definitely tag you once I need anyone to test driver updates in this thread, appreciate your availability :)

Talk to you all soon

Karen

**Comment by anon-apple** [comment] 2023-07-15 00:07
I looked into why Portal RTX wasn't working as RTX Remix (now at least) does work on Intel GPUs, but of course Portal RTX is using an older build of Remix and this ends up being the problem with it.

To get Remix to work properly on Intel we did 2 changes, the first one works around a shader compilation bug which causes rendering to not work properly (seen here: https://github.com/NVIDIAGameWorks/dxvk-remix/commit/82851a9e7feb7a562661bbe7456bf288b0fefeed, and the associated driver bug here: https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/318). 

The bigger issue though causing the actual crash is I think the second issue we fixed, that being the driver's inability to handle the presence of SPIR-V ray tracing pipeline shaders using `SPV_NV_shader_invocation_reorder` (haven't confirmed this yet or filed a driver bug but this is my suspicion). This might be more of a valid issue on Remix's side as we shouldn't have been compiling shader permutations using this extension when the more general extension `VK_NV_ray_tracing_invocation_reorder` isn't supported, and Remix was updated a bit ago to take this into account (see: https://github.com/NVIDIAGameWorks/dxvk-remix/commit/6311439a6a749bdff796c96c4b09a5e87f5d8c55). AMD's drivers do seem to handle this more gracefully however rather than simply crashing which is likely why Portal RTX does work on AMD cards, so it may also be partially a driver bug as the driver shouldn't ever really crash like this regardless of what sort of data is given to it.

Since Portal RTX lacks these fixes on the Remix side it is more up to the driver for now, though we may be able to apply a patch with these fixes or update Portal RTX to a newer version of Remix at some point which would in theory fix/work around these problems.

Hopefully this provides some more insight on the issues.

**Comment by BelleNottelling** [comment] 2023-07-19 23:32
Hi, @Karen-Intel 
As I said I would, here is a recording of Portal RTX on my 6950 XT. As expected, the game launches without issue and lets me go in-game. The performance isn't especially good, but that is also to be expected given how intensive the game is and how it can even struggle on NVIDIA hardware without the use of DLSS.
https://www.youtube.com/watch?v=PgYV09HmCzU&feature=youtu.be

And confirmation that I have an AMD GPU installed:
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/17304943/142c1e52-adb0-4806-9a91-6ee7a8ef9330)

**Comment by Karen-Intel** [comment] 2023-07-20 00:38
Hey @BelleNottelling thank you for your evidences. @anon-apple thank you as well for sharing the whole reason why it is actually not working :) I will take this info back to the dev team.

We would ofc appreciate the implementation of the patch on Lightspeed's side but with this I'm sure I will make some noise internally (again) 

Karen

**Comment by BelleNottelling** [comment] 2023-07-20 01:53
> I'm sure I will make some noise internally (again)

Wishing you luck with that

**Comment by Karen-Intel** [comment] 2023-07-21 16:18
> > I'm sure I will make some noise internally (again)
> 
> Wishing you luck with that

Haha as making noise I'm referring to making some inquiries internally to analyze this case.

@anon-apple so if I got it correctly, you do work on the development team for this game, right?

**Comment by anon-apple** [comment] 2023-07-21 17:42
> @anon-apple so if I got it correctly, you do work on the development team for this game, right?

Yes I work at NVIDIA on Remix.

Also worth noting now that Portal Prelude RTX is out it does not work on Intel either sadly (couldn't mention this before since it was unreleased as of that previous comment I made). This is not because of the aforementioned issues though as it is using an up to date version of Remix which has those workarounds/fixes. Instead this is due to a new issue where the Intel shader compiler seems to miscompile our RTX IO fallback decompression compute shaders (that or it's some sort of UB in the shader being only seen on Intel, haven't figured it out yet). We're planning on making a patch to fix this though by having it fall back to a rather slow CPU decompression path just so it works until the issue with that shader can be figured out.

**Comment by Karen-Intel** [comment] 2023-07-21 17:45
> > @anon-apple so if I got it correctly, you do work on the development team for this game, right?
> 
> Yes I work at NVIDIA on Remix.
> 
> Also worth noting now that Portal Prelude RTX is out it does not work on Intel either sadly (couldn't mention this before since it was unreleased as of that previous comment I made). This is not because of the aforementioned issues though as it is using an up to date version of Remix which has those workarounds/fixes. Instead this is due to a new issue where the Intel shader compiler seems to miscompile our RTX IO fallback decompression compute shaders (that or it's some sort of UB in the shader being only seen on Intel, haven't figured it out yet). We're planning on making a patch to fix this though by having it fall back to a rather slow CPU decompression path just so it works until the issue with that shader can be figured out.

Okay then I think we can move this conversation to official channels. Can you email me? My email is on my profile.

Thank you :)

Karen

**Comment by nixcamic** [comment] 2023-07-27 21:32
I know this has moved to official channels now but could yall make sure to drop us a note in here when things change?

**Comment by Karen-Intel** [comment] 2023-08-01 23:13
Hey @nixcamic and all
Yes! Our engineering team is already collaborating with @anon-apple so good things are in the works
Of course when we have something you guys can try we will let you know here :)

Karen

**Comment by Arturo-Intel** [comment] 2023-09-15 00:47
Hello all!
Please give a try with the latest driver [101.4824](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)
In my end the crash is no happening

--r2

**Comment by Karen-Intel** [comment] 2023-09-19 19:24
Hi all! Like Arturo mentioned, this issue was fixed w/driver v/4284
@IGCIT could you help us close this one? TY

Karen

**Closed** 2023-09-19 21:45 UTC
Labels: Info: Replicated, Type: Application Crash
