### ISSUE TITLE
Oculus VR Support

### ISSUE THREAD

**Issue by shaqaruden** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#269] opened 2023-03-17 12:27 UTC
### Application [Required]

Oculus

### Processor / Processor Number [Required]

Any

### Graphic Card [Required]

Arc 7xx

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

Need support Oculus VR this includesa Quest Link/Air link support. Currently when opening the Oculus app, a message is shown stating that the graphics card is not supported. 

I believe Direct Display is required for this?

**Comment by IGCIT** [comment] 2023-03-17 14:09
hi,

this is a duplicate of #256

please see https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/256#issuecomment-1448539986

**Closed by IGCIT** 2023-03-17 14:09 UTC
Labels: Type: Feature Request
