### ISSUE TITLE
halo infinite graphics rough

### ISSUE THREAD

**Issue by papandbuddyg** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#796] opened 2024-06-12 20:32 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Halo infinite

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

ryzen 5 3600

### Graphic Card [Required]

Intel Arc A580

### GPU Driver Version [Required]

31.0.101.5534

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[system 2.txt](https://github.com/user-attachments/files/15810624/system.2.txt)

### Description and steps to reproduce [Required]

![halo](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/107985226/0f1bbb7e-4a89-4478-9307-2ee7dc4947f4)
the game looks low polly 

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

2560 x 1440p

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

high preset with rt on high

**Comment by rmorera-intel** [comment] 2024-06-13 20:24
Hi @papandbuddyg I'll go ahead and reproduce this issue. Is the low polygon/texture issue occurring only on specific sections of the game or is more of a general occurrence? Any tip you can give me to see the issue would help me a lot.

**Comment by papandbuddyg** [comment] 2024-06-14 00:09
it seemed like more when i started a big team battle match it was like extremely rough @rmorera-intel

**Comment by rmorera-intel** [comment] 2024-06-14 00:15
Thanks! Does it happen in any map? 
One final question: can you confirm if you also see this bug in Single-Player campaign? as far as I recall only MP has Ray-Tracing option so this can be a clue.

**Comment by papandbuddyg** [comment] 2024-06-14 00:17
from what i found it happened with any map but i dont have single player purchased on the steam version so i have 0 way of knowing if it happens in single player unless i install the xbox version @rmorera-intel

**Comment by rmorera-intel** [comment] 2024-06-25 23:57
@papandbuddyg I was able to reproduce this issue and it has been promoted to our driver debug team - Bug ID 14022699963.
Sorry it took me a bit longer to reply... I didn't owned an A580 GPU so I had to order one.

As soon as there is an update I'll update this thread.

**Comment by papandbuddyg** [comment] 2024-06-26 00:22
ty for the help @rmorera-intel

**Comment by rmorera-intel** [comment] 2024-09-12 04:05
@papandbuddyg It's been a while since my last update. 
I just want to let you know that we have marked this as a known issue. There is no ETA nor we can't commit to a fix anytime soon though. 

Please watch [this article](https://www.intel.com/content/www/us/en/support/articles/000099232/graphics.html) on our website for any possible changes to this situation.

I'll close this bug report since further updates will be provided through the official support page mentioned above.

**Closed by rmorera-intel** 2024-09-12 04:05 UTC
Labels: Info: Replicated, Type: Graphical Glitches
