### ISSUE TITLE
The Ascent: Crash in Title Screen/ DX12 Graphical Issues

### ISSUE THREAD

**Issue by Saracchini** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#75] opened 2021-08-11 18:32 UTC
#### Checklist [README]

- [x] Device is not undervolted nor overclocked.
- [x] Device is using the [latest drivers](https://downloadcenter.intel.com/download/30381/Graphiques-Intel-Pilotes-DCH-Windows-10).
- [x] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Required]

---
#### Game Platform [Required]
- [x] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Other

---
#### Processor / Processor Number [Required]

Intel i7 1165g 
---
#### GPU Driver Version [Required]
- [x] 30.0.100.9805 (*latest*)
- [x] 30.0.100.9684
- [x] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

---
#### Rendering API [Required]
- [ ] Vulkan
- [ ] OpenGL
- [x] DirectX12
- [x] DirectX11
- [ ] DirectX10
- [ ] DirectX9

---
#### Windows Build Number [Required]
- [ ] Windows 11 (*Insider Preview*)
- [x] Windows 10 21H1 (*May 2021 Update*)
- [x] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (*Please specify your build number*)

---
#### Description and steps to reproduce [Required]

1. Start the game
2. Game engine crashes in intro screen

One can get into the Lobby menu and  in-game if you press Enter repeatedly (very fast) so the intro screen don't load. Game runs normally then.
If one forces Directx 12 mode (add "-dx12" in command-line), the Title Screen loads, but it is very laggy. Crashes when entering in the game.

This was verified with latest 3 stable driver versions.
---
#### Device / Platform [Optional][Recommended]

GPD Win3 i7 1165g . Stock TDP (25w-28w)

---
#### Game Settings [Optional][Recommended]

![Capture](https://user-images.githubusercontent.com/18572281/129083784-67b397d1-decb-4f6c-94ea-1450d95106ca.PNG)

---
#### Save game (*if possible, could help solve the issue faster*) [Optional]

---
#### Windows mini dump (*small memory dump*) (*if available*) [Optional][Recommended]

---

**Comment by RSaracchini** [comment] 2021-08-15 11:31
If you set the unreal engine (through command-line) to use all threads or only one thread, you can actually navigate int he title screen less frenetically in order to get in game. You cannot stay for longer than a couple of seconds in the title screen (it crashes after a while), but you can at least go to single-player and then new game or resume.  It will not crash in DirectX12 mode, but it will be VERY sttutery.
The performance in game is rather acceptable in Directx11( and I'm running with 15-20W). It is not in DirectX12 (graphic glitches, low frame rate)

**Comment by BreakPoints** [comment] 2021-08-17 09:16
I believe this is the shader pre-caching that was added in the later patches which happens on the menu. This causes the game to focus mostly on creating shaders to avoid stutter in-game and makes the menu pause a lot, this happens also on my RTX 2080 just not to the same degree.

I found that on the 1165G7 the menu pauses and stuttering lasts a very long time and has the chance to crash but does not always and eventually the menu returns to 60FPS once the shaders are compiled and cached.

This game has other issues on Intel Xe, though

**Comment by Saracchini** [comment] 2021-08-17 09:20
Yes, the crash is always D3D device lost. I'll experiment and let it running when it does not crash and see how it does. I saw the game once running out of GPU memory in the city hub probably doing that too. 
In DirectX12 mode, I notice that that there some visual glitches that definitely do not occur in DirectX11 mode.

**Comment by Saracchini** [comment] 2021-08-22 15:24
Crash issue persists in Beta 9862 in DirectX11. Tested and crash happens consistently. It does not happen in DirectX12, but performance is too low to be considered "playable": Consistent and Regular stuttering, and it is not the "loading assets" stutter it normally has.  In comparison performance with Low/Medium settings in DirectX11 is actually great.

**Comment by Saracchini** [comment] 2021-08-22 19:12
With the current version of the game, one can play as follows:

 - add the "-NOTEXTURESTREAMING" parameter to the launch command options
 - That makes the Title screen to not lag as much
 - You have few seconds to start a new game (single player Resume only start by luck, but you can start a Couch Coop to bypass this, or start a Single Player new game ). The crash STILL will happen after few seconds, if you dont start a Couch-Coop or Online Coop lobby.
- It does run well then with low settings.

**Comment by Saracchini** [comment] 2021-08-28 11:59
Workaround around the Title Screen crash.
By Setting the TDR time for a value above the default in Windows, allows the game to pre-compile the shaders without the engine crashing. 
I followed these instructions (https://docs.microsoft.com/en-us/windows-hardware/drivers/display/tdr-registry-keys) and set TDR for 60 seconds, and waited the game to pre-compile all shaders. The Unreal Engine did not crashed, and the game runs normally. 

To whom doesn't want go to the site. You should set the following keys in registry as adminstrator and then reboot your machine:

HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\GraphicsDrivers
Value: TdrDelay
Type: DWORD
ValueData: 60 (decimal)

HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\GraphicsDrivers
Value: TdrDdiDelay
Type: DWORD
ValueData: 60 (decimal)

**Comment by Valkirie** [comment] 2021-08-28 12:35
Brilliant. We should recommend this as a mandatory modification for any Intel based devices. Ended-up using the same workaround for It Takes Two and fixed crash issues (still would suffer from disconnection because of too long hanging time).

**Comment by Saracchini** [comment] 2021-08-28 18:24
After letting it compile all shaders, you can actually run it with quite nice performance and little sttuter in DX12. 
In order to run in DX12 you must NOT run with "-NOTEXTURESTREAMING" launch parameter or you will run out of video memory. Launch with no command line parameters in DX12 mode after compiling shaders. Often it waits for a while with black screen but then it opens. Gameplay is super-smooth.

On additional note, sometimes you have the glitches I saw in MechWarrior5 (blank screen, heavy tinting). If this happens, go back to the title screen and open the game again. 

Played for solid 2 hours with 15W with low settings and 100% resolution scale. Performance is even better than DX11.

**Comment by Saracchini** [comment] 2021-09-11 10:22
Tested with 9864 version. Title screen in DX12 now do not take some time to start after compiling shaders, which means the game starts immediately. Visual glitches still occur (same issue as MechWarrior 5), but in lesser scale. Crashes less often too.

**Comment by KaeAlSa** [comment] 2021-10-30 02:51
I don't have any of these problems on 9955, but I've also got the texture detail set to low. Resolution scale set to 95. Display at 1920x1200 Fullscreen vsync off. I'm on an 1195.

**Comment by Saracchini** [comment] 2021-10-30 07:55
> I don't have any of these problems on 9955, but I've also got the texture detail set to low. Resolution scale set to 95. Display at 1920x1200 Fullscreen vsync off. I'm on an 1195.
> 
> I do have some small stutters when getting into new areas where it's loading in new textures but it's very playable.

Which render are you using ? There are no graphic issues in DX11 (which is the default). That is a DX12 issue only.

**Comment by KaeAlSa** [comment] 2021-10-30 14:31
Yes. DX12.

![Screenshot (12)](https://user-images.githubusercontent.com/92998658/139537312-23e9403e-6671-42b3-89dd-2ab6e025cc0b.png)

**Comment by KaeAlSa** [comment] 2021-10-30 15:02
https://www.reddit.com/r/OneXPlayer/comments/qj37eh/the_ascent_running_dx12/?utm_medium=android_app&utm_source=share

**Comment by Saracchini** [comment] 2021-10-30 15:55
Just uploaded a video illustrating the issue.
Just to be sure. I did a clean driver install (using Intel instructions) and cleaned the Direct X driver cache. The game does start normally and you can play a while without issues. You can trigger it by doing as I do in the video or by switching levels taking the elevator. It sometimes also happens when you go back to the title screen,

https://vimeo.com/640702992

**Comment by KaeAlSa** [comment] 2021-10-30 16:12
Yeah I haven't had that happen on my onexplayer. I'm not that far in the game but I have taken the elevator and changed the scale and gone back to the title screen.

**Comment by Saracchini** [comment] 2021-10-30 16:21
In previous drivers DX12 was much worse. In current versions it usually happens only in certain scene switchings.
For instance, I did not observed this issue in the intro part of the game (going to from-to DeepStink to Warrens rarely triggers it). Later in the game, going to the upper levels, it is more common. That problem do not happens until you switch certain scenes. The worst one is the top level.

**Comment by BreakPoints** [comment] 2021-10-31 02:25
Certain effects in the game also trigger these issues, especially one enemy type where every time they attack the screen has a high chance to swap to the coloured overlays blinding you

**Comment by KaeAlSa** [comment] 2021-10-31 03:09
I'm still pretty early in the game. If you want to send me a save file at the end of the game I can test it if you'd like. I just have not seen those issues in my about 5.5 hours on it.

**Comment by Saracchini** [comment] 2021-10-31 08:56
@KaeAlSa . I can send you my save. But the video I linked  showed how you can trigger the glitch at will at any section of the game. You are running which Windows (11 ? 10 21H1 ? something else ?)  and game version (Steam, Xbox Game Pass) in your device ?

**Comment by Saracchini** [comment] 2021-11-11 17:46
Graphic Issues persist with latest 1069 driver.

**Comment by KaeAlSa** [comment] 2021-11-13 05:25
I'm still not seeing them on my OXP. I changed my resolution scaler down all the way and up all the way and several other spots in-between. Besides some minor frame drops when I first get out of the menu. And I'm on 1069 now but it was the same for me on the last drivers. 

Sorry, I didn't see your questions when you originally posted your last response @Saracchini .

I'm on W11 home 21H2 Steam version. Stock TDP.

**Comment by Saracchini** [comment] 2021-11-13 09:37
@KaeAlSa . Which version are you running ? Game pass or Steam ?

**Comment by KaeAlSa** [comment] 2021-11-13 14:50
@Saracchini Steam. Latest updated version.

**Comment by Saracchini** [comment] 2021-11-14 17:21
Which means we are running exactly the same version. The difference is in the OS (I'm in Win10 , latest version 21H2, I think...). Other user from the Win3 discord also reproduced the same issue with DX12.  I'll give a look if disabling all the GPD software, in order to check if they could be the reason (kind of doubt but doest hurt to try). 
Very strange because as far I know the OXP and Win3 are almost the same SOC.

**Comment by Saracchini** [comment] 2021-11-17 17:08
Graphic Issues persists with latest 1121 driver.

**Comment by KaeAlSa** [comment] 2021-11-17 18:55
@Saracchini I asked someone else to test on a OneXPlayer and they were not able to get the graphical glitches.

**Comment by Saracchini** [comment] 2021-11-18 09:31
There are some differences with the gamepass version (some people mentioning ray-tracing, DLSS, and other Dx12-only features  not working) and the Steam one.
It is very strange that issue is happening in GPD Win3 devices but not OneXPlayer. My device is stock as it can be (replaced SSD and cloned original install).

**Comment by BreakPoints** [comment] 2021-11-19 20:30
I still get the issue on my OneXPlayer on the latest drivers and game version

**Comment by estebanr863** [comment] 2021-11-22 18:38
Hi all,

We were able to reproduce both issues (graphical corruption and crash) and they have now been moved to our driver development team. Please do note that it might take from 3 to 6 months for a possible fix to be included in a driver release.

**Comment by Saracchini** [comment] 2021-11-24 09:54
I decided to do the same test @estebanr863 requested me for [Mechwarrior5 issue](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/74#issuecomment-977708660). A very similar behavior happens, so I'm reporting here.

When switching between screen modes with ALT+ENTER, the issue can be  gone or a  different glitched effect happens, as if switching resolution scales. Quite often it switches from a good state to a glitched one and vice-versa.

**Comment by Saracchini** [comment] 2022-03-09 09:05
Issue persists with 1404 driver.

**Comment by Saracchini** [comment] 2022-05-26 12:53
Issue persists with 1994 driver.

**Comment by estebanr863** [comment] 2022-07-22 15:59
Hi @Saracchini,

Our driver development team is experiencing a high volume of requests for fixes on game issues. And since we have limited resources, this means that fixes for issues on games outside of our top games list (we maintain an internal list of top games, considering the most played, recently released, etc.) will need to be put on hold. The fix for this issue falls into this category, so we currently cannot commit to target date for this fix to be released. I’ll update you once the development of a fix for this issue is resumed.

**Comment by EstebanIntel** [comment] 2022-10-27 00:26
Hi @Saracchini,

A possible fix for this issue is included with our latest driver version [31.0.101.3790](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html). Can you please install this version and test it?

**Comment by EstebanIntel** [comment] 2022-11-16 23:37
@Saracchini, separating this thread on the 2 issues:

**Crash on Launch Issue**: This is fixed on driver [31.0.101.3790](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html). I tested this in multiple systems with the i7-1165G7 (performed a clean driver install on all) and the game is not crashing.

**Corruption Issue**: This issue is still present on the latest driver. However, due to the high volume of issues our development team is working on, we have been force to prioritize some issue over others. So the development for a fix for this issue has been put on hold indefinitely.

**Comment by Saracchini** [comment] 2023-03-01 12:47
Issue still persists on 31.0.101.4146.

**Closed** 2023-08-31 17:43 UTC
Labels: Info: Replicated, Type: Application Crash, Info: Won't fix
