### ISSUE TITLE
The last of us graphical anomalies in downtown area

### ISSUE THREAD

**Issue by Anoniemer** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#701] opened 2024-02-06 14:33 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

The Last of Us

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5 5600

### Graphic Card [Required]

Arc A380, Arc A750 and A770 16GB

### GPU Driver Version [Required]

31.0.101.5186

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14181616/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Only noticed it in down town area. More noticable on higher settings and FSR on. Happens with and without overclock on all my arc cards.

Video: https://www.youtube.com/watch?v=LH9AmyRIQR0

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Very low, FSR on quality. minimal issues, Medium setting more noticable. Think its something with the effects settings (higher setting more noticable.

**Comment by Gabriela-Intel** [comment] 2024-02-06 19:38
Hi @Anoniemer! Is it possible for you to provide the save file for the downtown area so we can take a look at this?

It should be found here:
`C:/Users/{UserProfile}/Saved Games/The Last of Us Part I/users/{SteamAccountId}/savedata/
`

**Comment by Anoniemer** [comment] 2024-02-06 20:23
[savedata.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14185683/savedata.zip)

**Comment by Gabriela-Intel** [comment] 2024-02-07 00:33
Thanks! Yep, I can confirm that I'm seeing the same thing on my Arc Graphics system. I don't see anything abnormal when I try it a with an Nvidia card. 

I'll get back to you tomorrow with a bug id for this issue.

**Comment by Gabriela-Intel** [comment] 2024-02-07 22:20
Hi again @Anoniemer I did some digging and turns out there's already a bug filed internally for this. :)

The bug id # is 15015215457 . The team is looking into it. I'll post again here once we have an update on the status of the issue.

Thanks for reporting the issue :)

**Comment by Gabriela-Intel** [comment] 2024-08-19 17:31
Hi again @Anoniemer. Thanks for your patience!

This should be fixed with the driver we released this past Friday, [101.5971](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html?). Can you please install the driver and let me know your results?

Thanks :)

**Comment by Gabriela-Intel** [comment] 2024-09-03 16:44
@Anoniemer have you had the chance to test this out?

**Closed** 2024-10-01 17:42 UTC
Labels: Info: Replicated, Type: Graphical Glitches

**Comment by Lolihunter1337** [comment] 2025-04-08 14:32
hey sorry @Gabriela-Intel but im on the latest Driver 32.0.101.6732 on the B580 and i seem to have graphical issues. 

![Image](https://github.com/user-attachments/assets/022c49eb-f2b4-4cdc-9b6d-fc7f904a8bc4)

**Comment by Lolihunter1337** [comment] 2025-04-08 14:38
if you would like me to open a new issue let me know.

**Comment by Gabriela-Intel** [comment] 2025-04-08 16:57
Yes, would you mind opening a new case? Different types of corruption can be caused by different issues. Thank you!
