### ISSUE TITLE
ArcControl, system missing VRR option on AOC 24G2U5/BK

### ISSUE THREAD

**Issue by J0dla** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#381] opened 2023-07-05 19:00 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Arc Control

### Processor / Processor Number [Required]

5700G

### Graphic Card [Required]

Intel A380

### GPU Driver Version [Required]

- [X] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11960918/igcit_ssu.txt)

### Description and steps to reproduce [Required]

No VRR option using DP,HDMI. FreeSync is working fine.
 Model: AOC 24G2U5/BK (Reported in system as AOC 24G2W1G5 and thats normal for AOC i have another model that also has different device/model name but VRR is working on it, it has FreeSyncPremium Pro)
No VRR option in windows -> display -> graphics -> default 
![missing_vrr](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/17433864/565e6834-1e11-4bf7-bcdb-d9f0725a4fac)

Found similiar thread with same problem but another model and closed
https://community.intel.com/t5/Intel-ARC-Graphics/No-VRR-Adaptive-Sync-Option/m-p/1492799

**Comment by Karen-Intel** [comment] 2023-07-05 22:42
Hey @J0dla thank you for your report!

Got it, allow me to do some testing and I will get back here if I have questions or could repro.

Talk to you soon

Karen

**Comment by SopaDeMacaco-UmaDelicia** [comment] 2023-07-06 01:16
Looks like AOC related issue, I have the same problem on Windows on my 24G2U/BK. There are multiple AOC related threads. 
https://community.intel.com/t5/Intel-ARC-Graphics/No-VRR-Adaptive-Sync-Option/m-p/1495869
https://community.intel.com/t5/Intel-ARC-Graphics/Adaptive-Sync-options-cannot-be-changed/m-p/1469431

**Comment by SopaDeMacaco-UmaDelicia** [comment] 2023-08-01 00:42
Is there any news? Kinda frustrating to not be able to use FreeSync. It really makes your experience smooth.

**Comment by Karen-Intel** [comment] 2023-08-01 00:52
Hey @J0dla @SopaDeMacaco-UmaDelicia as the threads you posted state, the issue is in development stage
We expect to have news about a fix soon :) Once I have confirmation about a release where you can test it I will let you know

Karen

**Comment by Karen-Intel** [comment] 2023-10-09 17:53
Hi guys, we have recent confirmation in another thread (#460) that this issue has been fixed already w/driver v.4885

Can someone else confirm in this thread? TY

Karen

**Comment by SopaDeMacaco-UmaDelicia** [comment] 2023-10-09 19:53
@Karen-Intel 24G2U/BK, can confirm VRR can be turned on and does actually work. 👍

**Comment by Karen-Intel** [comment] 2023-10-09 23:44
@IGCIT can you close this one please? Fix has been confirmed w/driver v.4885

Thanks

Karen

**Closed** 2023-10-10 12:29 UTC
Labels: Info: Replicated, Type: Arc Control
