### ISSUE TITLE
Arc Control overlay settings are not saved when rebooting

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#345] opened 2023-06-17 17:15 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Arc Control

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 17.06.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11779632/Intel.SSU.17.06.2023.txt)

### Description and steps to reproduce [Required]

Change something in the Arc Control overlay, and reboot

### Device / Platform

ASUS Prime Z790 WiFi D4

**Comment by IGCIT** [comment] 2023-06-17 19:36
duplicate of #336 , please share your findings in that issue

thanks

**Closed by IGCIT** 2023-06-17 19:36 UTC
Labels: Info: Needs Replication, Type: Arc Control
