### ISSUE TITLE
Yakuza 0 crashing on cutscenes

### ISSUE THREAD

**Issue by k-tronix** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#11] opened 2021-01-09 08:38 UTC
#### Game _[Required]_
Yakuza 0

---
#### CPU _[Required]_
Intel I5-1035G7

---
#### GPU Driver Version _[Required]_
27.20.100.9126

---
#### Rendering API _[Required]_

**API** _[DirectX, OpenGL, Vulkan]_: DirectX
**API Version** _(example DirectX 12)_: DirectX 11

---
#### Windows Build Number _[Required]_
Windows 10 v2004
OS Build 10941.685

---
#### Description _[Required]_
Game crashes on cutscenes randomly

---
#### Steps To Reproduce _[Required]_
Playing the game till it runs into cutscenes. However crashes may be random. I sometimes get crashes at the opening cutscene but sometimes it runs smooth but crashes at other parts of the game.

---
#### Screenshots _[Optional]_

---
#### Notes _[Optional]_
I am not too sure if this is poor optimization and a game issue or a driver issue.

**Comment by leoben2** [comment] 2021-01-13 18:11
Will report back tomorrow if we can repro.

**Comment by kristheb** [comment] 2021-01-13 19:19
its a problem of the game engine, it happens also in yakuza 1

**Comment by leoben2** [comment] 2021-01-14 16:10
We haven't been able to reproduce this issue yet. Do you have an error message that pops up? Or is it just a crash to desktop?

**Comment by kristheb** [comment] 2021-01-14 22:17
see video i made of a typical crash when the game switches to the cutscenes 

https://share.icloud.com/photos/0a9brijUi7zzKm9zzuqBv2H2A#Wien_-_22._Bezirk_Donaustadt

**Comment by leoben2** [comment] 2021-01-21 18:37
Still no luck on reproing this, but will follow up with some new hw tests next week.

**Comment by THFourteen** [comment] 2021-01-22 21:16
I can reproduce the same issue using driver 9168.

**Comment by leoben2** [comment] 2021-01-27 20:48
we're getting this i5 part in house by EOW, hopefully will have better luck by then. Will report back.

**Comment by KingYozora** [comment] 2021-01-29 18:26
You can fix the crashing by disabling RC6 (Render Standby) on the BIOS.

**Comment by k-tronix** [comment] 2021-01-31 03:22
I can confirm that the crash on cutscenes for Yakuza 0 seems to be resolved by disabling RC6 (Render Standby) in the BIOS. As such, Intel team, may we trouble you to enable RC6 Render standby in BIOS to see if you are able to replicate this issue?

**Comment by Valkirie** [comment] 2021-01-31 06:14
> I can confirm that the crash on cutscenes for Yakuza 0 seems to be resolved by disabling RC6 (Render Standby) in the BIOS. As such, Intel team, may we trouble you to enable RC6 Render standby in BIOS to see if you are able to replicate this issue?

Nice catch! Let see if @leoben2 and team can reproduce.

**Comment by leoben2** [comment] 2021-02-03 17:25
So we tried this with and without RS, no luck in reproducing :( I'm now thinking this is very platform specific. We'll see if we can buy one of these laptops and reproduce that way.

**Comment by kristheb** [comment] 2021-02-03 17:46
its not only a gpd device issue, there are a some reports with intel GPUs on the Net. see some examples below:

Intel 620 graphics
https://www.reddit.com/r/yakuzagames/comments/l6lm5l/possible_fix_to_yakuza_0_cutscene_crashes/

Intel UHD 617 graphics
https://www.reddit.com/r/yakuzagames/comments/hy6uqt/yakuza_0_opening_cutscene_crash/

Intel HD Graphics 520
https://steamcommunity.com/app/638970/discussions/0/2242174386381136684/ -

Intel card mentioned
https://www.reddit.com/r/YakuzaZero/comments/fdz16f/yakuza_0_pc_cutscene_freeze/

Intel card mentioned
https://steamcommunity.com/app/638970/discussions/0/2656452469262058609/

**Comment by HenryQuan** [comment] 2021-10-31 04:41
I also have similar issues. The game crashes quite randomly for me. Today, I tried it again using lastest Intel XE driver and it crashes within 5 minutes of my gameplay. However, sometimes, it works for hours.

**Comment by estebanr863** [comment] 2021-11-03 23:30
HI all,

I tried to reproduce this on a i7-1165G7+16GB of RAM driver version 30.0.100.9955 without any luck. Tried several times and the cutscenes never crashed my game.

@HenryQuan can you try a driver [clean install](https://www.intel.com/content/www/us/en/support/articles/000057389/graphics.html) of driver version 30.0.100.9955 and try again? Also, please run this [tool](https://www.intel.com/content/www/us/en/support/articles/000057926/network-and-io.html) and attach the resulting file.

**Comment by HenryQuan** [comment] 2021-11-06 05:24
I have reinstalled but the issue is not fixed. The game doesn't crash during cutscenes but after it (about 10s). It seems that this is by chance and after a few cutscenes, the game will eventually crash. Maybe, it is due to a series of events but I am not sure which event triggers the crash. According to the event, it is coming from d3d11.dll.

[ssu-results.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/7489948/ssu-results.txt)
[yakuza 0 crash.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/7489949/yakuza.0.crash.txt)

**Comment by grassehh** [comment] 2021-12-31 18:18
Same issue here. Running Windows 10 with i7 9700k. 
Crashes with exception code 0xc0000005

**Comment by estebanr863** [comment] 2022-02-08 18:01
Hi @HenryQuan and @grassehh,

A possible fix for this issue was included in the recently released driver version 30.0.101.1340. Can you please preform a [clean install](https://www.intel.com/content/www/us/en/support/articles/000057389/graphics.html) of the [latest drivers](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html) and test if the issue is fixed?

**Comment by KingYozora** [comment] 2022-02-09 00:13
> Hi @HenryQuan and @grassehh,
> 
> A possible fix for this issue was included in the recently released driver version 30.0.101.1340. Can you please preform a [clean install](https://www.intel.com/content/www/us/en/support/articles/000057389/graphics.html) of the [latest drivers](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html) and test if the issue is fixed?

Played for about 40 minutes without crashing on the latest driver.

**Comment by estebanr863** [comment] 2022-02-11 21:48
Great! Thanks for testing!

@IGCIT @mva can this be closed?

**Closed** 2022-02-12 10:29 UTC
Labels: Info: Can't Replicate, Type: Application Crash

**Comment by HenryQuan** [comment] 2022-02-12 12:51
Sorry for late reply. I have also played for around 40 mins with a long cutscene and it seems fine so far.

**Comment by Toxic25I** [comment] 2023-08-07 10:23
Hey i download yakuza 0 on my Intel i3 8th and Intel uhd 620 graphic. Games is keeping crashing at chapter 1 before going dojima family house for final fight i update my graphics drives but still not working what should I do

**Comment by IGCIT** [comment] 2023-08-07 10:47
try to run the game with [dxvk](https://github.com/doitsujin/dxvk/releases)

**Comment by dzastsed** [comment] 2023-09-05 19:31
Bumping this myself as well. Cutscenes crash as well - intro scene, nishikiyama introduction or judgement cutscene, didnt try going further. My computer has an I3-8310U CPU with UHD 620 graphics. Driver version 31.0.101.2125 DCH / Win10 64 (latest at the moment). Tried with DXVK 2.2 and 2.3 as well, but game just opens to a black screen and immediately crashes. My laptop (Thinkpad L480) bios unfortunately does not have an option for toggling RC6 so cannot test that out.

**Comment by ihsanx404** [comment] 2025-01-14 10:48
I had issues with Yakuza 0 crashing during cutscenes and experiencing micro-stutters on Intel graphics. Here's how I fixed it with:

Download DXVK Version 1.6.1
Extract the downloaded archive.

Create a Configuration File
In the game folder, create a text file named dxvk.conf.
Add the following lines to the file:

dxvk.enableAsync = true
dxvk.numCompilerThreads = 4
dxvk.shaderCache = true
dxvk.shaderCacheSize = 512
dxvk.presentInterval = 1
dxvk.fpsLimit = 60

Save the file.

Launch the Game
