### ISSUE TITLE
Experiencing display glitches when playing a game (Tower of Fantasy)

### ISSUE THREAD

**Issue by SippinTeaz** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#274] opened 2023-03-23 15:02 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Tower of Fantasy

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [X] Other (please specify)

### Other game platform

Official game website

### Processor / Processor Number [Required]

11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz

### Graphic Card [Required]

Intel(R) Iris(R) Xe Graphics  

### GPU Driver Version [Required]

- [ ] 31.0.101.4148
- [X] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11052295/igcit_ssu.txt)

### Description and steps to reproduce [Required]

![fun](https://user-images.githubusercontent.com/128716649/227242917-15f838a5-4c7c-4742-8c1d-85289d9e2f18.jpg)
![ahhhh](https://user-images.githubusercontent.com/128716649/227242943-7e842c18-c049-4d73-a367-7b37a0357b38.jpg)
![wows](https://user-images.githubusercontent.com/128716649/227242973-a3869a36-9521-4424-bc84-5e4cf4d70923.jpg)

### Game graphic quality [Required]

- [ ] Low
- [X] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1366x768

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![settings](https://user-images.githubusercontent.com/128716649/227244943-0097276f-f430-4e39-82b0-e3376f7f18f0.jpg)

### Device / Platform name

Laptop

**Comment by Karen-Intel** [comment] 2023-03-27 15:58
Hey @SippinTeaz thank you for reporting your findings.
We have a new official driver, v4255, can you confirm if this behavior is still showing?
We'll do some debug on our end and get back here in case we have questions

Karen

**Comment by Karen-Intel** [comment] 2023-04-04 17:20
Hey @SippinTeaz QQs
In which part of the game do you see the display glitches? Can you send me a video?
I have passed the first part but I cannot reach Simulacra yet as I haven't completed the missions
Pls help
Thanks

Karen

**Comment by SippinTeaz** [comment] 2023-04-11 16:41
> Karen

Hello. Sorry for the late reply. Yes I've downloaded the latest graphics driver version (4255) but it's still glitching. Here's a video of some of the glitch showing (sorry for the low frame rate. My laptop can't handle screen recordings) . The glitch comes and goes for some reason. It probably has something to do with my directx having issues because if I use 11 instead of 12 it doesn't show any glitches. I'm not so sure myself but your help would be very much appreciated.

https://user-images.githubusercontent.com/128716649/231230662-7c5f7aa3-ef78-452c-87f3-487774812894.mp4

**Comment by Karen-Intel** [comment] 2023-04-20 22:34
Hey @SippinTeaz!

Thank you for sharing the vid. We were finally able to reproduce the same artifacts in an i7 Iris Xe system so we'll report them internally. 
Just FYI, a fix can take a while to be released (which takes from 3 up to 6 months, due to cadence) 
Please do not close this post and keep your drivers up to date. We'll let you know the minute we get any news

Thank you for your patience along the debug process! Have a great day :)

Karen

**Comment by Arturo-Intel** [comment] 2023-07-12 15:03
@SippinTeaz 
Our dev team is working on this, its seems that this case open a big pandora box regarding the integrated GPU driver, 
I hope we have good news soon!

Thank you for your patience
--r2

**Comment by rmorera-intel** [comment] 2024-01-18 17:24
@SippinTeaz could you please re-test this issue with our latest driver [31.0.101.5085/31.0.101.5122 (WHQL Certified)](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)?

**Comment by rmorera-intel** [comment] 2024-01-22 15:10
I'll go ahead and close this bug report for now. If the issue persists or reappears please file a new report and reference this one.

**Closed by rmorera-intel** 2024-01-22 15:10 UTC
Labels: Info: Replicated, Type: Graphical Glitches
