### ISSUE TITLE
Hitman 3 running in slow motion with newest beta driver

### ISSUE THREAD

**Issue by Rebusmind** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#58] opened 2021-05-29 06:20 UTC
#### Checklist [README]

- [X] Device is not undervolted nor overclocked.
- [X] Device is using the [latest drivers](https://downloadcenter.intel.com/download/30381/Graphiques-Intel-Pilotes-DCH-Windows-10).
- [X] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Required]
Hitman 3 (Epic Game Store) 
---
#### Processor / Processor Number [Required]
i7-1165 
---
#### GPU Driver Version [Required]
- [X] 27.20.100.9616 beta (*latest*)
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

---
#### Rendering API [Required]
- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

---
#### Windows Build Number [Required]
- [X] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)

---
#### Description and steps to reproduce [Required]

1. Open the game
2. Wait
3. It runs super slow from the beginning

---
#### Device / Platform [Optional][Recommended]

GPD Win 3

---
#### Game Settings [Optional][Recommended]

Low to medium settings (basic physics simulation, no super sampling) 
---
#### Save game (*if possible, could help solve the issue faster*) [Optional]

---

**Comment by Valkirie** [comment] 2021-05-29 06:21
Hey, was the game running better on previous drivers?

**Comment by Atnik** [comment] 2021-05-29 06:23
Yes, on the most recent official release (9466) the game runs perfectly.

**Comment by Valkirie** [comment] 2021-08-12 14:53
@Rebusmind can we close this issue ?

**Comment by Rebusmind** [comment] 2021-08-15 11:48
I don't know tbh, as I don't have the game on my Win 3 anymore.

**Comment by estebanr863** [comment] 2021-12-31 16:59
Hi @Rebusmind and @Valkirie, we can't reproduce this issue on the latest drivers 30.0.101.1191. Can we close this issue?

**Closed** 2021-12-31 17:21 UTC
Labels: Info: Needs Replication, Type: Regression
