### ISSUE TITLE
UHD 730 igfxn stopped responding with EventID 4101

### ISSUE THREAD

**Issue by GameO7er** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#154] opened 2022-08-18 09:58 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Tower of Fantasy

### Game Platform [Required]

- [ ] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [X] Other (please specify)

### Other game platform

Tower of Fantasy Game Launcher

### Processor / Processor Number [Required]

Intel i3 12100

### GPU Driver Version [Required]

- [X] 31.0.101.3222 / 31.0.101.2111 (*latest*)
- [ ] 30.0.101.3113
- [ ] 30.0.101.3109
- [ ] 30.0.101.1994
- [ ] 30.0.101.1960
- [ ] 30.0.101.1934
- [ ] 30.0.101.1660
- [ ] 30.0.101.1631
- [ ] 30.0.101.1404
- [ ] 30.0.101.1340
- [ ] 30.0.101.1191
- [ ] 30.0.101.1121
- [ ] 30.0.101.1069
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11
- [X] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/9371943/igcit_ssu.txt)
[igcit_ssu.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/9371946/igcit_ssu.zip)

### Description and steps to reproduce [Required]

I just downloaded launcher (~9MB) from official website and it will download all files (23GB) from the official servers. The game is free and it doesn't need any crack. the problem is when I start the game, after random minutes (at highest ~10-15 mins) the game will exit automatically and I checked the "Event Viewer" and the error is:

`Display driver igfxn stopped responding and has successfully recovered.
EventID: 4101`

**I think the problem is with "Shading"** because when I played with shading:off, the game was OK for about ~20 minutes but when I enabled "Shading" the game immediately quit. I repaired the game data, reinstalled VGA driver from[ Gigabyte website](https://www.gigabyte.com/Motherboard/H610M-H-DDR4-rev-12/support#support-dl-driver-vga) (I have `Gigabyte H610M Rev 1.2` ) but doesn't work so then I downloaded latest driver again from [Intel website](https://www.intel.com/content/www/us/en/products/sku/134584/intel-core-i312100-processor-12m-cache-up-to-4-30-ghz/downloads.html) but this doesn't work too. I should note that before opening this issue I checked with 1600x900 (full screen) with "**Shading:No**" and it was good for ~20 minutes and the game didn't crash/quit and the highest temperature of my sensors was 42 cel (using `CoolerMaster T200`). I also installed `Company Of Heroes 1` but I don't have problem with this and I also playing `Call Of Duty Mobile` with tencent gamebuddy and I don't have any problem with that.

Thank you so much for your helping
![ToF Game Settings 2](https://user-images.githubusercontent.com/16391794/185365601-2cd412a7-164e-445d-9360-3115a48fc216.jpg)
)

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1600x900

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

FPS: 25 with no Shading
FPS: 30 with Shading (crashed/quit)
I also applied FPS 30 and it didn't quit the game but after I enabled "Shading" immediately the game did quit.
Screen Size: 1600x900 (Full Screen)

![ToF Game Settings 2](https://user-images.githubusercontent.com/16391794/185365601-2cd412a7-164e-445d-9360-3115a48fc216.jpg)
)

### Crash dumps [Required]

the file was in `.7z` format and I couldn't upload it because GitHub doesn't let me to upload `.7z` and I added it to `.zip` file and uploaded it here.

[igcit-dumps_fead6bf2.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/9372433/igcit-dumps_fead6bf2.zip)

### Game custom logs

[Tower Of Fantasy log.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/9372459/Tower.Of.Fantasy.log.zip)

**Comment by IntelSupport-Rozilah** [comment] 2022-08-19 06:21
hi @GameO7er,

I will start verifying the case as soon as possible once our setup is ready and will get back to you, stay tuned!

**Comment by IntelSupport-Rozilah** [comment] 2022-08-29 02:05
Hi @GameO7er,

The case has been verified on our side and we are able to reproduce it with our configurations as below:
Processor:  ALD-S and TGL-U
Graphic Driver version: 31.0.101.3222/31.0.101.1660
We will be working on a fix. I want to give you a heads-up that the fix may take 3 to 6 months to be included.

**Comment by IntelSupport-Rozilah** [comment] 2022-10-25 00:37
hi @GameO7er , 
There is a new update for this issue, a fix for this issue has been included [here](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html) driver 31.0.101.3729.
could you please try this driver on your system and update the result here?

**Comment by IntelSupport-Rozilah** [comment] 2022-10-28 00:50
hi @GameO7er , 
did you have any chances to try the driver?

**Comment by IntelSupport-Rozilah** [comment] 2022-11-01 06:19
hi @GameO7er,
before we proceed to close this issue, could you try on latest [driver](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html) as confirmation?, if there is no reply we will close this issue accordingly.

**Comment by IntelSupport-Rozilah** [comment] 2022-11-04 06:57
hi @GameO7er ,
Please to inform that we are proceeding to close this case since there is no response from your side. If you require any further assistance please follow our suggestions and update your finding, then we will resume our support again. You may submit a new GitHub case if you have new questions and we are happy to assist you.

hi @IGCIT can we close this case since there are no responses?

**Closed** 2022-11-04 08:27 UTC
Labels: Info: Needs Replication, Type: Application Crash
