### ISSUE TITLE
A380 World Warz Z artifacting in DX11 + VULKAN option missing

### ISSUE THREAD

**Issue by J0dla** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#317] opened 2023-05-16 19:42 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

World War Z

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [X] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Other game platform

X470

### Processor / Processor Number [Required]

AMD Ryzen 2700

### Graphic Card [Required]

Arc A380

### GPU Driver Version [Required]

- [X] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11491178/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Go to settings and back to menu to see artifacting.
Go to settings -> F8 benchmark -> fps drops in run also textures artifacting and models slow load
Go to settings -> VULKAN option is missing

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/17433864/2273ae59-548a-4cc6-8c34-298fe949c58e

![wwz_menu](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/17433864/8a4d0005-9647-41b9-8a00-aa3238455d92)

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![wwz_settings](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/17433864/eb81aaff-cdfb-489c-9458-ade9885226cb)

**Comment by Arturo-Intel** [comment] 2023-05-17 22:09
@J0dla thank you for sharing this data

I can confirm the issue is happening in the latest driver (4369) and our drivers dev team is working on it. 
I will post here any update a get from them!

--r2

**Comment by LadyMikea** [comment] 2023-05-23 23:42
For the record you can enable Vulkan option, by adding the line:

"disableVulkanOnIntelAdapters":0

to AppData\Local\Saber\WWZ\client\storage\video.dat

This requires drivers 4255+ and working pretty well.  
Note the role of separator "," and the limiter "}" in the video.dat file ("other options":3, "disableVulkanOnIntelAdapters":0}, "other options":1}.)

**Comment by Arturo-Intel** [comment] 2023-05-24 03:40
Thanks for the info @LadyMikea

**Comment by J0dla** [comment] 2023-07-05 18:36
Small update 
4514, 4502 no change
Opened ticket on game support site, get reply that they know about issue and working on a fix

**Comment by LadyMikea** [comment] 2023-07-29 12:59
4576 (Beta) still not fixes flickering, in fact there's no difference between 4575 and 4576 (still the same amount of flickering textures.  Tokyo - Setting Sun - is a best example of bad flicker). But, since this is a beta driver...

**Comment by J0dla** [comment] 2023-07-29 13:18
@LadyMikea hmm i have different results:
From 4575 to 4576
https://youtu.be/8_CRC7j-4oE?t=96
It fixed flickering but performance wise its not bad but gpu utilisation between 50-64% shows that there is still place for imporvement, play tests give me feeling that its "playable" but sometimes not so smooth.
I tried to turn VULKAN, even with your cfg switch i cant make it work. There is high chance VULKAN will work much better than DX11 we have now.

**Comment by LadyMikea** [comment] 2023-07-29 16:20
Thanks for sharing video. That very interesting. I have an arc a750 and none of the settings does change situation (fullscreen/borderless/vsync on/off/smart sync). I even "ddu" 4576, but with no effect. Just the same flickering as was before (pre 4576). Vulkan option works only with 4255 (for some reason, any earlier or later driver doesn't expose Vulkan).

**Comment by Karen-Intel** [comment] 2023-10-17 15:53
Hi all, just leaving here the internal tracking number for the Vulkan option missing: 1809250327
Whever we have an update we will let you know

Karen

**Comment by J0dla** [comment] 2023-11-08 18:59
@Karen-Intel

After testing my EpicGamesLauncher version (wwzRetailEgs.exe) i conclude that it is not fixed using driver 4952, the Epic version exe is different than STEAM one(wwzRetail.exe).

In other hand Steam version with driver 4952 is getting better gpu utilization, near 100% depends on settings, and about 100% more fps,lows on medium compared to old test (i was using better CPU but still impressive on AMD Ryzen 2700). I am really impressed what driver team has achieved ^^

Unfortunately EGS version is not affected by this wonderful changes. Its artefacting and 4952 changes are not in, so i confirm what @LadyMikea found that EGS version is not fixed, improved.

**Comment by LadyMikea** [comment] 2023-11-14 12:12
Yes, I also can confirm version .4953 fixes problem with flickering textures (Epic version of game). Thanks Intel! :)

**Comment by ewahl-osc** [comment] 2024-01-04 01:49
As late as 5084/5122 this is still an issue.  Low utilization in DX11 (avg ~86%) is part of the issue. 

Still cannot select Vulkan as an option.  No workarounds I've found work. 

eg:
"Video":{"AdapterId":0,"GPU":"Intel(R) Arc(TM) A770 Graphics - Vulkan","disableVulkanOnIntelAdapters":0","DisableVulkanDuetoFailedInit = false"

**Comment by rmorera-intel** [comment] 2024-10-30 22:15
Hello everyone, it has been a while since our last update.
I wish I had better news but our dev team confirmed that in order to address this issue there are changes needed to the game code. Each game developer manages their own priorities and we can only influence as much from our side. 

Please report this issue directly to the game developer/support team.

I'll be closing this report now.

**Closed by rmorera-intel** 2024-10-30 22:15 UTC
Labels: Info: Replicated, Type: Bad Performance, Type: Graphical Glitches
