### ISSUE TITLE
Disco Elysium Final Cut crashes on boot

### ISSUE THREAD

**Issue by IGCIT** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#42] opened 2021-04-01 23:56 UTC
Submitter: Sam Gajewski
Game Disco Elysium Final Cut

CPU Intel Core i5 - 1035G7

GPU Driver Version 27.20.100.9316

Rendering API DX 11

Windows Build Number [Required]

Description [Required]

Steps To Reproduce [Required]

Screenshots [Optional]

Save game (if possible, could help solve the issue faster) [Optional]

Game logs (if available) [Optional] [Recommended]

Notes [Optional]

**Comment by Valkirie** [comment] 2021-04-16 07:49
@leoben2 could you give this a look ?

**Comment by Saracchini** [comment] 2021-10-18 18:04
I have this game and just tested it with 9955, Windows 10, 21H1, Steam version.
It does hang for a bit in the intro screen but the game starts normally afterwards. No crashes or issues. Could play the game normally.
Note I have the TDR fix enabled.

**Comment by estebanr863** [comment] 2021-11-02 23:59
@mva94 since both I and @Saracchini confirmed the issue is no longer happening on driver version 30.0.100.9955, can we close this issue?

**Comment by mva94** [comment] 2021-11-03 00:14
@estebanr863 done

**Closed** 2021-11-03 00:14 UTC
Labels: Type: Application Crash, Info: Anonymous issue
