### ISSUE TITLE
Need For Speed Payback Crash

### ISSUE THREAD

**Issue by hididi31** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#36] opened 2021-03-22 13:50 UTC
#### Game _[Required]_
Need for speed playback 

---
#### CPU _[Required]_
I7-1160g7

---
#### GPU Driver Version _[Required]_
Latest GPU driver

---
#### Rendering API _[Required]_

**API** _[DirectX, OpenGL, Vulkan]_:DirectX
**API Version** _(example DirectX 12)_:DirectX11

---
#### Windows Build Number _[Required]_
Latest build windows

---
#### Description _[Required]_
The games random crash after some minutes or seconds race start. 
It seems got this message GPU is disconnected
---
#### Steps To Reproduce _[Required]_

---
#### Screenshots _[Optional]_

---

**Comment by leoben2** [comment] 2021-04-01 06:03
we reproduced this, under debug.

**Comment by leoben2** [comment] 2021-04-01 06:03
please provide actual build numbers instead of 'latest'.

**Comment by hididi31** [comment] 2021-04-01 16:19
Hello I reply to you for battlefield 5 just copy my answer try to provide more détails Windows 10.0.19042 build 19042I7 1160g7 last GPU driver16gb ramOneGXproIt happens with all games using the frostbyte engine from Dice  so battlefront battlefield 1 , battlefield 5, Need for speed playback, nfs heat. The games run Fine but crash suddenlyLaunching games on OriginTell me if need more infoThanks you for your workLe 1 avr. 2021 08:03, leoben2 ***@***.***> a écrit :
we reproduced this, under debug.

**Comment by hididi31** [comment] 2021-04-01 16:20
Hello I reply to you for battlefield 5 just copy my answer try to provide more détails Windows 10.0.19042 build 19042I7 1160g7 last GPU driver16gb ramOneGXproIt happens with all games using the frostbyte engine from Dice  so battlefront battlefield 1 , battlefield 5, Need for speed playback, nfs heat. The games run Fine but crash suddenlyLaunching games on OriginTell me if need more infoThanks you for your workLe 1 avr. 2021 08:04, leoben2 ***@***.***> a écrit :
please provide actual build numbers instead of 'latest'.

**Comment by estebanr863** [comment] 2021-11-02 22:58
Hi @hididi31, can you test this using driver 30.0.100.9955?

**Comment by estebanr863** [comment] 2021-11-11 17:04
Hi @mva94, you mentioned @hididi31 has not been active in several months. Been this so, can we close this issue since it cannot be reproduced with our latest drivers?

**Closed** 2021-11-11 17:05 UTC
Labels: Info: Replicated, Type: Application Crash
