### ISSUE TITLE
Flashes of light in NFS Heat

### ISSUE THREAD

**Issue by CnF-Gris** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#674] opened 2024-01-14 11:46 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Need for Speed Heat

### Processor / Processor Number [Required]

i5-13500

### Graphic Card [Required]

Intel Arc 770 16GB

### GPU Driver Version [Required]

31.0.101.5085

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[NFS-Heat-14-01-24.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13931283/NFS-Heat-14-01-24.txt)

### Description and steps to reproduce [Required]

Just open the game and play

**Comment by IGCIT** [comment] 2024-01-14 12:32
hi,

is this the same as #307 ?

**Comment by CnF-Gris** [comment] 2024-01-14 12:54
https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/75698846/5f44e30c-0342-4eca-89f3-a16fdbbc304a

Basically, you can see flashes on the screen.

I restarted my pc and now it does not reproduce the bug, but this was the issue

**Comment by freak2fast4u** [comment] 2024-01-18 11:45
On a similar note, here's a lighting glitch under a speed limit panel, at night during rainfall : https://youtu.be/fXLQzIjuEXk
This is on A770 with 5085 drivers.

**Comment by rmorera-intel** [comment] 2024-10-31 16:33
Hello everyone, I have some good news: this issue is fixed with driver 32.0.101.6127 and newer.
Please install latest driver to date [32.0.101.6130](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html).

I tested it myself and can confirm the issue is no longer visible.
I'll proceed to close this but if you need further assistance feel free to re-open it or create a new bug report.

**Closed by rmorera-intel** 2024-10-31 16:33 UTC
Labels: Info: Needs Replication, Type: Graphical Glitches
