### ISSUE TITLE
Vrchat not displaying when in steam vr mode

### ISSUE THREAD

**Issue by Starwingyt** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#531] opened 2023-09-21 21:55 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Vrchat

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel core i5 12th gen

### Graphic Card [Required]

Intel arc a770 

### GPU Driver Version [Required]

- [X] 31.0.101.4826
- [ ] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

Nothing

### Description and steps to reproduce [Required]

![C69C8F0B-A0C1-4ACA-81FC-A847841BB754](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/145720591/321bbd58-d3ae-4a88-800a-584a18ae3d60)
How to reproduce: start vrchat in steam vr, observe

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [X] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Default settings, only in vr mode, works fine on desktop and runs other vr games perfectly

### Crash dumps [Required, if applicable]

None

**Comment by Arturo-Intel** [comment] 2023-09-22 18:45
@Starwingyt hey, unfortunately, VR support for Intel ARC is still a WIP so, for the time being, we will be marking this case as FUTURE and closing this thread.

@IGCIT can you close this case please?

**Closed** 2023-09-22 20:39 UTC
Labels: Info: Needs Replication, Type: Graphical Glitches

**Comment by BuyMyMojo** [comment] 2023-10-18 08:00
I would like to request this issue to be opened again. I understand VR is WIP but I would like to be able to see if this issue is here without updates instead of needing to run and crash to verify the issue is still present.

I have tested the issue and found it is resizable bar causing the issue, when enabled VRC with crash before the first visuals are displayed but when disabled it runs with I'd assume a mass performance dip.

VRC works perfectly outside of needing to disable Resizable-bar and I feel investigating this issue could be a big benefit to the community for other Unity based VR titles.

**Comment by BuyMyMojo** [comment] 2023-10-18 08:01
last tested on driver 31.0.101.4887.
