### ISSUE TITLE
STATE OF DECAY 2

### ISSUE THREAD

**Issue by remag1247** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#84] opened 2021-09-15 15:42 UTC
---
#### Game / Application [Required]
State of Decay 2
---
#### Game Platform [Required]
- [X] Steam
- [] Origin
- [] Microsoft Store
- [] GOG Galaxy
- [] Ubisoft Connect
- [] Battle.net
- [] Epic Games
- [] Bethesda.net
- [] Other

---
#### Processor / Processor Number [Required]
I7 1165g7 i71160g7
---
#### GPU Driver Version [Required]
- [X] 30.0.100.9864 (*latest*)
- [X] 30.0.100.9862
- [X] 30.0.100.9805
- [] 30.0.100.9684
- [] 30.0.100.9667
- [] 27.20.100.9616
- [] 27.20.100.9466
- [] 27.20.100.9316
- [] 27.20.100.9313
- [] 27.20.100.9168
- [] 27.20.100.9128

---
#### Rendering API [Required]
- [] Vulkan
- [] OpenGL
- [] DirectX12
- [ ] DirectX11
- [] DirectX10
- [] DirectX9

---
#### Windows Build Number [Required]
- [X] Windows 11 (*Insider Preview*)
- [] Windows 10 21H1 (*May 2021 Update*)
- [] Windows 10 20H2 (*October 2020 Update*)
- [] Windows 10 20H1 (*May 2020 Update*)
- [] Windows 10 19H2 (*November 2019 Update*)
- [] Windows 10 19H1 (*May 2019 Update*)
- [] Other (*Please specify your build number*)

---
Make sure you describe the issue and steps to reproduce.
-->
1. Load up the game
2. Go into the game (I joined through the campaign)
3. As your loading in and the loading screen is done, it doesn't display any graphics, just a black screen and then a crash

Note: The very first time I ever loaded into the game on this device, it loaded in just fine. The next time I try to load in I can't. I tried various steps and couldn't get anything to work.
---
Share game settings and screenshots if needed.
-->
All graphic settings are on low or off
---

**Comment by estebanr863** [comment] 2021-11-03 22:29
I just tried this on driver 30.0.100.9955 and couldn't reproduce either. Loaded the game fine several times. Can you test it with this driver version @remag1247?

**Comment by estebanr863** [comment] 2021-11-11 17:46
Hi @remag1247. Did you had a chance to test this with the latest drivers?

**Comment by estebanr863** [comment] 2021-11-18 19:05
Hi @mva94 and @IGCIT can any of you help and try this with the latest driver?

**Comment by IGCIT** [comment] 2021-11-21 20:42
unfortunately i don't own the game

**Comment by remag1247** [comment] 2021-11-22 17:51
sorry for late reply I don't pay attention to this but I will reinstall the game and try it out again on newer drivers

**Comment by remag1247** [comment] 2021-11-22 18:47
@estebanr863  I tried drivers 9955 and 1121 and both had the same issue still stuck on a loading screen that eventually turns black and freezes and then crashes.  I'm halfway through the story if that helps. Maybe u could recreate it by finding a save file that puts u somewhere in the middle of the campaign?

**Comment by estebanr863** [comment] 2021-11-22 22:33
@remag1247 can you please provide your save game so I can try to replicate the issue at the same point of the game you are at?

**Comment by estebanr863** [comment] 2021-12-07 17:50
Hi, @remag1247 can you please provide your save game so I can try to replicate the issue at the same point of the game you are at?

**Comment by remag1247** [comment] 2021-12-10 14:28
@estebanr863 https://drive.google.com/file/d/1dFERGbrUMyCT9YB-RiJ2W04avRu2NHw2/view?usp=sharing

**Comment by hoangnguyen1979** [comment] 2021-12-22 00:43
@remag1247 The file that you shared does not have the saved game data. Can you navigate to %localappdata%\StateOfDecay2 directory, zip up the Saved folder and reshared?

**Comment by remag1247** [comment] 2021-12-22 12:24
@hoangnguyen1979 https://drive.google.com/file/d/1Qfk5sq993vu7FFvDmyAtO12e7_AqCxrA/view?usp=sharing

**Comment by hoangnguyen1979** [comment] 2021-12-29 22:39
Thank you, @remag1247. 
One more favor from you, please:
Can you provide a System Report of the system where you encounter the issue?
Here is the link to the Intel SSU tool: https://www.intel.com/content/www/us/en/download/18377/25293/intel-system-support-utility-for-windows.html
Run SSU.exe. Select "Everything". Then click Scan. Save the data to the text file and attach it to the sighting or share w/ us thru the good drive.
Thanks.

**Comment by estebanr863** [comment] 2022-01-11 18:16
Hi @remag1247,

Were you able to runn the Intel SSU tool?

**Comment by remag1247** [comment] 2022-01-14 21:28
@estebanr863 @hoangnguyen1979

 https://drive.google.com/file/d/1gPmFkb4oDXfG5rj1VHwxDzkAg2-1Kmk1/view?usp=sharing

**Comment by estebanr863** [comment] 2022-02-02 21:29
Hi @remag1247,

After several attemps using different systems, we have not been able to reproduce this issue, even when using your save files. At this point our only advice would be for you to contact he manufacturer of your device for support, since it seems that the issue is specific to your device.

**Comment by IGCIT** [comment] 2022-02-08 20:16
closing this, 
@remag1247 you can still reply if you find more details or a way to reproduce on other systems

**Closed by IGCIT** 2022-02-08 20:16 UTC
Labels: Info: Needs Replication, Type: Application Crash
