### ISSUE TITLE
A770 will randomly not allow booting of games

### ISSUE THREAD

**Issue by AverageGithubBugReporter** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#227] opened 2023-01-19 03:57 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Any game, has happened with F1 2020, Battlefield V and Jedi Fallen Order

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [X] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5-12400F

### Graphic Card [Required]

Arc A770 Special Edition

### GPU Driver Version [Required]

- [X] 31.0.101.4034 (*latest*)
- [X] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10453326/igcit_ssu.txt)

### Description and steps to reproduce [Required]

System will randomly throw errors that games cannot be run because the GPU lacks the necessary feature level, images below

GPU-Z also does not recognize DirectML, Ray Tracing, or DirectCompute as features

Happened with both 4032 and 4034

There is no reliable way to reproduce I am aware of, I stepped away from my computer for a bit and it threw the error message when I attempted to boot a game

Restarting the system has fixed it both times this has happened

![image2](https://user-images.githubusercontent.com/123030628/213351339-5fc5b7cd-270f-4c5a-99d1-db6705b5a267.png)
![image](https://user-images.githubusercontent.com/123030628/213351340-462fc4ac-64dd-41eb-9f94-395557c1199f.png)

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

2560x1440p

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

N/A, error occurs with multiple games

**Comment by IntelSupport-Arun** [comment] 2023-01-19 17:14
Hi @AverageGithubBugReporter ,

May I know if the issue is intermittent? What is the failure rate?
Also, could you try to verify the integrity of the games installed on your system via Steam?

**Comment by AverageGithubBugReporter** [comment] 2023-01-19 17:39
> Hi @AverageGithubBugReporter ,
> 
> May I know if the issue is intermittent? What is the failure rate? Also, could you try to verify the integrity of the games installed on your system via Steam?

The issue is intermittent, yes, it will seemingly randomly occur for no reason at all

As mentioned, I tried several games after this error and nothing would boot up, and upon restarting the system all games worked fine

As also mentioned, this has happened twice and I've tried booting four different games when it happens, with a similar error being given for all of them

**Comment by IntelSupport-Rozilah** [comment] 2023-02-03 04:51
hi @92lucio92,
The case has been verified on our side and we are not observing the issue on our configurations as below:
Processor:  i7-12700K and Intel(R) Core i7-11700K
Graphic driver version: 31.0.101.4032.
1. do you update your system on latest window update and bios?
2. can you try on latest driver 31.0.101.4032 and let us know?

**Comment by IntelSupport-Rozilah** [comment] 2023-02-07 05:04
hi @92lucio92,
do you have any updates for us?

**Comment by 92lucio92** [comment] 2023-02-08 12:15
sorry didn't saw that you replied me there, as I wrote on my issue I think i figured out what is causing for me the problem:

> I think I found out the issue: I was able to replicate the bug after I open a "heavy" hw accelerated program (in my case, I use bluestacks a lot) Sometimes I'm getting extremely low fps on some games after I used Adobe XD (no dxdiag bug tho) but a reboot is fixing the issue.
> 
> I'm sorry but I still have to try to test with only one screen because I didn't have much time this week,



> Yes, if I don't open bluestacks or adobe xd the games will run fine.
> 
> But if, for example:
> 
> 1. Run bluestacks
> 2. Close blustacks
> 3. Try to run a game
> 4. The bug is here and:
> 
> * I get extremly low fps      OR
> * cannot launch dx11 version --> force to run dx9 (Lost Ark)      OR
> * cannot launch at all
> 
> A user log out/sys reboot fix the issue

**Comment by IntelSupport-Rozilah** [comment] 2023-02-09 06:37
Thanks @92lucio92 for the quick explanation and I will try to replicate the issue with your steps as well.
can you both @92lucio92 @AverageGithubBugReporter check the issue on latest driver?

**Comment by 92lucio92** [comment] 2023-02-09 11:53
I'm on latest 'public' driver atm, I'll try the beta one

**Comment by 92lucio92** [comment] 2023-02-09 22:06
Well I have to say well done with the new drivers! Just tried once and there is no isse (windows screenshot capture is working too!)

**Comment by IntelSupport-Rozilah** [comment] 2023-02-10 01:23
hi @92lucio92,
thanks for the quick check, since the issue was resolved on the latest driver, we will close the issue

**Comment by 92lucio92** [comment] 2023-02-10 22:53
unfortunately that was just a lucky night...I had to reopen my issue because i encountered again the same bug

**Comment by IntelSupport-Rozilah** [comment] 2023-02-13 05:34
Hi @IGCIT , Since there is no response from the customer and the issue was confirmed resolved by another customer, so please proceed to close this case.

**Closed** 2023-02-13 08:33 UTC
Labels: Info: Needs Replication, Type: Application Crash
