### ISSUE TITLE
Windows RDP crash - A device attached to the system is not functioning

### ISSUE THREAD

**Issue by nyanmisaka** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#577] opened 2023-11-03 11:01 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel(R) Arc(TM) A380 Graphics

### Processor / Processor Number [Required]

AMD Ryzen 7 5700G

### Graphic Card [Required]

Intel(R) Arc(TM) A380 Graphics + AMD Radeon(TM) Graphics

### GPU Driver Version [Required]

31.0.101.4952

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13249373/igcit_ssu.txt)

### Description and steps to reproduce [Required]

1. Prepare a **multi GPU** setup: an Intel ARC discrete GPU + AMD integrated GPU
2. Enable both iGPU and dGPU in the BIOS settings (some motherboard may disable iGPU automatically)
3. Leave **all HDMI/DP/VGA ports un-plugged** on both motherboard and ARC GPU, to make it a **headless** setup
4. Run `mstsc` Windows Remote Desktop on another PC and connect to the headless PC
5. In Windows RDP client you will see it fails at login screen and shows an error **"A device attached to the system is not functioning"** before the session is disconnected.

When I switch back the dGPU to my older nVidia card, RDP works fine.
An workaround is to have a **HDMI dummy plug** on Arc GPU.

Same issues on [reddit - "[Trouble shooting] - A380 causing RDP "crashing" issue."](https://www.reddit.com/r/IntelArc/comments/17mnkox/trouble_shooting_a380_causing_rdp_crashing_issue/)

For me, this issue is not a regression. I encountered this as early as the 39xx drivers.

![intel-arc-windows-rdp-crash](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/14953024/322cf118-a1a6-485d-b8c9-1300223eeca0)

**Comment by Karen-Intel** [comment] 2023-11-06 15:39
@nyanmisaka Ty for your report here. We'll be checking it out! Stay tuned

K

**Comment by multi-vitamin** [comment] 2023-12-04 11:50
I'm using an a770.
Something similar happens with Chrome Remote.
When I run remote, I get a screen that changes resolution and then goes to a black screen.

It happens with the monitor turned off.
I haven't checked with the monitor on.

**Comment by Gabriela-Intel** [comment] 2024-02-16 23:11
Hi @nyanmisaka I just tried to replicate the issue with the config below but I was able to remote successfully into the A380 system. Can you try again using the latest drivers?

AMD Ryzen 5 7600
Intel Arc A380 Graphics
Win 11 Pro 22631
31.0.101.3194
32 GB RAM

**Comment by nyanmisaka** [comment] 2024-02-17 12:03
> 22631

@Gabriela-Intel Thank you for your time. I've been using the latest driver release in January but the problem still persists.

Could you also test on Windows 10, there are a lot of changes between Windows 11 **22631** and Windows 10 **19045**, especially when it comes to handling multiple graphics cards.

Note that in this configuration, remote desktop may succeed the first time, but it will continue to fail after reboot.

**Comment by Gabriela-Intel** [comment] 2024-02-20 21:47
Hey again! I tried on the same config using Windows 10 22H2 and 101.5330 this time but I still can't seem to reproduce even after rebooting and remoting in multiple times.. Any other tips that might help me see the issue?

**Comment by nyanmisaka** [comment] 2024-02-20 22:12
> Hey again! I tried on the same config using Windows 10 22H2 and 101.5330 this time but I still can't seem to reproduce even after rebooting and remoting in multiple times.. Any other tips that might help me see the issue?

The remaining difference between our setups might be, the default graphics card settings in the BIOS, IGP vs PEG (PCI Express Graphics/Integrated Graphics). My setting is PEG. And no monitor is connected to the motherboard and graphics card of this host.

**Comment by pcslide** [comment] 2024-02-21 04:51
> Hey again! I tried on the same config using Windows 10 22H2 and 101.5330 this time but I still can't seem to reproduce even after rebooting and remoting in multiple times.. Any other tips that might help me see the issue?

Have you tried to sleep/wakeup the PC remotely?

**Comment by Gabriela-Intel** [comment] 2024-02-22 21:51
@nyanmisaka Hm yes my system is set up similarly as well.

@pcslide I lose connection when the system is put to sleep. Is there something I need to enable to ensure I can force it to sleep/wake using a remote connection?

Thanks for the help!

**Comment by pcslide** [comment] 2024-02-23 02:59
@Gabriela-Intel 
If you have enabled Wake-On-LAN on your remote pc, you can try to use https://www.nirsoft.net/utils/wake_on_lan.html.
If the remote pc is not on the same LAN as you are on, then you need a proxy to wake the remote pc. Usually, a router or a server, being on the same side of  the remote pc, can act as a proxy.

**Comment by multi-vitamin** [comment] 2024-02-23 06:58
I think it's something about the HDMI dummy plug.
Try testing with nothing connected to the ARC GPU.
AMD and NVIDIA have no problem with nothing plugged in.

**Comment by Gabriela-Intel** [comment] 2024-02-23 17:11
Thanks @pcslide! Still no luck :( See details below on my set up and steps.
Let me know if ANYTHING differs from what you have been doing. 

Steps:
1. Using System 1, remote into System 2 by running mstsc Windows Remote Desktop
2. Put System 2 to sleep (lose connection)
3. Use WakeOnLAN to wake System 2 after some time (couple of minutes)
4. Using System 1, remotely access System 2 again 

System 1:
i5-12600K
Intel Arc A770
Windows 11 23H2
32 GB RAM
101.5330

System 2:
AMD Ryzen 5 7600 (iGPU enabled)
Intel Arc A380 
Windows 10 22H2 
32 GB RAM
101.5330
All HDMI/DP/VGA ports un-plugged on both motherboard & Arc card (headless setup)

**Comment by pcslide** [comment] 2024-02-24 04:20
@Gabriela-Intel 
After you did your step 3,  did system 2 wake up?  
If system 2 can not be waked up remotely, can it be waked up locally ( by using power-button /  keyboard)?

**Comment by multi-vitamin** [comment] 2024-02-24 14:00
Is iGPU disabled?
I'm pretty sure the iGPU should be disabled.

**Comment by Gabriela-Intel** [comment] 2024-02-26 23:36
@multi-vitamin I also tried it with integrated graphics disabled in the BIOS but to no avail..

**Comment by multi-vitamin** [comment] 2024-02-27 06:58
Windows runs with the monitor enabled and monitor is turned off
Will it still work in this situation?

**Comment by Gabriela-Intel** [comment] 2024-02-27 18:00
@multi-vitamin Can you elaborate?? I'm not following. I used a headless set up for system 2, so there wasn't a monitor connected.

**Comment by multi-vitamin** [comment] 2024-02-28 13:06
This seems to happen when it's not a full headless setup.

On Chrome Remote 
when connected, the resolution changes and immediately goes to black.
I boot up with the monitor connected and connect the chrome remote with the monitor off.

**Comment by pcslide** [comment] 2024-02-28 17:45
Now that you mentioned that, it seems resolution changes play some roles in causing the issue.  

> This seems to happen when it's not a full headless setup.
> 
> On Chrome Remote when connected, the resolution changes and immediately goes to black. I boot up with the monitor connected and connect the chrome remote with the monitor off.

**Comment by Gabriela-Intel** [comment] 2024-02-29 17:56
I tried to replicate the issue again booting with a monitor on using System 2 and remoting in with monitor off. This monitor is using a different resolution than System 1. I also tried using Chrome remote but the issue doesn't occur.

Since we haven't been able to successfully replicate after various attempts, I think we are unfortunately going to have to close this one out. It's an absolute must for us to see the issue to move forward. :(

**Comment by nyanmisaka** [comment] 2024-02-29 18:09
Isn't there something that I can do to capture a log or trace for the Windows Remote Desktop Application/Service? If so, you developers can diagnose it and see what's going on.

**Comment by Gabriela-Intel** [comment] 2024-02-29 18:32
Let me investigate internally about the logs/trace files that we can maybe pass along. I'll get back to you on this!

**Comment by Gabriela-Intel** [comment] 2024-03-01 17:16
Hey everyone. Please run these commands as Administrator in the command line:

```
if not exist C:\AppCrashDumps\NUL mkdir C:\AppCrashDumps

reg add "HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\Windows Error Reporting" /v "Disabled" /t REG_DWORD /d "0x1" /f
reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\Windows Error Reporting" /v "Disabled" /t REG_DWORD /d "0x1" /f

reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps" /v "DumpFolder" /t REG_EXPAND_SZ /d "C:\AppCrashDumps" /f

reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps" /v "DumpType" /t REG_DWORD /d "0x2" /f

reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CrashControl\LiveKernelReports" /v "DeleteLiveMiniDumps" /t REG_DWORD /d "0x0" /f

reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CrashControl" /v "FilterPages" /t REG_DWORD /d "0x1" /f
reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CrashControl" /v "CrashDumpEnabled" /t REG_DWORD /d "0x1" /f
```

then restart the system.

Basically, this will keep any TDR/Watchdog dump in C:\Window\LiveKernelReport\Watchdog folder or any application crash dump in C:\AppCrashDumps folder

Reproduce the issue and please send us any dump file generated in those folders. Thanks!

**Comment by Gabriela-Intel** [comment] 2024-03-11 20:28
Hey again. Anyone have any updates or logs to provide for us to look into?

**Comment by multi-vitamin** [comment] 2024-03-14 19:31
I've only tested with Chrome Remote.
If it's a black screen, it's visible immediately when you turn on the monitor.
However, when I turn off the monitor, reboot and reconnect it, it goes into a black screen.

It seems to be an issue with not being able to specify the initial resolution.

I have a headless from AMD or NVIDIA. 
When I run chrome remote, it defaults to 1024x768 resolution.
It never goes into a black screen.

My system:
AMD Ryzen 3600xt
Intel Arc A770
Windows 10 22H2
16 GB RAM
101.5333
DP port plugged

**Comment by Gabriela-Intel** [comment] 2024-03-15 20:36
@multi-vitamin As mentioned previously, I also checked the behavior using Chrome remote but didn't notice anything abnormal.

**Comment by Gabriela-Intel** [comment] 2024-03-15 20:38
Again, we really need those logs to proceed since we can't reproduce :/ I'll check back in a week. If there's no success with logs or replicating, I'll have to continue with closing this out.

**Comment by nyanmisaka** [comment] 2024-03-15 20:41
I'll try it this weekend and see if I can get the log.

**Comment by Gabriela-Intel** [comment] 2024-03-15 20:43
Awesome. Keep me posted!

**Comment by nyanmisaka** [comment] 2024-03-17 15:10
I found that this issue did not cause the application and kernel to crash, but it exited gracefully. So nothing is captured in AppCrashDumps and LiveKernelReport. Instead, errors and warnings can be observed in the Windows event viewer.

I saved some `.evtx` (Windows XML Event Log) logs from both client and server side, hope it can still be helpful to you team. [RemoteDesktopServices-RdpCoreTS.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14627839/RemoteDesktopServices-RdpCoreTS.zip)

![err](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/14953024/6779f904-8a54-4022-b0e7-69f423fa5ec8)

**Closed** 2024-03-28 18:05 UTC
Labels: Info: Needs Replication, Type: Application Crash

**Comment by yetdragon** [comment] 2024-09-23 22:59
Hello, I experienced the same issue. When I RDP into my computer with Arc A770 and 13500 with iGPU, it ocassionaly crash the system and force reboot. I managed to confirm that it is indeed an issue related to Intel graphics driver initialization error.

This is how I found it.

This is the error from the system section of Windows event viewer (Meaning computer is rebooted after error check):

```plaintext
컴퓨터가 오류 검사 후 다시 부팅되었습니다. 오류 검사: 0x00000116 (0xffff9784506bb050, 0xfffff80582541e60, 0x0000000000000000, 0x000000000000000d). 덤프 저장 위치: C:\Windows\Minidump\092424-14390-01.dmp. 보고서 ID: 0b6b3678-309d-4913-a200-3171cab318d
```

I checked the Minidump file with WinDbg tool avaiable in Microsft Store and found this:

```plaintext

************* Preparing the environment for Debugger Extensions Gallery repositories **************
   ExtensionRepository : Implicit
   UseExperimentalFeatureForNugetShare : true
   AllowNugetExeUpdate : true
   NonInteractiveNuget : true
   AllowNugetMSCredentialProviderInstall : true
   AllowParallelInitializationOfLocalRepositories : true
   EnableRedirectToChakraJsProvider : false

   -- Configuring repositories
      ----> Repository : LocalInstalled, Enabled: true
      ----> Repository : UserExtensions, Enabled: true

>>>>>>>>>>>>> Preparing the environment for Debugger Extensions Gallery repositories completed, duration 0.000 seconds

************* Waiting for Debugger Extensions Gallery to Initialize **************

>>>>>>>>>>>>> Waiting for Debugger Extensions Gallery to Initialize completed, duration 0.031 seconds
   ----> Repository : UserExtensions, Enabled: true, Packages count: 0
   ----> Repository : LocalInstalled, Enabled: true, Packages count: 42

Microsoft (R) Windows Debugger Version 10.0.27704.1001 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:\Users\<USERNAME>\Downloads\092424-14390-01.dmp]
Mini Kernel Dump File: Only registers and stack trace are available

Symbol search path is: srv*
Executable search path is: 
Windows 10 Kernel Version 22621 MP (20 procs) Free x64
Product: WinNt, suite: TerminalServer SingleUserTS
Kernel base = 0xfffff805`55e00000 PsLoadedModuleList = 0xfffff805`56a134f0
Debug session time: Tue Sep 24 07:39:24.362 2024 (UTC + 9:00)
System Uptime: 0 days 1:37:34.297
Loading Kernel Symbols
...............................................................
................................................................
................................................................
......................................
Loading User Symbols

Loading unloaded module list
....................
For analysis of this file, run !analyze -v
nt!KeBugCheckEx:
fffff805`56215cb0 48894c2408      mov     qword ptr [rsp+8],rcx ss:0018:fffffc81`0ad4f700=0000000000000116
0: kd> !analyze -v
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

VIDEO_TDR_FAILURE (116)
Attempt to reset the display driver and recover from timeout failed.
Arguments:
Arg1: ffff9784506bb050, Optional pointer to internal TDR recovery context (TDR_RECOVERY_CONTEXT).
Arg2: fffff80582541e60, The pointer into responsible device driver module (e.g. owner tag).
Arg3: 0000000000000000, Optional error code (NTSTATUS) of the last failed operation.
Arg4: 000000000000000d, Optional internal context dependent data.

Debugging Details:
------------------

Unable to load image igdkmdnd64.sys, Win32 error 0n2
*** WARNING: Unable to verify timestamp for igdkmdnd64.sys

KEY_VALUES_STRING: 1

    Key  : Analysis.CPU.mSec
    Value: 1156

    Key  : Analysis.Elapsed.mSec
    Value: 9606

    Key  : Analysis.IO.Other.Mb
    Value: 3

    Key  : Analysis.IO.Read.Mb
    Value: 0

    Key  : Analysis.IO.Write.Mb
    Value: 24

    Key  : Analysis.Init.CPU.mSec
    Value: 281

    Key  : Analysis.Init.Elapsed.mSec
    Value: 39034

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 107

    Key  : Analysis.Version.DbgEng
    Value: 10.0.27704.1001

    Key  : Analysis.Version.Description
    Value: 10.2408.27.01 amd64fre

    Key  : Analysis.Version.Ext
    Value: 1.2408.27.1

    Key  : Bugcheck.Code.LegacyAPI
    Value: 0x116

    Key  : Bugcheck.Code.TargetModel
    Value: 0x116

    Key  : Dump.Attributes.AsUlong
    Value: 1808

    Key  : Dump.Attributes.DiagDataWrittenToHeader
    Value: 1

    Key  : Dump.Attributes.ErrorCode
    Value: 0

    Key  : Dump.Attributes.KernelGeneratedTriageDump
    Value: 1

    Key  : Dump.Attributes.LastLine
    Value: Dump completed successfully.

    Key  : Dump.Attributes.ProgressPercentage
    Value: 0

    Key  : Failure.Bucket
    Value: 0x116_IMAGE_igdkmdnd64.sys

    Key  : Failure.Hash
    Value: {7eb0cc99-c85b-4092-6430-8f1db059b7c1}

    Key  : Hypervisor.Enlightenments.ValueHex
    Value: 1417df84

    Key  : Hypervisor.Flags.AnyHypervisorPresent
    Value: 1

    Key  : Hypervisor.Flags.ApicEnlightened
    Value: 0

    Key  : Hypervisor.Flags.ApicVirtualizationAvailable
    Value: 1

    Key  : Hypervisor.Flags.AsyncMemoryHint
    Value: 0

    Key  : Hypervisor.Flags.CoreSchedulerRequested
    Value: 0

    Key  : Hypervisor.Flags.CpuManager
    Value: 1

    Key  : Hypervisor.Flags.DeprecateAutoEoi
    Value: 1

    Key  : Hypervisor.Flags.DynamicCpuDisabled
    Value: 1

    Key  : Hypervisor.Flags.Epf
    Value: 0

    Key  : Hypervisor.Flags.ExtendedProcessorMasks
    Value: 1

    Key  : Hypervisor.Flags.HardwareMbecAvailable
    Value: 1

    Key  : Hypervisor.Flags.MaxBankNumber
    Value: 0

    Key  : Hypervisor.Flags.MemoryZeroingControl
    Value: 0

    Key  : Hypervisor.Flags.NoExtendedRangeFlush
    Value: 0

    Key  : Hypervisor.Flags.NoNonArchCoreSharing
    Value: 1

    Key  : Hypervisor.Flags.Phase0InitDone
    Value: 1

    Key  : Hypervisor.Flags.PowerSchedulerQos
    Value: 0

    Key  : Hypervisor.Flags.RootScheduler
    Value: 0

    Key  : Hypervisor.Flags.SynicAvailable
    Value: 1

    Key  : Hypervisor.Flags.UseQpcBias
    Value: 0

    Key  : Hypervisor.Flags.Value
    Value: 21631230

    Key  : Hypervisor.Flags.ValueHex
    Value: 14a10fe

    Key  : Hypervisor.Flags.VpAssistPage
    Value: 1

    Key  : Hypervisor.Flags.VsmAvailable
    Value: 1

    Key  : Hypervisor.RootFlags.AccessStats
    Value: 1

    Key  : Hypervisor.RootFlags.CrashdumpEnlightened
    Value: 1

    Key  : Hypervisor.RootFlags.CreateVirtualProcessor
    Value: 1

    Key  : Hypervisor.RootFlags.DisableHyperthreading
    Value: 0

    Key  : Hypervisor.RootFlags.HostTimelineSync
    Value: 1

    Key  : Hypervisor.RootFlags.HypervisorDebuggingEnabled
    Value: 0

    Key  : Hypervisor.RootFlags.IsHyperV
    Value: 1

    Key  : Hypervisor.RootFlags.LivedumpEnlightened
    Value: 1

    Key  : Hypervisor.RootFlags.MapDeviceInterrupt
    Value: 1

    Key  : Hypervisor.RootFlags.MceEnlightened
    Value: 1

    Key  : Hypervisor.RootFlags.Nested
    Value: 0

    Key  : Hypervisor.RootFlags.StartLogicalProcessor
    Value: 1

    Key  : Hypervisor.RootFlags.Value
    Value: 1015

    Key  : Hypervisor.RootFlags.ValueHex
    Value: 3f7


BUGCHECK_CODE:  116

BUGCHECK_P1: ffff9784506bb050

BUGCHECK_P2: fffff80582541e60

BUGCHECK_P3: 0

BUGCHECK_P4: d

FILE_IN_CAB:  092424-14390-01.dmp

TAG_NOT_DEFINED_202b:  *** Unknown TAG in analysis list 202b


DUMP_FILE_ATTRIBUTES: 0x1808
  Kernel Generated Triage Dump

FAULTING_THREAD:  ffff978437b4f0c0

VIDEO_TDR_CONTEXT: dt dxgkrnl!_TDR_RECOVERY_CONTEXT ffff9784506bb050
Symbol dxgkrnl!_TDR_RECOVERY_CONTEXT not found.

PROCESS_OBJECT: 000000000000000d

BLACKBOXBSD: 1 (!blackboxbsd)


BLACKBOXNTFS: 1 (!blackboxntfs)


BLACKBOXPNP: 1 (!blackboxpnp)


BLACKBOXWINLOGON: 1

CUSTOMER_CRASH_COUNT:  1

PROCESS_NAME:  System

STACK_TEXT:  
fffffc81`0ad4f6f8 fffff805`5b0bb00e     : 00000000`00000116 ffff9784`506bb050 fffff805`82541e60 00000000`00000000 : nt!KeBugCheckEx
fffffc81`0ad4f700 fffff805`5b0ba699     : fffff805`82541e60 ffff9784`506bb050 fffffc81`0ad4f819 00000000`0000050c : dxgkrnl!TdrBugcheckOnTimeout+0xfe
fffffc81`0ad4f740 fffff805`9db27bf6     : 00000000`0000050c ffff9784`2d5b65c8 ffff9784`2d5b65d0 ffff9784`2d5b65d8 : dxgkrnl!TdrIsRecoveryRequired+0x1b9
fffffc81`0ad4f770 fffff805`9dbb3d99     : ffff9784`3dee9000 00000000`00000000 ffff9784`3dee9000 00000000`00000000 : dxgmms2!VidSchiReportHwHang+0x5fe
fffffc81`0ad4f880 fffff805`9db85919     : 00000000`00000000 00000000`00000000 00000000`0005b619 00000000`00989680 : dxgmms2!VidSchiCheckHwProgress+0x2e459
fffffc81`0ad4f900 fffff805`9dae6ae1     : 00000000`00000000 ffff9784`3dee9000 fffffc81`0ad4fa39 00000000`00000000 : dxgmms2!VidSchiWaitForSchedulerEvents+0x389
fffffc81`0ad4f9d0 fffff805`9db9a405     : ffff9784`37d86000 ffff9784`3dee9000 ffff9784`37d86060 ffff9784`370098a0 : dxgmms2!VidSchiScheduleCommandToRun+0x291
fffffc81`0ad4faa0 fffff805`9db9a37a     : 00000000`00000000 fffff805`9db9a2b0 ffff9784`3dee9000 00000000`00050246 : dxgmms2!VidSchiRun_PriorityTable+0x35
fffffc81`0ad4faf0 fffff805`56154d07     : ffff9784`37b4f0c0 fffff805`00000001 ffff9784`3dee9000 006fe47f`b19bbdff : dxgmms2!VidSchiWorkerThread+0xca
fffffc81`0ad4fb30 fffff805`5621ae24     : ffffd580`86851180 ffff9784`37b4f0c0 fffff805`56154cb0 cccccccc`cccccccc : nt!PspSystemThreadStartup+0x57
fffffc81`0ad4fb80 00000000`00000000     : fffffc81`0ad50000 fffffc81`0ad49000 00000000`00000000 00000000`00000000 : nt!KiStartSystemThread+0x34


SYMBOL_NAME:  igdkmdnd64+11e60

MODULE_NAME: igdkmdnd64

IMAGE_NAME:  igdkmdnd64.sys

STACK_COMMAND:  .process /r /p 0xffff9784238f3040; .thread 0xffff978437b4f0c0 ; kb

FAILURE_BUCKET_ID:  0x116_IMAGE_igdkmdnd64.sys

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {7eb0cc99-c85b-4092-6430-8f1db059b7c1}

Followup:     MachineOwner
---------
```

It says that the error is `VIDEO_TDR_FAILURE (116): Attempt to reset the display driver and recover from timeout failed.` It seems the Intel driver sometimes fails to initialize the driver on RDP connection for some reason.

I think we should reopen the issue.

**Comment by nyanmisaka** [comment] 2024-09-24 10:07
@yetdragon I would suggest you to open a new issue since I didn't encounter any TDR or BSOD.

**Comment by Gabriela-Intel** [comment] 2024-09-24 21:22
@yetdragon Yes, this one has been closed for some time so please file a new issue so we can properly track it. Thanks!
