### ISSUE TITLE
DaVinci Resolve won't launch when DaVinci Resolve Control Panels is installed

### ISSUE THREAD

**Issue by willamettefour** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#341] opened 2023-06-13 17:27 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

DaVinci Resolve

### Processor / Processor Number [Required]

i5-12490F

### Graphic Card [Required]

ASRock ARC A770

### GPU Driver Version [Required]

- [X] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[intel_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11737583/intel_ssu.txt)

### Description and steps to reproduce [Required]

DaVinci Resolve versions 18.1.4 and 18.5 Public Beta 3 will crash on the loading screen if DaVinci Resolve Control Panels is installed. Uninstalling Control Panels allows Resolve to open. I tested with the High Performance power plan, but that doesn't seem to matter.
![Screenshot 2023-06-13 093350](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/94886283/de434bb3-894c-4c7e-baf4-3d1533b376c8)
 

### Crash dumps [Required, if applicable]

https://mega.nz/file/tk0ggJIY#u4Tfff2pTEgB5k3Ao_c6Yel6ps03hKB8zL23NPiMVDE

**Comment by Karen-Intel** [comment] 2023-06-13 22:21
Hey @willamettefour thank you for your report.

I was able to reproduce the same issue on a similar machine so, I will make sure to report this asap.

In case I need any additional info I will get back to you, in the meantime, let's leave this post open until a fix has been released.

Thank you for your help!

Karen

**Comment by Karen-Intel** [comment] 2023-06-14 18:31
Hey @willamettefour update on this

I just tested it one more time in my system (13900k + A750 + GFX v.4382) and it launched for me.

I am testing v.18.5 beta and here you have the [evidence](https://www.youtube.com/watch?v=M6wk8ra2Coc). I also have installed the Resolve Control panel.

![Launch](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/91162218/a04acd49-bb72-420f-9ba3-03dd36b74279)

I did not do anything special, just rebooted my PC probably twice before trying again and applied the latest Windows updates available on Jun13th (yesterday) and rebooted my system this morning.

![Windows Settings](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/91162218/ffe4e20b-8efa-46cb-8aee-dcf4416e15c0)

I wonder if the system update helped as I did not change anything else, can you try again?
Consider using DDU to reinstall your driver. I always do that and it works like a charm

Thanks, hope to hear from you soon!

Karen

**Comment by willamettefour** [comment] 2023-06-14 20:40
After further testing, the issue doesn't appear to be driver or Windows related, as I was able to replicate it on a friend's system with Radeon graphics (both systems were updated to build 22621.1848). The culprit seems to be recent versions of Cloudflare WARP (2023.3.450.0 and 2023.5.587.1), as I was able to successfully launch Resolve with Control Panels once it was closed. Something to note is that older versions don't cause the crash (version 22.12.476.0, for example, worked just fine with Resolve).

**Comment by Karen-Intel** [comment] 2023-06-14 20:54
@willamettefour great info! Thank you so much for sharing

It will be helpful to other users that are having a similar situation. As the issue seems to be related to a 3rd party, I think we can close this bug for the time being

@IGCIT can you help us close this one? Based on our customer's last testing results, the culprit seems to be recent versions of Cloudflare WARP (2023.3.450.0 and 2023.5.587.1

Thanks!

Karen

**Closed** 2023-06-15 07:27 UTC
Labels: Info: Needs Replication, Type: Application Crash
