### ISSUE TITLE
Minecraft raytracing doesn't work on current latest drivers

### ISSUE THREAD

**Issue by cellos51** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#190] opened 2022-12-05 06:24 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Minecraft for Windows

### Game Platform [Required]

- [ ] Steam
- [X] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 7 5800X

### Graphic Card [Required]

Intel Arc A770

### GPU Driver Version [Required]

- [x] 31.0.101.3802 (*latest*)
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Windows 10 21H1
- [ ] Other (Please specify)

### Intel System Support Utility report

[log.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10151065/log.txt)

### Description and steps to reproduce [Required]

If you download any RTX world or resource pack and attempt to load it. The game will flash red and black for a few seconds and then will load in but everything will be black and running at an extremely low frame rate. However this issue is nonexistent on driver version 31.0.101.3490.
![Screenshot (50)](https://user-images.githubusercontent.com/70788102/205562878-148195b0-0235-4041-bc07-be87b0f3b8c1.png)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920 x 1280

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

I did a clean reinstall of the game. Everything was left at default settings.

![Screenshot (54)](https://user-images.githubusercontent.com/70788102/205563292-cbbb15b1-763a-46ed-a623-cd00f0b6ee53.png)
![Screenshot (56)](https://user-images.githubusercontent.com/70788102/205563300-56171ea7-2406-4e65-b6fa-4a7cde143819.png)
![Screenshot (55)](https://user-images.githubusercontent.com/70788102/205563302-4b48b31c-a07c-4511-97a8-f8835956fbef.png)

**Comment by cellos51** [comment] 2022-12-05 07:04
https://www.xbox.com/en-us/games/store/minecraft-launcher/9pgw18npbzv5?rtc=1 This is where I got the game from. The version is v1.19.50

**Comment by IntelSupport-Arun** [comment] 2022-12-06 08:00
Hi @cellos51 ,
Thank you for the quick reply. The link provided leads to the Minecraft launcher, where I can see different versions. Could you confirm which version you're using? I would appreciate it if you could attach a video of your issue.
![minecraft_screenshot](https://user-images.githubusercontent.com/91881865/205853773-1fc8ea05-235c-4682-962a-160dbc8c53be.JPG)

**Comment by cellos51** [comment] 2022-12-06 19:28
I just got the newest driver 3959 and now raytracing will load but the lighting is broken and everything seems to glow.

Here are the videos

This video shows the game version on Windows Store and is using driver 3959 in game: https://www.youtube.com/watch?v=KZAyQSPCFAA

This video is the game running on 3490 and everything is working correctly: https://www.youtube.com/watch?v=bf0v94EuaqQ

**Comment by IntelSupport-Arun** [comment] 2022-12-12 08:59
Hi @cellos51 ,
I have verified the issue on the below configuration and am able to reproduce the issue :
Issue reproduce on(Platform): AMD Ryzen 7 5800X
Graphics device: Arc A770
Graphics Driver: 31.0.101.3959/Internal Driver
Operating System: Windows 11 22H2(22621)

I have forwarded this issue to the next level for further debugging and fixing. I want to give you a heads-up that the fix may take 3 to 6 months to be included. So you may please stay tuned for our next update regarding the fix. Thank you.

**Comment by cellos51** [comment] 2022-12-12 17:25
Alright then thanks.

**Comment by IGCIT** [comment] 2022-12-14 19:55
@cellos51
please keep issues open until a fix has landed in drivers so that other users with the same problem can find updates about them.
when this is confirmed to be fixed, by you or someone else, it can be closed.

thank you :)

**Comment by joelschwartz** [comment] 2022-12-27 01:50
https://user-images.githubusercontent.com/22087235/209598452-25a09413-5907-4864-aa0a-24321c30b43b.mp4
here is how I loaded into minecraft with raytracing on the intel arc A770 LE at 1440x900 resolution since it's still very hard to run on intel arc without using TAAU upscaling.

**Comment by kode54** [comment] 2023-01-10 22:45
For further testing metrics, there's this Vanilla RTX resource pack. The only issue is that the developer put the downloads behind the usual adfly link guards.

https://github.com/CubeIR/Vanilla-RTX

That should prove to be usable once a fix is released. See everyone again in 2-5 months, hopefully.

**Comment by BelleNottelling** [comment] 2023-03-07 17:17
So, I can't speak for other people, but for me ray tracing with bedrock edition is working just fine.
Well, "fine" is subjective, I'm getting about 20-24 FPS at 1440p with ray tracing, but even without ray tracing enabled, I still only get about 35 FPS as the driver doesn't seem to realize there's a demand / game being run and the clock speeds fell down to 1500Mhz. (with RT, it's clock speed boosted as as normal)

Tested specs:
- i9 9900k 
- 32GB of ram
- Arc A770 LE 16GB
- Resizable Bar is enabled
- Windows 11 Pro, 22H2
- Driver ver 4146
![image](https://user-images.githubusercontent.com/17304943/223498091-133f6ada-71a2-4866-be6d-2e647f44ae47.png)

So it works, but the performance is pretty poor, even without RT enabled

**Comment by joelschwartz** [comment] 2023-03-07 22:12
first of all @BelleNottelling you didn't turn off vsync and that was why you were getting low fps with dxr raytracing turned off. Also I don't consider getting 24 fps at 1440p working since it's terrible performance not to mention that multiple people were getting black screens and crashing all the time. Just because you didn't have the black screen issue doesn't mean other people weren't and you might not have a lot of game time and that might be why you didn't have it happen to you since if you load up the game for the first time it's less common to happen until playing the game for a while

**Comment by EstebanIntel** [comment] 2023-03-30 14:31
Hi @cellos51 a possible fix for this issues is included in the [latest driver](14018436632) version 31.0.101.4255. Can you please verify the fix works for you?

**Comment by cellos51** [comment] 2023-03-30 16:43
I tested the drivers mentioned, and all the visual issues that I had before are now nowhere to be found. I compared screenshots from my RTX 2070 Super and my Intel Arc A770 LE, and they appear to be identical now.

**Comment by EstebanIntel** [comment] 2023-03-30 18:10
That's great news!  Thanks for testing!

@IGCIT  I think this issue can be closed now

**Closed** 2023-03-30 18:34 UTC
Labels: Info: Needs Replication, Type: Regression, Type: Graphical Glitches
