### ISSUE TITLE
Intel Arc A580 constantly experiences Encoder Overload in OBS Studio

### ISSUE THREAD

**Issue by SapphireDrew** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#865] opened 2024-11-17 00:17 UTC
### Checklist [README]

- [x] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

OBS Studio

### Processor / Processor Number [Required]

Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz

### Graphic Card [Required]

Intel Arc A580 - ASRock Challenger OC Edition

### GPU Driver Version [Required]

32.0.101.6297

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build [Required]

Windows 10 22H2

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/user-attachments/files/17788244/igcit_ssu.txt)

### Description and steps to reproduce [Required]

_**Problem:**_

OBS Studio experiences encoder overloads with the Intel Arc A580's QuickSync H.264 encoder (_Twitch doesn't support AV1 encoding except from Nvidia RTX 40xx series cards yet_) even when the fastest TU (_Target Usage_) preset and baseline profile were used.

_**Additional Relevant Info:**_

Affected machine is a custom built tower PC with an Intel Core i7 9700K @ 3.60GHz at stock settings, 32 GB of Crucial Ballistix DDR4-3200 CL16 RAM, and an ASRock Challenger OC Edition Intel Arc A580 graphics card on ASRock Taichi Intel Z390 Motherboard. The latest firmware revision of that motherboard added support for ReBAR and Above 4G Decoding, both of which were enabled prior to testing. I understand that the system requirements for Intel Arc cards are a 10th gen Intel CPU or later with Intel 400 series or later motherboard, but I was hoping this set up would work since it offered the required features. Graphics card was purchased with the goal of replacing an ASUS TUF Nvidia RTX 2060 in hopes of equal or better performance; especially since I was considering migrating to Linux full time in the near future if all went well.

Canvas and output resolution are both set to 720p. TU setting was set to Fastest and the profile was set to the `baseline` preset. Games tested while attempting to stream were Stray and Deep Rock Galactic. These were streamed on a single DP display configuration at a refresh rate of 60 Hz with both games being played in Windowed Mode and captured via Game Capture Source in OBS Studio. FPS has been locked to 60 both in-game and via Arc Control's Universal Settings. V-Sync was enabled both in-game and via Arc Control.

I'm willing to test and troubleshoot as advised if possible within the return period of the graphics card (_12 days remaining as of writing this_) in hopes of getting good QuickSync H.264 encoder performance with near parity or better performance than an 5 yr old PCIe Gen 3 x8 RTX 2060. C'mon, Team Blue, I know you can make this happen. <3

### Device / Platform

PC - Windows 10. Twitch.

### Application / Windows logs

https://obsproject.com/logs/9puluLlPm0vKf4kc

[OBS_Log.txt](https://github.com/user-attachments/files/17788313/OBS_Log.txt)

**Comment by Gabriela-Intel** [comment] 2024-11-21 19:14
Hi @SapphireDrew! Have you tried [DDU'ing](https://www.wagnardsoft.com/display-driver-uninstaller-DDU-) yet?

**Comment by SapphireDrew** [comment] 2024-11-22 03:09
@Gabriela-Intel Yes. I used DDU each time I swapped and compared graphics cards, as well as whenever #868 occured.

**Comment by Gabriela-Intel** [comment] 2024-11-22 18:33
Thanks for confirming! Let me investigate this and get back to you on this.

**Comment by Gabriela-Intel** [comment] 2024-12-04 22:45
Apologies for the delay. I had to get hold of a system to try to replicate these issues on.

Since we don't support anything older than 10th gen and newer with Arc (as you mentioned) I tested on a system as close as we could get. You'll see I used the same system for the other issues you reported as well. I wasn't able to observe this issue, or the other issues recently reported (#870, #866, #868)

System: 
10900k
A580 Sparkle 
16 GB RAM
512 GB SSD
Win 10 Home
Asus RoG Swift PG38UQ
Driver 101.6299

For this issue, I played Stray for about an hour but didn't see any "Encoder Overload" messages in OBS. The OBS "dropped frames" counter stayed at zero. 

Since I wasn't able to reproduce this issue, or the others you've mentioned, there is a chance that the older processor/motherboard combo with the Arc card may be the problem. My recommendation for all these issues would be to (if possible) test the card on another system so we can rule out the possibility of an issue with the card itself. Another recommendation would be to try a fresh OS install.

You previously mentioned you only have 12 days remaining of the return period so it seems that we are past that, so I'm sorry we weren't able to help you in time if you did return the card.

**Comment by SapphireDrew** [comment] 2024-12-05 00:27
I appreciate you getting back to me with your findings. I hoping your results could be achieved even on my PC given it does have ReBAR and Above 4G Decoding but it is what it is.

I plan on building a new PC this month, so I'll reply once it's built and tested and let you know if my problem still exists or not on the new hardware.

**Comment by SapphireDrew** [comment] 2024-12-05 00:35
@Gabriela-Intel And just to confirm, your test was done while simultaneously streaming and recording?

**Comment by Gabriela-Intel** [comment] 2024-12-05 21:55
Hi there, no it was only streaming. Let me retest and get back to you.

**Comment by Gabriela-Intel** [comment] 2024-12-05 23:00
Just tried it and the results are the same.

**Comment by Gabriela-Intel** [comment] 2024-12-10 16:35
Since you are building a new system and will be retesting the issues you filed, let's close this for now. If the issue is seen again with the new build, then please reopen the issue. :)

**Closed by Gabriela-Intel** 2024-12-10 16:35 UTC
Labels: Info: Needs Replication, Type: Support
