### ISSUE TITLE
Forza Horizon 5 UI graphical glitch under certain settings. 

### ISSUE THREAD

**Issue by Maniir** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#173] opened 2022-10-30 22:46 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Forza Horizon 5

### Game Platform [Required]

- [ ] Steam
- [ ] Origin
- [X] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Other game platform

Xbox Launcher for PC

### Processor / Processor Number [Required]

Intel Core i9-11900K

### Graphic Card [Required]

Intel ARC A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.3793 (*latest*)
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1 (*October 2021 Update*)
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/9896925/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Setting the **"Lens Effects" setting to Ultra** produces a series of flickering black lines when in game. The effect doesn't seem to happen under other settings as far as I can tell.

![page1](https://user-images.githubusercontent.com/46582102/198905286-ef979552-34da-417a-92a4-d3413a312365.png)
![page2](https://user-images.githubusercontent.com/46582102/198905290-ca71bcd1-1871-4516-80fb-232c80b80ccb.png)
![Glitchjpg](https://user-images.githubusercontent.com/46582102/198905325-a8cb7ac2-b3db-44da-8765-b985d1a8d7b7.jpg)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

It seems to be specifically the "Lens Effects" setting at Ultra that causes the issue.

![page1](https://user-images.githubusercontent.com/46582102/198905361-4c2462d8-c0f0-4895-ad27-c9a4370af8dc.png)
![page2](https://user-images.githubusercontent.com/46582102/198905362-04c7c644-18d1-41c7-9ba6-ce6d674e8edb.png)

**Comment by IntelSupport-Arun** [comment] 2022-10-31 08:31
Hi @Maniir ,
To narrow down the issue I would like to know few details from your side:
1.   Currently there is a known issue with the beta driver version "Forza Horizon 5 (DX12) may experience corruption lines when MSAA 2x is enabled" so could you change the value of MSAA and see if it resolves the problem. Also, please confirm the issue is only observing with lens effect = Ultra. what about the other settings Low and High?
2. Did you get any chance to verify the issue on the official released driver [31.0.101.3490](https://www.intel.com/content/www/us/en/download/726609/intel-arc-graphics-windows-dch-driver.html) ? We want to know whether its a regression issue or not?

**Comment by Maniir** [comment] 2022-10-31 20:46
1. You are right. Under further investigating, it appears the Lens Effects setting is just exacerbating the issue. MSAA creates the basis of the glitch, and the Lens Effects setting makes it worse / noticeable. For example: 

- MSAA Off -> No Glitch.
- MSAA=2x + Lens Effects=Off -> Very small glitch in bottom right corner.
- MSAA=2x + Lens Effects=Medium -> Very small glitch in bottom right corner.
- MSAA=2x + Lens Effects=High -> Glitch across bottom edge of screen.
- MSAA=2x + Lens Effects=Ultra -> Very large glitches all over the screen.

My apologies, it is clearly the same MSAA glitch, the Lens Effect setting was just making it harder or easier to notice in some cases. 

2. I can not get the glitches to appear when using the 3490 driver, only with the 3793 driver.

**Comment by Bryce-7995** [comment] 2022-10-31 21:47
Yo Evan 
Coincidentally this was just seen & reported internally by Bob too. Working on the bug submission to debug.

**Comment by IntelSupport-Arun** [comment] 2022-11-04 06:03
Hi @Maniir ,
This issue has been already internally and our team is working on it. . I want to give you a heads-up that the fix may take 3 to 6 months to be included. Thank you.

**Comment by IntelSupport-Arun** [comment] 2022-11-23 05:05
Hi @Maniir ,
There is new driver version [31.0.101.3802](https://www.intel.com/content/www/us/en/download/729157/intel-arc-graphics-windows-dch-driver-beta.html) has been released and has the fix for the graphical glitches.
Please update the latest given driver and let us know your observations.

**Comment by Maniir** [comment] 2022-11-23 05:30
The issue appears to be fixed with the newest beta driver.

**Comment by IntelSupport-Arun** [comment] 2022-11-23 05:33
Hi @Maniir , Thanks for the quick confirmation.
Since the issue has been fixed with the latest driver please close this case. Thank you.

**Closed** 2022-11-23 06:45 UTC
Labels: Info: Needs Replication, Type: Graphical Glitches
