### ISSUE TITLE
CS2 random crash at executable startup (no window displayed)

### ISSUE THREAD

**Issue by freak2fast4u** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#589] opened 2023-11-08 15:12 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Counter-Strike 2

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 7800X3D

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

31.0.101.4952

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Other Windows build number

19045.3636

### Intel System Support Utility report

[igcit_ssu_20231108_cs2startcrashrandom_anon.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13298248/igcit_ssu_20231108_cs2startcrashrandom_anon.txt)

### Description and steps to reproduce [Required]

Start the game, notice no window opened and Steam reports the game can be started. No popup, no crash, nothing, the process just silently exits. Random.

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

N/A

### Device / Platform name

ASUS TUF GAMING B650-PLUS WIFI

### Crash dumps [Required, if applicable]

[cs2_2023_1108_154646_0_accessviolation.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13298283/cs2_2023_1108_154646_0_accessviolation.zip)

**Comment by freak2fast4u** [comment] 2023-11-08 15:13
Excerpt from WinDbg : 
![2023-11-08 16_03_30-E__SteamLibrary_steamapps_common_Counter-Strike Global Offensive_game_bin_win64_](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3486369/2d03e817-0176-4726-8723-0d92e746c732)

**Comment by freak2fast4u** [comment] 2023-11-16 22:26
Another occurence today (happened twice in fact, but here's the latest one) : 
[cs2_2023_1116_232030_0_accessviolation.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13384671/cs2_2023_1116_232030_0_accessviolation.zip)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3486369/804519db-2e98-400d-8214-5081317e1024)

[crash_dump_synthesis_windbg_cs2.exe_20231116.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13384678/crash_dump_synthesis_windbg_cs2.exe_20231116.txt)

**Comment by Joseph-Intel** [comment] 2023-11-17 20:06
Hey @freak2fast4u thanks for bringing up your concern. I was able to test this out and i wasn't getting any crashes and was able to play the game. I know this game updated a couple of times since this post. I am also on the latest graphics driver V1014953. Would you be able to test this out and let me know? I recommend checking the files or reinstalling the game as well if you haven't done so.

**Comment by freak2fast4u** [comment] 2023-11-17 22:18
Hi @Joseph-Intel, thank you for your interest. Sadly, the problem appears randomly, and also rarely. Maybe on average once every fifty runs ? Reproducing it will be tedious. Re-running the game a second time after a crash usually works fine.

It also just so turns out that it happened to me twice yesterday alone (I only uploaded the second occurence in my last comment).

Valve has indeed rolled out a massive patch to CS2 on 16/11 (a few hours after my previous comment) which I recieved today. The patch notes don't mention any crash-related fixes, but I'll stay on the lookout for any spurious launch crashes that might happen going forward, if any.

I sure hope both crash dumps I provided give actual pointers to where exactly in the driver code the crash occurs, wether it's induced by bad input from CS2's game engine or an actual oopsie in the Intel Arc driver.

The game crashed a total of 13 times in the past 2 months, and I've been starting/restarting it quite a lot. 
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3486369/9174dcd2-b50a-4245-b542-498db0a44503)

**Comment by Joseph-Intel** [comment] 2023-11-20 16:31
@freak2fast4u thank you for updating! we will continue testing and let you know if we find anything

**Comment by freak2fast4u** [comment] 2023-11-25 15:32
It happened yet again today with latest beta drivers (4972 currently) on latest CS2 build (20/11/2023). 
[cs2_2023_1125_162007_0_accessviolation.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13464447/cs2_2023_1125_162007_0_accessviolation.zip)

I played the game earlier without issues, and just relaunched it without any issues either. Completely random, and still happening with up-to-date software on all sides.

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3486369/7ed33a79-c644-47fd-a455-f6d908e525de)

Take note that one of the first things CS2 does when launching is playing an intro video, so it isn't necessarily 3D-related.
Could it be related to some hw-accelerated decoding of the launch video that randomly fails ? DXVA/DXVA2 come to my mind as a plausible area of exploration, but who knows ... See attached dump for a more detailed view of what's going on :)

**Comment by Joseph-Intel** [comment] 2023-12-04 17:40
Hi @freak2fast4u After more testing i still have not been able to reproduce. Since i can not reproduce the issue i cannot pursue or file an internal report. @IGCIT Please help close this case. This case can be reopened at anytime that you can help find a way to reproduce it more reliably or if others are having this issue.
Thanks for your time

**Comment by freak2fast4u** [comment] 2023-12-04 18:15
Seems fair by me, if noone else is complaining then it has to be something specific with my setup. 
I agree your time would be better spent elsewhere. Thanks for your time also. See you around :)

**Closed** 2023-12-04 18:16 UTC
Labels: Info: Needs Replication, Type: Application Crash
