### ISSUE TITLE
Microsoft Flight Simulator (MSFS, FS2020) crashes PC

### ISSUE THREAD

**Issue by derlade** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#291] opened 2023-04-24 19:39 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Microsoft Flight Simulator

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i3-12100

### Graphic Card [Required]

Intel Arc A770 LE

### GPU Driver Version [Required]

- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [X] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11313977/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Microsoft Flight Simulator crashes in different stages of the game. Once during flight, twice in the main menu when loading a flight plan and twice in the initial loading screen. 
First, I encounter a black screen with audio still working for a few seconds, then the audio stops and my PC is on for about 10 seconds, then it reboots. Minidumps are created for every crash. They all have in common that dxgkrnl.sys seems to be the culprit for the crashes. Happens both in DX11 and DX12 mode.
I will post ICGIT crash dumps after posting the issue. When I get back into the game, I can also post screenshots of the in-game graphics settings, if required.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

n/a

### Crash dumps [Required, if applicable]

[igcit-dumps_8ec144f4.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11314272/igcit-dumps_8ec144f4.zip)
Repackaged as .zip, since Github didn't allow .7z upload

**Comment by Karen-Intel** [comment] 2023-04-24 20:07
Hey @derlade thank you for your submission!

We will perform some testing and get back to you in case we have questions

Talk to you soon

Karen

**Comment by Karen-Intel** [comment] 2023-04-28 15:18
Hey @derlade a quick update. Have you tried our latest driver release?
Please upgrade to latest driver [v.4314](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html) and [DDU version](https://www.wagnardsoft.com/forums/viewtopic.php?t=4491) and let us know if you see any improvement
I have tried the game on my system and I have had no crashes so far.
 It is also recommended to follow these steps when updating the game to ensure there's nothing else interfering with its performance
[](https://flightsimulator.zendesk.com/hc/en-us/articles/360017133940-All-versions-How-to-install-a-new-update-safely)
Please give ir a try and let us know how it goes!

Karen

**Comment by derlade** [comment] 2023-04-30 12:11
Hi @Karen-Intel , I've installed 4314 and also DDU'd and reinstalled the driver, unfortunately to no avail. The crash even occurs on other games now, i.e. in CS:GO after a few minutes of matchmaking. Initially, I suspected some kind of malconfiguration with third-party MSFS software, which seems to be unlikely now. Even if it is some kind of incompatibility though, the driver should never crash like this.

**Comment by Karen-Intel** [comment] 2023-05-02 15:12
> Hi @Karen-Intel , I've installed 4314 and also DDU'd and reinstalled the driver, unfortunately to no avail. The crash even occurs on other games now, i.e. in CS:GO after a few minutes of matchmaking. Initially, I suspected some kind of malconfiguration with third-party MSFS software, which seems to be unlikely now. Even if it is some kind of incompatibility though, the driver should never crash like this.

Hey @derlade that's definitely not expected. In the case of [CSGO](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/295) we did have a case that got fixed with DDU and latest driver, however we have not been able to reproduce the crash in that game anymore.
In the case of MSFS it has been the same case so far. If you want we can keep on trying but we need consistent data to reproduce the issue. We are following the recommendations I shared with you before and no crash has happened so far.
Please share with me if you already have performed the recommended steps and I will keep on trying to reproduce the crash, sounds good? Thanks

Karen

**Comment by Karen-Intel** [comment] 2023-05-03 00:22
@derlade Hi again

Well, the thing is that VIDEO_TDR_FAILURE are pretty difficult to track and reproduce. 
If there are dumps that you have already created and could share, that would be great. I can analyze it and get more details about the culprit with the help of the dev team. 
Question, have you tried an older driver version to see if there's any change? That way we could get to a regression but again, the repro % should be consistent in a machine different to yours.

Also, this forum is only for Windows support and we don't have technicians. Only engineers :)

Karen

**Comment by derlade** [comment] 2023-05-03 14:20
Well, I've found the culprit. Parts of the 8-pin connector to the graphics card got loose, presumably by vibrations or something similar. The problems I've encountered all make sense now: MSFS crashed as soon as it demanded more than (probably) about 100 W of power (which is hard to debug by software, since in Arc Control one can only limit power usage to 95 W), Furmark crashed instantly, probably because it draws maximum power right from the start, CS:GO only crashed after a few rounds, since it is not too demanding of the graphics card most of the time, and so on. 
In hindsight, I should have expected a hardware malconfiguration much sooner, but it's the first time I've had to deal with cables that got loose over time, and not instantly after PC building. 

Thanks for the swift support anyways!

**Comment by Karen-Intel** [comment] 2023-05-03 16:40
Hey @derlade thank you for sharing! 

This info is very useful and we will make sure to inform this situation internally, specially if we start seeing similar behavior.

@IGCIT can you please help to close this issue? Game crashes due to loose GPU power cables

Karen

**Closed** 2023-05-03 17:32 UTC
Labels: Info: Needs Replication, Type: Application Crash
