### ISSUE TITLE
EA App (Launcher) does not work with Driver 31.0.101.4514 BSOD, App won't open.

### ISSUE THREAD

**Issue by gargamel314** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#386] opened 2023-07-12 15:05 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

EA App (Launcher)

### Processor / Processor Number [Required]

i7-13700K

### Graphic Card [Required]

Arc A770

### GPU Driver Version [Required]

- [X] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssu - EA App BSOD & not loading.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12029177/ssu.-.EA.App.BSOD.not.loading.txt)

### Description and steps to reproduce [Required]

So this is with the EA Launcher App, which launches every EA-branded game.

The first time I installed this driver, the EA app would BSOD every time I launched it. Uninstalling 4514 and installing 4502 fixed this. When I tried 4514 again, the app opened fine the first time, then I rebooted the PC, and the app simply wouldn't open. It would begin loading, but the window would remain blank, looking like a Windows 7 window (which is unusual) with nothing inside. It is completely  unresponsive. Uninstalling/reinstalling doesn't accomplish anything - the launcher simply doesn't register as uninstalled, and prompts a "repair" option, but you end up right back in the same situation. Rolling back to 4502, it behaves normally again, but even after DDU and reinstalling 4514, it behaves just like this. I've posted bug reports about this launcher before on these forums, it seems to have a specific issue with the A770. It's clearly unstable, and submitting bug reports to EA has been useless. They don't seem to care.

![Screenshot 2023-07-12 110003](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/124757309/3efc2795-10ec-4807-a4ff-aa9447e24e78)

### Device / Platform

ASUS Strix Z690-A D4

**Comment by Arturo-Intel** [comment] 2023-07-12 16:57
Hello @gargamel314 
I was trying to reproduce this on my side but:
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/a32492f4-a9ac-44a8-88ad-a65eab3a4c4e)
I was able to open the EA app without any trouble, 

We almost have the same rig only I have a 12gen instead of a 13gen.
I have this version of EA app
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/50cdc509-51c2-4de2-8005-5284ad3a6773)

I was wondering if the "Parsec Virtual Display Adapter" was having something to do with, so I reinstalled the Parsec software to test it, unfortunately I couldn't reproduce it

You say you used DDU to reinstall 101.4514 right? did you use "safe mode"?

--r2

**Comment by gargamel314** [comment] 2023-07-12 17:57
I always run it in safe mode. 

I was able to get it to work, but I had to uninstall EA App with no GPU driver installed (just basic Microsoft display driver) and then update to 5414. I got it to load, but in the past it took a couple reboots to start having problems. It might be that EA App gets corrupted over time and starts acting like this. 

I could uninstall parsec - I'm not currently using it, and see if that helps.

**Comment by Arturo-Intel** [comment] 2023-07-12 18:17
I assume we have the same EA app version right?
>...but I had to uninstall EA App with no GPU driver installed ..

AFAIK, the EA app doesn't mess with GPU drivers, I might be wrong, but if this was true, the app would could affects other comp GPUs drivers, which is not happening, at least I didn't find nothing related on Nvidia/AMD forums...

>... I could uninstall parsec - I'm not currently using it, and see if that helps.

I have it installed and it looks it doesn't affect at all

>...  in the past it took a couple reboots to start having problems....

Ok lets keep this thread open, just in case the issue comes again. I will keep trying to see what could be triggering the BSOD on the EA app.

Do you use EA app a lot? I mean, do you play constantly games from it? 
--r2

**Comment by gargamel314** [comment] 2023-07-12 18:58
> I assume we have the same EA app version right?
> 
Correct, mine is the same version.

> > ...but I had to uninstall EA App with no GPU driver installed ..
> 
> AFAIK, the EA app doesn't mess with GPU drivers, I might be wrong, but if this was true, the app would could affects other comp GPUs drivers, which is not happening, at least I didn't find nothing related on Nvidia/AMD forums...
Is it possible something gets corrupted within their app that does not jive with the A770?
here's a link to the original thread that I opened months ago (and logs). the BSOD I saw the other night was the same as in this thread:  https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/283

In the past, launching this app would immediately result in BSOD, and continue consistently on every launch until i uninstalled the Intel Arc driver. It would even BSOD in Safe Mode, but once I used DDU to uninstall, it would function normally. 


> Do you use EA app a lot? I mean, do you play constantly games from it? --r2
I use it 3-4 nights a week for the past couple months. This DRIVER_VERIFIER_DMA_VIOLATION thing shows up very randomly, sometimes just after I install a new Arc driver, sometimes a week later, sometimes it doesn't show up for a month.

**Comment by Arturo-Intel** [comment] 2023-08-21 18:51
Thanks for sharing the vid,
will look at it

-- r2

**Comment by gargamel314** [comment] 2023-08-21 19:01
> AFAIK, the EA app doesn't mess with GPU drivers, I might be wrong, but if this was true, the app would could affects other comp GPUs drivers, which is not happening, at least I didn't find nothing related on Nvidia/AMD forums...

SOMETHING definitely happens when the app launches, even before it lets you sign in. Is it examining your system to see what your system specs are? It's definitely doing something because the Intel Driver is key here! This will probably happen again in the next month. Is there any logs, or maybe a copy of a directory that I should share next time?

Check out the Reddit Sub r/EAApp, I did find other occurrences of this, but no one found a solution. I wonder if they tried reinstalling their GPU driver if it would make a difference. Look here: https://www.reddit.com/r/EAApp/comments/15i88mi/ea_app_not_working/

**Comment by Vivek-Intel** [comment] 2023-08-25 18:09
Hi @gargamel314 

Greetings.

We have been trying to reproduce the issue you have mentioned above but we did not encounter it even single time on multiple setups we tried on,  so it seems very specific to your setup and may be your network.

If display driver is causing a problem to EA app to launch, generally it should either make it crash or silent crash or throw some error results in obtaining some error/info entries in event viewer but as per above description you are not able to launch it at all whenever the issue occurs.

![EA-App](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/114637913/e8cff8d7-6e75-4324-ae01-6d2aca5a4f8d)

We are not ruling out driver's role completely here so here are few things which you can help us with whenever you see the issue :

1: Check if issue occurs without Intel drivers (Uninstall Arc driver and check if issue persists whenever you see the issue )
2: Check if there are any crash entries reported under event viewer when the issue occurs ?
3: You can get EA service logs that will be saved at C:\ProgramData\EA Desktop\Logs to see if there is any obvious debug prints that can help us understand the issue
4: Can you also try changing your network when you see the issue is happening. 

you can update to the 101.4644 which is latest driver now.

**Comment by gargamel314** [comment] 2023-08-25 19:46
[EABackgroundService.log](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12443023/EABackgroundService.log)
[EAGEP.log](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12443024/EAGEP.log)


> 1: Check if issue occurs without Intel drivers (Uninstall Arc driver and check if issue persists whenever you see the issue )
I actually did this in the video, you'll see that I was able to open the same installation of the EA Launcher with no Arc driver installed. This has worked every single time for the past several months. It's the only way to fix this.

> 2: Check if there are any crash entries reported under event viewer when the issue occurs ? 
I actually created another bug report for this earlier in this ticket here: 
https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/283
Those logs are in there, it's the exact same situation happening, but with the added BSOD. I have no idea why I created another ticket instead of updating that one. 

> 3: You can get EA service logs that will be saved at C:\ProgramData\EA Desktop\Logs to see if there is any obvious debug prints that can help us understand the issue
No problem, I have attached those logs to this comment.

I will try the network thing and collect more logs the next time it happens.

**Comment by Vivek-Intel** [comment] 2023-08-28 07:44
@gargamel314 Thanks for sharing logs.

Unfortunately we could not identify error codes from EA service logs but I would request you to delete previous log files from directory and capture logs when you start seeing failure next time so that we can narrow down the logs at failure point only.
Would you like to consider contacting EA support as well on this issue and check what they have to say on this random issue?
And also another way to isolate the issue and see if this workaround works  , can you try killing EA background service from task manager once you see the failure launching the app and then again try to launch the app and check if app can be launched without need to uninstall Intel driver.

**Comment by gargamel314** [comment] 2023-08-28 21:13
>@gargamel314 Thanks for sharing logs.

> Unfortunately we could not identify error codes from EA service logs but I would request you to delete previous log files from directory and capture logs when you start seeing failure next time so that we can narrow down the logs at failure point only.

No problem, thanks for the clarification.

> Would you like to consider contacting EA support as well on this issue and check what they have to say on this random issue?

I already did in this post here: https://answers.ea.com/t5/Bug-Reports-Technical-Issues/BSOD-with-EA-App-launch/m-p/12278633/highlight/true#M17493
You will see EA has absolutely nothing useful to bring to the table for their flaming dumpster fire of a launcher app. They didn't even try to address anything.

> And also another way to isolate the issue and see if this workaround works , can you try killing EA background service from task manager once you see the failure launching the app and then again try to launch the app and check if app can be launched without need to uninstall Intel driver.

I have tried that, it doesn't do anything.

**Comment by Arturo-Intel** [comment] 2023-09-22 19:06
@gargamel314 Do you try it with the last beta driver?
I see you posted a WA in the EA forums, it seems the problem is somehow related with the order of installation (first EA and the Intel drivers) and by the anwser of the EA Comunity manger, seems it also happens in comp. 

Shall we close this case?

**Comment by gargamel314** [comment] 2023-09-22 19:29
I haven't had this happen since August. I'm sorry, if it's my forum post that you're talking about, he's just acknowledging my workaround for uninstalling GPU drivers and reinstalling a "clean install."

![Screenshot 2023-09-22 152611](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/124757309/dbf6eb46-f4f5-4b12-9248-29eb2086a9f0)

 I wouldn't say it's fixed, unless someone actually fixed it. Can this be reopened again if it continues? 

I've had situations where I already had the EA Desktop app installed, uninstalled the Intel ARC drivers and installed an updated driver, and then suddenly getting the above BSOD error. That's usually how it happens. It's never from messing around with the EA App, although often trying to troubleshoot the EA app, i've tried uninstalling it in the process, but that's not the cause. Sometimes it won't happen for days or weeks after making a change to either of those installations, and it just seems to happen on its own.

**Comment by Arturo-Intel** [comment] 2023-09-22 20:00
> Can this be reopened again if it continues?

Sure!, if you find anything new please do!. In the mean time I will work to reproduce it in my end ( I still cant )

--r2


--r2

**Closed** 2023-09-23 00:59 UTC
Labels: Info: Needs Replication, Type: Application Crash

**Comment by gargamel314** [comment] 2023-11-12 04:04
Hi there,

I had the same behavior as before. No BSOD, but the EA App opens with a blank screen now. I am attaching the Windows logs from the start of this glitch, as well as the EA App logs. I did what was asked and deleted the old logs before trying to activate EA Desktop. 
[EABackgroundService.log](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13327115/EABackgroundService.log)
[EA App Error.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13327117/EA.App.Error.zip)
