### ISSUE TITLE
Ghost Recon Breakpoint - Bad performance and crashes.

### ISSUE THREAD

**Issue by jumofogit** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#447] opened 2023-08-21 21:53 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Tom Clancy's Ghost Recon Breakpoint

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [X] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5-1155G7

### Graphic Card [Required]

Intel Iris Xe

### GPU Driver Version [Required]

- [X] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[log.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12402843/log.txt)

### Description and steps to reproduce [Required]

Crashes - play some time, it can crash even in start of campaign after logo fade
Terrible performance - play on DX exe file
Vulkan doesn't show any life at all, crashing even before launching game itself.

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1280x720

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![Снимок экрана (120)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116519368/8e7345c0-53b7-4c86-bfce-f18b1ccfec81)
![Снимок экрана (121)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116519368/a0424c81-b075-464b-a3e1-ccb4abfa0fd9)

### Device / Platform name

MSI Modern 14 B11MOU

### Crash dumps [Required, if applicable]

Not any left, if there is any folder with'em - gonna try to got.

**Comment by IGCIT** [comment] 2023-08-22 07:48
about vulkan crash https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/91#issuecomment-1138635592

you must disable anti-aliasing in settings or config file, then you can enable vulkan

**Comment by jumofogit** [comment] 2023-08-22 11:42
Well...
There is a problem...
https://youtu.be/9m57hY8peCg

**Comment by Karen-Intel** [comment] 2023-08-22 22:06
Hey @jumofogit thank you for the report! Adding to our debug queue, will get back soon with our findings

Karen

**Comment by Karen-Intel** [comment] 2023-08-24 20:00
Hey @jumofogit update!
I've been able to reproduce the crash in the Vulkan game mode. Allow me to report this internally and please leave this post open, in case I have any updates I will let you know

Karen

**Comment by jumofogit** [comment] 2023-08-24 20:36
Sure. Gonna wait and pray for this.

**Comment by jumofogit** [comment] 2023-08-28 10:50
Hey, any update or I'm too early?

**Comment by Karen-Intel** [comment] 2023-08-28 15:34
@jumofogit actually fixes can take from 3 to 6 months to be released so yeah we may have to wait a while longer before having any updates. :) Keep you posted

Karen

**Comment by jumofogit** [comment] 2023-08-30 19:41
@Karen-Intel, a little update here. Just closed the game on newest driver 31.0.101.4669, and I don't exactly know if I'm lucky or game works better, but game haven't crashed for... 40 minutes, I guess? Anyway, performance lowered for eye, FPS can drop up to 20 even on minimal settings with 80% render. And yeah, Vulkan still doesn't work. A little screenshot for a little celebration!
![Снимок экрана (20)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116519368/be88096e-3039-4f55-856b-f83e10911b39)

**Comment by Karen-Intel** [comment] 2023-08-31 15:30
@jumofogit that is good!...I guess xD
No worries I'm still reporting the Vulkan part :D

Karen

**Comment by jumofogit** [comment] 2023-08-31 16:09
nah, FPS is more unstable than on 4644 driver D:

**Comment by jumofogit** [comment] 2023-09-22 12:34
It's been so long... I saw two things globally during this time. First of all, Operation Motherland is a lot more stable, but have less FPS than main campaign. Also, I tried installing DXVK for fun, but dlls got blocked by anticheat. Last two drivers aren't fixing problems (at least on my hardware).

**Comment by jumofogit** [comment] 2023-10-15 12:48
Oh. Well. New driver changed artifacts on Vulkan dramatically.

**Comment by jumofogit** [comment] 2023-11-08 19:40
Nothing changed in particular, still crashes during gameplay after 2 minutes and Vulkan doesn't work too on 4952 driver.

**Comment by Karen-Intel** [comment] 2024-02-08 18:10
Adding internal report information: 18036345513

When fix is in a public release driver we will update this thread

Karen

**Comment by jumofogit** [comment] 2024-05-15 18:54
Any updates on fix development?

**Comment by jumofogit** [comment] 2024-05-21 20:30
Most of the crashes now are related to VRAM outage (DX12)

**Comment by jumofogit** [comment] 2024-06-30 15:29
Any updates soon?

**Comment by Karen-Intel** [comment] 2024-07-01 15:55
Hey @jumofogit the issue is still a WIP on our end. Do you have any other threads where users have reported similar behaviors so I can add to the existing report? Thanks

Karen

**Comment by jumofogit** [comment] 2024-07-01 16:43
Don't think so, altho I tried to launch game on Linux with drm-xe driver and it crashed after showing GRB splash screen, not even showing black screen. Might wanna report it to mesa GitLab, I suppose.

**Comment by rmorera-intel** [comment] 2024-10-08 21:49
Hi @jumofogit sorry for the delay with updates.
The dev team confirmed the issue but addressing it is trickier than expected since it requires cooperation with the game dev and they can shuffle their internal priorities.
For now our best recommendation is to run the game in DirectX 11 mode.

**Closed by rmorera-intel** 2024-10-08 21:49 UTC
Labels: Info: Replicated, Type: Application Crash, Type: Bad Performance
