### ISSUE TITLE
desktop window manager crashes intel arc a580

### ISSUE THREAD

**Issue by papandbuddyg** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#794] opened 2024-06-09 00:21 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

dwm.exe

### Processor / Processor Number [Required]

Ryzen 5 3600

### Graphic Card [Required]

Intel Arc A580

### GPU Driver Version [Required]

31.0.101.5534

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Other Windows build number

22635.3720

### Intel System Support Utility report

[system.txt](https://github.com/user-attachments/files/15749949/system.txt)

### Description and steps to reproduce [Required]

screen goes black and sound goes all wonky then after a few minutes screen and audio goes back to normal i checked event logs and i found desktop windows manager crashed its happened more then once i actually installed the arc a few days ago used ddu i went from the rx580 i never had this issue in the past it just started to happen when i installed my intel arc a580 i tried reinstalling drivers reseating my gpu and checking power connections everything was fine and i still have this issue its seems to def be related to the arc i have provided a membory dump as well
unknown reproducing it happened while i was gaming and also while on idle

### Device / Platform

DESKTOP-K8IJRPO

### Crash dumps [Required, if applicable]

https://drive.google.com/file/d/18sp4cUR5W03E4UV82xsK5BhtU1xwDHhL/view here is a memory dump its the closest thing i could get

### Application / Windows logs

![crash 2](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/107985226/e75a8202-9ade-4609-8911-b02a39d8729f)
![crash](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/107985226/3a1985a0-a50b-4cc6-b847-9477bd5f04cf)
Faulting application name: dwm.exe, version: 10.0.22621.3646, time stamp: 0x85e98d33
Faulting module name: ntdll.dll, version: 10.0.22621.3646, time stamp: 0x0cdcba7b
Exception code: 0xc0000005
Fault offset: 0x000000000002169d
Faulting process id: 0x0x5A8
Faulting application start time: 0x0x1DAB9D56B69E4D4
Faulting application path: C:\Windows\system32\dwm.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 47b16fd4-5d05-4d73-b0d8-10cae049a892
Faulting package full name: 
Faulting package-relative application ID:

**Comment by papandbuddyg** [comment] 2024-06-09 00:31
i did find a few forms with the same issue https://www.reddit.com/r/IntelArc/comments/13l68kq/black_screen_crash_while_gaming/
https://community.intel.com/t5/Intel-ARC-Graphics/If-your-system-crashes-when-using-an-Arc-GPU-try-this/td-p/1479254

**Comment by papandbuddyg** [comment] 2024-06-14 00:11
turning off safe mode did end up being a workaround but ya im glad im reporting the issue

**Comment by papandbuddyg** [comment] 2024-06-20 05:16
it happened one more time i googled the error it seems Error code 0xc0000005 is a common Windows error primarily related to memory access violation. It may occur while backing up files or launching any program or application. When a program/application tries to access memory that is either not allocated or used by another program, the system typically throws this error. it hasnt happened until today after i turned off fast start it stopped for a bit but it happened today
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/107985226/ce18076b-4ff9-434e-9101-e17ee5770e42)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/107985226/c8bf1e59-6a02-446a-a8c4-7ae92991beec)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/107985226/3edc853d-0210-42d0-a16a-7babcd135535)

**Comment by mujeeb-intel** [comment] 2024-08-02 22:36
Hey @papandbuddyg could you try with the latest graphics driver, I could not reproduce this issue.

**Comment by papandbuddyg** [comment] 2024-08-04 23:20
ya i actually submitted a bug report to microsoft as well it seems to be a windows issue @mujeeb-intel

**Comment by mujeeb-intel** [comment] 2024-08-05 16:39
ah, I see. Can i go ahead and close this ticket then? and if you want to refer back, you can always do that. @papandbuddyg

**Closed** 2024-08-05 17:46 UTC
Labels: Info: Needs Replication, Type: Application Crash
