### ISSUE TITLE
Disciples Liberation freezes/crashes constantly

### ISSUE THREAD

**Issue by Baboonfighter** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#89] opened 2021-10-29 19:57 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Disciples Liberation

### Game Platform [Required]

- [X] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Other (please specify)

### Processor / Processor Number [Required]

11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz

### GPU Driver Version [Required]

- [X] 30.0.100.9894 (*latest*)
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11
- [ ] Windows 10 21H2 (*Insider Preview*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [X] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Description and steps to reproduce [Required]

Crashes in first level. Such as enemy by treasure chest.

### Device / Platform

Intel GPD Win Max 2021

### Game Settings

Medium graphics but crashes on low also

**Comment by estebanr863** [comment] 2022-03-09 17:14
Hi @Baboonfighter 

A possible fix for this issue was included in the [latest drivers](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html) version 30.0.101.1404. Can you test if the issue is fixed for you?

**Comment by Baboonfighter** [comment] 2022-03-14 09:28
Hi,
This appears to be fixed now. Thank you so much for this.
    On Wednesday, 9 March 2022, 17:14:27 GMT, Esteban ***@***.***> wrote:  
 
 


Hi @Baboonfighter

A possible fix for this issue was included in the latest drivers version 30.0.101.1404. Can you test if the issue is fixed for you?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Closed** 2022-03-14 09:45 UTC
Labels: Info: Needs Replication, Type: Application Crash
