### ISSUE TITLE
Line artifacts/corruption in video streamed/recorded with OBS 30.0.0

### ISSUE THREAD

**Issue by zrmdsxa** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#726] opened 2024-03-05 01:45 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

OBS

### Processor / Processor Number [Required]

Ryzen 7600X

### Graphic Card [Required]

Intel Arc 750

### GPU Driver Version [Required]

31.0.101.5330

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[report.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14489235/report.txt)

### Description and steps to reproduce [Required]

It seems to be a very rare thing that happens when I stream or record. I press the stream/record button and the video with look like this but looks fine in the OBS preview. The problem goes away if I end stream/recording and start it again but it may still happen.

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/5502880/893788ad-e1cf-4726-a40d-65e172f26886)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/5502880/744aa8d0-0e59-40c9-b9c5-eaaf851fb7ae)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/5502880/80188a00-bfb1-4047-94ff-9853a7633c44)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/5502880/41ef3009-466b-4f82-80be-b3de01eb7aac)

Previous times it has happened: 
https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/282#issuecomment-1528177668
https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/282#issuecomment-1537356224
https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/282#issuecomment-1791737541

**Comment by rmorera-intel** [comment] 2024-03-06 00:10
Hi @zrmdsxa 
I'll set a system to reproduce this issue. 
Have you identified any specific instance or scenario in which the issue can be consistently reproduced? I'm asking because I saw from the comments on #282 that replicating this issue is tricky - actually 3 other Intel engineers tried replicating this to no avail. 
I also checked the [OBS Forums](https://obsproject.com/forum/list/windows-support.32/) to find out if this is happening to other users but couldn't find any hit. Have you reported this to OBS dev just in case?

**Comment by rmorera-intel** [comment] 2024-03-07 19:06
Hi @zrmdsxa I haven't been able to reproduce this issue on OBS 30.0.2 (64-bits). So far all the recordings I make preview and end up ok.
Did you get the chance to report this to the app dev?

**Comment by zrmdsxa** [comment] 2024-03-08 03:05
I made a post in their Windows support forum yesterday but no replies 

https://obsproject.com/forum/threads/line-artifacts-corruption-in-video-streamed-recorded-with-obs-30-0-0.173848/

**Comment by rmorera-intel** [comment] 2024-03-11 15:46
Thanks! I'll check it out. 
If it ok with you I'll close this one while we track it from OBS's forum (believing it to the an app issue for now).

**Closed** 2024-03-12 19:09 UTC
Labels: Info: Needs Replication, Type: Graphical Glitches
