### ISSUE TITLE
Death stranding stuck for minimum 10 minutes on game loading time, performance are much worse on newer drivers, also crash ( see the picture) and weird glitches happening see the video

### ISSUE THREAD

**Issue by mva94** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#64] opened 2021-06-06 19:34 UTC
#### Checklist [README]

- [x] Device is not undervolted nor overclocked.
- [x] Device is using the [latest drivers](https://downloadcenter.intel.com/download/30381/Graphiques-Intel-Pilotes-DCH-Windows-10).
- [x] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Required]
Death stranding 
---
#### Game Platform [Required]
- [x] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Other

---
#### Processor / Processor Number [Required]
I7 1165g7
---
#### GPU Driver Version [Required]
- [x] 27.20.100.9616 (*latest*)
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

---
#### Rendering API [Required]
- [ ] Vulkan
- [ ] OpenGL
- [x] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

---
#### Windows Build Number [Required]
- [x] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)

---
#### Description and steps to reproduce [Required]

1. Start the game,  it will take about 10 minutes just to start...
2. In game performances are 50 percent worse than previous drivers with no reason,  looks like there is a bottleneck somewhere as for some reason tdp is stuck at 12-13w tdp
3. 

---
#### Device / Platform [Optional][Recommended]

---
#### Game Settings [Optional][Recommended]

---
#### Save game (*if possible, could help solve the issue faster*) [Optional]

---
#### Windows mini dump (*small memory dump*) (*if available*) [Optional][Recommended]

---

**Comment by mva94** [comment] 2021-06-07 12:00
![Uploading 20210607_135611.jpg…]()

**Comment by mva94** [comment] 2021-06-07 13:04
Here is the crash 
![20210607_135611](https://user-images.githubusercontent.com/78859716/121021404-a5304c00-c7a1-11eb-80e4-8505a62703d3.jpg)

**Comment by mva94** [comment] 2021-06-07 19:49
@leoben2 
Video showing weird glitches 
https://youtu.be/SwVoGzEMgjU

**Comment by PacoAvelar** [comment] 2021-09-02 03:10
I just booted and played from New game up to grown up character on:
i7 1165G7
16 GB ram
Win 11
GPU Driver 9862
Screen resolution 720p,
![image](https://user-images.githubusercontent.com/29181120/131775452-4923cc78-b4a7-4529-b442-0678eae3b7e0.png)

**Comment by PacoAvelar** [comment] 2021-09-16 20:58
Issue still there on 9894

**Comment by PacoAvelar** [comment] 2021-09-27 20:19
still here
	Driver version:	30.0.100.9922

**Comment by estebanr863** [comment] 2021-11-11 16:23
Hi all,

We were able to reproduce the game crash issue reported by @KaeAISa and it is now in our driver development team’s queue.

Regarding the graphics corruption issue with the grass “shooting up to the sky” reported by @PacoAvelar. This issue was previously reported internally, and a possible fix has now been developed. We expect this fix to be included in the next driver release. I’ll keep you posted when this new driver is released so you can help test this fix.

**Comment by KaeAlSa** [comment] 2021-11-11 16:36
@estebanr863 great thank you!

**Comment by estebanr863** [comment] 2021-11-11 16:42
@PacoAvelar the new driver is now live https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html. This driver includes the possible fix for the issue you reported. Please help us test it and let us know.

**Comment by estebanr863** [comment] 2021-11-11 17:07
@ KaeAlSa, just to set the correct expectations, our development team has a very large queue of issue to work on. So, this fix could take from 3 to 6 month to be included in a driver release.

**Comment by KaeAlSa** [comment] 2021-11-11 17:41
@estebanr863 I completely understand, it's nice to have it on the list at all. I can wait. I did try the new version of the driver and obviously the crash still happens. I appreciate you checking it out.

**Comment by PacoAvelar** [comment] 2021-11-13 00:12
Got a different error this time with latest driver, I am trying to get to the same area that was always doing graphical glitches
https://youtu.be/di1uhkgbsl8

**Comment by PacoAvelar** [comment] 2021-11-13 00:34
After that crash, game gets playable with no graphical glitches
![DS_New](https://user-images.githubusercontent.com/29181120/141598477-545c33cd-2c3e-4ef1-bb2c-d4d77ed80fb7.png)
s

**Comment by KaeAlSa** [comment] 2021-12-22 01:12
I am no longer crashing while using tools on the latest 1191 driver!

**Comment by estebanr863** [comment] 2021-12-22 19:04
Hi all,

Yes, we can confirm the issue is no longer present with driver 30.0.101.1191

@IGCIT abd @mva94, can we close this one?

**Closed** 2022-01-14 22:32 UTC
Labels: Info: Needs Replication, Type: Application Crash, Type: Bad Performance, Top 5
