### ISSUE TITLE
Arc Control Performance Tuning sets different settings after driver update.

### ISSUE THREAD

**Issue by Code-Vlue** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#555] opened 2023-10-05 23:34 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Arc Control

### Processor / Processor Number [Required]

Ryzen 5 3600

### Graphic Card [Required]

Arc A750

### GPU Driver Version [Required]

- [X] 31.0.101.4885
- [ ] 31.0.101.4826
- [ ] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssulog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12825550/ssulog.txt)

### Description and steps to reproduce [Required]

Issue is a regression, voltage offset changed from 0 to +55 and power limit changed from 228 to 190, also fan curve was reset to auto, performance slider however remained the same at 45.

**Comment by Gabriela-Intel** [comment] 2023-11-15 00:13
This seems to be the same issue as #502 

I'll check back here once the new version of Arc Control with the fix is available.

**Comment by Gabriela-Intel** [comment] 2023-12-14 22:48
The new version of Arc Control is available with today's (12/14) driver update. Can you please see if the issue is resolved? You can find the driver [here](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html?).

**Comment by Gabriela-Intel** [comment] 2023-12-18 22:51
@Code-Vlue Have you had the chance to check this?

**Comment by Gabriela-Intel** [comment] 2024-01-02 17:53
@IGCIT Please close this one. We haven't received a response on the status.

**Closed** 2024-01-02 17:59 UTC
Labels: Info: Needs Replication, Type: Arc Control
