### ISSUE TITLE
can not fully disable Intel® Display Power Saving Technology in Intel Graphics Control Center

### ISSUE THREAD

**Issue by pcslide** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#643] opened 2023-12-16 15:42 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel® Display Power Saving Technology

### Processor / Processor Number [Required]

 i3-1215U

### Graphic Card [Required]

None

### GPU Driver Version [Required]

31.0.101.5074

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

https://community.intel.com/t5/Graphics/Washed-out-or-faded-colours-on-Intel-Iris-Xe-Graphics/m-p/1448656/thread-id/113124/highlight/true?attachment-id=89360

### Description and steps to reproduce [Required]

 Intel® Display Power Saving degrades color accuracy of internal display of laptop profoundly in low light conditions.  It is enabled by default after driver installation.   There is a toggle to disable it through Intel Graphics Control Center.  The issue is the toggle doesn't work as it supposed to be anymore in Windows 11 23H2, and the toggle is missing in Windows 10.  On Win10, the only tools, I found, that can disable it completely is https://github.com/orev/dpst-control
I hope Intel can change the default behavior of the driver,  the function should be disabled by default.  
The full description of the issue  and  how it affects user experience can be found
https://community.intel.com/t5/Graphics/Washed-out-or-faded-colours-on-Intel-Iris-Xe-Graphics/m-p/1448656/highlight/true#M113124

**Comment by pcslide** [comment] 2023-12-16 16:01
As for how to tell the color is distorted by Intel® Display Power Saving, find yourself a dim room, turns the brightness of the internal display down to 10 per cent, uses portraits of someone with fair/light skin tone,  the face will look orangish when Display Power Saving is enabled.

**Comment by Vivek-Intel** [comment] 2023-12-20 17:54
@pcslide I see more than one issue here so before I try to simulate the issue at our end , please confirm below.
1: Display power saving technology (DPST) washout colors when enabled (in very specific situation - dim light, bright pixels, low brightness)
2: issue 1 continues even if DPST is disabled from Intel graphics command center 
3: toggle is missing on win 10 
4: feature request - should be disabled by default.

can you share your system specification with latest driver, ssu you shared is using very old driver ? are you using OEM drivers ?
does disabling Change brightness based on content from OS settings help you with the issue?

**Comment by pcslide** [comment] 2023-12-21 06:48
@Vivek-Intel 
I think your summary is almost perfect, except I would want to emphasize the color issue manifests on internal display of the laptop and I need to apply [orev/dpst-control](https://github.com/orev/dpst-control) patch after every driver update/installment to resolve the issue.  
In addition,  toggle is missing on win 10 for the internal display.  However, if I connect a external display, the toggle appears for that external display.
As for the "screen brightness and contrast based on content" setting from OS,  my laptop doesn't have that setting on Win10/11.
[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13737074/igcit_ssu.txt)

**Comment by Ilya-intel** [comment] 2024-01-09 16:38
@pcslide 
The issue seems to be isolated by some laptop models.
Mine is fine :)
Could you uninstall current IGCC and install IGCC Beta from MS Store (https://apps.microsoft.com/detail/9NMR79ZTJFTC?hl=en-us&gl=US) for testing purposes?

**Comment by Vivek-Intel** [comment] 2024-01-24 09:02
@pcslide can you contact your laptop OEM support because OEMs can disable this feature in their designs as you say you dont see this option in win10.
We have tried to simulate a per your suggestion but in none of the laptops we have observed this issue and we do not have specific model to try outs.

You see color distortion on both win 10 (No DPST option available in your laptop) and Win11 (regardless of DPST toggle value) that suggest that it could be some other settings implemented by OEM or windows color settings that might affect . Can you try contacting OEM support.

**Comment by pcslide** [comment] 2024-01-26 11:07
@Vivek-Intel 
I had talked with OEM of my laptop and they have no idea that this feature exits.  So I told them maybe they can tweak the firmware somehow to disable the feature.  They promised they will ask OD of this model about that.  I hope I didn't lead them to bark up the wrong tree.

**Comment by Vivek-Intel** [comment] 2024-01-30 07:14
@pcslide best route to this issue would be let OEM/ODM root cause this issue with their model and they can contact Intel if they find the issue in their design/model is due to one of the Intel driver features.

**Comment by Vivek-Intel** [comment] 2024-02-08 17:59
@IGCIT please help close this issue , user needs to contact OEM support for this issue.

**Closed** 2024-02-08 18:25 UTC
Labels: Info: Needs Replication, Type: Support
