### ISSUE TITLE
Discord screen sharing application crash

### ISSUE THREAD

**Issue by BlauerToad** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#748] opened 2024-03-26 11:46 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Discord

### Processor / Processor Number [Required]

AMD Ryzen 5 2600X

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

31.0.101.5379

### Other GPU Driver version

31.0.101.5382
31.0.101.5444
31.0.101.5445

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14757715/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Open Discord, join any voice channel and start streaming your entire screen.

**Update:** The problem seems to be related to the transmission quality of the screen sharing.

Using the "Smoother video" quality setting, Discord operates fine; however, selecting the "better readability of texts" quality setting leads to the mentioned application crash.

Notes:
1. the error almost always occurs. Streaming sometimes works after a restart, but very rarely.
2. while the entire screen cannot be streamed, sometimes the individual applications can still be streamed (e.g. VS Code, Discord itself, IGCIT Helper). However, this does not mean that all application streams always work. Microsoft Edge application streams may or may not work.
3. deactivating hardware acceleration solves the problem.

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92584570/a1d12a40-22f9-4c04-b233-52920fc0e323

### Device / Platform

Monitor Information: Alienware AW2724DM - 2560x1440

### Crash dumps [Required, if applicable]

No crash dumps could be extracted with the IGCIT Helper.

### Application / Windows logs

I haven't found any logs from Discord either

**Comment by BlauerToad** [comment] 2024-03-26 21:10
>  it has to do with hardware acceleration

Well it seems so. As stated above, discord does not crash anymore when hardware acceleration is turned off.

> If your application does not crash, it'll black out the screen (for example, a video player on YouTube which uses HW accel)

Just tried screen sharing Microsoft Edge (just the application, not whole screen) and scrolling through YouTube and watching some videos, nothing got blacked out for the viewers of my the stream. 

But I'm not sure if I understood your message correctly. Please feel free to correct me if I misunderstood it.

**Comment by phyziyx** [comment] 2024-04-16 13:25
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/96657278/ce3da27e-ead4-4ed3-97ea-cee5c1957e7a)

Is this ever going to be looked into or resolved? I had this crash on a game now, and the only solution is to completely disable CEF acceleration in every application (some may not even offer such an option!)

**Comment by BlauerToad** [comment] 2024-04-19 16:58
I would also appreciate feedback on whether the problem has been noticed.

**Comment by Felipe-Intel** [comment] 2024-04-19 19:43
Hello @BlauerToad sorry for the delay. I have to set up my lab system for this. I was working with a couple other things. Rest assure I'll communicate my results and actions once I run the lab.

**Comment by BlauerToad** [comment] 2024-04-19 21:11
Hello @Felipe-Intel, no worries about the delay. Looking forward to hearing about your results. Thanks for keeping us updated.

**Comment by Felipe-Intel** [comment] 2024-05-08 18:08
Hello all. Just tested again with driver 101.5445 and the app is not crashing: screen share + test readability. Can you check on your side if you still see the issue?

**Comment by BlauerToad** [comment] 2024-05-08 18:28
Hello, thanks for checking back. I am still facing the crash.

**Comment by Felipe-Intel** [comment] 2024-05-08 20:57
Thanks for testing. For some reason in my system doesn't fail right away after installing a new driver, but I get it to fail again. 
This issue seems to be happening only on Windows 10. We suggest to upgrade your system to Windows 11 to avoid this issue. 

If you prefer or have to stay on Windows 10, please try one the following workarounds:

- This issue doesn't happen if you share an Application regardless of the Stream Quality setting. If possible share only an app window. Or,

- This issue doesn't happen with Smoother Video setting in Stream Quality regardless of the shared source. If possible share only using this Stream Quality setting

Finally, please report this issue to [Microsoft Windows Support.](https://support.microsoft.com/es-es/windows)

We will do our due diligence in promoting this issue to MSFT from our end and co-work to try to find a solution. Said that, Windows 10 support will end October, 2025. We can't commit to time frame for this to be fixed. 
Would it be ok if we close this ticket? Please share your ticket number with Microsoft so we can add it to our report.

**Comment by BlauerToad** [comment] 2024-05-09 19:08
Thank you as well,

at least the error is reproducible and not a “but it works on my machine” type.

I still have some questions:

- How should I report the error to Microsoft? The support article you linked has no obvious way to contact Microsoft.

- Should I use the “Feedback Hub” or the “Get Help” app? It seems like the “Get Help” app only provides a live chat. Does this create a support ticket?

- Do you want me to share Microsoft's support ticket number with you (if I get one) or should I share this GitHub issue with Microsoft?

Thanks for your investigations.

**Comment by Felipe-Intel** [comment] 2024-05-10 15:01
@BlauerToad we got some feedback from our on-site point of contact with Microsoft. We will continue debugging this with them. I'll keep this ticket open and update you with news as soon as I have them. In the meantime you can still follow the workaround options I posted before. A third one is to force Windows to use the integrated graphics instead, but this is not possible in your specific case. 

From your side, there is no need to create a ticket with Microsoft. For future reference, you can go "[contact them](https://support.microsoft.com/contactus?ContactUsExperienceEntryPointAssetId=S.HP.SMC-HOME)" or "[ask the community](https://answers.microsoft.com/)"

**Comment by phyziyx** [comment] 2024-05-12 19:44
I know this is a Discord specific report, but I guess this also applies to Google Meet on Chromium/Google Chrome when sharing entire screen.  Although the application does not crash, there is an entire black screen for a mere second or two.  Perhaps this is related?

**Comment by Felipe-Intel** [comment] 2024-06-03 22:31
Hi all, this was in the end root caused to the OS. So as mentioned before, if you want to report this issue, follow the links in my previous comment. And if you must stay in Win10, remember the [workaround](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/748#issuecomment-2101441862) to avoid crashes. 

I will proceed to close this issue.

**Closed by Felipe-Intel** 2024-06-03 22:31 UTC
Labels: Info: Replicated, Type: Application Crash

**Comment by BlauerToad** [comment] 2024-06-04 19:38
Hi Felipe, thanks for checking back. Do you have any further information for us? Will this issue be fixed in future Windows 10 Updates? Since you investigated the issue with Microsoft, they should aready know about it. I hope it does not need hundreds of mad useres reporting this issue further to Microsoft, that they will hopefully fix it.

As it seems, this issue only occurs with Intel Arc graphic cards (neither AMD nor Nvidia), I also see Intel as having a responsibility to tell Microsoft to fix this problem. We all know, that Windows 10 will be EOL Oct. 2025, but we also know that Windows 10's market share is still on par with Windows 11.

So I hope that this issue will not be played down and that Intel will still work towards a solution.

**Comment by Felipe-Intel** [comment] 2024-06-04 21:02
For updates on this issue, please check [this article](https://www.intel.com/content/www/us/en/support/articles/000098842.html)

**Comment by BlauerToad** [comment] 2024-06-05 07:59
Thank you for your assistance 👍
