### ISSUE TITLE
Vulkan format request: VK_FORMAT_S8_UINT

### ISSUE THREAD

**Issue by Morph1984** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#104] opened 2021-11-17 22:08 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

yuzu

### Processor / Processor Number [Required]

All processors with Gen9, 9.5, Gen11, and Gen12 iGPUs

### GPU Driver Version [Required]

- [ ] 30.0.101.1121 (*latest*)
- [X] 30.0.101.1069
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11
- [X] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Description and steps to reproduce [Required]

The `VK_FORMAT_S8_UINT` format is currently not supported by any Intel Windows Vulkan driver.
This is used in Nintendo Switch emulation, with emulators such as [yuzu](https://github.com/yuzu-emu/yuzu).
I have implemented the use of this format in the following [PR](https://github.com/yuzu-emu/yuzu/pull/7357) within yuzu, however, Intel does not have support for this format. At the moment, only NVIDIA has support for this format on their proprietary Windows drivers.

This format is available on OpenGL as `GL_STENCIL_INDEX8`. Is it possible to implement in Vulkan?

**Comment by estebanr863** [comment] 2021-12-10 15:44
Hi @Morph1984,

Please open a support ticket with [Intel at https://www.intel.com/content/www/us/en/support/contact-intel.html](Intel at https://www.intel.com/content/www/us/en/support/contact-intel.html), so your issue can be routed to the correct team supporting developers.

**Comment by Valkirie** [comment] 2022-10-28 05:01
> Hi @Morph1984,
> 
> Please open a support ticket with [Intel at https://www.intel.com/content/www/us/en/support/contact-intel.html](Intel at https://www.intel.com/content/www/us/en/support/contact-intel.html), so your issue can be routed to the correct team supporting developers.

@EstebanIntel can you reconsider this issue?

**Comment by EstebanIntel** [comment] 2022-11-07 23:46
Hi @Valkirie,

The problem with emulator issues, is that we have no legal way of reproducing the issues, as the games can't be legally acquired.

My advice actually get this resolved would be to have the developers of Yuzu to post their issue on our [Developer Forum](https://community.intel.com/t5/Developing-Games-on-Intel/bd-p/developing-games-graphics), where our support engineers specialized on the topic will pick it up.

**Comment by IGCIT** [comment] 2022-11-08 07:49
Hi @EstebanIntel,

there is no need for games nor yuzu, the OP request is to implement a vulkan extension that is not available in windows intel vulkan driver, that, if i'm not wrong, is available in intel anv driver (mesa)

**Comment by EstebanIntel** [comment] 2023-03-07 23:11
Hi @Morph1984, after consulting with our development team, due to their limited resources and needing to work on other higher priority game issues, VK_FORMAT_S8_UINT won't be supported on Arc A-Series GPUs.

**Closed** 2023-08-31 17:42 UTC
Labels: Type: Feature Request, Info: Won't fix
