### ISSUE TITLE
Forza horizon menu broken and performances have gotten worse with the latest beta version 

### ISSUE THREAD

**Issue by mva94** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#57] opened 2021-05-28 12:25 UTC
#### Checklist [README]

- [X] Device is not undervolted nor overclocked.
- [x] Device is using the [latest drivers](https://downloadcenter.intel.com/download/30381/Graphiques-Intel-Pilotes-DCH-Windows-10).
- [X] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Required]
Forza horizon
---
#### Processor / Processor Number [Required]
I7 1165g7
---
#### GPU Driver Version [Required]
- [x] 27.20.100.9616 (*latest*)
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

---
#### Rendering API [Required]
- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [x] DirectX11
- [ ] DirectX10
- [ ] DirectX9

---
#### Windows Build Number [Required]
- [x] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)

---
#### Description and steps to reproduce [Required]

1. 
2. 
3. 

---
#### Device / Platform [Optional][Recommended]

---
#### Game Settings [Optional][Recommended]

---
#### Save game (*if possible, could help solve the issue faster*) [Optional]

---

**Comment by evang-x** [comment] 2021-10-13 22:50
Hello, 
 
Can you please provide information on which Forza Horizon and edition you are having issues with?

**Comment by PacoAvelar** [comment] 2021-10-13 23:12
Not sure about performance, but ln the Game pass edition I was able to reproduce the crash on the menu shen going to the settings

**Comment by PacoAvelar** [comment] 2021-10-13 23:27
Forza horizon is 4

**Comment by estebanr863** [comment] 2021-11-11 16:52
Hi all,

The new driver version 30.0.101.1069 can now be downloaded at https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html.

This driver includes the possible fix for both the performance issue and the game crash reported. Please help us test it and let us know.

**Comment by Saracchini** [comment] 2021-11-11 17:43
Tested 1069. 
Managed to go through the entire tunning screen and options and so far I had no crashes.  Did a 20 minutes test going though a variety of menus and options that previously were very unstable and did not had crashes of any sort.
I did not see loss of performance so far too.
I'll report if I see further issues.

**Comment by Saracchini** [comment] 2021-11-11 22:22
Ran for almost 3 hours in almost one sitting(never it happened before !). No crashes of any sort. The only visible issue I could find is black car logos in certain occasions. Besides that performance is still good and very stable !

**Comment by halljames** [comment] 2021-11-11 22:58
So, my official Forza Horizon 4 testing with intel drivers 1069
Time played in total : 4 hours
Number of times oxp put into standby, and resumed while game running : 2
Times Battery warning appeared : 1
Times entered settings menu to tweak display settings : 2
Times entered game menu and map : 5
FPS at 1440 x 900 and Medium Dynamic Settings : 50 - 60
Number of crashes : 0

Test still ongoing, very happy with results.

**Comment by mva94** [comment] 2021-11-11 23:02
@halljames appreciate it, will still wait a day or so before closing the issue to make sure nobody raises any new/other issues

**Comment by Saracchini** [comment] 2021-11-12 11:30
Managed to reproduce the black borders. The issues do not show in Photo mode, but do show in free-roaming. Specially if the car is covered on decals.

Photo mode (how logos are supposed to be):
![forzaok2](https://user-images.githubusercontent.com/18572281/141460187-d511024a-3283-4848-b6e0-50976ed6d181.png)
![forzaok3](https://user-images.githubusercontent.com/18572281/141460196-d571c82e-0c50-4ea4-b328-83acad114574.png)

Free-roaming/in-race (black border):
![forzanok](https://user-images.githubusercontent.com/18572281/141460226-26004dd3-f830-47f8-b902-2868162b4497.png)
![forzanok2](https://user-images.githubusercontent.com/18572281/141460236-0ca0283c-067c-4a9a-919a-0f063563c64b.png)

**Comment by Bryce-7995** [comment] 2021-11-13 00:23
@Saracchini @mva94 Looks like the fix is holding for crash and poor perf. We should close this out then. Is there an issue opened for the black border? I'd suggest do a search and if not entered already please do so. Thanks for all the effort folks! Love that we're getting these issues closed out!

**Closed** 2021-11-13 08:44 UTC
Labels: Info: Replicated, Type: Regression, Top 5
