### ISSUE TITLE
MSAA doesn't do anything in Trackmania

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#668] opened 2024-01-11 11:47 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Trackmania (2020)

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

31.0.101.5084

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 11.01.2024.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13902619/Intel.SSU.11.01.2024.txt)

### Description and steps to reproduce [Required]

Toggling MSAA on simply doesn't do anything, both visually and performance-wise. It goes along what I noticed about Arc cards almost always having issues with MSAA in a ton of games

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Max, no TAA

### Device / Platform name

ASUS PRIME Z790-P WiFi D4

**Comment by Felipe-Intel** [comment] 2024-01-23 00:03
Hello @TheWonderfulTartiflette I tested the game with the setting turned off and set to x16 with "Nice AA" turned off. As you can see below, there is a difference between settings showing improvement in the jagging. 

OFF 
![Screenshot 2024-01-22 174820](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/101756820/223de50a-5c17-4e81-b92d-c09215dfbc18)


x16
![Screenshot 2024-01-22 174910](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/101756820/86612d40-d794-4f9c-ad38-c6489ee8dd10)

About the performance, as mentioned in your other case, when enabling MSAA you can expect reduction in the performance. Consider it a good outcome if enabling MSAA in this game doesn't affect the performance.

I'll proceed to close this issue since I wasn't able to reproduce.

**Closed by Felipe-Intel** 2024-01-23 00:03 UTC
Labels: Info: Needs Replication, Type: Support
