### ISSUE TITLE
Forza Horizon 4 - Black borders around logos and decals

### ISSUE THREAD

**Issue by Saracchini** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#98] opened 2021-11-15 08:21 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Forza Horizon 4

### Game Platform [Required]

- [X] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

1165g7

### GPU Driver Version [Required]

- [X] 30.0.101.1069 (*latest*)
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11
- [ ] Windows 10 21H2 (*Insider Preview*)
- [X] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Description and steps to reproduce [Required]

 Issue: logos and decals of the vehicles in free-roaming mode and races shows a black border around them. Issue can happen randomly, and never show up in photo mode. 
 
Most of the time, it happens immediately after exiting with your vehicle in the garage into free roam. Some times it does happen when starting an event race. Issue happens more often when the car is using a decoration with a high amount of decals. 
 
 Game is in default settings set by the game (almost everything in low, 30 fps frame cap).
 
 Photo mode (issue not occuring, logos as supposed to show up):
 

![](https://user-images.githubusercontent.com/18572281/141460187-d511024a-3283-4848-b6e0-50976ed6d181.png)

![](https://user-images.githubusercontent.com/18572281/141460196-d571c82e-0c50-4ea4-b328-83acad114574.png)

Free roaming mode (black borders showing up in the same vehicles as above)
 
![](https://user-images.githubusercontent.com/18572281/141460226-26004dd3-f830-47f8-b902-2868162b4497.png)

![](https://user-images.githubusercontent.com/18572281/141460236-0ca0283c-067c-4a9a-919a-0f063563c64b.png)

### Device / Platform

GPD Win3 1165g7

### Game Settings

Default settings set by the game. 
30 fps lock

**Comment by estebanr863** [comment] 2021-12-02 18:39
Hi @Saracchini, we were able to reproduce the issue and escalate it ot our driver development team. I'll let you know when the possible fix is included in a driver release.

**Comment by estebanr863** [comment] 2022-02-08 18:02
Hi @Saracchini,

A possible fix for this issue was included in the recently released driver version 30.0.101.1340. Can you please preform a [clean install](https://www.intel.com/content/www/us/en/support/articles/000057389/graphics.html) of the [latest drivers](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html) and test if the issue is fixed?

**Comment by Saracchini** [comment] 2022-02-08 20:42
I tested with the same vehicles on the picture above and three more problematic ones (one Porsche showed black headlights because  texture on top of it that was being blackened). No black borders in any of these ! The cars looks all correctly rendered. 
The game, however is not anymore in a vert playable state due UI slowing down severely ( reported in this issue [here](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/108))

**Closed** 2022-02-12 10:29 UTC
Labels: Info: Needs Replication, Type: Graphical Glitches
