### ISSUE TITLE
Weird West - Intro Video black screen hard-locking the device in DX12 mode

### ISSUE THREAD

**Issue by Saracchini** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#117] opened 2022-04-03 11:19 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Weird West

### Game Platform [Required]

- [X] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel 1165g7

### GPU Driver Version [Required]

- [X] 30.0.101.1660 (*latest*)
- [ ] 30.0.101.1631
- [ ] 30.0.101.1404
- [ ] 30.0.101.1340
- [ ] 30.0.101.1191
- [ ] 30.0.101.1121
- [ ] 30.0.101.1069
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11
- [X] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

[ww_igcit_ssu_1660.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/8404334/ww_igcit_ssu_1660.txt)

### Description and steps to reproduce [Required]

- Set launch parameters as "-dx12" on steam (standard to any Unreal Engine game).
- Open game as normal
- Video plays, audio can be heard, but screen is totally black, and device do not respond
- Hard lock up: CTRL+ALT+DEL, ALT+TAB, or any key press has no effect
- Device has to be rebooted with power button

Note: the game supports DX12 mode as reported by users of different graphics cards. Game run normally in DX11 mode. 

### Game graphic quality [Required]

- [ ] Low
- [X] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1280x720

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Issue happens with any settings before reaching even the game menu.
Attempted to start the game in Windowed mode but game forces full-screen in intro video (which then causes a hard lock-u

### Device / Platform name

GPD Win3 1165g7

### Crash dumps [Required]

No crash dumps available.

**Comment by Saracchini** [comment] 2022-04-27 09:49
Issue persists with 1934 Beta driver. If one wait enough in the black screen, the device will TDR after a while, even with the TDR tolerance time set to very high values.

**Comment by Saracchini** [comment] 2022-05-10 21:44
Issue seems to be attenuated in 1960 driver. I can enter in the game in DX12 mode mode and performance is acceptable. Instead TRDs in the intro screen, I'm now occasionally having "Unreal Engine is exiting due to D3D device being lost : error DXGI_ERROR_DEVICE_REMOVED with Reason: DXGI_ERROR_DEVICE_HUNG"

**Comment by IntelSupport-Arun** [comment] 2022-05-16 03:55
Hi @Saracchini, The issue has been verified on our side, and we are able to reproduce it. We will be working on a fix. I want to give you a heads up that the fix may take 3 to 6 months to be included.

**Comment by estebanr863** [comment] 2022-07-22 15:59
Hi @Saracchini,

Our driver development team is experiencing a high volume of requests for fixes on game issues. And since we have limited resources, this means that fixes for issues on games outside of our top games list (we maintain an internal list of top games, considering the most played, recently released, etc.) will need to be put on hold. The fix for this issue falls into this category, so we currently cannot commit to target date for this fix to be released. I’ll update you once the development of a fix for this issue is resumed.

**Comment by EstebanIntel** [comment] 2022-10-27 00:25
Hi @Saracchini,

A possible fix for this issue is included with our latest driver version [31.0.101.3790](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html). Can you please install this version and test it?

**Comment by Saracchini** [comment] 2022-10-27 15:26
Tested here with 3790, loading a city map (Quickbend). No issues, TDRs or crashes with DX12 mode. I'll further test but the game seems really in  stable state now in DX12.

**Comment by EstebanIntel** [comment] 2022-11-04 22:57
Thanks for testing @Saracchini! Can this be closed?

**Closed** 2022-11-06 20:28 UTC
Labels: Info: Needs Replication, Type: Application Crash
