### ISSUE TITLE
Intel Arc A-Series GPUs VFIO (Startup / Shutdown)

### ISSUE THREAD

**Issue by Yomi0** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#252] opened 2023-02-23 20:04 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows

### Processor / Processor Number [Required]

AMD Ryzen 5900X

### Graphic Card [Required]

intel ARC A770

### GPU Driver Version [Required]

- [X] 31.0.101.4125
- [X] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10817872/igcit_ssu.txt)

### Description and steps to reproduce [Required]

On startup of the VM: 
If you try to pass through an A770 Limited Edition (or any other Arc A-Series GPU) from a Linux host to a Windows guest, you do not get any video out or detected monitors on the Arc card. But, the card is being picked up by the drivers and will run whatever workload you throw at it, just not a picture on the Monitor. The Monitor detects something on VM Boot but nothing other than a black screen is visible.

There is a "fix" found out by u/taoj17v on Reddit:
https://www.reddit.com/r/VFIO/comments/yjo44b/comment/ivp4gw8/?utm_source=share&utm_medium=web2x&context=3

He also points out that it is likely a bug in the Firmware.

On shutdown/reboot of the VM:
Not entirely sure what's happening here, but the system freezes up for quite some time.

### Crash dumps [Required, if applicable]

n/a

### Application / Windows logs

n/a

**Comment by IGCIT** [comment] 2023-02-23 20:56
Hi,

you are running linux, is this reproducible in windows (host) too?

if no, then i have to close this because support here is for windows only, you may want to open a ticket for the vm software you are using

thank you for your understanding

**Comment by Yomi0** [comment] 2023-02-23 21:07
I am running Linux, yes. 
This happens when I boot the Windows VM (guest).

**Comment by IntelSupport-Rozilah** [comment] 2023-02-24 14:39
hi @Yomi0,
can you explain the steps to reproduce the issue and attach some video or picture of the issue, so that easy for us to understand the issue?

**Comment by Arturo-Intel** [comment] 2023-03-01 16:21
Hello @Yomi0 reading through the reddit post its a behavior of the Arc driver over Linux. 
This GitHub support limits to Windows. 

@IGCIT Please close this case. The user is running a Windows VM over Linux.

**Closed** 2023-03-01 17:20 UTC
Labels: Info: Needs Replication
