### ISSUE TITLE
Gothic 3 - visual glitches with trees while screen moving 

### ISSUE THREAD

**Issue by Kopryk** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#390] opened 2023-07-16 16:35 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Gothic 3

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i7 13700k

### Graphic Card [Required]

a770

### GPU Driver Version [Required]

- [X] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [X] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[aa.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12064579/aa.txt)

### Description and steps to reproduce [Required]

Move around and you can see that trees disapeer while you are moving the screen.
I believe this bug is forever on intel gpu's ( arc and uhd).
There are multiple videos with this bug e.g: https://youtu.be/PiOtxVfFtNY?t=77

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

All full options.

**Comment by Karen-Intel** [comment] 2023-07-17 18:05
Hey @Kopryk thank you for your report!

Allow us some time to do some debug and will get back with our findings

Karen

**Comment by Vivek-Intel** [comment] 2023-08-25 18:34
Hi @Kopryk 

We were not able to reproduce the issue with latest driver 101.4644 and after installing [latest game patch](https://steamcommunity.com/app/39500/discussions/0/612823460277516777/)

Please find simulation video [here 
](https://www.youtube.com/watch?v=S7K8xjv469s)

As per your SSU logs, driver used is 101.4382 which is older so we would like to ask you to update the driver to the latest one, please update the game as well and let us know the results

**Comment by BiZkViT96** [comment] 2023-08-26 03:41
@Vivek-Intel  Outdated driver and wrong info = bad bug report. 

Here is the driver 31.0.101.4644

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/88586431/e5174855-72e0-4a7b-a016-c9fdf27b32b8

@IGCIT Can be closed.

**Comment by IGCIT** [comment] 2023-08-26 16:36
closing as fixed in latest drivers as shown above

@Kopryk please update your system, if the problem persists for you, reply here and this will be reopened

thanks

**Closed by IGCIT** 2023-08-26 16:36 UTC
Labels: Info: Needs Replication, Type: Graphical Glitches
