### ISSUE TITLE
Dakar 18 - Crash on launch

### ISSUE THREAD

**Issue by rabbit0864** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#69] opened 2021-07-08 11:13 UTC
#### Checklist [README]

- [x ] Device is not undervolted nor overclocked.
- [ x] Device is using the [latest drivers](https://downloadcenter.intel.com/download/30381/Graphiques-Intel-Pilotes-DCH-Windows-10).
- [x ] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Required]
Dakar 18
---
#### Game Platform [Required]
- [ x] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Other

---
#### Processor / Processor Number [Required]
i5 1135g7
---
#### GPU Driver Version [Required]
- [x ] 30.0.100.9667 (*latest*)
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

---
#### Rendering API [Required]
- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

---
#### Windows Build Number [Required]
- [ x] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)

---
#### Description and steps to reproduce [Required]
Game crashes on launch. Shows title screen for a few seconds then crash to desktop.

1.  Launch game
2. 
3. 

---
#### Device / Platform [Optional][Recommended]

Win 3

---
#### Game Settings [Optional][Recommended]

---
#### Save game (*if possible, could help solve the issue faster*) [Optional]

---
#### Windows mini dump (*small memory dump*) (*if available*) [Optional][Recommended]

---

**Comment by estebanr863** [comment] 2021-12-22 18:52
Hi @rabbit0864,

We have found the root cause of this issue to be related to the [OpenSSL* SHA Crash Bug](https://www.intel.com/content/www/us/en/developer/articles/troubleshooting/openssl-sha-crash-bug-requires-application-update.html). This must be fixed by the game developer, but a workarround you can use is described in the link above:

Short-Term Workaround
This is most useful for testing or identification of the bug. If the ISV (independent software vendor) controls the process launch 100 percent through a script or launcher, it could then be used as a fix.

OpenSSL provides an environment variable control for enabling features, including one that modifies the Intel® CPU identification, OPENSSL_ia32cap:

set OPENSSL_ia32cap=:~0x20000000
![image](https://user-images.githubusercontent.com/87549650/147141212-c986031c-da03-40a6-b1da-1e311e90ee9f.png)

This disables the OpenSSL code check for SHA extensions and runs a different code path that does not contain the crashing bug. We verified this on a TigerLake laptop and the game launch successfully after adding the key.

**Closed** 2021-12-24 11:20 UTC
Labels: Info: Needs Replication, Type: Application Crash
