### ISSUE TITLE
Dead By Daylight performance regression on latest driver

### ISSUE THREAD

**Issue by ABagOfPotato** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#288] opened 2023-04-16 22:57 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Dead by Daylight

### Processor / Processor Number [Required]

i5-11400

### Graphic Card [Required]

Arc A770 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssulog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11244862/ssulog.txt)

### Description and steps to reproduce [Required]

Play Dead by Daylight in DirectX12 mode by adding a launch command, this has been the only way to play the game with good performance on Intel Arc so far, however in the latest driver the game is suddenly performing terribly when in matches, performing similar to how it runs in DX11.

Wasn't sure what the issue was and reverted back to a previous driver and the issue was immediately gone, however it returns when running the latest driver.

Of note, in the log uploaded I'm running an older driver which works fine, however the issue is on the latest 4311 driver.

### Device / Platform

Windows 11

**Comment by Karen-Intel** [comment] 2023-04-17 15:55
Hi @ABagOfPotato thank you for posting your findings

We are already in progress of testing some reports with this driver so we'll get back to you in case we have questions

Keep you posted

Karen

**Comment by Karen-Intel** [comment] 2023-04-26 16:30
Hey @ABagOfPotato can you clarify if you downloaded the game directly from the website or through STEAM, Epic Games Store or Microsoft Store?

Thanks

**Comment by ABagOfPotato** [comment] 2023-04-26 23:17
> Hey @ABagOfPotato can you clarify if you downloaded the game directly from the website or through STEAM, Epic Games Store or Microsoft Store?
> 
> Thanks

Hi,

I'm playing using the steam version/downloaded through steam :), I'm hopefully going to give the just released driver a go and will report back again if it still persists!

**Comment by Karen-Intel** [comment] 2023-04-26 23:22
> > Hey @ABagOfPotato can you clarify if you downloaded the game directly from the website or through STEAM, Epic Games Store or Microsoft Store?
> > Thanks
> 
> Hi,
> 
> I'm playing using the steam version/downloaded through steam :), I'm hopefully going to give the just released driver a go and will report back again if it still persists!

Hi again @ABagOfPotato please do! And let me know if v4314 fixed the issue for you or not :)

Talk to you soon

**Comment by ABagOfPotato** [comment] 2023-04-29 14:43
> > > Hey @ABagOfPotato can you clarify if you downloaded the game directly from the website or through STEAM, Epic Games Store or Microsoft Store?
> > > Thanks
> > 
> > 
> > Hi,
> > I'm playing using the steam version/downloaded through steam :), I'm hopefully going to give the just released driver a go and will report back again if it still persists!
> 
> Hi again @ABagOfPotato please do! And let me know if v4314 fixed the issue for you or not :)
> 
> Talk to you soon

Hi,

Thanks for the reply! Gave it a very quick try today and ended up on a small map, however performance was still much worse than on the previous drivers, and I suspect unplayable on a larger map like before.

For context when I play on the older driver I can cap the A770's TDP at 115 watts so I don't waste electricity and still pretty much max out every single map at 95fps without any drops(outside of shader compilation when you first play on a new driver).

However on the newer drivers it is still broken on DirectX 12, with GPU usage at 99% and frames dropping below 60fps even on the small map I played today, so I suspect it is still the same and would probably still drop below 40fps if I were to play one of the more detailed maps.

It's a shame as it seems like something has been broken in the DX12 implementation on Arc.

**Comment by Karen-Intel** [comment] 2023-05-03 00:30
Hey @ABagOfPotato that's a shame :(

Now that you mention that performance decreased in newest drivers, do you recall an older version that had better performance? 

That will definitely help once we report this behavior to the dev team

Thank you!

Karen

**Comment by ABagOfPotato** [comment] 2023-05-03 14:41
> Hey @ABagOfPotato that's a shame :(
> 
> Now that you mention that performance decreased in newest drivers, do you recall an older version that had better performance?
> 
> That will definitely help once we report this behavior to the dev team
> 
> Thank you!
> 
> Karen

Hi,

I've just gone back to the older driver that works well, it's version 4146 :), I believe the driver after that was the one that had the DX12 updates which broke the performance here.

Also of note is that to run the game in DX12 you have to add the launch command -DX12 in steam or whatever store people use. The DX11 mode runs really badly in this game and this has been the only way to play on Arc. Unfortunately we can't use DXVK or VKD3D either because of the anti-cheat.

Hopefully they can figure out what the regression is, because outside of shader compilation which is part of the game in DX12 it runs really really well on the 4146 driver and drivers before that!

**Comment by Karen-Intel** [comment] 2023-05-03 15:57
@ABagOfPotato that is just great information. I will make sure to report this internally, just remember that for a fix to be released we have to wait ~3 to 6 months, so please keep your drivers up to date and do not close this post.

Thank you so much for your help! Have a great day

Karen

**Comment by Arturo-Intel** [comment] 2023-06-01 21:37
@ABagOfPotato can you share to me your graphics configuration? 
I was comparing the 101.4246 vs 101.4382 and I have almost the same results:
101.4382 > FPS Avg 116.5
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/10747b5f-e2e3-4e9a-91b6-1cd43be1e4ce)

101.4246 > FPS Avg 119.8
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/b4cf291e-631b-4a3c-b0ff-1f3ef11411e1)

Using the following configuration:
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/9ff4175a-47b1-4e1f-8acd-b2051ea3c82c)

Keep in mind that both FPS counts were made in different maps and that could affect the FPS avg (I didn't find a way to select a particular map, if you know please share the info)

--r2

**Comment by ABagOfPotato** [comment] 2023-06-01 23:27
> I try with this configuration: ![image](https://user-images.githubusercontent.com/92489452/242737766-425c6628-304b-40a9-b6ae-ec86849ce010.png)
> 
> And got 118.3 FPS average: ![image](https://user-images.githubusercontent.com/92489452/242737722-950666b3-3f21-42cb-8945-41661079c1d0.png)

Hi thanks for the reply and looking into it!

The only difference I can see settings wise is that I have ‘auto adjust’ turned off as that lowers the graphics quality automatically to increase fps.

I’ll have a look tomorrow evening if that’s ok as I’m working this morning! Will test again with the just released drivers, but so far I was getting very low fps with the previous driver and had reverted. What CPU are you testing with?


Also is that using the DX12 mode or the standard DX11 mode?

Will test the new driver and post back results!

**Comment by ABagOfPotato** [comment] 2023-06-03 02:58
Hey,

Back with some quick data, it's almost 4am and it took me over an hour to get things going again but -

It looks like you are using DX11 with a high powered CPU? I can't get close to your results with DX11, and you can't be using DX12 because I imagine it would be far worse on that.

This is my result using DX11 on the latest driver on Haddonfield which while not the worst performing is not a small map by any means. 
![Haddonfield-BigishMap-DX11](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/5942191/214fbf2f-79e9-46dc-a2a2-b4b481bd8784)

Here is the same map running in DX12.
![Haddonfield-DX12-NewDrivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/5942191/d3cb9b15-da50-4935-9f0e-998791e62a95)

Finally here is the same map running in DX12 on the old driver.
![HaddonField-DX12-OldDriver](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/5942191/3fa9380c-f49b-4395-9609-62b5ac1c12af)

As you can see the older driver performs far far better, in fact most of the drops and stutters are from the game engine compiling shaders for the first time, which goes away as you play leaving me with very solid and great performance, hence why it has been the recommended way to play on Arc since release.

Here is an example of how badly the DX12 mode can now perform on the new drivers. Meanwhile in the same situation I would have a locked 95fps/Hz on the older driver.

![DbDScreenshotDX124382](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/5942191/bc1e085f-311a-4911-a129-3fd6046adcc4)

Even in this bad example where shaders have not been compiled you can already see just how much faster it is than the DX11 mode, need more info but I suspect there is some kind of CPU bottleneck in the driver which makes it run better on your system than mine under DX11, however I imagine DX12 on the old driver would still outperform it.

Tests done tonight on a fresh windows 11 install that is up to date, using a fresh install of the latest driver and then reverting back to the old driver for testing.

**Comment by ABagOfPotato** [comment] 2023-06-11 21:25
Thanks for the info @Arturo-Intel. I'm not sure what to add to this, as I have re-installed my system with fresh everything and the problem still persists.

On my i5-11400 the game runs perfectly like it does for you on the older driver, but it drops frames drastically on the newer drivers with the difference being so big it is unplayable on the new drivers.

Maybe start testing on a more realistic CPU for the use case with these GPU's? If there is some kind of CPU overhead issue going on I'm really not sure.

All I can say for certain is that when I had an Nvidia GPU there were no issues like this, and I don't have the issue on AMD. If this is not a bug for you then I think I should just sell on the Arc card and take a small loss and move on, as the game is currently not playable for me and it isn't my system.

The issue will be negated if DX11 performance is fixed for the title though(see the other thread where I was recommended to use the DX12 mode because of that issue). In the meanwhile I have swapped back to a RX 6600 and my performance is great again :)

A CPU upgrade is not the issue here, there is something off going on with Arc...

**Comment by Arturo-Intel** [comment] 2023-06-12 16:10
@ABagOfPotato, 
I understand your frustration, you bought a GPU and it doesn't run one of your favorite games well.

You commented that you already did a fresh install, I think everything (OS, drivers, game) and you keep seeing this behavior, so the software is ruled out.

You mention that in another thread you found that using -dx12 is the solution to fix the problem, can you share the link?

One of the different things we have (besides the CPU) is the amount of RAM, maybe that is what is affecting the game? I'm going to experiment with that. I'm going to keep trying to reproduce this on other systems we have in the lab (different CPU, GPU and ram memory) to find out what is affecting the game in this way.

The behavior you describe in this thread is really a serious problem and I'm going to keep working on it. The main thing is to find out what is triggering the game to behave like this, once we find it, we are 50% advanced in resolving the problem and who knows, maybe this can give us some ideas as to why it is failing in other critical cases.

Thank you for your time and your patience, this case will really help us to have a better product for you.
--r2

**Comment by ABagOfPotato** [comment] 2023-06-12 17:12
> @ABagOfPotato, I understand your frustration, you bought a GPU and it doesn't run one of your favorite games well.
> 
> You commented that you already did a fresh install, I think everything (OS, drivers, game) and you keep seeing this behavior, so the software is ruled out.
> 
> You mention that in another thread you found that using -dx12 is the solution to fix the problem, can you share the link?
> 
> One of the different things we have (besides the CPU) is the amount of RAM, maybe that is what is affecting the game? I'm going to experiment with that. I'm going to keep trying to reproduce this on other systems we have in the lab (different CPU, GPU and ram memory) to find out what is affecting the game in this way.
> 
> The behavior you describe in this thread is really a serious problem and I'm going to keep working on it. The main thing is to find out what is triggering the game to behave like this, once we find it, we are 50% advanced in resolving the problem and who knows, maybe this can give us some ideas as to why it is failing in other critical cases.
> 
> Thank you for your time and your patience, this case will really help us to have a better product for you. --r2

Hi,

Thanks for your understanding! I'm really glad that you're still going to investigate the issue, if there is anything else I can do on my end please let me know! I was very worried that it would be put down to 'just get a better CPU' so I'm glad that's not the case.

Regarding ram, I'm running 32GB 2666mhz DDR4 ram running on two sticks in dual channel, not the fastest ram by any means but I've not had issues in the past given that my aim is to be at or above 95fps, and I sometimes like to work with very ram intensive applications so quantity is paramount to me vs speed. Not sure if that would be the cause of it but it is definitely a difference.

Since swapping between cards again I can always DDU and do some more testing on the newest driver.

It was [this](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/247) thread where the DX12 mode was recommended to me, and it had worked really well in DX12 until the aforementioned driver update. As a side note my performance was still bad in DX11 for the duration, and in retrospect I think the DX11 performance I had was always bad, it was just more map/situation dependant. 

Performance issues are different between DX11 and DX12 in this game though. With the current issue in DX12 the GPU usage will be at 99% but performance will drop and be quite bad, compared to the old driver for me where performance is really good and GPU usage stays high(the card actually seems to throttle at times if I have FPS capped at 95fps/Hz).

On DX11 the performance is definitely CPU bottlenecked on Arc somehow, or just bottlenecked in some way with GPU usage not staying high at all with FPS drops happening frequently and GPU usage dropping along with it.

Again I don't have this problem on the other AMD card, while DX12 may provide slightly more performance than the default DX11 mode it is not large enough to be apparent and it works fine on the default DX11 mode.

Also adding specs info if it helps replicate anything -

Asrock H570m Pro4 motherboard
i5-11400(iGPU disabled otherwise Arc Control will sometimes give error messages and not see the A770)
Corsair TX850M 850w 80+ Gold PSU
32GB DDR4-2666
A770LE 16GB

This whole issue is frustrating, as it runs flawlessly on the older driver for me, and the one where things went wrong was the one where there were optimisations that made some DX12 games run much faster on Arc.

This whole issue could become moot though if there is some kind of DX11 optimisation in the near future as then the game could be played like that in its default mode, but until then it's been the only way to play for me and a few others(there have been posts in the past on the subreddit with people complaining about the games default performance, with the DX12 mode recommended). 

Apologies if I ever come across blunt, I mean no disrespect. I tend to just say things as they are and get on with it :)

**Comment by JohnnyTex** [comment] 2023-06-29 21:20
Just here to confirm that this issue is **still** an issue in the latest public beta. What even caused this? DBD used to be one of the best examples of a game running superbly on ARC, it's still unplayable in DX12 and unstable in DX11. Not at all a good look for one of Steam's most popular games, especially not during an anniversary event.

**Comment by JohnnyTex** [comment] 2023-06-30 23:57
In fact, the game may well have become unplayable on the newest driver to some extent, as I haven't been able to complete a match when forcing DX11 due to crashing.

**Comment by Arturo-Intel** [comment] 2023-07-03 17:14
@ABagOfPotato @JohnnyTex 
I was able to play DBD on Dx12 using 101.4569 
-> https://youtu.be/TTdAgdkddhU

Don't forget to set the FPS cap set to 144

`%localappdata%\DeadByDaylight\Saved\Config\WindowsClient\Engine.ini`

add:

```
 [/script/engine.engine]
 bSmoothFrameRate=false
 MinSmoothedFrameRate=5
 MaxSmoothedFrameRate=144
 bUseVSync=false 
```

**Comment by ABagOfPotato** [comment] 2023-07-03 20:07
> Edit: I just notice that this version of the driver maybe is not available for you, so I try again with the [101.4514](tel:101.4514) -> https://youtu.be/5Y8V8Dd_Bk0
> 
> @ABagOfPotato @JohnnyTex I was able to play DBD on Dx12 using [101.4569](tel:101.4569) -> https://youtu.be/TTdAgdkddhU
> 
> Don't forget to set the FPS cap set to 144
> 
> `%localappdata%\DeadByDaylight\Saved\Config\WindowsClient\Engine.ini`
> 
> add:
> 
> ```
>  [/script/engine.engine]
>  bSmoothFrameRate=false
>  MinSmoothedFrameRate=5
>  MaxSmoothedFrameRate=144
>  bUseVSync=false 
> ```

Unfortunately you are playing on an i9-12900k system which is most likely sidestepping the massive issue through sheer brute force on the CPU. Your video and testing is unfortunately for the most part completely irrelevant for this thread, please test on appropriate hardware and then report back.

I have not tried the latest driver as I sold my Arc card due to it having been broken in this game for so long while being a clear and blatant and easily reproducible regression in the drivers, however given the lack of acknowledgement in the release notes to numerous known bugs including this and with the history of it not being fixed since the regression occurred I highly doubt it has changed.

That is something for another thread though, the numerous bugs and bug fixes which don’t get mentioned. (I understand it is embarrassing but it is unprofessional)

Currently running a used RTX 3080 which cost me £50 more than the arc card did when it was new and I have no issues on that whatsoever :)


Regarding the advice, yes I already do play with the FPS unlocked as you describe :)

All the best!

**Comment by JohnnyTex** [comment] 2023-07-03 20:25
Both videos show footage of DBD being run on an integrated graphics solution. Also, getting the game to startup in DX12 is no problem, it was just that the game was borderline unplayable due to the terrible performance w/ plunges all the way down to the 20s. I'm on 4514 myself, running the game w/ uncapped fps and whatnot, and even just in the training course the game still plunged down to the 30s. Even in your video it shows the game plunging well below the 100fps marker, when this wasn't the case at all before. Before the driver update (and every driver since) the game easily ran well above 100fps no matter the situation and was a clear-cut example of a game where ARC destroyed the RTX 3060. Now not only is this not the case, this is an example of a game being made practically unplayable on ARC. And that this issue persists on one of Steam's most popular games throughout the anniversary event is frankly unacceptable.

**Comment by JohnnyTex** [comment] 2023-07-03 20:29
And just to further drive in a point; the truly embarrassing thing about this whole episode (which has dragged on for months now) is that this is a _regression_. This wasn't the case before, and it shouldn't be the case now. Pretend this game actually ran at a locked 60fps instead of taking unplayable plunges into the 30s. How is this an acceptable change from running at a consistent 120fps? It's not, not in any circumstance.

**Comment by Karen-Intel** [comment] 2023-07-04 16:31
Just FYI we have reported the differences between driver v.4146 and v.4514, we will let you know if the issue is going to be fixed in a future release or if it is considered expected behavior.

A few facts:

- Game is playable in DX12, FPS average on both v4146 and v4514 is ~90, tops 120 with a few drops between 60 and 70, never touching 30 FPS.
- We have tested on 11th, 12th and 13th Gen, average is the same on the 3 systems so it is not HW related.
- About user experience performance acceptability, we need more than putting personal experience into words: video evidence or numbers are required for every submission. 

Thank you @ABagOfPotato for posting your experience with numbers and data that allowed us to make a comparison even tho we have not been able to point our finger in the root cause yet. We hope the dev team can help us identify if the issue is on our end or of we need help from the ISV.
@JohnnyTex we invite you to add evidence of the behavior you're seeing in every submission you make as many other users in this forum do.

Thanks, keep you posted.

Karen

**Comment by JohnnyTex** [comment] 2023-10-07 19:27
I was fixing to record the game in DX12 to show off the performance of the game contradicting the above numbers, but amazingly I did something else that seemingly made the game run like a charm; just set it all to low. Something is very, very wrong in regards to how ARC is handling the various quality presets, cause the moment I stepped up to Med everything went back to hell. I'll provide some recording of that later tonight, but the game on DX12 is 100% playable and even runs amazingly, as long as you play on Low. A confusing thing to say the least, but perhaps that info can be of help.

**Comment by JohnnyTex** [comment] 2023-12-10 20:04
This issue remains on the latest driver.

**Comment by Arturo-Intel** [comment] 2024-01-25 16:57
@ABagOfPotato @JohnnyTex 
Using driver 101.5186, Ultra quality, 2K res, full screen
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/2bbc2df3-af3f-4e7c-bbdd-7ea4fd470e7e)

Can you please verify it?

-- r2

**Comment by JohnnyTex** [comment] 2024-01-25 17:05
Yes I can! This issue is fully resolved.

**Comment by Arturo-Intel** [comment] 2024-01-25 17:18
@JohnnyTex Thanks for the confirmation
Closing this issue (finally!)

**Closed by Arturo-Intel** 2024-01-25 17:18 UTC
Labels: Info: Needs Replication, Type: Regression, Type: Bad Performance
