### ISSUE TITLE
GPU clock drops in Grid 2019 and Grid Legends

### ISSUE THREAD

**Issue by diesel-dogg** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#149] opened 2022-06-06 18:38 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Grid 2019, Grid Legends

### Game Platform [Required]

- [X] Steam
- [X] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

1165G7

### GPU Driver Version [Required]

- [X] 30.0.101.1994 (*latest*)
- [X] 30.0.101.1960
- [X] 30.0.101.1934
- [ ] 30.0.101.1660
- [ ] 30.0.101.1631
- [ ] 30.0.101.1404
- [X] 30.0.101.1340
- [X] 30.0.101.1191
- [X] 30.0.101.1121
- [ ] 30.0.101.1069
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11
- [X] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [X] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssuOutput.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/8854562/ssuOutput.txt)

### Description and steps to reproduce [Required]

For both-- Grid 2019 and the newer Grid Legends-- the GPU clock drops to around 500-600 MHz after some minutes of gameplay causing a significant drop in FPS. It's like the GPU drops to a lower power state, not recognising that the application is still rendering. 

The only way around is to switch between Fullscreen and Windowed Borderless mode from the in-game settings repeatedly and at some point, the clock goes back up to 1.1-1.3 GHz and stays that way for a fair amount of time resulting directly in a gain of 20-25 fps. Things work normally for a while before the problem comes back after a system restart or an application crash etc. 

I've generally noticed that DirectX performance on all codemasters games is very poor with Xe graphics with a similar issue of low GPU speed on older games like Dirt Rally. Using DXVK to direct the calls to Vulkan in Dirt Rally, immediately pulls the clock up and improves performance but this is not an option for the newer codemasters games that exclusively support DirectX12. 

### Game graphic quality [Required]

- [ ] Low
- [X] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1280x720

### Game VSync [Required]

Off/On

### Game display mode [Required]

- [x] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Any settings

### Device / Platform name

GPD Win 3 1165g7

### Crash dumps [Required]

No crashes

### Save game

Happens with freshly installed version of game as well with no save files

**Comment by IntelSupport-Arun** [comment] 2022-06-07 05:50
Hi @diesel-dogg ,
Can you please run the [Intel SSU Tool](https://www.intel.com/content/www/us/en/support/articles/000057926/memory-and-storage.html) on your system and attach the log?

**Comment by diesel-dogg** [comment] 2022-06-07 15:35
> Hi @diesel-dogg ,
> Can you please run the [Intel SSU Tool](https://www.intel.com/content/www/us/en/support/articles/000057926/memory-and-storage.html) on your system and attach the log?

Hi, I've updated the post to include SSU log.

**Comment by IntelSupport-Arun** [comment] 2022-06-09 18:19
Hi @diesel-dogg,
I tested your issue at our lab on multiple operating systems (Windows 10, 20H2 and 21H2)and also on multiple systems and was unable to reproduce it.
There is no drop in the GPU clock to 500-600 MHz at any point during the game and it runs smoothly.
So far, we have verified the issue in "Grid 2019" only, and we are working on verifying it in "Grid Legend". Once the verification is complete, we will post an update.

**Comment by diesel-dogg** [comment] 2022-06-09 19:05
A possibly quicker way to reproduce this would be to launch the game in fullscreen and then return to desktop and back to the game a couple of times. Unfortunately, there is no specific race track or scenario in the game that seems to be tied to this and it is a very sporadic issue which occurs at an unpredictable instant so it may take some fiddling to reproduce the problem. 

In Grid Legends, please also try running the game in borderless windowed mode (please restart after applying that setting in-game) and you will see that the sky textures start glitching in rain, snow, storm weather conditions. This is relevant because so far the only way I am able to maintain a steady GPU clock on either of these games is to run them in borderless windowed mode.

**Comment by IntelSupport-Arun** [comment] 2022-06-13 11:47
Hi @diesel-dogg,
Following your recommendation, we tried to reproduce the issue with both "Grid Legend" and "Grid" on our systems but we cannot see the issue on our systems. Again, I have verified the issue on two different systems and neither can reproduce the problem. 

In "Grid legends", While playing in different weather conditions such as rain, snow, and storm, I did not experience any glitches or GPU clock drops.

In Grid 2019, I have tried several times to launch the game in full screen, then return to the desktop, and then back to the game again. The game is working fine and has not observed any kind of issue.

Considering everything we've seen on your device and our systems, we suspect that the issue is specific to your device and not the drivers or the game. Our recommendation would be to get in touch with your device manufacturer since this issue is specific to your device.

**Comment by IntelSupport-Arun** [comment] 2022-06-15 08:29
Hi @diesel-dogg, Would you be able to contact the manufacturer of your device?
Since we cannot reproduce the issue on multiple systems, I suspect this might be specific to your device.

**Comment by diesel-dogg** [comment] 2022-06-15 15:45
I doubt it's something at the manufacturer's end. More to do perhaps with a difference in TDP in your testing rig and my handheld which I am running at 15-18w. I am able to reproduce this problem quite easily and repeatedly if I use the fullscreen option or if I try to turn off VSync from in-game settings. Turning vsync ON and toggling to borderless windowed mode allows me to get almost 60fps at a TDP of 15w and the CPU coasts along at around 1.5-1.6 GHz allowing the GPU to run full tilt most of the time. 

If you'd be willing to look further, I could send a video with the problem highlighted through an in-game OSD which will show the GPU clock or alternatively you can close this if you are sure there won't be much you could at your end. 

My "fix" unfortunately only works on Grid 2019 and not on Legends so I've had to now refund the latter

**Comment by IntelSupport-Arun** [comment] 2022-06-16 05:19
Hi @diesel-dogg, Because we were unable to reproduce the issue on our side on multiple systems, you can capture the issue reproduction video and attach here and I will confirm that we are on the same page.

**Comment by diesel-dogg** [comment] 2022-06-18 20:23
- I am linking a [video](https://drive.google.com/file/d/12wGe1wolOAjxSQ6Ygo8jW7YhVDU4QT7V/view?usp=sharing) where the game starts out with the problem of low GPU clock visible through the OSD. You can see the GPU is running at around 800 MHz and typically drops down to 600 if given time. I was not able to record the actual process of the GPU clock dropping to 800 because whenever I minimise the game window, the recording stops, and minimising the game window is what causes the GPU clock-drop in my case. 

Subsequently, at around 48s mark, you will see that I go into the settings and change from Fullscreen to Windowed Borderless and I almost simultaneously hit the ctrl+shit+win+b combination to reset the display driver. At this point, quite instantaneously, the GPU pulls up to almost 1.1GHz and the FPS goes up. 

Total chip power is also shown in the OSD along with the PL1 and you can see that the chip has plenty of headroom. Once the GPU is back up, it gradually picks up and will eventually hit 1.3GHz. 

- I am attaching a screenshot with labels to indicate what the different sections in the OSD are. 

- Since this issue was opened, various users on different platforms with 1165g7 have reported almost EXACT issue with other titles like Forza Horizon 5. I have experienced this with Grid 2019, Grid Legends, Forza Horizon4 and WWE 2K22.

<img width="1279" alt="Screenshot 2022-06-19 at 1 39 50 AM" src="https://user-images.githubusercontent.com/106082199/174455967-4ef69558-b46d-4383-9243-05db6baee40c.png">

**Comment by IntelSupport-Arun** [comment] 2022-06-20 07:28
Hi @diesel-dogg,
The steps you mentioned in your comments have been followed, but we are unable to replicate your issue on our systems.
GPU clocks do not drop at any point of the gameplay, whether the game is played in windowed mode or in fullscreen mode.
Also, I'm attaching the screenshot of the gameplay for your reference
GRID_2019_FullScreen Setting Page:
<img width="375" alt="GRID_2019_FullScreen_Setting" src="https://user-images.githubusercontent.com/91881865/174547384-26b84598-9eec-451f-bf58-990559e730aa.png">

GRID_2019_FullScreen GAME:
<img width="509" alt="GRID_2019_FullScreen_GAME" src="https://user-images.githubusercontent.com/91881865/174547462-1b8b7506-399f-4112-9c66-aca32fce0cb6.png">

GRID_2019_Windowed Full-screen Setting page:
<img width="461" alt="GRID_2019_WindowedFS_Setting" src="https://user-images.githubusercontent.com/91881865/174547642-0c9a1a3a-fdad-4d31-a072-ca1e485cc912.png">

GRID_2019_WindowedFS game:
<img width="670" alt="GRID_2019_WindowedFS_Game" src="https://user-images.githubusercontent.com/91881865/174547767-315b9807-835c-4c8a-b7af-9b7a20cc55ec.png">

The same observation is with GRID Legend as well.

**Comment by IntelSupport-Arun** [comment] 2022-06-22 10:22
Hi @diesel-dogg ,
In our testing on multiple platforms (Intel Core i7 11700K and Intel Core i7 12700K) with the latest versions of Intel graphics drivers, we have been unable to reproduce your issue, as informed we suspect it is specific to your device. Is there any chance of checking with your device manufacturer or any other device to reproduce the same issue? When you are checking with the device manufacturer please make that all the software on the device is up to date also please confirm your game has the latest fixes.

**Comment by diesel-dogg** [comment] 2022-06-22 10:52
You can go ahead and close this issue though I am not convinced that testing on a desktop i7 at a much higher power necessarily will show the same performance as my device which is a mobile 1165 i7. I borrowed a Dell Inspiron 5502 with a similar configuration as my original device (1165G7) and the issue is very much there. The manufacturer seems to think this is a driver problem but regardless, you can close this now.

**Comment by KingYozora** [comment] 2022-06-27 02:41
I also have the same  GPU clock bug on my 1135G7 device.  I made this video to show the problem: https://www.youtube.com/watch?v=Dtw_E79LhY0

**Comment by IntelSupport-Arun** [comment] 2022-06-27 06:58
Hi @diesel-dogg,
I have managed to get one system and verified the issue on i7-1165G7 in our lab , where after 10 minutes of playing, the GPU clock never dropped below 1100 MHz (as shown in the attached screenshot).
![Grid 2019 after 10 minutes](https://user-images.githubusercontent.com/91881865/175876863-f7a35b49-7ec6-43b6-9076-6564c040d168.png)

Also, I would like to clarify your previous comment, the reason for verifying the issue on i7-11700K, the iGPU on the i7-1165G7 is far more capable than the one on the i7-11700K, as shown in the image below. This is by design, as Desktop CPUs are usually paired with dGPUs, so there is no need for a strong iGPU. While mobile CPUs are usually used on systems without a dGPU, so they do include a stronger iGPU.
![11700k vs 1165G7](https://user-images.githubusercontent.com/91881865/175878200-a585ecf6-20e6-465f-9598-791d7d4b0fad.JPG)
Please let us know if you have anything further to discuss, if there is nothing to discuss we would like to close this issue.



 

Based on all our testing and observations on multiple platforms and operating systems, we believe the issue is specific to your device and not the graphics drivers. Our recommendation is for you to contact your device manufacturer's support if you are still experiencing the issue with this latest driver. The issue seems to be associated with your device.

**Comment by IntelSupport-Arun** [comment] 2022-06-27 14:28
HI @IGCIT , As requested please proceed to close this case.

**Closed** 2022-06-27 17:22 UTC
Labels: Info: Needs Replication, Type: Bad Performance
