### ISSUE TITLE
"Scanlines" on metallic surfaces in Halo Infinite

### ISSUE THREAD

**Issue by bulentyusuf** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#200] opened 2022-12-22 00:26 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Halo Infinite

### Game Platform [Required]

- [ ] Steam
- [X] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

12400

### Graphic Card [Required]

Arc A770 LE

### GPU Driver Version [Required]

- [ ] 31.0.101.3975 (*latest*)
- [X] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Windows 10 21H1
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU report.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10282626/Intel.SSU.report.txt)

### Description and steps to reproduce [Required]

Any stages that take place in an interior space, e.g. the silent auditorium. Scanlines appear on all metallic surfaces, like corridors, walls and floors.

![Uploading Halo Infinite 22_12_2022 01_24_49.png…]()

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Everything is on High, except for "Reflections" which have been set to Low. (Different bug)

**Comment by IntelSupport-Rozilah** [comment] 2022-12-22 01:27
hi @bulentyusuf, 
Thanks for contacting Intel.
1. can you provide the correct link of "Uploading Halo Infinite 22_12_2022 01_24_49.png…" because seem like the link is reflect back to this issue link and not as picture link?
2. do you try on this [31.0.101.3975](https://www.intel.com/content/www/us/en/download/729157/intel-arc-graphics-windows-dch-driver-beta.html) latest beta version ?

**Comment by bulentyusuf** [comment] 2022-12-22 02:29
![Halo Infinite 22_12_2022 01_24_49](https://user-images.githubusercontent.com/88731405/209041937-08b44cf6-28d3-4b63-a633-75cc34fa2c42.png)

No, I haven't tried the beta version. My worry is that this will be even less stable. But I'll give it a shot!

**Comment by IntelSupport-Rozilah** [comment] 2022-12-22 02:34
Thanks @bulentyusuf , I understood your concern and we will start verify the issue once the system is ready. Stay tuned!

**Comment by IntelSupport-Rozilah** [comment] 2022-12-23 01:10
hi @bulentyusuf ,
can you confirm which game version ("Halo Infinite" or "Halo Infinite (Campaign)" did you used?,because i did not observe this issue on "Halo Infinite"
![image](https://user-images.githubusercontent.com/44628772/209250977-3267cff4-be4f-45ed-952a-e28b1f2bda3c.png)

**Comment by bulentyusuf** [comment] 2022-12-23 01:30
Hello, it's the Halo Infinite (Campaign) where the bug is occuring.

**Comment by IntelSupport-Rozilah** [comment] 2022-12-23 01:35
Thanks @bulentyusuf , next time please specify the game version then easy for us to verify the issue. As for now, we need to purchase this game and will update you once we verify the issue.

**Comment by IntelSupport-Rozilah** [comment] 2022-12-30 07:56
hi @bulentyusuf , there is new ARC driver [31.0.101.4032](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html?) , can you have a try?

**Comment by IntelSupport-Rozilah** [comment] 2023-01-03 10:40
hi @bulentyusuf ,
The case has been verified on our side and we are able to reproduce it with our configurations as below:
Processor:  i7-12700K(ADL)
Graphic device: Intel Arc A770
Graphic Driver version: 31.0.101.4032
We will be working on a fix. I want to give you a heads-up that the fix may take 3 to 6 months to be included.

**Comment by bulentyusuf** [comment] 2023-01-03 20:09
That's great news, thanks for the update. I've already finished the game (it wasn't a game-breaking bug), but happy that others will benefit from the fix.

**Comment by kunit1** [comment] 2023-01-04 03:24
Thank you @IntelSupport-Rozilah, waiting for the fix.

**Comment by EstebanIntel** [comment] 2023-03-06 16:05
Hi @bulentyusuf and @kunit1, a possible fox for this issues is included in driver version [31.0.101.4146](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html?). Can you please test it and let me know?

**Comment by kunit1** [comment] 2023-03-07 23:54
Fixed on Arc A750 with driver [31.0.101.4146](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html?) 

Thank you

**Comment by EstebanIntel** [comment] 2023-03-08 01:02
Great news!!

@IGCIT  can this be closed?

**Closed** 2023-03-08 08:16 UTC
Labels: Info: Needs Replication, Type: Graphical Glitches
