### ISSUE TITLE
Latest driver destroys other drivers !!

### ISSUE THREAD

**Issue by paulober** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#716] opened 2024-02-20 10:52 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows Kernel

### Processor / Processor Number [Required]

AMD Ryzen 7 5800X

### Graphic Card [Required]

Intel ARC A770 LE

### GPU Driver Version [Required]

31.0.101.5330

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [X] DirectX11
- [X] DirectX10
- [X] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14343180/igcit_ssu.zip)

### Description and steps to reproduce [Required]

Install the newest driver.
After the reboot my bluetooth wasn't available anymore so i needed to plug the usb dongle out and back in in order for it to work again. (that was the first strange thing)
After that every time i connect my bluetooth keyboard to the PC i get following error in the device manager:
```
Bluetooth-HID-Device
The device cannot be started. (Code 10)
{contradictory address range)
The specified address range does not match the address space.
```
I reproduce the issue on a different machine. And it seems like the intel arc driver messes with things it isn't allowed to.
Or in other words: Call him off, please

**Comment by Arturo-Intel** [comment] 2024-02-20 16:13
@paulober I am not able to reproduce this with the Bluetooth dongle. 
Do you notice this behavior with another devices? or is only with Bluetooth devices?

**Comment by paulober** [comment] 2024-02-21 19:42
> @paulober I am not able to reproduce this with the Bluetooth dongle. Do you notice this behavior with another devices? or is only with Bluetooth devices?

Only my bluetooth keyboard. It works without the newest Intel Arc driver and it not works with the newest Intel Arc driver. And what made me aware of this in the first place. Was that after installing the driver on restart Windows didn't show bluetooth at all in the quick access and the device manager even though i have builtin bluetooth chipset from Intel and an external dongle from TP-Link.
So I just reinserted which made it available again. 
But since then i always get driver errors when connecting this bluetooth keyboard. (on other machines it still works) And it's not just an unknown brand keyboard it's an Keychron keyboard which normally has very good compatibility and never had any issues with my systems.

> When you did this test was with the same BT keyboard (in other machine)? Can you share your keyboard specs? (brand, model, etc etc)

Same keyboard but other machine.
Keychron K2 Pro (ANSI)
Bluetooth dongle: TP-Link Bluetooth 5.0 USB Adapter
and a deactivated Intel(R) Wireless Bluetooth(R) chipset on the motherboard.

**Comment by Felipe-Intel** [comment] 2024-02-22 20:45
Hi @paulober I have a very similar MoBo in my system (MSI Z790A) and I don't have any problem with the integrated Bluetooth device.
A couple of questions:
-Is it possible for you to use the MoBo integrated bluetooth to connect your keyboard? 
Which exact model of BT adapter are you using? I see UB500 and UB400 in tp-link website. Don't know if you have any of this two or a different model. Or instead, it is a specific dongle included with the keyboard?

Many Microsoft articles refer to the error 10 as a problem in the device driver, in this case, the BT drivers. I would suggest the following:

- Disconnect your BT dongle (use the keyboard with the cable or another keyboard if available)
- Update MoBo BIOS (if I'm not wrong, you are running v 2.I and there is a new version, 2.J released last january)
- Apply any pending Windows Update
- Check if your keyboard needs a firmware update (you may need to ask the manufacturer for guidance, specially if this is not done automatically by some software tool) and apply it . 
- Check if any keyboard related software, including drivers, are up-to-date.
- DDU the graphics driver and install driver 5330
- Uninstall and reinstall the TPLink BT device drivers. Make sure you completely remove this device driver before reinstalling it. 

If you still have issue with the keyboard, please check (if possible) if any other BT device (like a headset) also has connection problems using the TP-link adapter. Let me know if after this, you still have problems with the connection to your bluetooth adapter from your bluetooth devices (not only the keyboard).

**Comment by Felipe-Intel** [comment] 2024-03-05 16:23
Hello @paulober 
Since we have not heard any feedback regarding our previous post, we will close this thread now. If you need further assistance, please create a new thread and refer to this one.

**Closed by Felipe-Intel** 2024-03-05 16:23 UTC
Labels: Info: Needs Replication, Type: Support
