### ISSUE TITLE
Poor OpenGl Performance.

### ISSUE THREAD

**Issue by EliezYT** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#402] opened 2023-07-20 05:25 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Poor OpenGl Performance.

### Processor / Processor Number [Required]

Intel Xeon W-2145

### Graphic Card [Required]

Intel Arc A770 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [X] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Other Windows build number

N/A

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12102299/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Furmark gets very poor performance even a Rtx 4060 Laptop Gpu beats it. The gpu is very hot and maxing out all the time it can barely handle the benchmark.

![bench1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/110901380/9b0240be-9edd-4e80-b6a9-9ca6bf0aa516)

![bench2](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/110901380/583099bd-8353-42c5-9b3c-bea2283c46d1)

OpenGL needs to be improved on intel Arc so games, office tasks, and benchmarks can get good performance.

### Device / Platform

Windows 11 22H2 Desktop

### Crash dumps [Required, if applicable]

N/A

### Application / Windows logs

N/A

**Comment by LancerDawg75** [comment] 2023-07-23 02:56
To be fair, OpenGL is an older API - just like everything else that us Arc owners know:

> If it's not DirectX 12 or Vulkan, your performance...like mileage...will vary. 

Some applications still do offer OpenGL for productivity and content creation, but at the same time, they also offer other, more modern APIs such as OpenCL.

Vulkan is the evolution of OpenGL, and not to mention, the OpenGL API hasn't been officially updated since 2017. That being said, if this post was to state something along the lines of wanting to point out that since OGL performance is poor and we want the engineers to improve performance with the drivers in that area - it's probably not going to happen. At the very least, it might be considered, but it's going to be on the lowest rung of Intel's "tier" procedure in driver improvement priority. 

That being said, if the Furmark you were using were updated with Vulkan, you would more than likely see better results. 

Here is the [ASUS Furmark ROG version that does have benchmarks in either OpenGL or Vulkan](https://geeks3d.com/furmark/rog/downloads/). This is what I got. 

And here is the posted result
![ArcA770 Furmark VK](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/f84a8e95-ac48-441d-bdff-543a72c9f96e)

**Comment by EliezYT** [comment] 2023-07-23 08:40
> To be fair, OpenGL is an older API - just like everything else that us Arc owners know:
> 
> > If it's not DirectX 12 or Vulkan, your performance...like mileage...will vary.
> 
> Some applications still do offer OpenGL for productivity and content creation, but at the same time, they also offer other, more modern APIs such as OpenCL.
> 
> Vulkan is the evolution of OpenGL, and not to mention, the OpenGL API hasn't been officially updated since 2017. That being said, if this post was to state something along the lines of wanting to point out that since OGL performance is poor and we want the engineers to improve performance with the drivers in that area - it's probably not going to happen. At the very least, it might be considered, but it's going to be on the lowest rung of Intel's "tier" procedure in driver improvement priority.
> 
> That being said, if the Furmark you were using were updated with Vulkan, you would more than likely see better results.
> 
> Here is the [ASUS Furmark ROG version that does have benchmarks in either OpenGL or Vulkan](https://geeks3d.com/furmark/rog/downloads/). This is what I got.
> 
> And here is the posted result ![ArcA770 Furmark VK](https://user-images.githubusercontent.com/55825789/255371053-f84a8e95-ac48-441d-bdff-543a72c9f96e.png)

Interesting I'm curious if there can be some opengl performance uplifts regardless though it seems there is still a lot of opengl games and applications still out there.

**Comment by LancerDawg75** [comment] 2023-07-23 11:46
@EliezYT - I really doubt that they will despite there being [some games that still do use OpenGL](https://www.pcgamingwiki.com/wiki/List_of_OpenGL_games).  However, they are not exactly blockbusters or ones that many flock to and/or highly advertised. 

As a disclaimer, I'm not making apologetics for Intel, it's just this architecture was presented to us as a quirky, "You're gonna be a perpetual beta-tester" modern API biased card with very little thought to legacy APIs. You see it as engineers are trying their hardest to make more DX11 titles work because there are a lot of well known/popular titles out there that run on DX11. Before that it was DX9 because of CS;GO. 

Even Radeon cards were not strong under OpenGL because not much was put into an API that hasn't been maintained since 2017 and to them it was more along the lines of "....and why should we? We had a hand in making Vulkan with our Mantle API" 

The way it feels to me is - Intel's priority on things that are not DX12 or Vulkan go like this

DX11 > DX9 > DX10 > OpenGL (maybe)

More or less, unless there is some particular and popular game that was made with OpenGL or a good amount of games that again, meet the above criteria, I'm not sure much of the focus is going to get back to it. There is a reason why on the Intel Arc subreddit when people ask us the question 

> Would this be a good card?

We often say.....

> It can be, if the majority of your gaming is done under DX12 or Vulkan and you like RT (since it actually does this pretty well for the price). Anything else? Not so much. If you want it to "Just work" across the entire aisle of games from different time periods and APIs -- this is definitely not the card for you. We can teach you how to use DXVK Async if you still want to do it. 

I'm not sure what can be done going forward for OpenGL. There is [Zink](https://docs.mesa3d.org/drivers/zink.html) which translates OpenGL to Vulkan, but that is for Linux only and I don't think that there is a package like DXVK where you can insert a .dill file to make the translation happen. However, there is [this article in Phoronix that states it is a work in progress.](https://www.phoronix.com/news/Zink-Windows-Kopper-Progress)

**Comment by EliezYT** [comment] 2023-07-24 19:38
> @EliezYT - I really doubt that they will despite there being [some games that still do use OpenGL](https://www.pcgamingwiki.com/wiki/List_of_OpenGL_games). However, they are not exactly blockbusters or ones that many flock to and/or highly advertised.
> 
> As a disclaimer, I'm not making apologetics for Intel, it's just this architecture was presented to us as a quirky, "You're gonna be a perpetual beta-tester" modern API biased card with very little thought to legacy APIs. You see it as engineers are trying their hardest to make more DX11 titles work because there are a lot of well known/popular titles out there that run on DX11. Before that it was DX9 because of CS;GO.
> 
> Even Radeon cards were not strong under OpenGL because not much was put into an API that hasn't been maintained since 2017 and to them it was more along the lines of "....and why should we? We had a hand in making Vulkan with our Mantle API"
> 
> The way it feels to me is - Intel's priority on things that are not DX12 or Vulkan go like this
> 
> DX11 > DX9 > DX10 > OpenGL (maybe)
> 
> More or less, unless there is some particular and popular game that was made with OpenGL or a good amount of games that again, meet the above criteria, I'm not sure much of the focus is going to get back to it. There is a reason why on the Intel Arc subreddit when people ask us the question
> 
> > Would this be a good card?
> 
> We often say.....
> 
> > It can be, if the majority of your gaming is done under DX12 or Vulkan and you like RT (since it actually does this pretty well for the price). Anything else? Not so much. If you want it to "Just work" across the entire aisle of games from different time periods and APIs -- this is definitely not the card for you. We can teach you how to use DXVK Async if you still want to do it.
> 
> I'm not sure what can be done going forward for OpenGL. There is [Zink](https://docs.mesa3d.org/drivers/zink.html) which translates OpenGL to Vulkan, but that is for Linux only and I don't think that there is a package like DXVK where you can insert a .dill file to make the translation happen. However, there is [this article in Phoronix that states it is a work in progress.](https://www.phoronix.com/news/Zink-Windows-Kopper-Progress)

Amd made a OpenGL update not to long ago that drastically improved performance in OpenGl applications.

Also there is some popular games using OpenGL being Minecraft, lots of emulators, Doom 2016, and many more old games people still play there is a need for it not just for gaming but for all OpenGl applications as a whole which includes many editors and recording software.

I am curious if that OpenGl to Vulkan conversion can be a way that ARC A770 can get a lot more performance in OpenGL applications.

**Comment by Arturo-Intel** [comment] 2023-08-08 18:08
Hi @EliezYT 
I understand your point of view about OpenGL and Arc, and somewhat agree, many of the best games (for some of us) are old games that use old libraries.

As @LancerDawg75 mentioned within our plan to support all the multiple APIs that exist was to give them priority, the reality is that **OpenGL unfortunately has low priority**. It does not mean that there is no support for OpenGL as there are several very popular games (minecraft java as an example) that are still alive and there are several cases of OpenGL titles/software that are currently being worked on.

Obviously these priorities are significantly affected by the popularity of the game or the API, but also by the interest of customers reflected in these forums.

For me, asking (or even demanding) these types of requirements (better performance for OpenGL/Vulkan/DX12/etc) shows the real interest of our customers.

You just have to understand that Intel has a plan and is following it step by step, in order to offer an option with a fair price and acceptable performance, sometimes sacrificing development time on certain APIs/games

With all this, I'm going to make a case for requiring (or at least reviewing) an increase in performance for OpenGL in our products in order to show our developers that a good part of our customers are still really interested in this.

Invite people interested in this type of performance increase in OpenGL to participate in this thread to increment the social impact of the request. This will help a lot to push it through the priorities levels.

Keep in mind that I can't guarantee that they're going to work on this (because of the defined priorities), much less an implementation date or a driver version with performance implementation. And if they do, it's going to take time to see this live. 

--r2

**Comment by Darklegion1978** [comment] 2023-08-18 06:59
Works perfect ;)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/123353653/91e58fcd-349c-4800-a8d9-7ee22d496ff8)
and
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/123353653/21d154f9-e86d-46d8-833b-07773db25e88)

Greetings

**Comment by Danjhop4** [comment] 2023-08-25 13:57
Yeah

**Comment by EliezYT** [comment] 2023-09-03 00:30
> Works perfect ;)
> 
> ![image](https://user-images.githubusercontent.com/123353653/261525643-91e58fcd-349c-4800-a8d9-7ee22d496ff8.png) and ![image](https://user-images.githubusercontent.com/123353653/261525774-21d154f9-e86d-46d8-833b-07773db25e88.png)
> 
> Greetings

How are you getting this?

**Comment by Darklegion1978** [comment] 2023-09-03 06:38
@EliezYT Done with an Asrock A770 with 252 Watts max. and in Arc Control +45/+45.

Greetings

**Comment by LancerDawg75** [comment] 2023-09-03 07:04
I'm wondering if it has to do with the version of Furmark you are using. 
There is a ROG version that has support for Arc, but then there is the [vanilla version that doesn't seem to have any kind of support ](https://geeks3d.com/furmark/downloads/)for Arc.

ROG Furmark - 1080p Benchmark Preset
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/ae753680-8cbb-42b1-a8ef-308b0a2d8b23)

Granted, it's not as high as @Danjhop4, but that might be my install because I'm having issues with getting Super Robot Wars 30 that can't seem to be reproduced, so I'm going to nuke my install from orbit - it's the only way to be sure.

Then again, I just tried the most recent version of vanilla Furmark using the 1080p Preset. Still not as good as @Danjhop4, but still better than the laptop score you are comparing it to. Danjihop is also on a more recent beta version driver as well as opposed to me that is a bit too lazy to move off from the latest WHQL.
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/a26a45e5-ecb0-40a2-8de3-db800c41ce97)

I think the Arc support of the ROG version is for monitoring purposes, but I don't know. It may be your hardware configuration. I don't know much about the Intel Xeon line and their compatibility/features tables. [Looking at Intel ARK, your processor was made in Q2017](https://ark.intel.com/content/www/us/en/ark/products/126707/intel-xeon-w2145-processor-11m-cache-3-70-ghz.html) - perhaps it doesn't have ResizeBAR + Above 4G Decoding given that the boards possibly needed to run a Xeon are server based. Looking at your SSU, you are running a Lenovo ThinkStation P520. 

It could be the slot you have your Arc in. Looking at the [specifications table for a ThinkStation P520](https://thinkstation-specs.com/thinkstation/p520/), PCI-E Slot 1 is PCI-E 3.0  x8, only PCI-E slots 2 and 4 have the full 3.0x16 bandwidth. At the same time, I think you already know which PCI-E slots have the correct bandwidth. I really don't know if these are factors that play into it. I could try later on and drop the PCI-E spec down to Gen3 and turn off ResizeBAR on my system to see if that is the case. 

It's both the beauty and curse of PC gaming. Infinite configurations introduce infinite performance numbers.

**Comment by Darklegion1978** [comment] 2023-09-03 07:51
Btw. its awesome to see, that the Arc A770 blows away most of the Nvidia and Amd Cards to Hell :)
RTX 3060, 3070, 3070Ti, 4060, 4060Ti, 4070

Its great to see, that Intel do his Job perfect.

Greetings

**Comment by Danjhop4** [comment] 2023-09-03 09:47
@LancerDawg75 i am stuck at my current driver due to not having admin

**Comment by LancerDawg75** [comment] 2023-09-03 10:16
> @LancerDawg75 i am stuck at my current driver due to not having admin

Is this a work issued PC? If so, that might be the reason - you may be set at "User" level, but not Administrator as Windows is configurable via Group Policy Editor to lock out certain aspects. 

If not, you might want to look at your account settings to see if you are an Administrator or setup a local admin account.
If that's not the issue - the quick (but not recommended) band-aid method might be to disable Data Execution Prevention as that might potentially bypass it....

Finally, it just might be your install is borked and you might have to start all over again. I know I'm going to do that in the next day or two due to my issue that I'm having with Super Robot Wars 30 and also having some small issues with Windows Subsystem for Android since TikTok Web sucks and there is no desktop application option for Threads.

**Comment by Danjhop4** [comment] 2023-09-03 12:52
@LancerDawg75 personal laptop but my dad hates this type of stuff and he’s the admin it’s kinda of a odd situation

**Comment by LancerDawg75** [comment] 2023-09-03 14:38
> I am 25 but still treat me like 10 when it is computers

ha! I understand. I'm 48, but I still have my wife to answer to (and be her lifetime free tech support).

**Comment by EliezYT** [comment] 2023-09-05 21:28
> @EliezYT Done with an Asrock A770 with 252 Watt max. and in Arc Control +45/+45.
> 
> And thats made with the Acer Predator A770 252 Watt and in Arc Control 0/0
> 
> ReBar is on with both Cards
> 
> ![image](https://user-images.githubusercontent.com/123353653/265246595-e0859d28-251d-4607-87e9-805b70f56ada.png)
> 
> ![image](https://user-images.githubusercontent.com/123353653/265246682-4e35685f-e6b6-4fb5-b6cc-2a43ed26f826.png)
> 
> Greetings

I sadly don't have rebar because for some reason it's not supported on my motherboard despite many other brands having it as a option. Does rebar affect OpenGL performance that much compared to having it turned off?

**Comment by freak2fast4u** [comment] 2023-09-06 18:37
I have observed rather good OpenGL performance running the Furmark 2 beta : https://www.geeks3d.com/dl/show/705/UEEYzxyKzVp6ayq

Results are similar to Nvidia 3070's performance, depending on the CPU/RAM/MOBO it's running on. 
Also their result browser is way more usable for the Furmark 2 results than for Furmark 1 (see here : https://www.gpumagick.com/scores/). 

I'm more concerned about the Vulkan performance, and more specifically at 1440p where it tanks severely compared to 1080p. It simple doesn't seem to scale as well.

**Comment by LancerDawg75** [comment] 2023-09-08 16:24
@EliezYT 
> I sadly don't have rebar because for some reason it's not supported on my motherboard despite many other brands having it as a option. Does rebar affect OpenGL performance that much compared to having it turned off?

I really am not sure without having to test it. There are so many other factors with your system vs mine and also your system vs others here. So many factors influence how a system performs overall

- BIOS Settings
- BIOS version
- Thermals
- Memory speed and CAS timings (although CAS timings don't affect performance as much as how many MT/s does. However, MT/s affects Ryzen systems more significantly than Intel platforms.....so)
- Drivers (Intel does have chipset drivers too....sometimes they just are not easy to find)
- Windows Build and installed updates
- Startup options and resident programs running in the background

The list can go on and on. 

I don't think having ResizeableBAR could be a factor, but again, it's something that I would have to test or someone else that wants to beat me to the punch. I also would have to test to see if it is your PCI-E Gen that affects performance. So, it would be like

- Test with 4G Above Decoding/ResizeBAR off PCI-E Gen4
- Test with 4G/ResizeBAR on PCIE Gen 3
- ReBAR disabled Gen3
- Rebar Disabled Gen3 and (maybe) the current RAM speed you are running
- Same as above but also adding the CAS Latency timings that you are running as well

**Comment by Darklegion1978** [comment] 2023-09-08 17:59
@freak2fast4u done the Benchmark with Unigine / Arc Control 0/0 - 252 Watt

![Screenshot 2023-09-08 195007](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/123353653/08fb8f51-9b4e-4188-8c23-b246abf92270)

and

![Screenshot 2023-09-08 195417](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/123353653/6574bc32-371d-4f90-98da-865c66024bb5)

Its really ok for the A770

With the Furmark 2 beta, as you told before, VK with 1440p half the Points than with 1080p.

Greetings

**Comment by Arturo-Intel** [comment] 2023-09-19 19:31
@EliezYT if I read correctly, you cant enable ReBar?

**Comment by EliezYT** [comment] 2023-09-20 11:58
> @EliezYT if I read correctly, you cant enable ReBar? therefore getting that low score ?

From their results yes but I still need someone to test it on their system to see if this is the actual issue. I still think that regardless of rebar or not OpenGL shouldn't still be this low even with rebar on.

**Comment by LancerDawg75** [comment] 2023-09-22 11:10
I've been really lazy about this because there are way too many variables 

- My system is very different from yours. That means everything down to the hardware selection and configuration, BIOS settings, versions of Windows and things installed on it. There is really no real way that I could pin it down specifically and give you a definitive answer on what is going on

Either way, I did run it with the newer Furmark Beta 2.0.10 that I had to grab from the Discord server on Geeks3D. I'll put it up on my GDrive for anyone else that doesn't want to go through the motions of doing that, but also want to try it. It does have both OpenGL and Vulkan benchmarks on it. 

This is VERY oversimplified. The only things I did were:
- Disable Above 4G Decoding
- Disable Resizeable BAR
- Set PCI Express to 3.0/Gen3 

On my end, there wasn't a huge difference. It would be margin of error in this case. There was a performance hit reducing the settings down to close to what you are at, but nothing that says it is significant. The only way I would really know is if I had your exact system. I don't think that lowering my memory speed down to whatever you are operating at and changing the memory timings exactly the same as your system would change anything. 

I don't know if your CPU has anything to do with it. It might. Despite Furmark being a GPU only benchmark, it still needs the CPU to execute some aspects of the application in question. All that I can see is - something is off on your end. 

Anyway, on what I got. The only thing I have tweaked in Arc Control is that I have the power slider target maxed at 228W and a more aggressive fan curve. Only thing hugely different that I have in my system BIOS settings is a -25 Curve Optimizer setting in my Precision Boost Override. 

![furmark 2 PCI4-Rebar-Above 4G-OpenGL](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/b5e43522-2acd-4389-abc9-db530045d8f8)
Furmark with my system at PCI-E 4.0/Above 4G and Resizeable BAR enabled/OpenGL Benchmark 1080p

![furmark3 PCI4-rebar-above4G-Vulkan](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/08f62665-a703-46b4-b26d-3f5205e2e5fb)
Furmark Vulcan 1080p PCI-E 4.0/Above 4G Decoding + ReBAR enabled

![furmark 4 info PCI3-no rebar-no above 4G](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/9d92eab6-16a1-4876-ab6b-8cd63d9fb340)
Information to show that I have lowered the settings down to PCIE 3.0 and ReBAR + Above4G is disabled

![furmark 5 PCI3-NoRebar-NoAbove4G-OGL](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/e16c2228-fa40-48aa-9cbd-c8f1d667fb0a)
Furmark OpenGL 1080p with PCIE 3.0/ReBAR + Above4G Decoding disabled

![furmark 6 PCI3-noRebar-noAbove4G-Vulkan](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/0463cc74-ec11-4fb5-bb5a-cd0986c205ac)
Furmark Vulkan 1080p PCI-E 3.0/ReBAR + Above4G Decoding disabled

**Comment by LancerDawg75** [comment] 2023-09-22 11:14
Here is the [Google Drive link](https://drive.google.com/file/d/10ieN95D5xkV8PT0ULGaZnF8CEL_n3Erq/view?usp=sharing) for the updated Furmark Beta. 

It will trip Microsoft SmartScreen as an untrusted application. If you don't trust the link I provided, that's fine. [The link for the Discord channel to get it is here. ](https://geeks3d.com/discord/)

**Comment by Arturo-Intel** [comment] 2023-12-15 17:26
Closing this case

**Closed by Arturo-Intel** 2023-12-15 17:26 UTC
Labels: Info: Needs Replication, Type: Bad Performance

**Comment by Espionage724** [comment] 2024-04-05 22:07
> There is [Zink](https://docs.mesa3d.org/drivers/zink.html) which translates OpenGL to Vulkan, but that is for Linux only and I don't think that there is a package like DXVK where you can insert a .dill file to make the translation happen. However, there is [this article in Phoronix that states it is a work in progress.](https://www.phoronix.com/news/Zink-Windows-Kopper-Progress)

There's https://github.com/pal1000/mesa-dist-win/tree/master

Here's a guide I wrote for RuneScape: https://steamcommunity.com/sharedfiles/filedetails/?id=3198378027
And there appears to be a few posts about using it with Arc like: https://www.reddit.com/r/OpenMW/comments/187q239/better_performance_on_intel_arc_windows/

Trying to use Zink with UHD 630 had RuneScape crash (D3D12 works) but that's the only game I tried it with and I'm not sure if it's a driver thing, Mesa packaging, or RuneScape-specific.
