### ISSUE TITLE
Flashing in Only Up!

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#343] opened 2023-06-14 16:20 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Only Up!

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 14.06.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11748198/Intel.SSU.14.06.2023.txt)

### Description and steps to reproduce [Required]

Play the game

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

19020x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

I noticed that the Shading setting causes the most flashes, but other settings affect the flashes as well. Here's a screen record : https://1drv.ms/v/s!AmnzYyniwxuygaIa26-krdDLI5F0zA?e=cMdQdd (you have to download it, OneDrive for web doesn't support AV1)

**Comment by Arturo-Intel** [comment] 2023-06-14 17:54
Well i was unable to reproduce the flashing lights, I think i am missing something:
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/50439b44-5c75-4cc9-a0ab-700a42483793)

Using DX12 -> https://youtu.be/oXrzKoy4Qok

There is an error at the end of the video (DX12 related), the developers recommend to force the game to DX11 
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/78546dc1-0519-4668-bb70-3116dfb3bcfa)
Using DX11 -> https://youtu.be/nvQZZOnq81E
still no issue in there.

Just be sure that the ARC 770 is actually used to run the game
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/f53882e2-141c-4f41-a283-7170307c17c2)

You can find the exe file in this path:
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/ab2eaef9-8395-41c5-8caa-a506c59e6662)

Other thing could it be a corrupted drivers data, run a [Safe Mode DDU](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html) and re-install the drivers :)

I will be in the lab trying to reproduce this issue, 
--r2

**Comment by TheWonderfulTartiflette** [comment] 2023-06-14 18:20
Yes indeed, using -dx11 fixes the problem, but now the game runs on DX11, worse than DX12, and I'm not sure everyone would think of putting -dx11 in the Steam arguments

**Comment by Arturo-Intel** [comment] 2023-06-14 18:24
so in dx11 you cant see the flashing lights?
or the game doesn't crash after a minute or so?

**Comment by Arturo-Intel** [comment] 2023-06-14 18:25
I don't see the flashing lights either on dx11 nor dx12, so I am still thinking what could you have or I am missing to have that behavior on my end

**Comment by TheWonderfulTartiflette** [comment] 2023-06-14 18:29
Zell in DX!! I never crqshedm so I zon4t be qble to sqy if DX!@ hqs i;proved qnything here< Zhqt version qre you on M I4; on driver $#*(m so it ;qy be becquse ze hqve different drivers

**Comment by Arturo-Intel** [comment] 2023-06-14 18:44
OMG, I assumed it was 101.4382, sorry my bad, let me test with the 101.4289

**Comment by TheWonderfulTartiflette** [comment] 2023-06-14 18:45
Wait no no sorry I confused drivers, it's indeed with 4382, sorry

**Comment by Arturo-Intel** [comment] 2023-06-14 18:48
ahh! ok so we are in the same version, ok ok.

Did you try to run a Safe Mode DDU?
Sometimes there some drivers data corrupted 
Also running the ddu will give us a clean starting point

-- r2

**Comment by TheWonderfulTartiflette** [comment] 2023-06-14 18:49
I have already done DDUs like 30 times now, so yeah I don't think another DDU would help, given that I did one like 4 days ago

**Comment by Arturo-Intel** [comment] 2023-06-14 18:58
I am getting out of ideas, did you verify that the ARC 770 is being used to run the game?
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/a367333c-6854-4232-bb58-0c2c3db735e1)
?

--r2

**Comment by TheWonderfulTartiflette** [comment] 2023-06-15 20:22
The issue still appears with 4499 by the way

**Comment by Arturo-Intel** [comment] 2023-06-20 13:24
A quick summary:
using -dx11 it wont show the flashes and lights, but the quality of the game is not good
using -dx12 shows the behavior and also after a min or so the game crashes with a LowLevelFatalError
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/2afb7484-797a-40f8-b4ba-a39b887fc05e)

Is this the actual status of the bug?

--r2

**Comment by Arturo-Intel** [comment] 2023-06-20 13:28
I want to comment that I can't reproduce the flashing behavior at all, I have been trying in different systems, with different GPUs, resolutions, configurations, etc with no luck.

Also, the crash using Dx12 is already reported on our side and it is work in progress

--r2

**Comment by TheWonderfulTartiflette** [comment] 2023-06-20 14:09
> Also I want to comment that I can't reproduce the flashing behavior at all, I have been trying in different systems, with different GPUs, resolutions, configurations, etc with no luck.
> 
> Also, the crash using Dx12 is already reported on our side and it is work in progress
> 
> --r2

Would that be an issue on my game's files ? If you're allowed to download, [here they are](https://1drv.ms/f/s!AmnzYyniwxuygaInavwH2-J9l6T6YA?e=rA3Eum), you might try to launch the game from my own files

**Comment by Arturo-Intel** [comment] 2023-06-20 15:12
Ok i will try, meanwhile try to do a "verify files" routine from steam, just in case

**Comment by Arturo-Intel** [comment] 2023-06-20 17:07
Definitely something is wrong with your files, I see the flashing behavior.
Did you run the verify files option from steam?

**Comment by TheWonderfulTartiflette** [comment] 2023-06-20 18:02
Wow that's weird. Yes I actually verified the game files, even tried to
reinstall the game on another drive, no success
Even downloading the checked version, doesn't do anything. Clearly a
problem on my PC then, but I absolutely don't know where to start looking
for issues

Le mar. 20 juin 2023, 19:07, Arturo-Intel ***@***.***> a
écrit :

**Comment by Karen-Intel** [comment] 2023-08-18 16:27
@IGCIT could you help us close this one? Looks like the game configuration is different from the one we can access to
@TheWonderfulTartiflette please contact OnlyUP support to see why your game version is different
TY

Karen

**Closed** 2023-08-18 17:45 UTC
Labels: Info: Needs Replication, Type: Graphical Glitches
