### ISSUE TITLE
Unable to enable 10bpc on Monitor while using Intel ARC graphics, unless HDR is enabled

### ISSUE THREAD

**Issue by bizude** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#179] opened 2022-11-09 02:20 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

All applications. 

### Processor / Processor Number [Required]

Intel i9-13900K

### Graphic Card [Required]

Intel ARC A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.3793 (*latest*)
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1 (*October 2021 Update*)
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

[intel-ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/9966744/intel-ssu.txt)

### Description and steps to reproduce [Required]

![image](https://user-images.githubusercontent.com/81831122/200720974-db04322b-966e-47de-aa6c-f834b126da32.png)
![image](https://user-images.githubusercontent.com/81831122/200721123-d4a3fda0-9b7e-41f1-9f26-23f8c874c209.png)

I am unable to select bit-depth output options while using ARC A770 LE. When HDR is disabled, it forces 8-bit. When HDR is enabled, it forces 10-bit. I should be able to enable 10-bit without using HDR. 

### Device / Platform

Nixeus EDG27240X, connected via DisplayPort

**Comment by IntelSupport-Arun** [comment] 2022-11-10 06:15
Hi @bizude ,

Thank you for contacting us.
I have the following questions for you for further investigation:
1. May I know are you facing the same issue with Internal graphics or if the issue is specific while connecting the ARC 770? Please specify.
2. May I know the reason for disabling the HDR ? Any specific reason?
3.  Have you verified the issue with the previous  Intel Graphics Driver  [31.0.101.3430](https://www.intel.com/content/www/us/en/download/726609/intel-arc-graphics-windows-dch-driver.html)? If not, could you give a try and let us know your observations?

Help us get the above information so we can continue our investigation and issue reproductions. Thank you.

**Comment by IntelSupport-Arun** [comment] 2022-11-11 04:35
Hi @bizude ,
I had a discussion with the internal Team and here is update:
The Intel Graphics Command Center currently only supports changing the color depth for native HDMI outputs.
The Intel® Arc™ Limited edition cards use a Protocol Converter (PCON) to drive its HDMI from Display Port, thus this HDMI is not native.
In consecuense, changing the color depth in currently not supported the Intel Graphics Command Center when using an Intel® Arc™ Limited Edition card.
For Intel® Arc™ cards from other manufacturers and systems using mobile SKUs of Intel® Arc™, please refer to the manufacturer's documentation to verify if their HDMI are native or not.

Hope this help to answer your questions. Thank you.

**Comment by bizude** [comment] 2022-11-11 15:05
> Hi @bizude ,
> 
> Thank you for contacting us. I have the following questions for you for further investigation:
> 
>     1. May I know are you facing the same issue with Internal graphics or if the issue is specific while connecting the ARC 770? Please specify.
> 
>     2. May I know the reason for disabling the HDR ? Any specific reason?
> 
>     3. Have you verified the issue with the previous  Intel Graphics Driver  [31.0.101.3430](https://www.intel.com/content/www/us/en/download/726609/intel-arc-graphics-windows-dch-driver.html)? If not, could you give a try and let us know your observations?
> 
> 
> Help us get the above information so we can continue our investigation and issue reproductions. Thank you.

1. I haven't tested the Xe iGPU lately
2. While my monitor "supports" HDR, it isn't a good implementation. 
3. I have been unable to do this on any driver version

**Comment by bizude** [comment] 2022-11-11 15:10
> Hi @bizude , I had a discussion with the internal Team and here is update: The Intel Graphics Command Center currently only supports changing the color depth for native HDMI outputs. The Intel® Arc™ Limited edition cards use a Protocol Converter (PCON) to drive its HDMI from Display Port, thus this HDMI is not native. In consecuense, changing the color depth in currently not supported the Intel Graphics Command Center when using an Intel® Arc™ Limited Edition card. For Intel® Arc™ cards from other manufacturers and systems using mobile SKUs of Intel® Arc™, please refer to the manufacturer's documentation to verify if their HDMI are native or not.
> 
> Hope this help to answer your questions. Thank you.

It "answers" the question but not in a good way.  How can you lack the ability to change bit depth via DisplayPort?!

Being able to select bit depth is a **required** feature for me. 

At the very least, if a user is not allowed to manually choose the bit depth then the card should use the highest option available otherwise.

**Comment by IntelSupport-Arun** [comment] 2022-11-15 03:19
Hi @bizude ,
Sorry, unfortunately changing the color depth is currently only supported over native HDMI outputs not via Display port.

 Intel® ArcTM Limited Edition cards architecture does not support HDMI natively (via PCON) and DP does not offer the capability to change color depth, so this feature isn't supported. 

As this feature is not supported, I would like to close this case. Let me know if you have any further questions.

**Comment by Pawels1992** [comment] 2022-11-15 11:11
Hi! I have a question because 10-bit is important for me too. @IntelSupport-Arun You wrote that "changing the color depth is currently only supported over native HDMI outputs not via Display port" but how it works when I'm using Display Port with SDR and I have 8-bit but when I change to HDR then I have 10-bit depth via Display Port? It is possible to forced in next update to use 10-bit with SDR or its only "exclusive" for HDR?

**Comment by IntelSupport-Arun** [comment] 2022-11-21 06:50
Hi @bizude  ,
The support for 10-bit color depth is currently hardcoded to work only when HDR is enabled, since this is a requirement for HDR [displayhdr.org](https://displayhdr.org/#tab-500)

And, as mentioned earlier, manually changing the color depth is currently only supported on native HDMI outputs.
Our team has submitted a feature request asking to enable changing the color depth manually on DisplayPort outputs. 

Due to current workloads, I would like to let you know it might take up to 12 months to complete. However, it will take time, and it is very unlikely it will be available in the next update.

 Having answered your follow-up questions and raised a feature request for your request, I would like to close this case if you don't have any more questions. I appreciate your understanding.

**Closed** 2022-11-21 16:48 UTC
Labels: Info: Needs Replication, Type: Support

**Comment by mickeybricks** [comment] 2023-04-04 07:37
It`s Apr 4 2023, and I faced the same problem.

**Comment by sergeyn** [comment] 2023-05-28 12:51
Hi, same here. It is end of may 2023 now and I'm trying out graphics output of 13900k  and I Can't make 10 bit work neither over display port nor over thunderbolt. It's 8 bit always. My monitor is not an HDR monitor, and 10 bit works no problem on nvidia gpu (both over thunderbolt and DP connections)

**Comment by Shonk** [comment] 2023-09-24 20:15
Still no support added 24/09/23

Pull your fingers out of your a**es

I have enabled my igp on my 13900K to diagnose multi a monitor problem with my RTX 3090
and guess what the UHD 770 with 31.0.101.4826 has no 10bit support for DP without HDR enabled

Its not rocket science you can either fix it with a toggle like nvidia does
or use 10bit by default like amd does on my 6900XT

**Comment by srgzx** [comment] 2023-11-23 23:00
How is this still not fixed when it's nearly 2024?

**Comment by theofficialgman** [comment] 2024-06-15 05:55
Same deal on iris xe graphics systems.

Guess another reason to keep recommending AMD apus when basic features like this are missing on Intel.

**Comment by srgzx** [comment] 2024-06-15 15:24
So this still hasn't been fixed?  Unbelievable...I stopped using Intel GPU because of this problem, lol.

**Comment by brzz** [comment] 2024-07-12 10:39
NOW,new driver is release,  5762 can be enable 10bit SDR output at DP
![无标题](https://github.com/user-attachments/assets/819b0c74-58df-4ebc-a793-2567aca64e88)

**Comment by KevinMX** [comment] 2024-07-13 08:13
> NOW,new driver is release, 5762 can be enable 10bit SDR output at DP ![无标题](https://private-user-images.githubusercontent.com/8848257/348231051-819b0c74-58df-4ebc-a793-2567aca64e88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NTczOTEsIm5iZiI6MTcyMDg1NzA5MSwicGF0aCI6Ii84ODQ4MjU3LzM0ODIzMTA1MS04MTliMGM3NC01OGRmLTRlYmMtYTc5My0yNTY3YWNhNjRlODgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTNUMDc1MTMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2E2YTRhMzIzNWRiMTUwZDIwZjljMTc0YjE2MzliNzhiNDdmNmQ3YTM4YjVlMzZlZTg4MDUyMWNiMmM0NGQ3OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EtKDvbPj67W7r_Q_CFEd1X_xhZADZbDf_H16fLVPAVA)

Confirmed 10bpc is working on my Arc A380 now.

And also for those who tried to enter UEFI BIOS via HDMI and found their resolution locked at 800*600, and probably with the UEFI BIOS GUI not working properly (e.g. on MSI boards the UEFI Settings GUI is totally messed up via HDMI), the new version has fixed this.

Please connect via HDMI and upgrade the driver, which will also upgrade firmware.

**Comment by alphagojo** [comment] 2024-07-13 22:17
any chance we will see this on Iris Plus 655? Just bought a high-dollar Eizo monitor for photography editing which supports 10-bit SDR thinking Nuc was 10-bit capable (as it literally says in the manual).

**Comment by leonids2209** [comment] 2024-08-01 22:02
Any chance this can be supported for UHD620 as well? is it a change in the driver or in the command center only?

**Comment by Akaccia** [comment] 2024-10-31 02:30
> UHD620 也有可能支持此功能吗？是驱动程序的更改还是仅命令中心的更改？

![image](https://github.com/user-attachments/assets/d959a0de-9702-40ca-9205-7c542681ba57)

**Comment by esierp** [comment] 2025-01-31 12:52
Will be there any update on this Topic? @IntelSupport-Arun 

Will there be any support for the UHD Graphics 620 10-Bit SDR?

**Comment by freddellmeister** [comment] 2025-05-23 19:33
Intel® UHD Graphics 630 still waiting for 10 bit support for my internal oled panel.
