### ISSUE TITLE
Issues with Spider-Man: Remastered

### ISSUE THREAD

**Issue by BelleNottelling** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#377] opened 2023-07-02 04:22 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Spider-Man: Remastered

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i7 13700K

### Graphic Card [Required]

Arc A770 LE 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11928573/igcit_ssu.zip)

### Description and steps to reproduce [Required]

I've noticed a handful of issues while playing Spider-man: Remastered on my A770.
These two issues seem to get worse / happen after an extended playtime (an hour or longer): 
 - The game will occasionally crash, seemingly with no repeatable cause. No error message is shown, the game just closes. I've actually had to roll back to a backup save twice from this.
 - In some fights, the game will exhibit graphical glitches. There doesn't seem to be a specific cause for it, but I captured an example: https://www.youtube.com/watch?v=SbU7n-ZvFAo

I've also noticed the game will fairly frequently freeze to load in assets. However, I am running the game on an HDD which I know isn't recommended. With that being said though, I have a friend who's also playing the game off an HDD and an NVIDIA GPU who said it doesn't do that for him and it was also an issue that Iceberg Tech noted in his review of the A770: https://youtu.be/b4RPVNhUwSg?t=573.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2460x1440

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/17304943/f0256026-775b-4a23-9b1b-5ed488d4ed77)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/17304943/199f56b8-c0cb-4053-8035-10836f364ee9)

**Comment by BelleNottelling** [comment] 2023-07-03 07:15
Noticed some more graphical glitching:
https://www.youtube.com/watch?v=iTy1DOc395o

The settings I used were different than the ones when I originally submitted this report, but you can see the specific settings at the start of the YT clip. It's also worth noting the crashing and other glitches are still happening with the new settings I am currently playing with

**Comment by LancerDawg75** [comment] 2023-07-04 03:35
I saw this too using XeSS. I also saw flickering while standing still on a rooftop and red bricked buildings would also flicker. Switching over to IGTI was my remedy. It's kind of weird because using XeSS on MM, there wasn't any of the problems with flickering. 

I can't remember if going to IGTI helped with the stutters though. It's been awhile since I have played it and I recently finished MM not too long ago and well, DeQuervain's has struck me again, so high button pressing games are kind of on the backburner for me.

**Comment by Karen-Intel** [comment] 2023-07-13 16:24
Just a heads up in this thread :)
I was able to repro the crash for the game. Looks like the ray traced reflections setting is the one that triggers it if you set it up before launching the game > If you set it up when the game has loaded it doesn't crash at all
About the reflections we could not repro them :( with the same configuration in the video. [Have a look](https://www.youtube.com/watch?v=SXNbJ9wZyHc)

We will keep on doing some testing with the ray traced reflections setting in other systems and see what else we can find

Karen

**Comment by BelleNottelling** [comment] 2023-07-20 01:54
Fyi: now that I have upgraded to an RX 6950 XT, it looks like the occasional freezing this game would do to load in assets is completely gone, so it seems likely that is also caused by some kind of driver issue with the A770

**Comment by Arturo-Intel** [comment] 2023-09-19 21:16
@BelleNottelling did you jump also to SSD? just curious

**Comment by BelleNottelling** [comment] 2023-09-19 22:00
@Arturo-Intel I did not. Other than the GPU being swapped out my system specs remained the same and Spider-Man stayed on the same HDD as before

**Comment by Arturo-Intel** [comment] 2023-09-19 22:04
@BelleNottelling I see, ok, still working on reproduce this. 
AH! another question, do you remeber if you had several displays? or if you where using a DP or an HDMI? when the issues ocurred?

**Comment by BelleNottelling** [comment] 2023-09-19 22:16
@Arturo-Intel Just a single display that's 2560x1440, 144Hz, free-sync compatible, and connected over display port.
It's either an Asus `VG32VQ` or `VG32V` depending on if you go by the order history on Amazon or what Windows lists it as.

I'm still using that display now if you need me to run any tool or give you info on it.

**Comment by Arturo-Intel** [comment] 2023-09-19 22:17
@BelleNottelling No, no, its ok, im just gathering info. Thank you

**Comment by BelleNottelling** [comment] 2023-09-19 22:17
Not a problem, wishing you luck

**Comment by Arturo-Intel** [comment] 2023-12-11 17:39
@LancerDawg75 can you help us to confirm the issue is still there? using the latest driver ([101.5074](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) 
I cant see the flickering at all

**Comment by LancerDawg75** [comment] 2023-12-13 08:39
> @LancerDawg75 can you help us to confirm the issue is still there? using the latest driver ([101.5074](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) I cant see the flickering at all

I'll install it tommorrow, @Arturo-Intel and get back with you on the results using XeSS. 
Do you want me to try it in all modes of XeSS or does it not matter -- and just pick one?

**Comment by LancerDawg75** [comment] 2023-12-14 08:17
Update: 14 Dec 2023: 
Tried it with the latest driver, and on my end, it does seem like the flickering under XeSS (using Ultra Quality) no longer appears on red bricked buildings anymore and it also seems like the frequent hitching during transversal is gone (which didn't seem to matter what upscaling method you used or if it was off). 

This was me playing a NewGame+ at the beginning and for about 30 minutes.

**Comment by Arturo-Intel** [comment] 2023-12-15 16:54
@LancerDawg75 Thanks for the confirmation.
Closing this issue.

**Closed by Arturo-Intel** 2023-12-15 16:54 UTC
Labels: Info: Replicated, Type: Application Crash, Type: Graphical Glitches
