### ISSUE TITLE
Just Cause 4

### ISSUE THREAD

**Issue by poulan9** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#31] opened 2021-03-02 13:11 UTC
#### Game _[Required]_

Just Cause 4
---
#### CPU _[Required]_
i7 1160G7
---
#### GPU Driver Version _[Required]_

27.20.100.9168
---
#### Rendering API _[Required]_

**API** _[DirectX, OpenGL, Vulkan]_:
**API Version** _(example DirectX 12)_:
DirectX11
---
#### Windows Build Number _[Required]_
Latest

---
#### Description _[Required]_
Awful frame rate
---
#### Steps To Reproduce _[Required]_

Present at all times
---
#### Screenshots _[Optional]_

---

**Comment by leoben2** [comment] 2021-04-01 06:05
I think the performance on this game on iGPU is generally poor, we're seeing sub 15 FPS on top TGL SKU. Not sure we can do much about it as the min spec is above it.

**Comment by poulan9** [comment] 2021-04-01 06:33
Yet Microsoft FS2020 and Cyberpunk 2077 play fine on TGL at lowest settings.

**Comment by estebanr863** [comment] 2021-11-03 00:03
Hi @poulan9, this issue was reported internally and a fix is in developmente. I'll let you know once this fix is included in a driver for you to test it.

**Comment by poulan9** [comment] 2021-11-03 00:33
That's awesome news. thank you so much.
    On Wednesday, 3 November 2021, 00:03:30 GMT, Esteban ***@***.***> wrote:  
 
 


Hi @poulan9, this issue was reported internally and a fix is in developmente. I'll let you know once this fix is included in a driver for you to test it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PacoAvelarDiaz** [comment] 2021-11-03 18:02
@estebanr863 
Has this issue been replicated too  ?
https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/81

It is same game, but graphical issue

**Comment by poulan9** [comment] 2021-11-04 10:23
That one I haven't noticed. Do you have an idea if the fix for my issue will be in the next driver release or a subsequent one?
Thanks
    On Wednesday, 3 November 2021, 18:02:34 GMT, PacoAvelarDiaz ***@***.***> wrote:  
 
 


@estebanr863
Has this issue been replicated too ?
#81

It is same game, but graphical issue

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by estebanr863** [comment] 2021-11-04 16:13
Not yet, there are several other issues in the queue that one. I'll comment on the [#81](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/81) once we get to it.

**Comment by poulan9** [comment] 2021-11-04 18:33
#81 isn't affecting me, I was referring to the issue that I raised. Do you know where that is in the queue?
Regards

    On Thursday, 4 November 2021, 16:13:30 GMT, Esteban ***@***.***> wrote:  
 
 


Not yet, there are several other issues in the queue that one. I'll comment on the #81 once we get to it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pacoa-kdbg** [comment] 2021-12-31 18:56
This issue is not present on latest driver @estebanr863 performance has improved a lot

**Comment by poulan9** [comment] 2022-01-01 02:07
The performance is slightly better but still unplayable and rarely more than 19 FPS. I also experienced a crash on the first outing:




    On Friday, 31 December 2021, 18:56:41 GMT, pacoa ***@***.***> wrote:  
 
 


This issue is not present on latest driver @estebanr863 performance has improved a lot

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pacoa-kdbg** [comment] 2022-01-01 07:45
@poulan9
Sorry, my bad
It is still really bad (just tested again to confirm)

It used to be <10 fps for me,
Now is between 18 and 24, still not enjoyable

Win11
Latest driver
Steam version

**Comment by estebanr863** [comment] 2022-03-09 20:22
Hi @poulan9 and @pacoa-kdbg 

Our driver development team found this issue’s root cause to be on the game side. The issues seem to be caused by the game being heavily CPU-bound on Intel Tiger Lake in contrary to AMD. This results on the game not fully utilizing the iGPU when running in Intel. We have already escalated this issue to the game developer, but they are unwilling to work on a fix for this.

**Closed** 2022-03-09 20:59 UTC
Labels: Type: Bad Performance, Info: Won't fix, Info: Game Issue
