### ISSUE TITLE
No display signal via DP in WinRE (black screen in Windows Recovery)

### ISSUE THREAD

**Issue by szmigieldesign** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#437] opened 2023-08-18 12:07 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

WinRE

### Processor / Processor Number [Required]

i5-13600KF

### Graphic Card [Required]

Acer Predator ARC A770 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12378938/igcit_ssu.txt)

### Description and steps to reproduce [Required]

I have no display signal on any of the A770's DP when entering WinRE. The WinRE seems to boot normally, as it proceeds to normal boot after pressing "Enter", although I can't see anything since my screen powers down. I've tried all 3 DP's and they all work fine on normal boot, but have no signal on WinRE.

I have been using this PC for approx. two months, and it was possible to enter WinRE earlier with the same connection, calbe and display. However, I'm unable to pinpoint an exact moment in time when the GPU stopped giving me DP signal when entering WinRE as I rarely enter it (basically just for the DDU and the safe mode).

I've tried reinstalling latest A770 driver with DDU uninstall prior (although not in the safe mode as I can't access it) and it doesn't fix the issue.

I've also done a Windows 11 reinstall / fix via Media Creation Tool as instructed via Microsoft Support that didn't help either.

Otherwise, everything works fine - UEFI is ok and normal W11 boot is also OK.

I have no idea how to debug this issue further and would be happy if at last someone with similar config (Acer A770 and screen linked via DP) could try and reproduce the issue? My screen is ASUS PA279 (1440p / 60Hz).

**Comment by Karen-Intel** [comment] 2023-08-18 19:53
@szmigieldesign ty for your submission!

We will try to repro this behavior in our lab machines and let you know! Stay tuned!

Karen

**Comment by 12080257** [comment] 2023-08-25 13:14
Hi @szmigieldesign 

We were trying to simulate the issue described above with A770 on latest driver 101.4644 but could see that WinRE screen render fine even after trying multiple different models with DP port and cable. so I would like to ask you few more details and see if we can isolate the issue that you are facing. Please find internal [simulation video](https://www.youtube.com/watch?v=K02cfqkJDhY) for your reference only (its upside down) 

1: Can you try below steps to enter in WinRE screen over HDMI where its working for you and then on DP port (Keep pressing shift --> Click on Reboot option from Windows start menu --> Verify Please Wait message while computer restart and enter in WinRE)
2: Does issue occur over DP without Intel arc drivers (Please uninstall Arc drivers and then verify if you are able to enter into WinRE env) OR else disable Arc drivers from device manager and check
3: Can you access BIOS options on your setup ?
4: Can you try connecting same monitor and same cable to either to other GPU model or integrated motherboard DP port to check if it occur there too ?
5: Can you also try updating your BIOS to 1220 which is latest one and check issue ?
6: Can you check monitor under device manager, does it shows Generic PnP monitor or Monitor model name ? Is it possible to verify issue with other display model ?

**Comment by Vivek-Intel** [comment] 2023-08-29 05:09
Hi @szmigieldesign good to know that issue has been resolved with latest BIOS update.
Display render before control goes over to OS such as POST screen, BIOS screen, WinRE are dependent on generic UEFI drivers of the system also so it is not sure  that issue was caused by Arc display driver here.

Can we close the case as issue is solved with BIOS update ?

**Closed** 2023-08-29 06:37 UTC
Labels: Info: Needs Replication, Type: Support
