### ISSUE TITLE
OBS encoder error while streaming

### ISSUE THREAD

**Issue by zrmdsxa** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#747] opened 2024-03-25 11:03 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

OBS Studio 30.0.0

### Processor / Processor Number [Required]

Ryzen 7600X

### Graphic Card [Required]

Arc A750

### GPU Driver Version [Required]

31.0.101.5330

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[report.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14742450/report.txt)

### Description and steps to reproduce [Required]

Start streaming and it may randomly occur. This time I was streaming Helldivers2 and the error occurred 29 minutes into the stream.

Previous: https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/282

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/5502880/335cd5f4-894f-4531-9fb2-65ef70e0c0f5)

### Application / Windows logs

[2024-03-24 15-58-44.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14742423/2024-03-24.15-58-44.txt)

**Comment by rmorera-intel** [comment] 2024-03-26 21:53
@zrmdsxa I see you have been getting this error on random occasions with different games and yet replication hasn't been successful on other systems. 
Is this error also occurring when you record only (no streaming)? The reason I'm asking is because the app log shows connection errors ( "heart_beat_check_server_client_callback") right before the encoding error occurs - which perhaps leads to GPU time-out.

I checked [OBS forums](https://obsproject.com/forum/threads/an-encoder-error-has-occurred-while-streaming.136609/) and other users have reported the same error before on other GPUs, and among some of the causes can be a faulty GPU.
I'm leaning towards hardware since we haven't seen this reported by other Arc GPU users nor in our tests which seem to rule-out drivers. Can you swap the GPU? If this is an Intel Limited Edition (LE) you can contact [Intel Customer Support](https://www.intel.com/content/www/us/en/support/contact-intel.html) directly to evaluate warranty options.

**Comment by zrmdsxa** [comment] 2024-04-01 22:37
I contacted Intel support but they haven't responded yet. They were supposed to follow up today.

**Comment by rmorera-intel** [comment] 2024-04-02 05:52
Thanks for the heads-up, you'll be contacted by Intel support soon. I'll close this one but if you need further help with the new GPU just add a new comment and we'll pick it from here.

**Closed by rmorera-intel** 2024-04-02 05:52 UTC
Labels: Info: Needs Replication, Type: Support

**Comment by zrmdsxa** [comment] 2024-04-08 23:16
@rmorera-intel Suppport did not  follow up on April 1st like they said they would

**Comment by rmorera-intel** [comment] 2024-04-09 01:33
Let me know the case number and I'll check it and make sure they get back to you ASAP.

**Comment by zrmdsxa** [comment] 2024-04-09 05:58
@rmorera-intel Request# 06176289
