### ISSUE TITLE
Dirt 5 crash at launch

### ISSUE THREAD

**Issue by hididi31** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#40] opened 2021-03-22 14:02 UTC
#### Game _[Required]_
Dirt 5

---
#### CPU _[Required]_
I7 1160G7

---
#### GPU Driver Version _[Required]_
Latest Intel GPU driver

---
#### Rendering API _[Required]_

**API** _[DirectX, OpenGL, Vulkan]_:don t know
**API Version** _(example DirectX 12)_:don t know

---
#### Windows Build Number _[Required]_
Latest build

---
#### Description _[Required]_
Just want to see if the game run well on IRIS XE but the game crash at launch 
---
#### Steps To Reproduce _[Required]_
Just launch the game and it will crash

---
#### Screenshots _[Optional]_

---

**Comment by leoben2** [comment] 2021-04-01 05:53
We've detected a corruption but can't find a crash so far. Can you provide more accurate system and OS details pls?

**Comment by PacoAvelar** [comment] 2021-09-01 19:44
This game works fine on the steam version
I just booted and played:
i7 1165G7
16 GB ram
Win 11
GPU Driver 9862
Screen resolution 720p,
In game settings to low


Not sure if the issue should be closed and keep track for the not-working games on windows store on a single issue instead of per-game

**Comment by Valkirie** [comment] 2021-09-16 15:15
@hididi31 can you let us know if the issue still exists and your game platform (steam, other) ?

**Comment by vumaquan** [comment] 2021-09-17 09:41
The game crashes at launch with an error code “tryCreatingPipelineStateFromCache(pipelineStateDescnullCashedPro, plnOutPipelineState)’failed with ‘HR = 0x8007000e”

Gamepass version
intel lastest driver 9864 on oneXplayer

**Comment by PacoAvelar** [comment] 2021-09-17 18:00
@vumaquan can you test with 9894 (BETA) ?

I have no issues with the steam version of it

**Comment by estebanr863** [comment] 2021-11-11 17:29
Hi @vumaquan ,

We were able to reproduce the crash on launch for the GamePass version and this issue is now on our driver development team’s queue. However, just to set the right expectations, given the current load on the dev team, this fix could take between 3 to 6 months to be included in a driver release.

**Comment by estebanr863** [comment] 2021-12-03 20:54
Hi @vumaquan, this issue is no longer happening on our lab with driver version 30.0.101.1069. Can you please test with this version?

**Comment by vumaquan** [comment] 2021-12-05 03:57
> Hi @vumaquan, this issue is no longer happening on our lab with driver version 30.0.101.1069. Can you please test with this version?

Nice! But I don’t have any devices with intel at that moment. Just sold all and purchased AMD version instead
Thanks for your info anyway! Appreciate that!

**Comment by IGCIT** [comment] 2021-12-05 11:45
closing this then, since both @hididi31 and @vumaquan no longer have an intel gpu and the issue appears to be fixed.

**Comment by bhatiak2050** [comment] 2022-01-02 07:26
Hello, I would like to add to this discussion as I am facing this issue today. I also downloaded the game from Game pass, i have an i3 1115g4 with latest iris xe graphics drivers (30.0.101.1191) and the error i get when launching the game is:

`'tryCreatingPipelineStateFromCache(pipelineStateDesc, nullCachedPso, pInOutPipelineState)' failed with 'HR = 0x80070057, Reason = E_INVALIDARG:  This usually means the shader binding layout has changed and the shader being loaded (see TTY immediately before this msg) was built with an old binding layout, so that shader/.gpso needs rebuilding.'`

**Comment by IGCIT** [comment] 2022-02-08 20:16
@bhatiak2050 can you try latest driver 1340?

**Comment by estebanr863** [comment] 2022-02-22 18:00
Hi @bhatiak2050,

Were you able to test if you issue is resolved on driver 30.0.101.1340?

**Comment by bhatiak2050** [comment] 2022-02-23 04:27
Hi,
I have tested the game on driver 30.0.101.1340 and it is now working as intended.

**Closed** 2022-02-23 09:08 UTC
Labels: Info: Can't Replicate, Type: Application Crash
