### ISSUE TITLE
In Modern Warfare 2, the Hydroelectric Map runs much, much slower than every other map

### ISSUE THREAD

**Issue by JohnnyTex** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#243] opened 2023-02-14 12:00 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Call of Duty: Modern Warfare II

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [X] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5 12600k

### Graphic Card [Required]

ARC A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[4123ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10732080/4123ssu.txt)

### Description and steps to reproduce [Required]

As the title suggests, this map for some reason just runs extremely slow compared to every other map in the game. While most other maps can at least keep the fps within striking distance or above 100fps, this map is at best an 85fps map on average, with frequent dips into the 70s and even plunges into the 60s. 

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2560 x 1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Ultra preset, w/ a few settings tweaked (mostly lower).

**Comment by IntelSupport-Arun** [comment] 2023-02-15 04:15
Hi @JohnnyTex ,

Thank you for contacting us.
I will check from our side and update you the result.

**Comment by JohnnyTex** [comment] 2023-02-16 00:40
I suppose it would be beneficial to include that I'm running the game using XeSS Performance.

**Comment by IntelSupport-Arun** [comment] 2023-02-17 05:20
Hi @JohnnyTex ,

Thank you for the confirmation.
There is a new Beta driver version [31.0.101.4125](https://www.intel.com/content/www/us/en/download/729157/intel-arc-iris-xe-graphics-beta-windows.html) has been released. Could you check and confirm the issue is still seeing with the latest driver?

**Comment by JohnnyTex** [comment] 2023-02-17 12:06
By virtue of the problems mentioned in issue #246 , the map is no longer much slower than the other maps, as now almost every map is as slow as this one. Short and to the point, there have been no improvements on this map, it still runs at best at 80fps, most of the time in the 70s, and often ventures into the 60s.

**Comment by JohnnyTex** [comment] 2023-02-17 15:18
See newest message of issue #246

**Comment by IntelSupport-Arun** [comment] 2023-02-20 04:30
Hi @JohnnyTex ,

Do you mean the issue is still observed with the latest driver [31.0.101.4125](https://www.intel.com/content/www/us/en/download/729157/intel-arc-iris-xe-graphics-beta-windows.html) ?

**Comment by JohnnyTex** [comment] 2023-02-20 05:08
Yeah. Poor phrasing on my part, what I mean to say is that the map still runs very, very slowly, but now the whole game runs slower too.

**Comment by Arturo-Intel** [comment] 2023-04-19 17:44
Hello @JohnnyTex 
I dont know if you had a chance to try with the 4255 version of the driver?
I was using a Arc 750 and had a 84.1FPS avarage playing a 6 man free-for-all match on the Hydroelectric map.
![image](https://user-images.githubusercontent.com/92489452/233156332-73e32acc-4180-4b63-91c1-8c0db0840283.png)

Settings:
![image](https://user-images.githubusercontent.com/92489452/233156858-cc7a3b33-26a2-430a-96ec-7bac2d01593b.png)
![image](https://user-images.githubusercontent.com/92489452/233157132-b7079fbf-4aae-4928-995c-5c70c8337477.png)

**Comment by JohnnyTex** [comment] 2023-04-19 20:33
What cpu were you using?

**Comment by JohnnyTex** [comment] 2023-04-19 22:07
Oh, I see you're using the "recommended" preset, I'm using basically Ultra. Every other map still performs markedly better I'd say, though there are emerging "problem spots" on other maps. I'm long overdue on a comprehensive update on all my MW2 reports, so bear with me. Things are hectic on my end (getting ready for finals, graduation and whatnot), so I've been behind in updating stuff.

**Comment by Arturo-Intel** [comment] 2023-04-19 22:28
ADL 129000k with Arc 750

**Comment by Arturo-Intel** [comment] 2023-04-19 22:29
I will try in ultra and share the FPS graphs in a moment, just to have it documented.
Did you use XeSS (or other) in your original configuration?

**Comment by JohnnyTex** [comment] 2023-04-19 23:18
I'd imagine the CPU difference may or may not have played a difference there (given that I play on a 12600k). This is a bigger and more complex map than, say, Farm 18, so maybe that's the culprit. I'd also like to see what the graphs are for other maps (like the Raceway map), given that I only reported this map's performance as an issue given that when I was testing it I noticed a performance disparity. 

And yeah, I did my tests with XeSS set to performance, and I also tested it with other methods (most notably FSR).

**Comment by JohnnyTex** [comment] 2023-04-20 07:34
I just got to play on the map again in regular Quick Play, and can say that the map performs much, much worse than the others. On smaller maps like Farm 18 or the Hotel map, I regularly hit 120fps if not above. Even on other large maps like the newer Resort map I was at a comfortable 100fps or above. But on Hydro, I never seemed to break out of the 80s, and plummets into the 70s weren't uncommon. All this despite having XeSS set to Performance.

**Comment by JohnnyTex** [comment] 2023-04-20 07:34
Do y'all think there's merit to the idea that it could come down to a processor difference? I'm open to the idea, again given that it's bigger and more complex.

**Comment by Arturo-Intel** [comment] 2023-04-24 18:04
I was talking with my engineering team about this (and others) performance issues and one of the things they request is to have is consistent data, meaning that testing the FPS drops/highs on multiplayer games are not constant (it depends a lot in the action of the match and other variables)
What this mean?, we need to being able to run the same run every time. 

Fortunately COD:MW2 comes with a benchmark tool (it takes no more than 1min to run it), that is using the Hydroelectric map (yes! 2 birds, one stone case).
I will run 10 times the benchmark tool and get data from my end but it would be very beneficial have also your data with your rig, this way we can have a better view of the problem.

If you can help me with this, please remember to use beta driver 4311 o stable driver 4255, do a DDU clean up before running the benchmark tool 

Thank you in advance and thank you for your patience.
--r2

**Comment by JohnnyTex** [comment] 2023-04-25 04:38
I'm not entirely certain the MW2 benchmarking tool is all that accurate, so I'm a tad skeptical if I'm gonna be honest. I can go ahead and run it soon to see just for the sake of it though. Also, if we really need things to be replicable to such an extent, how can any multiplayer game be reasonably benchmarked? Not all of them have benchmark tests. In this case specifically, I think it's fairly easy to test outside the benchmark test. The map performs worse from the very start of the match, with no extra factors complicating things.

**Comment by JohnnyTex** [comment] 2023-04-26 01:55
I was using 3411 when I made my observations. I haven't installed the newest one yet, and can't at the moment due to my PC having RAM issues. So, I'm gonna have to postpone testing this until I get my PC fixed.

**Comment by Arturo-Intel** [comment] 2023-05-05 17:33
Using driver 31.0.101.4314
Ultra settings with 2560x1440
![image](https://user-images.githubusercontent.com/92489452/236522417-171a0765-404b-46ce-ba56-a273ec6f0182.png)
Full Screen Exclusive 86FPS average
![image](https://user-images.githubusercontent.com/92489452/236522557-1e27119d-9da2-4f57-bdfb-60f6608f4437.png)
Full Screen Borderless 78FPS average
![image](https://user-images.githubusercontent.com/92489452/236526255-c09f8b86-a0ab-4f2a-ac25-55b5e112d927.png)

**Comment by Arturo-Intel** [comment] 2023-05-05 17:38
Benchmark tool:
![image](https://user-images.githubusercontent.com/92489452/236527881-7fde8e48-35c5-4528-84e3-2b07fb51ef0d.png)
:o

**Comment by rmorera-intel** [comment] 2024-01-18 17:08
Hi @JohnnyTex we haven't check this with you in a while - sorry about that.
Our internal tests revealed significant improvements since driver 101.4572 so our dev team closed this bug from our side. If the issue persists in other map(s) please open a new bug report.

**Closed by rmorera-intel** 2024-01-18 17:08 UTC
Labels: Info: Needs Replication, Type: Bad Performance
