### ISSUE TITLE
PAYDAY 3 very very VERY bad perfomance

### ISSUE THREAD

**Issue by Noobachyo** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#537] opened 2023-09-24 17:12 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

PAYDAY 3

### Game Platform [Required]

- [ ] Steam
- [X] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i3-10105f

### Graphic Card [Required]

Intel Arc A380

### GPU Driver Version [Required]

- [X] 31.0.101.4826
- [ ] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

No, because I can’t download your software from Russia

### Description and steps to reproduce [Required]

all settings

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

tried all the settings

### Device / Platform name

PC

**Comment by Noobachyo** [comment] 2023-09-24 17:14
The video card is constantly loaded at ~60% in the game, but it is always at 100% in the menu and cutscenes

**Comment by Noobachyo** [comment] 2023-09-24 17:17
https://drive.google.com/file/d/135EZBFQMC6zzWh0FhqXIscR1jTpb-MTj/view?usp=sharing
https://drive.google.com/file/d/1kwOCeVHtFkPuqcuZBdP-1FZqYKEOkKYS/view?usp=sharing

**Comment by IGCIT** [comment] 2023-09-24 18:24
duplicate of #536 

> https://drive.google.com/file/d/135EZBFQMC6zzWh0FhqXIscR1jTpb-MTj/view?usp=sharing
> https://drive.google.com/file/d/1kwOCeVHtFkPuqcuZBdP-1FZqYKEOkKYS/view?usp=sharing

please post this and any other info in #536 

thanks

**Closed by IGCIT** 2023-09-24 18:24 UTC
Labels: Info: Needs Replication
