### ISSUE TITLE
Extremely poor performance (~20fps) in Assassin's Creed: Origins with ARC A770 LE

### ISSUE THREAD

**Issue by bizude** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#169] opened 2022-10-30 04:17 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Assassin's Creed : Origins

### Processor / Processor Number [Required]

Intel i9-13900K

### Graphic Card [Required]

Intel ARC A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.3793 (*latest*)
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1 (*October 2021 Update*)
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

[intel-ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/9895070/intel-ssu.txt)

### Description and steps to reproduce [Required]

Start Assassin's Creed Origins
Set graphics preset to high
Set resolution to 2560x1440
Run in-game benchmark

### Application / Windows logs

![image](https://user-images.githubusercontent.com/81831122/198862327-51810c46-b90c-4c42-a39e-4e18c95d98fd.png)

**Comment by Maniir** [comment] 2022-10-30 05:10
I am also seeing the same issue.

**Comment by IntelSupport-Rozilah** [comment] 2022-10-31 12:36
hi @bizude,
Thanks for contacting Intel, to narrow down this issue, may I know which version of Assassin's Creed : Origins you used?

**Comment by IntelSupport-Rozilah** [comment] 2022-11-03 05:07
hi @bizude, 
can you confirm which game version you selected because I saw have a  lot versions here 
![image](https://user-images.githubusercontent.com/44628772/199651286-7eafbf78-6ae1-4267-8d5b-6bb808c8144c.png)
we need confirmation before purchasing the game :).

**Comment by Maniir** [comment] 2022-11-03 15:40
I am not @bizude but I can confirm that I am seeing the performance issues with the base version of Assassin's Creed: Origins on Xbox Game Pass.

**Comment by Bryce-7995** [comment] 2022-11-03 23:12
Thanks Evan 👍🏻

**Comment by bizude** [comment] 2022-11-05 15:47
> 

Sorry for the late response. I purchased the "standard edition" via Ubisoft Connect. 


![image](https://user-images.githubusercontent.com/81831122/200128290-762ae440-191c-4c66-b90b-01f22aedd0bb.png)

**Comment by IntelSupport-Arun** [comment] 2022-11-07 12:33
Hi @bizude 
Thank you for the confirmation. We will verify the issue on our side and let you know the observations.

**Comment by IntelSupport-Rozilah** [comment] 2022-11-25 05:43
hi @bizude 
The case has been verified on our side and we are able to reproduce it with our configurations as below:
Processor: ALD-S 
Graphic Driver version: 31.0.101.3802
We will be working on a fix. I want to give you a heads-up that the fix may take 3 to 6 months to be included.

**Comment by EstebanIntel** [comment] 2023-03-07 20:45
Hi @bizude, a possible fox for this issues is included in driver version [31.0.101.4146](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html?). Can you please test it and let me know?

**Comment by EstebanIntel** [comment] 2023-03-16 02:28
Hi @bizude, did you had the chance to check with the latest drivers?

**Comment by bizude** [comment] 2023-03-17 04:34
Sorry for the late reply, I'm downloading this game again now.

**Comment by bizude** [comment] 2023-03-18 17:18
The frametime performance still leaves much to be desired, one can perceive microstuttering in much of the game, but it is now "playable" averaging around 60fps

**Comment by EstebanIntel** [comment] 2023-03-22 19:32
Thanks for testing! Since the original issue is resolved, and with the intent of tracking issues in an orderly way, can you please close this one and submit a new issue on the microstuttering?

**Closed** 2023-03-23 01:33 UTC
Labels: Info: Needs Replication, Type: Bad Performance
