### ISSUE TITLE
No arc control

### ISSUE THREAD

**Issue by bandit8623** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#688] opened 2024-01-28 22:37 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Arc Control

### Processor / Processor Number [Required]

8700k

### Graphic Card [Required]

a770 sparkle

### GPU Driver Version [Required]

31.0.101.5186

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssu2.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14078046/ssu2.txt)

### Description and steps to reproduce [Required]

ddu drivers.  install drivers.  no arc control.
tried to manual just install arc control.  but says not installed when done.
ddu a second time and fresh install no arc control.
![Screenshot 2024-01-24 215152](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/9302078/4e2cd185-0353-4e62-bb73-e203cf0215be)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/9302078/1dc47d0e-2dc2-4af0-927f-a10cd1b934c6)

### Device / Platform

z390

**Comment by IGCIT** [comment] 2024-01-28 22:59
hi, can you please attach the installer log?
https://www.intel.com/content/www/us/en/support/articles/000091369/graphics.html

**Comment by bandit8623** [comment] 2024-01-28 23:06
[IntelGFX.log](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14078138/IntelGFX.log)
added

**Comment by EstebanIntel** [comment] 2024-02-02 21:56
Hi @bandit8623 

From your logs we have identified that the issue is caused by a bad installation/uninstallation of the Intel Driver & Support Assistant (IDSA); as currently having IDSA installed is a requisite for ArcControl.

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/87549650/bb2ad620-f078-4d2f-bf43-73803aa76405)
Note: IGCC Next was the code name for ArcControl when it was in development.

We are working we the IDSA team to identify and correct the installation issue.

**Comment by bandit8623** [comment] 2024-02-03 21:13
> Hi @bandit8623
> 
> From your logs we have identified that the issue is caused by a bad installation/uninstallation of the Intel Driver & Support Assistant (IDSA); as currently having IDSA installed is a requisite for ArcControl.
> 
> ![image](https://private-user-images.githubusercontent.com/87549650/301980617-bb2ad620-f078-4d2f-bf43-73803aa76405.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5OTUwMzEsIm5iZiI6MTcwNjk5NDczMSwicGF0aCI6Ii84NzU0OTY1MC8zMDE5ODA2MTctYmIyYWQ2MjAtZjA3OC00ZDJmLWJmNDMtNzM4MDNhYTc2NDA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDIxMTIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiYjQ2MTJkMmMwOTk3ZDUwNGNiODFlMzFhZjBiNjE3NTFjOThkMDA1NzAzZjcwMjdlZjkwNTFhYzk1ZDllYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OaHw20vFXobT9RcsPyrNjSUkB1F07IBcqRzYTDz7j4c) Note: IGCC Next was the code name for ArcControl when it was in development.
> 
> We are working we the IDSA team to identify and correct the installation issue.

ok cool.  thanks!  for now i was able to manually install arc control.

**Comment by bandit8623** [comment] 2024-02-09 13:31
5194 still same issue.   after ddu i cant get arc control to install.   manual still works.

**Comment by EstebanIntel** [comment] 2024-02-09 14:46
Hi @bandit8623, we have a possible fix for this issue. This fix will be included in an upcoming driver. I'll let you know once we post a driver with the fix for you to test.

**Comment by bandit8623** [comment] 2024-02-10 07:26
thanks

**Comment by EstebanIntel** [comment] 2024-02-19 14:59
Hi @bandit8623 

Latest driver version 101.5330 has a fix for this issue. I see you already confirmed this fix is working on this other thread [no arc control on latest driver - Intel Community.](https://community.intel.com/t5/Graphics/no-arc-control-on-latest-driver/m-p/1566790#M127745)

**Closed** 2024-02-19 16:29 UTC
Labels: Info: Needs Replication, Type: Drivers Installer
