### ISSUE TITLE
Unable to enable Ray Tracing in CONTROL

### ISSUE THREAD

**Issue by bizude** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#192] opened 2022-12-10 05:14 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Control

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel i9-13900K

### Graphic Card [Required]

Intel ARC A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.3959 (*latest*)
- [X] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Windows 10 21H1
- [ ] Other (Please specify)

### Intel System Support Utility report

[adf.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10199254/adf.txt)

### Description and steps to reproduce [Required]

I decided to try to play Control, I last played this game with a Nvidia RTX 3060ti. I discovered I was unable to change the Ray Tracing settings, which were locked to the high preset. I reset the graphics settings, and afterwards was unable to enable Ray Tracing - with a message on the side mentioning how a capable GPU is required.

After that, I verified the files of the game via Steam. No issues were found, so I deleted the game, and re-downloaded it - but disabled steam saves, just in case the old configuration files may have caused an issue. Nothing changed. Finally, I updated the Intel Graphics to the latest driver - but this also had no effect, I was still unable to enable Ray Tracing in Control. 

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

This does not matter. I was unable to enable any Ray Tracing related settings, no matter what other settings were selected.

**Comment by kunit1** [comment] 2022-12-10 19:38
Control has a problem with intel Arc where it will always launch the Dx11 version as opposed to the Dx12 version. I was able to get around the issue by adding -dx12 to the game shortcut. Ray tracing was then enabled and working within the game settings.

**Comment by IntelSupport-Rozilah** [comment] 2022-12-12 01:24
hi @bizude,
Thanks for contacting Intel, it is this version that you used?
![image](https://user-images.githubusercontent.com/44628772/206942013-ff2f53b3-c903-437a-b379-982fd1115270.png)
can you attach a screenshot or video of the issue so that easy for us to verify the game once the setup is ready?

**Comment by IntelSupport-Rozilah** [comment] 2022-12-16 08:14
hi @bizude, there is a new Beta release here 31.0.101.3975 [Intel® Arc™ Graphics Windows* DCH Driver - BETA](https://www.intel.com/content/www/us/en/download/729157/intel-arc-graphics-windows-dch-driver-beta.html), could you try it while we wait for the game purchasing?.

**Comment by bizude** [comment] 2022-12-18 04:27
There is no change in behavior with 3975

**Comment by IntelSupport-Rozilah** [comment] 2022-12-30 07:52
hi @bizude, there is new ARC driver ![image](https://user-images.githubusercontent.com/44628772/210047242-f3e3c601-f681-4f96-ae63-11d356df4ffa.png) , can you have a try? while we verify the issue.

**Comment by IntelSupport-Rozilah** [comment] 2023-01-03 03:06
hi @bizude,
We have verified the issue and found a solution to fix the issue, please follow the below steps to enable Ray Tracing in Control
Steps for enabling Ray Tracing in Control Steam:
1. Launch the Steam app, then go-to library and right-click on Control Ultimate Edition
2. Navigate to Properties > General > Launch Options
3. Type "-dx12" into the box to enable Ray Tracing in the game
4. Relaunch Control Ultimate Edition again and you will see there is no lock on Ray Tracing in the Display setting.

Please let us know if it is working with the steps provided.

**Comment by IntelSupport-Rozilah** [comment] 2023-01-05 01:24
hi @bizude,
do you have a chance to try on the steps that we provided? else we need to close the issue if there is no reply.

**Comment by bizude** [comment] 2023-01-05 02:02
I am at CES and won't be able to test it for you until 1/7. However, I
would add that I do not consider this a solution - while it's fine for a
more technical like myself, this would not be ideal for common users.

**Comment by IntelSupport-Rozilah** [comment] 2023-01-05 05:35
hi @bizude,
It's ok, we will wait till you are available to test.
1. As we can see from the game requirement here is Dx11 by default and need to manually add Dx12 in a game setting to enable ray tracing.
![image](https://user-images.githubusercontent.com/44628772/210706777-e1ce2b40-06ab-432b-a867-c6e25b675d0a.png)
https://www.pcgamingwiki.com/wiki/Control
2. For a770 is support for Dx12 by default, you can refer from here https://www.intel.com/content/www/us/en/products/sku/227955/intel-arc-a770-graphics-8gb/specifications.html
It is a game issue and what I can suggest is you may need to contact Control game support to fix the issue.

**Comment by IntelSupport-Rozilah** [comment] 2023-01-09 12:06
hi @bizude,
do you have any update on this issue?, if no, then we are proceeding to close this case. You may submit a new GitHub case if you have new questions and we are happy to assist you.

**Comment by kode54** [comment] 2023-01-11 00:07
I had to add a `-dx12` option to the command line arguments for the game, at least on Epic Games Store. Also, this game requires so much VRAM for RT, at least on High settings, that I can only recommend having a 16GB card for RT in general.

**Comment by IntelSupport-Rozilah** [comment] 2023-01-11 06:30
Thanks, @kode54 for confirmation.
Since the issue is related to the game issue, we would like to close this case. In the future, if you need assistance with this issue or any other issue, please raise it and we will be happy to assist.
hi @IGCIT, please close the issue.

**Closed** 2023-01-11 08:42 UTC
Labels: Info: Needs Replication, Type: Support
