### ISSUE TITLE
[Diablo 4] Subtle Screen Flickers when XeSS is Enabled

### ISSUE THREAD

**Issue by RhanCandia** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#755] opened 2024-04-02 09:39 UTC
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Diablo 4

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [X] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5 5600

### Graphic Card [Required]

ASRock Arc A750

### GPU Driver Version [Required]

31.0.101.5382

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14834528/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Play Diablo 4
Enabled XeSS (any preset)

Then if you stand in this area in the Kyovashad shop:
![Screenshot 2024-04-02 172718](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/7951366/56b3b5c7-7f91-44aa-84a3-c436b15deba2)

You'll see that the entire screen has subtle flickers. It's very subtle but you will see it in your peripheral vision while focusing on the main character for example.

I also noticed that the subtle flickers are in sync with the flickering flame in the brazier at the bottom left. Clearly the brazier is meant to flicker. But for some reason the entire room flickers too when XeSS is enabled.

When using FSR or even no upscaling, only the area around the brazier flickers. But with XeSS, the entire room does.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

1440p

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Just High Preset
XeSS Quality

**Comment by Arturo-Intel** [comment] 2024-04-03 18:16
@RhanCandia Can you share a quick video showing the problem? I am trying to reproduce it with no luck

**Comment by RhanCandia** [comment] 2024-04-03 22:46
> @RhanCandia Can you share a quick video showing the problem? I am trying to reproduce it with no luck

It's hard to capture. And hard to upload because the video is being compressed.

Here's a video I captured on my phone: https://photos.app.goo.gl/oMGKvtCi8eC75QB36

When I watch it on my phone where I originally captured it, it's easier to see. I tried to upload it on YouTube, Drive, and Photos (original quality). But the compression makes it even harder to see.

I suggest you download the video from the link I sent instead of just streaming it. Because Photos seem to have limited the streaming to 720p. But if you download it you get the full 4K video.

**Comment by Arturo-Intel** [comment] 2024-04-04 01:08
I see it now; it is quite difficult to notice. Also, you need to zoom in to see it right?
Do you see this behavior in other zones?

**Comment by RhanCandia** [comment] 2024-04-04 02:02
> I see it now; it is quite difficult to notice. Also, you need to zoom in to see it right? Do you see this behavior in other zones?

Yes it is very subtle. No need to zoom in actually. When I play I am usually an arms length away from my monitor.

I experience it everywhere there’s a light source. Dungeons, towns, most obvious in shops.

It is more obvious indoors like in the shop because that’s when I idle. I stand there, to browse the shop, that’s where it’s more obvious. When you are indoors, with a light source, like a brazier with flickering lights, and when not moving. 

I see it all the time in my pereipheral vision when I am in town and there are cut scenes or talking to NPC. 

When moving, walking, running, I don’t see it. 

While I kept on saying it’s subtle, it still bothers me. The flickering lights, even though subtle, hurts my head.

**Comment by RhanCandia** [comment] 2024-04-10 01:28
I made it to the Tree of Whispers. The flickering is more obvious in this area.

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/7951366/001efbde-001c-45a1-b4c9-5d3a94223dbe)

**Comment by RhanCandia** [comment] 2024-04-12 15:44
Thanks. I’ll wait for the updates. Would be nice if Diablo 4 updates XeSS to 1.3 too.

**Comment by rmorera-intel** [comment] 2024-11-08 00:14
Hi @RhanCandia I'm sorry this one went without an update for a while. Our dev team confirmed the subtle screen flicker is is a game issue since it also appears on DLSS and XeSS off.
If the issue persists please report it to the game developer. I'll close this one.

**Closed by rmorera-intel** 2024-11-08 00:14 UTC
Labels: Info: Replicated, Type: Graphical Glitches
